### ISSUE TITLE
Use Android 14 built-in cronet network stack if available 

### ISSUE THREAD

**Issue by asuka-mio** [Ehviewer-Overhauled/Ehviewer#1005]
https://developer.android.com/reference/android/net/http/HttpEngine

**Comment by asuka-mio** [comment]
https://github.com/square/okhttp/pull/7750

**Comment by wordlesswind** [comment]
话说这个应该包含对 HTTP/3 的支持对吧，有可能下放或 Backport 到 Android 13 及以下吗？
怎么感觉 Project Mainline 越做越回去了。

**Comment by asuka-mio** [comment]
> 话说这个应该包含对 HTTP/3 的支持对吧，有可能下放或 Backport 到 Android 13 及以下吗？ 怎么感觉 Project Mainline 越做越回去了。

包含 但是e站短时间上不了http/3吧

**Comment by asuka-mio** [comment]
> 话说这个应该包含对 HTTP/3 的支持对吧，有可能下放或 Backport 到 Android 13 及以下吗？ 怎么感觉 Project Mainline 越做越回去了。

用这个主要目的是为了实现jvmheapless的图片数据下载

**Comment by asuka-mio** [comment]
> 话说这个应该包含对 HTTP/3 的支持对吧，有可能下放或 Backport 到 Android 13 及以下吗？ 怎么感觉 Project Mainline 越做越回去了。

backport的话 app就会再大一倍的体积

**Comment by wordlesswind** [comment]
> 但是e站短时间上不了http/3吧

表站是支持的，毕竟套 Cloudflare，里站不能 Cloudflare 域前置所以没什么实际作用。
hath.network 不支持确实，但是目前也没被封，所以影响不大。

**Comment by asuka-mio** [comment]
> > 但是e站短时间上不了http/3吧
> 
> 表站是支持的，毕竟套 Cloudflare，里站不能 Cloudflare 域前置所以没什么实际作用。 hath.network 不支持确实，但是目前也没被封，所以影响不大。

要不给菠萝写个支持http/3的h@h服务器？
应该能有不少优化吧

**Comment by wordlesswind** [comment]
> 要不给菠萝写个支持http/3的h@h服务器？
> 应该能有不少优化吧

草，不过菠萝自己似乎是不打算维护 Java H@H 了，目标版本锁死在 Java 8。
然后他计划搞个 PHP H@H（

**Comment by wordlesswind** [comment]
> 里站不能 Cloudflare 域前置所以没什么实际作用。

突然发现我想错了，既然 HTTP/3 还没有被封锁，直接用不就是了，不需要管域前置。

**Comment by UjuiUjuMandan** [comment]
@wordlesswind 所以你有测试在 Android 14 上这个 patch 之后的 EhViewer 能直连 e-hentai.org 嘛?

**Comment by wordlesswind** [comment]
> @wordlesswind 所以你有测试在 Android 14 上这个 patch 之后的 EhViewer 能直连 e-hentai.org 嘛?

手上没 Android 14 设备 😂

**Comment by UjuiUjuMandan** [comment]
<img width="682" alt="Screenshot 2023-06-20 at 06 45 37" src="https://github.com/Ehviewer-Overhauled/Ehviewer/assets/125150101/407667a1-b73c-424f-93d0-37eaec7ce752">

Android 14 的模拟器尝试最新版本是这样的（revert了两个删除域前置的commit）。

看起来 HTTP/3 根本没有被启用？

**Comment by FooIbar** [comment]
> 看起来 HTTP/3 根本没有被启用？

那是因为首次连接会用h2，拿到alt-svc之后才会升级到h3

**Comment by UjuiUjuMandan** [comment]
> 那是因为首次连接会用h2，拿到alt-svc之后才会升级到h3

HTTPS 记录里就有 h3 ，怎么不看这个？

还有就是 https://developer.android.com/guide/topics/connectivity/cronet/reference/org/chromium/net/CronetEngine.Builder 里面说明了有`addQuicHint`这个选项，我认为它的意义就是提前告诉客户端这个主机这个端口支持 h3 ，但好像加了也还是被重置。

另外上面截图其实是错的，我后来发现如果用了 cronet 的话应该输出类似 Chromium 会给的`ERR_CONNECTION_RESET` 这样的信息。

**Comment by FooIbar** [comment]
> > 那是因为首次连接会用h2，拿到alt-svc之后才会升级到h3
> 
> HTTPS 记录里就有 h3 ，怎么不看这个？
> 
> 还有就是 [CronetEngine.Builder](https://developer.android.com/guide/topics/connectivity/cronet/reference/org/chromium/net/CronetEngine.Builder) 里面说明了有`addQuicHint`这个选项，我认为它的意义就是提前告诉客户端这个主机这个端口支持 h3 ，但好像加了也还是被重置。
> 
> 另外上面截图其实是错的，我后来发现如果用了 cronet 的话应该输出类似 Chromium 会给的`ERR_CONNECTION_RESET` 这样的信息。

加了`addQuicHint`是可以的

**Comment by asuka-mio** [comment]
> <img alt="Screenshot 2023-06-20 at 06 45 37" width="682" src="https://user-images.githubusercontent.com/125150101/246968832-407667a1-b73c-424f-93d0-37eaec7ce752.png">
> Android 14 的模拟器尝试最新版本是这样的（revert了两个删除域前置和Hosts的commit并在Hosts指定了未被封锁的IP）。
> 
> 看起来 HTTP/3 根本没有被启用？

谁家cronet从java上开套接字...

**Comment by FooIbar** [comment]
这个加到了 S Extensions 7 里

**Comment by asuka-mio** [comment]
> > 话说这个应该包含对 HTTP/3 的支持对吧，有可能下放或 Backport 到 Android 13 及以下吗？ 怎么感觉 Project Mainline 越做越回去了。
> 
> 这个加到了 S Extensions 7 里所以 Android 12 可能能用

嗯对 但是我自己跑的ROM apex没开update到mainline的选项 到时候会把那个加进去
