### ISSUE TITLE
缩略图模式下下滑显示不正常

### ISSUE THREAD

**Issue by HuaJi2333DaDa** [Ehviewer-Overhauled/Ehviewer#1023]
### 复现步骤 / Step to reproduce

1.启动 APP
2.随意上滑加载其他缩略图
3.下滑时就触发了

### 预期行为 / Expected behaviour

正常情况下下滑不会有这种卡顿的感觉，而且也不会重新排序

### 实际行为 / Actual Behaviour

https://user-images.githubusercontent.com/30079825/232209472-b820e201-7e23-4ed8-9d92-ae1684ee2959.mp4

### 应用日志 / App logs

[log-2023-04-15-18-50-33-297.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/11239159/log-2023-04-15-18-50-33-297.zip)

### EhViewer 版本号 / EhViewer version code

1.8.8.0-dev

### EhViewer CI 版本 / EhViewer CI Version

60f917a

### Android 系统版本 / Android version

one UI 5.1 / Android 13

### 设备型号 / Device model

Samsung Galaxy S20 Ultra 5G

### SoC 型号 / Soc model

高通骁龙 865

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
https://issuetracker.google.com/issues/240449681

**Comment by HuaJi2333DaDa** [comment]
@asuka-mio 还是有点，但是没有之前那么明显了

https://github.com/Ehviewer-Overhauled/Ehviewer/assets/30079825/261f744c-f4e6-40a3-bf8f-b46a04f7f3a7
