### ISSUE TITLE
导入大量图片后无法隐藏

### ISSUE THREAD

**Issue by DumbMo** [Ehviewer-Overhauled/Ehviewer#1026]
### 复现步骤 / Step to reproduce

0.重新安装应用
1.登录账号
2.设置下载目录(此时目录中已导入58万+图片)
3.使用 高级 -> 导入数据 恢复下载目录和快捷搜索

4.问题点： 此时 下载 -> 允许媒体扫描 是关闭状态，但是其他应用仍能扫描到下载文件。
![Screenshot_2023-04-17-11-03-19-67_99c04817c0de5652397fc8b56c3b3817](https://user-images.githubusercontent.com/66555400/232370162-a0f24e87-d1d2-4648-a4c9-cb67a682fd56.jpg)

然后尝试开关 "允许媒体扫描" 按钮，开启后无法关闭，点击关闭时会卡一会，然后弹回首页。

https://user-images.githubusercontent.com/66555400/232377549-fd4f4d19-a4c0-4fb6-bdb2-a7794202e4be.mp4

### 预期行为 / Expected behaviour

它应该在设置下载目录时就隐藏其中的下载文件。
或者可以通过手动开关 "允许媒体扫描" 隐藏所有下载文件。

### 实际行为 / Actual Behaviour

如上所述，无法正确隐藏下载文件

### 应用日志 / App logs

[log-2023-04-17-12-23-25-367.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/11246193/log-2023-04-17-12-23-25-367.zip)

### EhViewer 版本号 / EhViewer version code

1.8.7.2

### EhViewer CI 版本 / EhViewer CI Version

9cadf11

### Android 系统版本 / Android version

Android13 / realmeUI 4.0 / RMX3700_13.1.0.102(CN01)

### 设备型号 / Device model

真我GT NEO 5 SE

### SoC 型号 / Soc model

骁龙7+ Gen2

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
@asuka-mio 这个应该已经修了 f06da4c
