### ISSUE TITLE
从下午开始，缩略图开始加载不出来

### ISSUE THREAD

**Issue by 1429886467** [Ehviewer-Overhauled/Ehviewer#1070]
### 复现步骤 / Step to reproduce

![Screenshot_2023-05-16-14-54-19-688_moe tarsin ehviewer](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/107488796/9ca5ca11-04d5-4615-91a4-8e19d34f484a)
![Uploading Screenshot_2023-05-16-14-57-06-723_moe.tarsin.ehviewer.jpg…]()

### 预期行为 / Expected behaviour

应该正常显示缩略图

### 实际行为 / Actual Behaviour

缩略图加载不出来，但是阅读时可以加载

### EhViewer 版本号 / EhViewer version code

1.8.7.2

### EhViewer CI 版本 / EhViewer CI Version

9cadf11

### Android 系统版本 / Android version

miui14

### 设备型号 / Device model

xiaomi12s

### SoC 型号 / Soc model

骁龙8+

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by 1429886467** [comment]
![Uploading Screenshot_2023-05-16-14-57-06-723_moe.tarsin.ehviewer.jpg…]()

**Comment by 1429886467** [comment]
表站缩略图能正常加载

**Comment by 1429886467** [comment]
好像是e站被攻击了，网站都进不去了

**Comment by 373578807** [comment]
貌似是是sni前置出了什么问题  我也不显示 但用梯子就显示了

**Comment by boossy** [comment]
> > 我是下载列表里的无法显示缩略图，主页的可以
> 
> 我现在是表站能正常显示，里站挂梯子才能显示

表站可以，里站挂了梯子也不行

**Comment by 1429886467** [comment]
> > > 我是下载列表里的无法显示缩略图，主页的可以
> > 
> > 
> > 我现在是表站能正常显示，里站挂梯子才能显示
> 
> 表站可以，里站挂了梯子也不行

换个梯子试试，我刚开始也不行，换了个梯子就好了

**Comment by boossy** [comment]
> 
换了也不行，可能和别的因素有关系吧

**Comment by boossy** [comment]
> > 
> 
> 换了也不行，可能和别的因素有关系吧

现在好像全寄了，主页也不行了

**Comment by UjuiUjuMandan** [comment]
`exhentai.org` 现在解析出来的结果是

```
exhentai.org.		300	IN	A	172.64.169.3
exhentai.org.		300	IN	A	172.64.168.3
exhentai.org.		300	IN	AAAA	2606:4700:e4::ac40:a803
exhentai.org.		300	IN	AAAA	2606:4700:e4::ac40:a903
```

都是Cloudflare的IP，和之前的有所不同，不知道有没有关系。

**Comment by 1429886467** [comment]
> `exhentai.org` 现在解析出来的结果是
> 
> ```
> exhentai.org.		300	IN	A	172.64.169.3
> exhentai.org.		300	IN	A	172.64.168.3
> exhentai.org.		300	IN	AAAA	2606:4700:e4::ac40:a803
> exhentai.org.		300	IN	AAAA	2606:4700:e4::ac40:a903
> ```
> 
> 都是Cloudflare的IP，和之前的有所不同，不知道有没有关系。

电报群里面大佬的发言完全看不懂，只能等开发者解决了😂

**Comment by UjuiUjuMandan** [comment]
[Telegram群](https://t.me/ehviewer/2285768)里有人说给 `s.exhentai.org` 加入自定义Hosts就可以加载了，我测试了也确实是这样。这个域名是被DNS污染的，而且很可能是新近污染的。

目前看来解决方法是把以下IP加入EhViewer的Hosts里面。

```
s.exhentai.org.		89	IN	A	178.175.132.22
s.exhentai.org.		89	IN	A	178.175.128.254
s.exhentai.org.		89	IN	A	178.175.129.254
```

**Comment by 1429886467** [comment]
> [Telegram群](https://t.me/ehviewer/2285768)里有人说给 `s.exhentai.org` 加入自定义Hosts就可以加载了，我测试了也确实是这样。这个域名是被DNS污染的，而且很可能是新近污染的。
> 
> 目前看来解决方法是把以下IP加入EhViewer的Hosts里面。
> 
> ```
> 178.175.132.22 s.exhentai.org
> 178.175.128.254 s.exhentai.org
> 178.175.129.254 s.exhentai.org
> ```

嗯，hosts自定义改成
178.175.132.22
s.exhentai.org
就好了

**Comment by 1429886467** [comment]
> [Telegram群](https://t.me/ehviewer/2285768)里有人说给 `s.exhentai.org` 加入自定义Hosts就可以加载了，我测试了也确实是这样。这个域名是被DNS污染的，而且很可能是新近污染的。
> 
> 目前看来解决方法是把以下IP加入EhViewer的Hosts里面。
> 
> ```
> 178.175.132.22 s.exhentai.org
> 178.175.128.254 s.exhentai.org
> 178.175.129.254 s.exhentai.org
> ```

嗯，hosts自定义改成
178.175.132.22
s.exhentai.org
就好了

**Comment by aleck099** [comment]
再给你补几条
178.175.129.254
178.175.132.20
178.175.132.22
178.175.128.252
178.175.128.254
178.175.129.252

**Comment by wc0306** [comment]
![7FJ7ENPVA5OD_SE AM5YIVW](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/133834465/bedcc53e-69bb-4abf-97be-e441c6e4d583)
改完hosts为啥预览图还是加载不出来，但是缩略图没问题，求解？？

**Comment by 1429886467** [comment]
> ![7FJ7ENPVA5OD_SE AM5YIVW](https://user-images.githubusercontent.com/133834465/238817350-bedcc53e-69bb-4abf-97be-e441c6e4d583.jpg) 改完hosts为啥预览图还是加载不出来，但是缩略图没问题，求解？？

我这改完hosts之后能显示，但是历史和下载的缩略图显示不了，实在不行等更新吧

**Comment by wc0306** [comment]
我白E可以加载出来了，但是绿E还是不行

**Comment by 1429886467** [comment]
> 我白E可以加载出来了，但是绿E还是不行

绿e好像已经更新了，你去下载试试

**Comment by wc0306** [comment]
我绿e刚更新了试了还是不行，换了hosts也不行，我白e是换了hosts后才可以的

**Comment by wc0306** [comment]
没事都一样有一个能用就行

**Comment by 1429886467** [comment]
> 我绿e刚更新了试了还是不行，换了hosts也不行，我白e是换了hosts后才可以的

绿e更新之后设置里面不是多了个修复缩略图的选项吗？把那个打开试试

**Comment by wc0306** [comment]
https://github.com/Ehviewer-Overhauled/Ehviewer/issues/1070#issuecomment-1550616073
ok

**Comment by wc0306** [comment]
> > 我绿e刚更新了试了还是不行，换了hosts也不行，我白e是换了hosts后才可以的
> 
> 绿e更新之后设置里面不是多了个修复缩略图的选项吗？把那个打开试试

ok

**Comment by wc0306** [comment]
> > 我绿e刚更新了试了还是不行，换了hosts也不行，我白e是换了hosts后才可以的
> 
> 绿e更新之后设置里面不是多了个修复缩略图的选项吗？把那个打开试试

我试试

**Comment by wc0306** [comment]
> > 我绿e刚更新了试了还是不行，换了hosts也不行，我白e是换了hosts后才可以的
> 
> 绿e更新之后设置里面不是多了个修复缩略图的选项吗？把那个打开试试

还是不行，算了我先用着白E吧，都差不多，谢谢啦
