### ISSUE TITLE
所有漫画的图片包括封面都无法显示，显示不出来，但可以点开看到内容，只是外部不可见，卸载重下依然无法解决，

### ISSUE THREAD

**Issue by IMiaoZheng** [Ehviewer-Overhauled/Ehviewer#1073]
### 复现步骤 / Step to reproduce

![Screenshot_20230516_190904_moe tarsin ehviewer](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/95489820/3c74c836-7479-43b7-a7bf-2fa69b9ff28f)
![Screenshot_20230516_191044_moe tarsin ehviewer](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/95489820/7c782ad7-cb26-4964-a5bb-2e2a354f353d)

### 预期行为 / Expected behaviour

应该可以看到图片显示

### 实际行为 / Actual Behaviour

在主页应该可以看到图片显示

### EhViewer 版本号 / EhViewer version code

1.8.7.2

### EhViewer CI 版本 / EhViewer CI Version

9cadf11

### Android 系统版本 / Android version

11.0.0

### 设备型号 / Device model

华为p40pro

### SoC 型号 / Soc model

kirin990

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by skymkmk** [comment]
@asuka-mio fixed

**Comment by RxinnotRstar** [comment]
![Screenshot_2023-05-16-19-18-03-596_moe tarsin ehviewer](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/56676566/8ea09c77-d7a3-46e3-b867-2679a1a7cf59)
我也遇到了同样的问题，会不会是E站更新了？

**Comment by RxinnotRstar** [comment]
![IMG_20230516_192249](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/56676566/9fad50e4-9d70-4a0f-9a0e-e49831476663)
等一下，https://github.com/xiaojieonly/Ehviewer_CN_SXJ/releases 版本的是可以用的，是巧合吗？

**Comment by dinnerdingzhen** [comment]
感谢修复👍
