### ISSUE TITLE
历史与下载页面的缩略图无法加载

### ISSUE THREAD

**Issue by skymkmk** [Ehviewer-Overhauled/Ehviewer#1074]
### 复现步骤 / Step to reproduce

1. 访问历史与下载页面

### 预期行为 / Expected behaviour

缩略图应加载

### 实际行为 / Actual Behaviour

缩略图不加载

### EhViewer 版本号 / EhViewer version code

1.8.8.0–dev

### EhViewer CI 版本 / EhViewer CI Version

ea42fa5

### Android 系统版本 / Android version

MIUI 14, Android 13

### 设备型号 / Device model

Xiaomi 12S Pro

### SoC 型号 / Soc model

骁龙 8+ Gen 1

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by skymkmk** [comment]
狗狗说

> 历史和下载的链接是在数据库的 写死的
> 他要是没处理就永远显示不出来了

我也不知道你们怎么处理的，先留在这吧，关不关你们定 XD

**Comment by boossy** [comment]
我是今天之前的历史和下载都看不了缩略了，但今天下午的还可以看缩略

**Comment by boossy** [comment]
> 站点改成表站可以看下载的封面，但改成里站点就全白了。

我用的1.8.8.0–dev版本，表里站都看不了历史和下载的缩略
