### ISSUE TITLE
打开下载页就闪退

### ISSUE THREAD

**Issue by hdyzx** [Ehviewer-Overhauled/Ehviewer#1085]
### 复现步骤 / Step to reproduce

从1.8.7.2更新到1.8.8.0，打开下载页面

### 预期行为 / Expected behaviour

在1.8.7.2更新到1.8.8.0之前，下载页面中有许多画廊，并且可以正常打开。

### 实际行为 / Actual Behaviour

在1.8.7.2更新到1.8.8.0之后，下载新的画廊，无法打开下载页面，点击侧栏的下载就闪退，点击通知栏的通知跳转下载页也会闪退

### 应用日志 / App logs

[log-2023-05-17-22-51-08-045.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/11499540/log-2023-05-17-22-51-08-045.zip)

### EhViewer 版本号 / EhViewer version code

1.8.8.0

### EhViewer CI 版本 / EhViewer CI Version

36f411a

### Android 系统版本 / Android version

MIUI14 Android 13 & ASOP Android 11

### 设备型号 / Device model

红米note11t pro&杂牌平板

### SoC 型号 / Soc model

MTK 8100

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.8.8.0-alpha
