### ISSUE TITLE
1.8.8.0一点下载就崩溃

### ISSUE THREAD

**Issue by Yuuki-Rin** [Ehviewer-Overhauled/Ehviewer#1087]
### 复现步骤 / Step to reproduce

点击下载就会崩溃
https://github.com/Ehviewer-Overhauled/Ehviewer/assets/63774025/ef28e9eb-e883-43c9-861a-628d56f8cb41

### 预期行为 / Expected behaviour

正常浏览已经下载的项目

### 实际行为 / Actual Behaviour

![Screenshot_2023-05-17-23-27-22-821_com miui thirdappassistant](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/63774025/77e02a7b-c56d-4e5a-b79f-3dcb3525a629)

### 应用日志 / App logs

[log-2023-05-17-23-38-24-566.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/11500149/log-2023-05-17-23-38-24-566.zip)

### EhViewer 版本号 / EhViewer version code

1.8.8.0

### EhViewer CI 版本 / EhViewer CI Version

36f411a

### Android 系统版本 / Android version

miui14 ，安卓13

### 设备型号 / Device model

红米k50电竞版

### SoC 型号 / Soc model

8gen1

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.8.8.0-alpha
