### ISSUE TITLE
闪退bug

### ISSUE THREAD

**Issue by 11415263** [Ehviewer-Overhauled/Ehviewer#1090]
### 复现步骤 / Step to reproduce

0.重新安装软件
1.点击侧边栏下载

### 预期行为 / Expected behaviour

他应该打开已下载列表

### 实际行为 / Actual Behaviour

实际他崩溃了

### 应用日志 / App logs

>
[crash-2023-05-18-16-11-17-004.log](https://github.com/Ehviewer-Overhauled/Ehviewer/files/11506112/crash-2023-05-18-16-11-17-004.log)

### EhViewer 版本号 / EhViewer version code

1.8.8.0

### EhViewer CI 版本 / EhViewer CI Version

36f411a

### Android 系统版本 / Android version

Android 13

### 设备型号 / Device model

rog 6

### SoC 型号 / Soc model

骁龙8+gen 1

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.8.8.0-alpha
