### ISSUE TITLE
Crash when reading from favorites

### ISSUE THREAD

**Issue by emmaustotk** [Ehviewer-Overhauled/Ehviewer#1092]
### 复现步骤 / Step to reproduce

1. Open favorites
2. Select a saved gallery
3. Read

### 预期行为 / Expected behaviour

Reader should open like normal

### 实际行为 / Actual Behaviour

It crashes

### 应用日志 / App logs

[log-2023-05-18-21-43-32-423.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/11511841/log-2023-05-18-21-43-32-423.zip)

### 备注 / Addition details

You can restore the follow data to easily reproduce it.
[2023-05-18-21-30-57-973.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/11511856/2023-05-18-21-30-57-973.zip)

### EhViewer 版本号 / EhViewer version code

1.8.8.0 alpha

### EhViewer CI 版本 / EhViewer CI Version

746a045

### Android 系统版本 / Android version

Miui 14 Android 13

### 设备型号 / Device model

Xiaomi K40 pro

### SoC 型号 / Soc model

snapdragon 888

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
A full fix would require a massive rewrite, we'll fix it in the next major release, i.e., 1.8.9.0

**Comment by LzNOHentai** [comment]
> A full fix would require a massive rewrite, we'll fix it in the next major release, i.e., 1.8.9.0

关于从收藏里点击阅读已下载的画廊倒是有一个建议。
因为E站有很多本被版权炮了，所以收藏夹里有不少尸体，但其中部分是之前已下载的。
目前从收藏里点击阅读的逻辑是会首先跳转到画廊详情页，版权炮自然导致无法点击阅读按钮，这就导致无法从收藏里方便阅读已下载的版权炮本。
同时因为下载的本多了，下载列表里又没有搜索功能，非常不方便去找特定本子。

想说能否改进一下收藏里阅读已下载画廊的逻辑，比如识别到画廊不正常的时候可以直接阅读？或者为下载列表提供搜索功能？
