### ISSUE TITLE
希望当画廊被版权时不要跳出版权画面

### ISSUE THREAD

**Issue by InLem** [Ehviewer-Overhauled/Ehviewer#1098]
### 需求 / Requirement

已下载的画廊如果被版权，之后点进去会出现被版权的信息，而无法点阅读来观看。
希望当画廊被版权时不要跳出版权画面。
https://imgur.com/a/L5k6wlF

可能会有人觉得为什么不去下载里观看。是因为当画廊有更新时页面会有提示，從下载里点进去看则不会有。

### 建议实现 / Suggested implements

希望当画廊被版权时可以保留阅读纽，或是把被版权信息显示在下方。
https://imgur.com/a/WAej1jl

### 备注 / Addition details

已搜寻过 Issue Tracker，没有找到类似内容。
关键字：版权、下架。

### EhViewer 版本号 / EhViewer version code

1.8.8.0-beta

### EhViewer CI 版本 / EhViewer CI Version

fc24a18

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by LzNOHentai** [comment]
前几天也提过这个就是了。
https://github.com/Ehviewer-Overhauled/Ehviewer/issues/1092#issuecomment-1554043460

**Comment by InLem** [comment]
> 前几天也提过这个就是了。 [#1092 (comment)](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/1092#issuecomment-1554043460)

看来是我漏掉了。
