### ISSUE TITLE
画廊（本子）页信息框的一部分被遮挡在封面略缩图下

### ISSUE THREAD

**Issue by Lowwwwww** [Ehviewer-Overhauled/Ehviewer#110]
### 复现步骤 / Step to reproduce

点进去就这样，是个画廊都这样

### 预期行为 / Expected behaviour

完整显示不会被遮挡

### 实际行为 / Actual Behaviour

![IMG_20220721_091941](https://user-images.githubusercontent.com/44076275/180109182-dc922dd2-53f8-4f4b-8268-96f3c3517579.jpg)

### EhViewer 版本号 / EhViewer version code

1.7.28.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/2704954250

### Android 系统版本 / Android version

OriginOS PD2118_A_6.15.10

### 设备型号 / Device model

iQOO Neo5 活力版

### SoC 型号 / Soc model

骁龙870

### 应用日志 / App logs

提取出的当天错误日志为空

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
清协助测试 [关联 Pull Request 对应的 Action 产物](https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/2711349270)，检查您的问题是否已经解决

**Comment by Lowwwwww** [comment]
> 清帮忙协助测试 [关联 Pull Request 对应的 Action 产物](https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/2711349270)，检查您的问题是否已经解决
> 
> 我们将考虑您的测试结果，将其作为 Pull Request Check 的一部分

已下载测试，确认解决
![IMG_20220721_213514.jpg](https://user-images.githubusercontent.com/44076275/180226756-c6c6288f-fe81-4bb9-b526-651ca1d388ee.jpg)
