### ISSUE TITLE
未解析 [email protected]

### ISSUE THREAD

**Issue by wordlesswind** [Ehviewer-Overhauled/Ehviewer#1102]
### 复现步骤 / Step to reproduce

N/A

关闭“内置HOSTS”和“域前置”

仅限 ExHentai.org（Cloudflare），部分字段（比如画廊标题和上传者名称等）会触发 [Cloudflare Email Address Obfuscation](https://developers.cloudflare.com/support/more-dashboard-apps/cloudflare-scrape-shield/what-is-email-address-obfuscation/) 。

示例：https://exhentai.org/g/2555353/b72e7b13da/

### 预期行为 / Expected behaviour

正常显示

![Screenshot_2023-05-23-16-56-32-84_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/9050713/174d8745-3b5b-42b3-9c7d-7fb6c2da2575)

### 实际行为 / Actual Behaviour

显示 [email protected]

![Screenshot_2023-05-23-16-55-34-31_f2f1746601bf3b868d00d5efaf12e601](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/9050713/08217d80-66b0-445b-b008-aa93c0474da3)
![Screenshot_2023-05-23-16-55-52-57_f2f1746601bf3b868d00d5efaf12e601](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/9050713/83155e11-0013-4a84-87b3-0b7f59c52be0)

### EhViewer 版本号 / EhViewer version code

1.8.8.0-beta

### EhViewer CI 版本 / EhViewer CI Version

 06e411d

### Android 系统版本 / Android version

ColorOS 12.1

### 设备型号 / Device model

OnePlus 7 Pro

### SoC 型号 / Soc model

Snapdragon 855

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by UjuiUjuMandan** [comment]
发私信给Tenboro让他取消不存在站点的Email混淆会不会被封禁啊？
