### ISSUE TITLE
域前置未生效的警告通知

### ISSUE THREAD

**Issue by wordlesswind** [Ehviewer-Overhauled/Ehviewer#1103]
### 需求 / Requirement

由于 ExHentai.org 已接入 Cloudflare CDN

在关闭“内置 HOSTS”后启用域前置（不绕过 VPN）

那么这时实则获取 Cloudflare CDN IP，但此时并没有域前置，也不支持域前置。

### 建议实现 / Suggested implements

我不清楚域前置功能是怎么实现的

如果是先尝试域前置，失败后回退到普通模式，那理应应该有个警告。

如果域前置功能与“内置 HOSTS”绑定，即非名单中的 IP 地址则不进行域前置，那么在设置上应当有体现，比如启用域前置后强制启用内置 HOSTS。

### EhViewer 版本号 / EhViewer version code

1.8.8.0-beta

### EhViewer CI 版本 / EhViewer CI Version

 06e411d

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by UjuiUjuMandan** [comment]
以下回复均假设使用者在受审查的国内。

---

> 那么这时实则获取 Cloudflare CDN IP

如果没有DoH，是获取不到的。只能收到GFW注入的不可达IP，显示是“超时”。

> 失败后回退到普通模式，那理应应该有个警告。

假设有DoH，对正确的IP使用“普通模式”就会直接被GFW重置连接，显示“网络错误”了。

咱认为一个“网络错误”就足够了，没有必要为用户考虑那么多。

**Comment by wordlesswind** [comment]
> > 那么这时实则获取 Cloudflare CDN IP，但此时并没有域前置，也不支持域前置。
> 
> 解释一下这句话？

```
# nslookup exhentai.org one.one.one.one
Server:         one.one.one.one
Address:        2606:4700:4700::1111#53

Non-authoritative answer:
Name:   exhentai.org
Address: 172.64.96.13
Name:   exhentai.org
Address: 172.64.97.13
Name:   exhentai.org
Address: 2606:4700:e0::ac40:600d
Name:   exhentai.org
Address: 2606:4700:e0::ac40:610d

# curl -H 'Host: exhentai.org' https://[2606:4700:e0::ac40:600d]/
curl: (35) error:0A000410:SSL routines::sslv3 alert handshake failure
```

> 不开 内置 hosts 也是有域名前置的

> 在关闭“内置 HOSTS”后启用域前置（不绕过 VPN）
> https://github.com/Ehviewer-Overhauled/Ehviewer/issues/1103#issue-1721610658
