### ISSUE TITLE
大面积标签撕裂

### ISSUE THREAD

**Issue by Cryberghost** [Ehviewer-Overhauled/Ehviewer#1118]
### 复现步骤 / Step to reproduce

正常浏览主页

### 预期行为 / Expected behaviour

完整的标签

### 实际行为 / Actual Behaviour

标签被撕裂
![S30526-17400034_moe tarsin ehviewer](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/69906215/3721ae74-b240-4443-bad9-f004bcc32866)

### EhViewer 版本号 / EhViewer version code

1.8.8.3

### EhViewer CI 版本 / EhViewer CI Version

afbe0a4

### Android 系统版本 / Android version

Flyme 10

### 设备型号 / Device model

meizu 20 pro

### SoC 型号 / Soc model

骁龙 8gen2

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
![Screenshot_20230526-181531~2](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/43900799/f1e125d0-fdfc-4a81-b4c3-03356dab3895)
这个往高了调
