### ISSUE TITLE
屏幕方向为横屏状态下打开压缩包Ehviewer奔溃

### ISSUE THREAD

**Issue by AlexiaFate** [Ehviewer-Overhauled/Ehviewer#1122]
### 复现步骤 / Step to reproduce

0.重新安装应用
1.游客登录，进入Ehviewer
2.默认状态下打开压缩包，正常进入
3.切换横屏后打开压缩包，Ehviewer奔溃
[录屏](https://tmby.lanzout.com/it3bP0xtl9kd) 
不知道为什么不能上传到github，先用蓝奏云

### 预期行为 / Expected behaviour

正常观看

### 实际行为 / Actual Behaviour

Ehviewer奔溃

### 应用日志 / App logs

[log-2023-05-31-16-37-51-129.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/11610721/log-2023-05-31-16-37-51-129.zip)

### 备注 / Addition details

经过我的测试，Ehviewer在这个页面下横屏打开压缩包可以正常观看。
![Screenshot_20230531_164200_moe tarsin ehviewer](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/88327304/5ee5d4fb-88cd-48ff-b0c0-10a9a62d311b)
再补充一句，我平板在本身就是横屏的情况下是可以打开的，但竖屏下打开和手机一样奔溃。

### EhViewer 版本号 / EhViewer version code

1.8.9.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

7ca37ee

### Android 系统版本 / Android version

HarmonyOS 3.0.0.213

### 设备型号 / Device model

HUAWEI Nova 9 Pro

### SoC 型号 / Soc model

高通骁龙778G 4G

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by AlexiaFate** [comment]
@asuka-mio 下载[Resolve #1122](https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/5131942930)后依然奔溃
以下是日志![log-2023-05-31-19-22-21-261.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/11612410/log-2023-05-31-19-22-21-261.zip)

**Comment by AlexiaFate** [comment]
@asuka-mio 寄，还是奔溃
![log-2023-05-31-22-23-45-313.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/11615188/log-2023-05-31-22-23-45-313.zip)

**Comment by asuka-mio** [comment]
怪事 这没见别人崩溃过怎么就你这崩溃（
没事 有stacktrace都好修(

**Comment by AlexiaFate** [comment]
> 怪事 这没见别人崩溃过怎么就你这崩溃（
> 没事 有stacktrace都好修(

悲，想必是鸿蒙的原因

**Comment by start2-coin** [comment]
为什么我的缩略图能看见，但是点进去图片看不见，显示是错误代码403
