### ISSUE TITLE
当解锁失败时，进入重试页面而不是直接退出应用

### ISSUE THREAD

**Issue by wordlesswind** [Ehviewer-Overhauled/Ehviewer#1124]
### 需求 / Requirement

目前，当启用“需要解锁”功能时，用户启动应用需要通过系统安全判定进行解锁。

然而如果判定失败（例如指纹识别失败），则会直接退出应用，这导致使用上的不便，提供“重试”能够解决这个问题。

### 建议实现 / Suggested implements

首先一是要提供“重试”页面，二是可选择其他方案进行解锁，比如指纹识别、人脸识别和 PIN 等。

### EhViewer 版本号 / EhViewer version code

1.8.9.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

257e247

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by asuka-mio** [comment]
行

**Comment by asuka-mio** [comment]
至于这个解锁方式 取决于你系统设置了啥解锁方式 调起的系统实现 由于这个界面的设计和实现， 如果在app里实现比较out of scope 所以不打算自己实现
