### ISSUE TITLE
缩略图能看见，但是点进去大图片看不见，显示是错误代码403

### ISSUE THREAD

**Issue by start2-coin** [Ehviewer-Overhauled/Ehviewer#1125]
### 复现步骤 / Step to reproduce

已经重试过了，没用啊，也更新到最新版本了

### 预期行为 / Expected behaviour

他应该在我点击阅读的时候就全部显示出来

### 实际行为 / Actual Behaviour

![Screenshot_20230604_134731](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/135495112/0abbf30e-9790-4419-945d-f72a62267bd6)

### EhViewer 版本号 / EhViewer version code

1.8.8.3

### EhViewer CI 版本 / EhViewer CI Version

afbe0a4

### Android 系统版本 / Android version

PD2068B_A_1.25.8

### 设备型号 / Device model

vivoY31s

### SoC 型号 / Soc model

2.2GHz八核

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by KoinuDayo** [comment]
同样的情况

**Comment by ck1521** [comment]
同样的情况

**Comment by UjuiUjuMandan** [comment]
我把并发下载数和预载图片开到最大、下载延时关了都没法重现到，直连的。

**Comment by start2-coin** [comment]
不仅是没有办法点开大图，而且连下载也只能下到第四页就不行了

**Comment by KoinuDayo** [comment]
有解决方法了，用网页端纯净点的节点登入，登入完之后复制cookie。在eh里用cookie登入

**Comment by qwert-yui** [comment]
``

**Comment by RicardoMLu61** [comment]
> 

不行感觉可能是vivo手机bug我也这样

**Comment by Ayase-Naka-a** [comment]
努比亚z50u手机同样出现此问题，在web端重新登录后，拿到cookie在手机上再次登录，仍然出现此问题

**Comment by KoinuDayo** [comment]
> 努比亚z50u手机同样出现此问题，在web端重新登录后，拿到cookie在手机上再次登录，仍然出现此问题

得是纯净节点，cookie的igneous不能有值，有值就得重新换节点登

**Comment by Lacertavc** [comment]
想问一下，如果只有手机，没有电脑，如何获取网页端的cookies？我的igneous是null，我是里站账号，也是403的问题，我是捐献的，按理来说我是自己单独一个节点的啊？

**Comment by Lacertavc** [comment]
> 想问一下，如果只有手机，没有电脑，如何获取网页端的cookies？我的igneous是null，我是里站账号，也是403的问题，我是捐献的，按理来说我是自己单独一个节点的啊？

我找到解决方法了，这个方法是楼上的，感谢楼上提供的方法！，我做了一些改动，是手机可以适用的，可以使用alook浏览器，图标就是一个蓝色的大写A，在alook浏览器登录你自己的eh账号，找一个纯净的节点，登进去以后，点击菜单，然后是工具箱，有一个开发者工具，进去获取cookies，有两行字符分别是 ipb_member_id 
ipb_pass_hash 
 igneous是没有数值的，我成功登录进去之后看igneous是mystery
登录进去使用cookies登录，我只输入两行，就是ipb_member_id 
ipb_pass_hash
就这两个，第三行具体参考一下楼上，我没输入第三行，我也只看到了ipb_member_id 
ipb_pass_hash，没看到igneous，第三行我就没输入，我现在是可以正常使用了，没有403现象了
![IMG_20230608_130725.jpg](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/123647865/c02b3c50-23a8-4cd1-941b-1a884316ef51)

**Comment by Lacertavc** [comment]
> > 想问一下，如果只有手机，没有电脑，如何获取网页端的cookies？我的igneous是null，我是里站账号，也是403的问题，我是捐献的，按理来说我是自己单独一个节点的啊？
> 
> 我找到解决方法了，这个方法是楼上的，感谢楼上提供的方法！，我做了一些改动，是手机可以适用的，可以使用alook浏览器，图标就是一个蓝色的大写A，在alook浏览器登录你自己的eh账号，找一个纯净的节点，登进去以后，点击菜单，然后是工具箱，有一个开发者工具，进去获取cookies，有两行字符分别是 ipb_member_id 
> ipb_pass_hash 
>  igneous是没有数值的，我成功登录进去之后看igneous是mystery
> 登录进去使用cookies登录，我只输入两行，就是ipb_member_id 
> ipb_pass_hash
> 就这两个，第三行具体参考一下楼上，我没输入第三行，我也只看到了ipb_member_id 
> ipb_pass_hash，没看到igneous，第三行我就没输入，我现在是可以正常使用了，没有403现象了
> ![IMG_20230608_130725.jpg](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/123647865/c02b3c50-23a8-4cd1-941b-1a884316ef51)
> 
> 

忘记说了，我没开vpn也可使用

**Comment by guest-zero** [comment]
@KoinuDayo 纯净节点怎么打开，还是我上错网页端了，找不到cookie

**Comment by lzm654** [comment]
> > 努比亚z50u手机同样出现此问题，在web端重新登录后，拿到cookie在手机上再次登录，仍然出现此问题
> 
> @Ayase-Naka-a 得是纯净节点，cookie的igneous不能有值，有值就得重新换节点登

游客模式怎么办啊，我是iqoo。

**Comment by lzm654** [comment]
而且下载速度超级慢，之前是正常的。

**Comment by Misaka100** [comment]
我把画廊站点改成Ex后问题就解决了

**Comment by anaorton** [comment]
@Misaka100 我换成Ex会显示sad panda

**Comment by Misaka100** [comment]
> @Misaka100 我换成Ex会显示sad panda

我第一次换也是这样，你试试在web端重新登录下啥的，我重新登录了几下突然就好了

**Comment by Misaka100** [comment]
> @Misaka100 我换成Ex会显示sad panda

我第一次换也是这样，你试试在web端重新登录下啥的，我重新登录了几下突然就好了

**Comment by WeiYang1005** [comment]
是因为账号权限被收回了么，小米手机也突然这样了，也是上周开始

**Comment by shouzhuo0603** [comment]
加一，我还以为只有我是这样

**Comment by REwieder** [comment]
还没解决问题吗（指app）

**Comment by UjuiUjuMandan** [comment]
问题不能让开发者也遇到的话是修不了的。

**Comment by xiao-chouaaa** [comment]
好像只有晚上会这样，白天好像可以看

**Comment by shouou233** [comment]
问题已解决，设置>高级>域名前置，吧这个选项关了就行，如果不行关了之后挂梯子即可

**Comment by Soul-G-park** [comment]
按你说的做，关了之后网络错误，挂梯子之后509

**Comment by YUlrezaj** [comment]
内置host 域名前置都关了，用梯子

**Comment by t95270** [comment]
> 

有好用的梯子吗

**Comment by Soul-G-park** [comment]
用梯子就是什么都加载不出来了，主页就是熊猫头

**Comment by t95270** [comment]
> 是因为账号权限被收回了么，小米手机也突然这样了，也是上周开始

我也怀疑可能是，我也是小米手机同样不行

**Comment by mj2337** [comment]
相同的问题，华为手机，更换不同的网络（电信wifi，联通流量，移动流量）都是一样的问题，我觉得是账号的问题

**Comment by lniaen** [comment]
> 问题已解决，设置>高级>域名前置，吧这个选项关了就行，如果不行关了之后挂梯子即可

已解决问题，更改前置域名后需要重启应用生效。

**Comment by KoinuDayo** [comment]
> > 
> 
> 有好用的梯子吗

@t95270 
自己搭

**Comment by yaoshunli** [comment]
![Screenshot_20230611_174216_moe tarsin ehviewer](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/136361556/ed49ecad-a241-45ab-8102-1f3e63334fc8)
为什么
![Screenshot_20230611_174323_moe tarsin ehviewer](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/136361556/203da0ef-d6d3-4aab-87f8-9bda5b5ef517)
这样的我的是华为的，这个怎么解决，有没有大神说明一下谢谢

**Comment by SUNRAI2** [comment]
我刚下的时候还可以看，但过了一天就出现这种情况了
![Screenshot_2023-06-17-19-09-20-634_moe tarsin ehviewer](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/136897974/db16749f-912a-47a2-bf17-fb799def4c67)

**Comment by asuka-mio** [comment]
#1153
