### ISSUE TITLE
“排行”页面无法选择每月排行和昨日排行了

### ISSUE THREAD

**Issue by GAKKI939** [Ehviewer-Overhauled/Ehviewer#1129]
### 复现步骤 / Step to reproduce

之前应该一直用的用的1.8.3版本，升级1.8.8以后排行页面就不能选择排行类型了

### 预期行为 / Expected behaviour

进入排行界面右侧加号点开应该有选择排行类型的按钮

### 实际行为 / Actual Behaviour

只有首页、刷新、最后一页三个按钮
![Screenshot_2023-06-08-01-48-42-26_f2f1746601bf3b868d00d5efaf12e601](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/135867312/2b6d11bb-3584-4866-aebe-09512b233d35)

### EhViewer 版本号 / EhViewer version code

1.8.8.3

### EhViewer CI 版本 / EhViewer CI Version

afbe0a4

### Android 系统版本 / Android version

安卓13

### 设备型号 / Device model

realme GT

### SoC 型号 / Soc model

骁龙888

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
左划打开抽屉
