### ISSUE TITLE
display mode为Thumbnail时未显示上传者

### ISSUE THREAD

**Issue by UjuiUjuMandan** [Ehviewer-Overhauled/Ehviewer#1136]
### 复现步骤 / Step to reproduce

1. 去 https://e-hentai.org/uconfig.php 到 Front Page / Search Settings 设置 display mode 为Thumbnail
2. 进入EhViewer主页，注意画廊站点要和上面设置的相同
3.
![photo1686456007](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/125150101/5d805854-bf3f-4f4c-874b-590cb7974316)

### 预期行为 / Expected behaviour

显示上传者。

### 实际行为 / Actual Behaviour

所有画廊都显示DISOWNED。

### 应用日志 / App logs

无

### 备注 / Addition details

进入画廊页面是可以看到上传者的。另外，搜索特定character的结果里显示也是正常的。

### EhViewer 版本号 / EhViewer version code

1.8.9.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/commit/6e561ca9a903bf74d05cc02cd91ef4c1bf9ff508

### Android 系统版本 / Android version

未知

### 设备型号 / Device model

未知

### SoC 型号 / Soc model

未知

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
什么叫不用说怎么复现， 我要是自己遇到了我能不修？

**Comment by UjuiUjuMandan** [comment]
> 什么叫不用说怎么复现， 我要是自己遇到了我能不修？

抱歉，刚才发现应该是 display mode 的问题。请看编辑后的复现步骤。

**Comment by UjuiUjuMandan** [comment]
网页在Thumbnail情况下确实不会显示上传者名字的，这种情况下EhViewer的“列表模式”也应该自动变为“缩略图”才好。

**Comment by asuka-mio** [comment]
> 网页在Thumbnail情况下确实不会显示上传者名字的，这种情况下EhViewer的“列表模式”也应该自动变为“缩略图”才好。
> 
> 奇怪的是，虽然主页EhViewer获取不到上传者名字，搜索结果里却可以。Thumbnail模式下的网页，明明主页和搜索结果都没显示上传者名字。
> 
> https://e-hentai.org/?f_search=character%3Akafuu+chino

暂时先恢复原行为吧 这个等重构完这个页面再说
