### ISSUE TITLE
点进阅读无法观看

### ISSUE THREAD

**Issue by Soul-G-park** [Ehviewer-Overhauled/Ehviewer#1138]
### 复现步骤 / Step to reproduce

![Screenshot_20230612_002523_com xjs ehviewer](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/136257673/998beeb9-75e6-4826-b864-a473792083cf)
转一分钟左右之后第一页会显示解析失败
![Screenshot_20230612_002544_moe tarsin ehviewer](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/136257673/2e897a53-1778-4624-8186-3dfb41c2762d)
从第二页开始后面全部都是403
封面 页数 缩略图 搜索功能都是正常使用，只是点进阅读会这样

### 预期行为 / Expected behaviour

正常显示

### 实际行为 / Actual Behaviour

解析错误/403

### EhViewer 版本号 / EhViewer version code

1.9.5.1

### Android 系统版本 / Android version

EMUI10.1.1

### 设备型号 / Device model

华为nova7

### SoC 型号 / Soc model

麒麟9855GSoC

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [ ] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by lniaen** [comment]
遇到了同样的问题，目前有解决方案吗？

**Comment by UjuiUjuMandan** [comment]
您这issue真的太有诚意了，账号cookie都发出来了。可惜的是，我这边登陆了您的账号，进入任何画廊阅读，并没有看到任何403。

不过可以排除403和账号有关了。

**Comment by KoinuDayo** [comment]
哥你赶紧edit把cookie删掉

**Comment by lniaen** [comment]
> 遇到了同样的问题，目前有解决方案吗？

已解决，->设置->高级->关闭 域名前置->重启应用后正常浏览。

**Comment by Soul-G-park** [comment]
>按你的操作完了网络错误，挂梯子就是加载出来个
![Uploading Screenshot_20230614_043445_moe.tarsin.ehviewer.jpg…]()

**Comment by 1057520143** [comment]
同问题，请问解决了吗？
