### ISSUE TITLE
没有隐藏 HV 事件通知

### ISSUE THREAD

**Issue by UjuiUjuMandan** [Ehviewer-Overhauled/Ehviewer#1141]
### 复现步骤 / Step to reproduce

不好复现，待编辑。

### 预期行为 / Expected behaviour

不弹出任何HV通知。

### 实际行为 / Actual Behaviour

我还是会遇到“You have encountered a monster”通知啊。

### 应用日志 / App logs

[logcat-2023-06-13-02-38-03-589.txt](https://github.com/Ehviewer-Overhauled/Ehviewer/files/11728243/logcat-2023-06-13-02-38-03-589.txt)

（这日志里好像没啥和HV有关的东西）

### EhViewer 版本号 / EhViewer version code

1.8.9.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

5831761

### Android 系统版本 / Android version

未知

### 设备型号 / Device model

未知

### SoC 型号 / Soc model

未知

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
？
信息呢

**Comment by UjuiUjuMandan** [comment]
尝试多次均无法稳定复现，这几天也没弹出了。关了吧。
