### ISSUE TITLE
希望添加在已收藏的画廊详情界面，长按爱心按钮可以更改收藏类别

### ISSUE THREAD

**Issue by Krosec** [Ehviewer-Overhauled/Ehviewer#1150]
### 需求 / Requirement

如题

### 建议实现 / Suggested implements

如题

### EhViewer 版本号 / EhViewer version code

1.8.9.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

9611d81

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by asuka-mio** [comment]
别长按了 长按实现不了
换个交互操作吧

**Comment by Krosec** [comment]
> 别长按了 长按实现不了 换个交互操作吧

已收藏的画廊按下收藏按钮的时候不直接取消，而是弹出选择放入收藏画廊类别的界面，位于当前收藏的类别用别的背景色或者符号标识，点击当前收藏的类别就取消收藏，点击别的收藏类别就更改至该收藏类别，这样的交互操作如何

**Comment by asuka-mio** [comment]
> > 别长按了 长按实现不了 换个交互操作吧
> 
> 已收藏的画廊按下收藏按钮的时候不直接取消，而是弹出选择放入收藏画廊类别的界面，位于当前收藏的类别用别的背景色或者符号标识，点击当前收藏的类别就取消收藏，点击别的收藏类别就更改至该收藏类别，这样的交互操作如何

挺好
