### ISSUE TITLE
屏蔽功能失效

### ISSUE THREAD

**Issue by zzy450** [Ehviewer-Overhauled/Ehviewer#1158]
### 复现步骤 / Step to reproduce

1点击标签
2选择屏蔽标签
3刷新

### 预期行为 / Expected behaviour

相关画廊消失

### 实际行为 / Actual Behaviour

依旧出现

### 应用日志 / App logs

[log-2023-06-20-00-10-53-151.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/11790144/log-2023-06-20-00-10-53-151.zip)

### 备注 / Addition details

并不是所有标签都失效，存有一些没有失效的屏蔽标签

### EhViewer 版本号 / EhViewer version code

1.8.8.3

### EhViewer CI 版本 / EhViewer CI Version

afbe0a4

### Android 系统版本 / Android version

安卓12

### 设备型号 / Device model

TNA-AN00

### SoC 型号 / Soc model

晓龙778G

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
如果你用的是 compact 模式的话画廊列表页拿不到所有标签
