### ISSUE TITLE
导入数据后本地画廊需联网观看

### ISSUE THREAD

**Issue by qjmltz** [Ehviewer-Overhauled/Ehviewer#1169]
### 复现步骤 / Step to reproduce

将软件导出数据以后，导入新软件会提示出现无法读取文件。这依然可以导入本地画廊，但是在新软件里下载的所有本地画廊均无法观看，需要联网更新。如果联网时画廊是被禁止的，那么本地画廊会更新失败提示ERROR。如果不联网，那不能直接在本地看漫画，也提示ERROR。

实验过两次，第一次导入进新安装的SXJ_lonelydog版绿色软件，本地目录所有的画廊都需要联网更新，否则提示ERROR。
第二次是将第一次实验导入数据的绿色软件里部分画廊联网更新，删除软件并重新导入，这次在无网络情况下可以直接打开那部分画廊。
所以我觉得可能是作者的软件对本地画廊的导出数据缺了部分记录，使它可以出现在目录上，但是缺失部分信息使它无法打开，需要联网，但已经被ban的画廊联网也得不到信息所以提示ERROR。

这里我没有用作者的软件删除并重新导入的原因，是因为怕存在同样的问题导致我的本地漫画都打不开了，希望可以有人做一下用作者的软件复现实验。

### 预期行为 / Expected behaviour

导入数据后下载目录的本地画廊应该无需联网可以直接打开。

### 实际行为 / Actual Behaviour

导入数据后，本地画廊在无网络情况下会提示ERROR。
需要联网更新，更新时画廊没被ban则正常看，被ban的话则同样提示ERROR。

### 应用日志 / App logs

[log-2023-06-22-08-37-08-391.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/11827426/log-2023-06-22-08-37-08-391.zip)

### EhViewer 版本号 / EhViewer version code

1.8.8.3

### EhViewer CI 版本 / EhViewer CI Version

afbe0a4

### Android 系统版本 / Android version

MIUI 13.07

### 设备型号 / Device model

小米10

### SoC 型号 / Soc model

骁龙865

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
导出的数据不支持其他软件
