### ISSUE TITLE
Android app爲何重新下載以前所有被下載過的漫畫的檔案夾

### ISSUE THREAD

**Issue by newbiegituserj** [Ehviewer-Overhauled/Ehviewer#1174]
### 复现步骤 / Step to reproduce

Android
1. 用app下載漫畫A
2. 漫畫A出現在download list中
4. 在android裏把漫畫A移到另外的檔案夾
5. 用app下載另一本漫畫，漫畫B
6. app成功下載漫畫B，不過也會重新下載漫畫A的檔案夾。
7. 漫畫A的檔案夾除了.thumb檔外別無其他檔案

要是我的download list裏有五十本已下載移位的漫畫，那我下載新的五十一本的時候，app也會同時下載前五十本的檔案夾和.thumb檔。

### 预期行为 / Expected behaviour

app應該只下載現選的漫畫，而不是重新下載以前所有被下載過的漫畫的檔案夾

### 实际行为 / Actual Behaviour

要是我的download list裏有五十本已下載移位的漫畫，那我下載新的五十一本的時候，app也會同時下載前五十本的檔案夾和.thumb檔。

### EhViewer 版本号 / EhViewer version code

1.8.8.3

### EhViewer CI 版本 / EhViewer CI Version

afbe0a4

### Android 系统版本 / Android version

Android 13

### 设备型号 / Device model

Pixel 4

### SoC 型号 / Soc model

不知, 對不起

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
只要那个画廊在你的下载数据库里
你每次浏览下载界面的时候 如果缩略图不在 就肯定会存进去

**Comment by newbiegituserj** [comment]
> 只要那个画廊在你的下载数据库里 你每次浏览下载界面的时候 如果缩略图不在 就肯定会存进去
感謝回答
要如何把下載界面裏的漫畫清除掉？謝謝
