### ISSUE TITLE
进不去，打不开，不管是不是连着梯子

### ISSUE THREAD

**Issue by WWH2002** [Ehviewer-Overhauled/Ehviewer#1178]
### 复现步骤 / Step to reproduce

打开之后什么都没有，只有个哭泣机器人，之前还只是偶尔刷不出来东西，然后连上梯子关上域名前置就又能看，但现在是不管连不连梯子都没有东西，连着梯子显示页面无内容，不连梯子就显示连接超时

### 预期行为 / Expected behaviour

按理说因该能刷出来东西

### 实际行为 / Actual Behaviour

![Screenshot_2023-06-24-01-20-07-939_moe tarsin ehviewer](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/95118914/1c1ee480-6021-490d-af00-42c50b611cae)
连着梯子就显示这个，不连就显示连接超时

### 应用日志 / App logs

日志解压出来什么都没有就像这样
![Screenshot_2023-06-24-01-22-36-744_com android fileexplorer](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/95118914/1bad25f7-b51f-4118-8964-5aa6c5c759df)
![Screenshot_2023-06-24-01-22-33-911_com android fileexplorer](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/95118914/21aed8b7-3839-4b3d-b685-69874a4f520e)

### EhViewer 版本号 / EhViewer version code

1.8.8.3

### EhViewer CI 版本 / EhViewer CI Version

afbe0a4

### Android 系统版本 / Android version

MIUI14.0.5.0.TGACNXM，Android13

### 设备型号 / Device model

小米10s

### SoC 型号 / Soc model

骁龙870

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by UjuiUjuMandan** [comment]
> 现在挂梯子也进不去是啥情况

> 现在是挂梯子也不行了？

> 还没修完？
