### ISSUE TITLE
[UX] Completing supported mimetype/extensions in AndroidManifest.xml

### ISSUE THREAD

**Issue by flosnvjx** [Ehviewer-Overhauled/Ehviewer#118]
### What we already have
Atm, only `zip`, `rar`, and `7z` is listed in manifest.  These are sufficient in terms of eh torrent archive since most archives come with a `zip` extension (h@h only produce zip file, and sometimes scanlation group seed `rar` or `7z` archive on their own)

For better UX we could add a few for completeness, see below.

### What we could complete
- `cbz`, altho this extension could be hardly found on eh or some scanlation publish forum (say, south+), but afaik there is already [a popular comic reading app -- which is capable to read nh/etc -- ](https://github.com/tachiyomiorg/tachiyomi/search?q=cbz) produce zip comic archive after this extension.  See wikipedia entry comicbook format for detail, in short it is technically a zip comic archive like we DL'd from gallery torrent but the extension is semantically distinctive from arbitrary zip archive file.
  - Furthermore, some personal cloud storage provider is known to block comic archive by hash after someone unexpectly clicked to expand the archive online.  By uploading the comic archive with a `cbz` extension we can prevent the archive from being expanded by PCS (altho this trick won't work for a few aggressive providers).
- `cbr`, `cb7`, ditto.
- `tar` is supported in libarchive and support for tar is mentioned in #35, in my test it is well supported and image could be loaded in a streaming manner.
  - `tar.gz` / `tgz`, afaicr zlib is pulled from our current pipeline setup and supported by CI build atm.
  - `tar.xz` / `txz`, #35
  - `cbt`, comicbook extension for tar comic archive.  There is no distinctive extension for different compressor variants but it does not matter 'cause libarchive will take care of the "filter" detection regardless the actual extension.  Futher interesting thing is there is no PCS provider seems to support online expanding of these \*nix glue archive format -- no more hash kill.

### 其他细节 / Addition details

For mimetypes, see https://github.com/multiSnow/mcomix3/blob/483f4b3f2d9a125606d47597ae7eff3b38e5bf9d/mcomix/mcomix/constants.py#L81 for a ref.

I am not an android dev btw, so the actual mimetype string may need some test before copy linux ones.

### EhViewer 版本号 / EhViewer version code

1.7.29.0

### EhViewer CI 版本 / EhViewer CI Version

N/A

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by asuka-mio** [comment]
Thanks, I'll take a closer look.
