### ISSUE TITLE
转移本地下载数据时必须联网

### ISSUE THREAD

**Issue by qjmltz** [Ehviewer-Overhauled/Ehviewer#1182]
### 复现步骤 / Step to reproduce

当把软件删掉重新安装时，导出数据到重新安装的软件。
本地下载的画廊目录导入没有问题，但无网络的情况下不能打开，提示error。

### 预期行为 / Expected behaviour

在导入数据以后，无网络的情况下也可以看本地画廊

### 实际行为 / Actual Behaviour

无网络情况下打开本地画廊会黑屏。

### EhViewer 版本号 / EhViewer version code

1.8.8.3

### EhViewer CI 版本 / EhViewer CI Version

afbe0a4

### Android 系统版本 / Android version

MIUI13

### 设备型号 / Device model

小米10

### SoC 型号 / Soc model

骁龙865

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
必须联网
你家网费这么缺吗 连个网都要斤斤计较

**Comment by asuka-mio** [comment]
这不是一个设计上就为了离线使用的app
提供下载功能是节省以后再次阅读下载图片的时间
并不是为了在各种情况下离线使用
