### ISSUE TITLE
下载归档也要出现在已下载列表中

### ISSUE THREAD

**Issue by UjuiUjuMandan** [Ehviewer-Overhauled/Ehviewer#1209]
### 需求 / Requirement

像隔壁 [JHenTai](https://github.com/jiangtian616/JHenTai) 一样，下载画廊归档同样出现在下载列表中，而不是另外存储在系统下载目录下，需要另外用 EhViewer 打开。

### 建议实现 / Suggested implements

下载归档之后解压缩并按照普通下载的格式存储在 EhViewer 设定的下载目录下，并删除压缩包。

### 备注 / Addition details

如果可能，把现在的下载方式删了是最推荐的。下载归档是E站推荐的方式，而现在爬图的下载方式...

> EhViewer 下载本子的方式就是把整个画廊所有的图片都请求一遍、因此每张图片都要请求一次 EH API；反而你在 EH 上下载本子，要么使用种子、要么使用 Archive Download，下载一个画廊只需要请求 EH API 一次、不会对 EH API 造成压力。EhViewer 这种 bypass EH Archive Download 的行为本身就是错误的。
> -- [OnceForAll](https://forums.e-hentai.org/index.php?showtopic=257252&st=5920&p=6235283&#entry6235283)

### EhViewer 版本号 / EhViewer version code

1.8.9.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

52c2131

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by asuka-mio** [comment]
#405

**Comment by asuka-mio** [comment]
在重构整个下载系统的时候会考虑的
