### ISSUE TITLE
没有绕过 Content Warning 页面

### ISSUE THREAD

**Issue by UjuiUjuMandan** [Ehviewer-Overhauled/Ehviewer#1227]
### 复现步骤 / Step to reproduce

1. 切换站点到 e-hentai 。
2. 打开 https://e-hentai.org/g/2586122/9dd5aeee03/ 。

### 预期行为 / Expected behaviour

~~EhViewer 应该请求 [View Gallery](https://e-hentai.org/g/2586122/9dd5aeee03/?nw=session) 或者 [Never Warn Me Again](https://e-hentai.org/g/2586122/9dd5aeee03/?nw=always) 来绕过警告，继续解析网页。~~

Cookie 中应该包括 `nw=1` 并传递给网站，这个警告就不会出现。

### 实际行为 / Actual Behaviour

出现解析失败。

### 应用日志 / App logs

[logcat-2023-07-08-00-04-34-212.txt](https://github.com/Ehviewer-Overhauled/Ehviewer/files/11984718/logcat-2023-07-08-00-04-34-212.txt)

解析错误的页面: 
[2023-07-08-00-04-24-457.txt](https://github.com/Ehviewer-Overhauled/Ehviewer/files/11984727/2023-07-08-00-04-24-457.txt)
[2023-07-07-23-49-43-199.txt](https://github.com/Ehviewer-Overhauled/Ehviewer/files/11984730/2023-07-07-23-49-43-199.txt)
[2023-07-07-23-49-33-469.txt](https://github.com/Ehviewer-Overhauled/Ehviewer/files/11984732/2023-07-07-23-49-33-469.txt)

### 备注 / Addition details

看了下 [EHWiki](https://ehwiki.org/wiki/Technical_Issues/Chinese) 的介绍，这个警告只要 Cookie 里有 `nw=1` 就不会出现，看[EhCookieStore.kt](https://github.com/Ehviewer-Overhauled/Ehviewer/blob/1.8.x.x/app/src/main/java/com/hippo/ehviewer/client/EhCookieStore.kt)也是有处理这个值的，但是为什么还会出现呢？

### EhViewer 版本号 / EhViewer version code

1.8.9.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

4e1b4dd

### Android 系统版本 / Android version

Android 13

### 设备型号 / Device model

No Response

### SoC 型号 / Soc model

No Response

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by UjuiUjuMandan** [comment]
经测试，只有 https://github.com/Ehviewer-Overhauled/Ehviewer/commit/9dfc1324ad634e28a7271ca5188c3f3acb610c11 及其之后的 EhViewer 有这个问题。

**Comment by asuka-mio** [comment]
cronet没走那个路径 只有okhttp走了 一会我修上
