### ISSUE TITLE
Original version is more resilient to network filters

### ISSUE THREAD

**Issue by mirh** [Ehviewer-Overhauled/Ehviewer#1228]
### 复现步骤 / Step to reproduce

0. Sit behind an ISP that blocks the incoming traffic from the ex servers
1. Try to load anything

### 预期行为 / Expected behaviour

Ideally, everything should just work, but of course the app can just do so much when the network isn't cooperative. 

Once upon a time I was simply getting a "network error" message and nothing else, though since a few months the situation improved significantly. 
The gallery list finally started to work, at least the preview for the first picture (i.e. the one which is also the cover) does load, and everything is kinda how you'd expect it to be once you open the actual individual images. 
This is only with the original ehviewer though. 

### 实际行为 / Actual Behaviour

In inverter and overhauled (I also tried 1.7.24.1 btw) every single preview is broken. 
The bare minimum of an expectation would be getting at least the first one to load, but in the best case scenario my hope would be that we could figure a workaround for all the others too. 

### 应用日志 / App logs

There doesn't appear to be anything network-specific in them. 

### 备注 / Addition details

The original EhViewer, the fork by dujiaoxi404 and SXJ all works fine-ish in this regard. 

### EhViewer 版本号 / EhViewer version code

1.8.8.3

### EhViewer CI 版本 / EhViewer CI Version

afbe0a4

### Android 系统版本 / Android version

9

### 设备型号 / Device model

XZ2

### SoC 型号 / Soc model

Come on really?

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
Feature removed https://github.com/Ehviewer-Overhauled/Ehviewer/commit/2d20da70b8922e0b9988b007c31d970217691cb3

**Comment by FooIbar** [comment]
> Feature removed [2d20da7](https://github.com/Ehviewer-Overhauled/Ehviewer/commit/2d20da70b8922e0b9988b007c31d970217691cb3)

Not related to that. The original version doesn't even have that feature.

Though this app is not designed to solve network issues.
If you're unable to load images in web browser, you can't do it in app either.
Try finding a generic solution for your network, like a VPN or sth.

**Comment by mirh** [comment]
Indeed, this is has nothing to do with DNS or domain fronting (in fact, the later actually causes everything not to work). 
Thing is, there has probably been some very stupid change during the years that made a difference. 
I would try to further help with bisecting but you don't offer releases older than 2022.

**Comment by txyyh** [comment]
I think your ISP just enhanced their network filters in the past

And, Foolbar said above, this app won't solve network issues. Find other solutions instead.

**Comment by mirh** [comment]
The app is doing something to make them worse, and I wanted to understand what. 
It may even be that was a regression "worth having" then, but it's kind of difficult to argue without a clue. 

FWIW after a very lazy wireshark run I found out that while the OG version establishes and uses a connection with ehgt.org (81.171.10.48) after the initial handshake, EH-OH always seems to stick with the normal 188.114.96.7 server.

**Comment by FooIbar** [comment]
> The app is doing something to make them worse, and I wanted to understand what. It may even be that was a regression "worth having" then, but it's kind of difficult to argue without a clue.
> 
> FWIW after a very lazy wireshark run I found out that while the OG version establishes and uses a connection with ehgt.org (81.171.10.48) after the initial handshake, EH-OH always seems to stick with the normal 188.114.96.7 server.

Seems something went wrong with your DNS.
188.114.96.7 is not one of ehgt.org's [IPs](https://ehwiki.org/wiki/IPs).

The OG version uses 81.171.10.48 cus you have built-in hosts enabled.
https://github.com/seven332/EhViewer/blob/ba6d41b91f53b0835f73fb2903b5c4ff1259786c/app/src/main/java/com/hippo/ehviewer/client/EhDns.java#L45C21

**Comment by mirh** [comment]
AFAICT my dns is the evergreen 8.8.8.8, and 188.114.96.7 is the main address for exhentai, not ehgt (even though it's not stated on the page.. probably it's just out of date). 

But while the old version switches to the later after a few packets are exhanged (at least to show the previews) OH always seems to stick to the former. 
Which is not wrong per se (I mean, how else could I even establish a connection with the website otherwise?) except I just found out that content is served from [completely](https://ehgt.org/82/3b/823bef28ec94f3e82181f472587200e04feaeea7-905017-857-1200-jpg_250.jpg) [different](https://s.exhentai.org/t/82/3b/823bef28ec94f3e82181f472587200e04feaeea7-905017-857-1200-jpg_250.jpg) servers. 

I don't have built-in hosts enabled anywhere btw, and if I turn them on here everything stops to work.

**Comment by FooIbar** [comment]
> 



> AFAICT my dns is the evergreen 8.8.8.8, and 188.114.96.7 is the main address for exhentai, not ehgt (even though it's not stated on the page.. probably it's just out of date).
> 
> But while the old version switches to the later after a few packets are exhanged (at least to show the previews) OH always seems to stick to the former. Which is not wrong per se (I mean, how else could I even establish a connection with the website otherwise?) except I just found out that content is served from [completely](https://ehgt.org/82/3b/823bef28ec94f3e82181f472587200e04feaeea7-905017-857-1200-jpg_250.jpg) [different](https://s.exhentai.org/t/82/3b/823bef28ec94f3e82181f472587200e04feaeea7-905017-857-1200-jpg_250.jpg) servers.
> 
> I don't have built-in hosts enabled anywhere btw, and if I turn them on here everything stops to work. EDIT: lol, I think I probably found the cause https://github.com/seven332/EhViewer/blob/ba6d41b91f53b0835f73fb2903b5c4ff1259786c/app/src/main/java/com/hippo/ehviewer/client/EhUrl.java#L207L215 If you could just add a switch to do the same for every picture, I'd be really happy.

Ah, I see. So you're using exhentai, thus the thumb server would be `s.exhentai.org`, not `ehgt.org`
We do have provided an option to force using e-hentai's thumb server b5b096a, but it's not released yet.
You can download the latest dev build from [actions](https://github.com/Ehviewer-Overhauled/Ehviewer/actions) if you can't wait, though the dev version may be unstable.

**Comment by mirh** [comment]
Damn, I can't believe I finally took the bother to look into the issue exactly one week after it had been solved...
Fixed by #1199.
