### ISSUE TITLE
Support In-app language picker and the new APIs for per-app language preferences

### ISSUE THREAD

**Issue by txyyh** [Ehviewer-Overhauled/Ehviewer#128]
https://developer.android.google.cn/about/versions/13/behavior-changes-all#language-pickers

**Comment by asuka-mio** [comment]
This is completed

**Comment by txyyh** [comment]
Not completed.

![6330191842347430090_121](https://user-images.githubusercontent.com/41893946/184791879-0d944f74-81f3-498e-80d4-6cfb23d53d88.jpg)
![Screenshot_20220816_112531](https://user-images.githubusercontent.com/41893946/184791893-ed8a3dec-3800-484a-854a-fbbe14c96c4c.png)

**Comment by txyyh** [comment]
It looks easy.
I will try to impl it
