### ISSUE TITLE
“QUIC 支持”选项失效

### ISSUE THREAD

**Issue by Pony-CW** [Ehviewer-Overhauled/Ehviewer#1300]
### 复现步骤 / Step to reproduce

0.清除缓存
1.打开软件

### 预期行为 / Expected behaviour

正常访问

### 实际行为 / Actual Behaviour

Connection reset 网络错误
![Screenshot_2023-07-28-00-42-56-62_f2f1746601bf3b868d00d5efaf12e601](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/44076275/2834f3b8-fe9c-4c35-b7d5-d1dbef374868)

### 应用日志 / App logs

[log-2023-07-28-00-41-12-481.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/12186173/log-2023-07-28-00-41-12-481.zip)

### 备注 / Addition details

* 已开启“[实验性] QUIC 支持”，无任何效果
* 系统 DNS 已选择“私人 DNS”==>“指定 DNS 服务器”，指定为 DoT "dns.google"
* “Connection reset”字样在限额查询中发现
* 在 CI d79dc0c 无任何问题

> 题外话，在之前，QUIC 支持选项开启时，如果是 DNS 解析出污染的 IP，会显示“奇怪的错误”

### EhViewer 版本号 / EhViewer version code

1.8.9.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

0265ddc

### Android 系统版本 / Android version

ColorOS 13.1 PGZ110_13.1.0.182(CN01) / Android 13

### 设备型号 / Device model

一加 Ace 竞速版 / OnePlus Ace Racing Edition / PGZ110

### SoC 型号 / Soc model

天玑 8100-MAX / Dimensity 8100-MAX

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
啊这 你是用quic直连吗
那你最近先别更吧 我又开始重构了

**Comment by asuka-mio** [comment]
而且在正式版后quic只会支持Android14以上

**Comment by Pony-CW** [comment]
> 而且在正式版后quic只会支持Android14以上

14以上啊这…

**Comment by FooIbar** [comment]
这是因为现在只有下载图片会走quic，网页不会
不过用quic来直连本来就不太可靠，会时不时受干扰
