### ISSUE TITLE
下载界面列表，标题的文本重叠

### ISSUE THREAD

**Issue by chenodin1** [Ehviewer-Overhauled/Ehviewer#1304]
### 复现步骤 / Step to reproduce

重新安装app后，导入数据，在下载界面，标题显示出现问题

### 预期行为 / Expected behaviour

预期显示正常

### 实际行为 / Actual Behaviour

![29c3ddf0b4eb9a3170460250aceabac](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/117867866/eea82eb1-34c4-4cd1-bfe6-94889a557b5d)

### EhViewer 版本号 / EhViewer version code

1.8.8.3

### EhViewer CI 版本 / EhViewer CI Version

afbe0a4

### Android 系统版本 / Android version

rmx3708+android13

### 设备型号 / Device model

真我gtneo5

### SoC 型号 / Soc model

骁龙8+1代

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
`您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决`
我咋记得修过呢

**Comment by chenodin1** [comment]
> 
[图片]
应该是最新版本吧，这个

**Comment by chenodin1** [comment]
![e417cb38332c79e5b341679b6b65643](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/117867866/83c86b36-1a1a-4967-89ac-72f10aa596d5)

**Comment by txyyh** [comment]
去看Q&A，或者自己搜也可以啊
