### ISSUE TITLE
清空搜索历史记录

### ISSUE THREAD

**Issue by wordlesswind** [Ehviewer-Overhauled/Ehviewer#1306]
### 需求 / Requirement

感觉太过冗长的搜索历史记录不是很有必要，毕竟实在喜欢的话，会添加至快速搜索里。

夫人，你也不想让伴侣在 EhViewer 的搜索记录被发现吧？（不是

### 建议实现 / Suggested implements

允许清空搜索记录，以及类似于网页浏览器一样只显示最近几条，单独使用一个页面展示完整记录。

### EhViewer 版本号 / EhViewer version code

1.8.9.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

63a8325

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by FooIbar** [comment]
有必要单独搞个页面吗，毕竟ehv不是一个真正的浏览器

**Comment by wordlesswind** [comment]
那就能清空就好了
