### ISSUE TITLE
默认收藏夹功能消失了

### ISSUE THREAD

**Issue by tiger-git2022** [Ehviewer-Overhauled/Ehviewer#1319]
### 需求 / Requirement

采用新的收藏页面之后，没有默认收藏夹功能了，每次都需要重新选择

### 建议实现 / Suggested implements

和原来一样，有默认收藏夹的设置，点击直接收藏

### EhViewer 版本号 / EhViewer version code

1.8.9.0

### EhViewer CI 版本 / EhViewer CI Version

717e219

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by FooIbar** [comment]
这是有意移除的，作为支持收藏备注的一部分 #1217
因为这两个功能不协调，不过其他人可能有不同的想法

**Comment by tiger-git2022** [comment]
> 这是有意移除的，作为支持收藏备注的一部分 #1217 因为这两个功能不协调，不过其他人可能有不同的想法

那很蛋疼啊，我完全用不到收藏备注，但会大批量收藏，默认收藏算是刚需，这下只能老版本养老了

**Comment by FooIbar** [comment]
这个现在加到设置里了
![Screenshot_20230804_180101](https://github.com/Ehviewer-Overhauled/Ehviewer/assets/118464521/5eb3efb6-4b2f-4d92-a5ee-4c59f281640c)

**Comment by FooIbar** [comment]
> 草 你dialog咋没scrim（

这好像也是 Android 14 上的问题
