### ISSUE TITLE
返回逻辑

### ISSUE THREAD

**Issue by tmby** [Ehviewer-Overhauled/Ehviewer#1342]
### 复现步骤 / Step to reproduce

0.打开Ehviewer
1.执行搜索
2.返回

https://github.com/Ehviewer-Overhauled/Ehviewer/assets/88327304/0d335593-2dee-4536-8eb9-d05b04c2b10c

### 预期行为 / Expected behaviour

它应该清除搜索内容，返回前一个界面

### 实际行为 / Actual Behaviour

退出应用

### 备注 / Addition details

如果进入首页后，点击其他页面，执行搜索，会返回到首页，也就是前前界面

### EhViewer 版本号 / EhViewer version code

1.8.9.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

310be05

### Android 系统版本 / Android version

HarmonyOS 4.0.0.108

### 设备型号 / Device model

HUAWEI Nova 9 Pro

### SoC 型号 / Soc model

高通骁龙778G 4G

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by tmby** [comment]
本人搜索以后，想返回首页去看热门，返回的时候以为会回到首页，但是是直接退出了，再点进去还是搜索界面，得杀后台才能重新进入首页，用着很不舒服。

**Comment by FooIbar** [comment]
直接退出是预期行为，原版就是这样的

> 本人搜索以后，想返回首页去看热门，返回的时候以为会回到首页，但是是直接退出了

为什么看热门要返回首页，热门的入口在左侧的导航抽屉里


> 再点进去还是搜索界面，得杀后台才能重新进入首页

这个 [1.8.9.0](https://github.com/FooIbar/EhViewer/releases) 已经修了

**Comment by tmby** [comment]
> 直接退出是预期行为，原版就是这样的
> 
> > 本人搜索以后，想返回首页去看热门，返回的时候以为会回到首页，但是是直接退出了
> 
> 为什么看热门要返回首页，热门的入口在左侧的导航抽屉里
> 
> 
> > 再点进去还是搜索界面，得杀后台才能重新进入首页
> 
> 这个 [1.8.9.0](https://github.com/FooIbar/EhViewer/releases) 已经修了

我设置的启动页是热门，也就是我说的首页，然后搜索以后，我以为点返回会回到前一个界面，也是就是热门，但是是直接退出，而不是返回到首页

**Comment by FooIbar** [comment]
https://github.com/FooIbar/EhViewer/commit/6e00a4133c48afb0ea491a04ab5be7cb44a5bdcc
现在搜索后可以导航抽屉进入热门

**Comment by tmby** [comment]
> https://github.com/FooIbar/EhViewer/commit/6e00a4133c48afb0ea491a04ab5be7cb44a5bdcc
> 现在搜索后可以导航抽屉进入热门

嗯，这样也可以，不过我希望的是返回

比如说我启动页是热门，然后点击排行，进入排行页面后返回，可以返回到热门（也就是启动页）

但是如果我在启动页执行搜索，再返回，就和直接在启动页返回的效果一样，都是退出软件

我希望执行搜索之后再返回回到之前的页面，而不是直接退出

**Comment by FooIbar** [comment]
https://github.com/FooIbar/EhViewer/commit/c34ba56896802def8c23ae4ee460ab2a5a3144bb
在主页、订阅页面执行搜索会留在当前页面，返回会直接退出
在热门、排行页面执行搜索会跳转到新页面，返回会回原页面

**Comment by tmby** [comment]
> https://github.com/FooIbar/EhViewer/commit/c34ba56896802def8c23ae4ee460ab2a5a3144bb
> 在主页、订阅页面执行搜索会留在当前页面，返回会直接退出
> 在热门、排行页面执行搜索会跳转到新页面，返回会回原页面

谢谢您，解决的很好
