### ISSUE TITLE
点击本地收藏应用闪退

### ISSUE THREAD

**Issue by tmby** [Ehviewer-Overhauled/Ehviewer#1345]
### 复现步骤 / Step to reproduce

0.打开软件
1.点击收藏
2.点击本地收藏
3.进入某收藏画廊

https://github.com/Ehviewer-Overhauled/Ehviewer/assets/88327304/58d4f339-5cc5-4883-9635-695b373c2f26

### 预期行为 / Expected behaviour

正常进入画廊界面

### 实际行为 / Actual Behaviour

闪退

### 应用日志 / App logs

[log-2023-08-15-15-01-30-579.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/12341949/log-2023-08-15-15-01-30-579.zip)

### 备注 / Addition details

亲爱的 @FooIbar 
在使用您的版本时，我遇到了点击本地收藏应用闪退的问题。

### EhViewer 版本号 / EhViewer version code

1.8.9.1

### EhViewer CI 版本 / EhViewer CI Version

63f9c8d

### Android 系统版本 / Android version

HarmonyOS 4.0.0.108

### 设备型号 / Device model

HUAWEI Nova 9 Pro

### SoC 型号 / Soc model

高通骁龙778G 4G

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
于 https://github.com/FooIbar/EhViewer/commit/eee0f2dded4fd748a8e671f865719080a26646e5 修复
其实不用 @ 的，开了 issue 我会收到通知

**Comment by 1175347013** [comment]
发错仓库了，这个仓库还是1.8.8.3
