### ISSUE TITLE
标题复制

### ISSUE THREAD

**Issue by LinYves** [Ehviewer-Overhauled/Ehviewer#1365]
### 需求 / Requirement

在本子详情页中增加标题复制功能

### 建议实现 / Suggested implements

在本子详情页中，长按标题触发自动复制完整标题，可参考哔哩哔哩APP的复制bv号/简介功能

### EhViewer 版本号 / EhViewer version code

1.8.8.3

### EhViewer CI 版本 / EhViewer CI Version

afbe0a4

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by FooIbar** [comment]
点封面右侧的信息栏复制
________________________________
发件人: LinYves ***@***.***>
发送时间: 2023年8月30日 23:41
收件人: Ehviewer-Overhauled/Ehviewer ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Ehviewer-Overhauled/Ehviewer] 标题复制 (Issue #1365)


需求 / Requirement

在本子详情页中增加标题复制功能

建议实现 / Suggested implements

在本子详情页中，长按标题触发自动复制完整标题，可参考哔哩哔哩APP的复制bv号/简介功能

备注 / Addition details

No response

EhViewer 版本号 / EhViewer version code

1.8.8.3

EhViewer CI 版本 / EhViewer CI Version

afbe0a4<https://github.com/Ehviewer-Overhauled/Ehviewer/commit/afbe0a4de55804bab58389b1836d1905c788c27e>

自查步骤 / Verify steps

  *    如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
  *    您已仔细查看并知情 Q&A<https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61> 中的内容 / You have checked Q&A<https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61> carefully
  *    您已搜索过 Issue Tracker<https://github.com/Ehviewer-Overhauled/Ehviewer/issues>，没有找到类似内容 / I have searched on Issue Tracker<https://github.com/Ehviewer-Overhauled/Ehviewer/issues>, No duplicate or related open issue has been found
  *    您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
  *    您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

―
