### ISSUE TITLE
进入下载页面，下载页面中含有已被删除的画廊下载项目，出现闪退

### ISSUE THREAD

**Issue by VoidxHoshi** [Ehviewer-Overhauled/Ehviewer#148]
### 复现步骤 / Step to reproduce

1. 下载一个画廊
2. 此画廊被删除
3. 进入下载页面
4. 闪退

### 预期行为 / Expected behaviour

无闪退行为

### 实际行为 / Actual Behaviour

出现闪退行为

### EhViewer 版本号 / EhViewer version code

1.8.0.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/2759924231

### Android 系统版本 / Android version

MIUI 13

### 设备型号 / Device model

Redmi K30 Pro

### SoC 型号 / Soc model

骁龙888

### 应用日志 / App logs

[logcat-2022-07-30-22-18-10-486.txt](https://github.com/Ehviewer-Overhauled/Ehviewer/files/9226712/logcat-2022-07-30-22-18-10-486.txt)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
被删除是指文件夹在磁盘上被删除还是e站那边被删除了？
