### ISSUE TITLE
Migrate to androidx navigation

### ISSUE THREAD

**Issue by asuka-mio** [Ehviewer-Overhauled/Ehviewer#152]
https://developer.android.com/about/versions/13/features/predictive-back-gesture#migrate-androidx

**Comment by asuka-mio** [comment]
https://developer.android.google.cn/jetpack/androidx/releases/navigation

**Comment by tehcneko** [comment]
navigation 的我也有个分支，不过只做了一半

**Comment by asuka-mio** [comment]
> https://developer.android.com/about/versions/13/features/predictive-back-gesture#migrate-androidx

看起来提拉米苏实现的还是有点问题 划半路撤回去的时候还带闪屏的 而且就支持个预览启动器 先不着急了，等翻转蛋糕再说
