### ISSUE TITLE
点击下载闪退

### ISSUE THREAD

**Issue by wordly123** [Ehviewer-Overhauled/Ehviewer#154]
### 复现步骤 / Step to reproduce

1.打开app点击某个画廊进行下载菜单 此时是可以的看到下载的画廊点击阅读都没啥问题
2.完全退出app 再进入点下载菜单直接闪退回到手机桌面

### 预期行为 / Expected behaviour

显示下载列表

### 实际行为 / Actual Behaviour

闪退

### EhViewer 版本号 / EhViewer version code

1.8.0.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/runs/7599433895?check_suite_focus=true

### Android 系统版本 / Android version

android 12.0

### 设备型号 / Device model

RMX3366

### SoC 型号 / Soc model

Qualcomm Snapdragon 870

### 应用日志 / App logs

--------- beginning of crash
07-31 23:33:31.379 31703 19094 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x5c0020 in tid 19094 (Conaco-Disk-11), pid 31703 (tarsin.ehviewer)
07-31 23:33:32.078 19102 19102 F DEBUG   : Process name is moe.tarsin.ehviewer, not key_process
07-31 23:33:32.078 19102 19102 F DEBUG   : keyProcess: 0
07-31 23:33:32.078 19102 19102 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-31 23:33:32.078 19102 19102 F DEBUG   : Build fingerprint: 'realme/RMX3366/RE546F:12/RKQ1.211103.002/R.202207051443:user/release-keys'
07-31 23:33:32.078 19102 19102 F DEBUG   : Revision: '0'
07-31 23:33:32.078 19102 19102 F DEBUG   : ABI: 'arm64'
07-31 23:33:32.078 19102 19102 F DEBUG   : Timestamp: 2022-07-31 23:33:31.543424482+0800
07-31 23:33:32.078 19102 19102 F DEBUG   : Process uptime: 0s
07-31 23:33:32.078 19102 19102 F DEBUG   : Cmdline: moe.tarsin.ehviewer
07-31 23:33:32.078 19102 19102 F DEBUG   : pid: 31703, tid: 19094, name: Conaco-Disk-11  >>> moe.tarsin.ehviewer <<<
07-31 23:33:32.078 19102 19102 F DEBUG   : uid: 10430
07-31 23:33:32.078 19102 19102 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x5c0020
07-31 23:33:32.078 19102 19102 F DEBUG   :     x0  b400007b76ff3c00  x1  b400007be3e55aa0  x2  0000000000000020  x3  0000000000000001
07-31 23:33:32.078 19102 19102 F DEBUG   :     x4  0000007be3e55ac0  x5  0000007be731f608  x6  0000007be3e34248  x7  0000007be3e34228
07-31 23:33:32.078 19102 19102 F DEBUG   :     x8  00000000005c0000  x9  534ff63b6b971e0b  x10 00000000ffffffff  x11 0000007be731f678
07-31 23:33:32.078 19102 19102 F DEBUG   :     x12 0000007be731f688  x13 0000007be3e341f8  x14 0000000000000000  x15 aaaaaaaaaaaaaaab
07-31 23:33:32.078 19102 19102 F DEBUG   :     x16 0000007bf0909430  x17 0000007c9aa07240  x18 0000007b39952000  x19 b400007b76fdafb0
07-31 23:33:32.078 19102 19102 F DEBUG   :     x20 b400007b76ff3c00  x21 b400007be3e55aa0  x22 0000007be448ffcc  x23 0000000000001071
07-31 23:33:32.078 19102 19102 F DEBUG   :     x24 0000007bfd000880  x25 0000007b859fc000  x26 0000007b859fb3b8  x27 0000007b859fb3b0
07-31 23:33:32.078 19102 19102 F DEBUG   :     x28 0000007b859fb2b0  x29 0000007b859fb1f0
07-31 23:33:32.078 19102 19102 F DEBUG   :     lr  0000007b7a79e1f8  sp  0000007b859fb1f0  pc  0000007c9aa07250  pst 0000000060001000
07-31 23:33:32.078 19102 19102 F DEBUG   : backtrace:
07-31 23:33:32.078 19102 19102 F DEBUG   :       #00 pc 0000000000207250  /system/lib64/libhwui.so (android::ImageDecoder::isAnimated()+16) (BuildId: 4445135ffacfcf46be67b94a556686b2)
07-31 23:33:32.078 19102 19102 F DEBUG   :       #01 pc 000000000001e1f4  /data/app/~~N9JhjU44Je_v95SlzZ3IpA==/moe.tarsin.ehviewer-y5qC6Ulj89ThGeiT3ol78Q==/base.apk!libehviewer.so (BuildId: fb73c64b601372ca76a3c2a183d9c2dffb47560f)
07-31 23:33:32.078 19102 19102 F DEBUG   :       #02 pc 000000000001dc44  /data/app/~~N9JhjU44Je_v95SlzZ3IpA==/moe.tarsin.ehviewer-y5qC6Ulj89ThGeiT3ol78Q==/base.apk!libehviewer.so (Java_com_hippo_image_Image_nativeDecode+216) (BuildId: fb73c64b601372ca76a3c2a183d9c2dffb47560f)
07-31 23:33:32.078 19102 19102 F DEBUG   :       #03 pc 00000000002d7644  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
07-31 23:33:32.078 19102 19102 F DEBUG   :       #04 pc 0000000000209188  /apex/com.android.art/lib64/libart.so (nterp_helper+152) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
07-31 23:33:32.078 19102 19102 F DEBUG   :       #05 pc 00000000001fbfcc  /data/app/~~N9JhjU44Je_v95SlzZ3IpA==/moe.tarsin.ehviewer-y5qC6Ulj89ThGeiT3ol78Q==/base.apk (com.hippo.image.Image.decode+0)
07-31 23:33:32.078 19102 19102 F DEBUG   :       #06 pc 0000000000209124  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
07-31 23:33:32.078 19102 19102 F DEBUG   :       #07 pc 00000000001fb996  /data/app/~~N9JhjU44Je_v95SlzZ3IpA==/moe.tarsin.ehviewer-y5qC6Ulj89ThGeiT3ol78Q==/base.apk (com.hippo.image.ImageBitmap.decode+2)
07-31 23:33:32.078 19102 19102 F DEBUG   :       #08 pc 0000000000209124  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
07-31 23:33:32.078 19102 19102 F DEBUG   :       #09 pc 000000000014cf56  /data/app/~~N9JhjU44Je_v95SlzZ3IpA==/moe.tarsin.ehviewer-y5qC6Ulj89ThGeiT3ol78Q==/base.apk (gw.B+26)
07-31 23:33:32.078 19102 19102 F DEBUG   :       #10 pc 000000000020a044  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 2b417e2566f5eb686666666b6ee952ea)
07-31 23:33:32.078 19102 19102 F DEBUG   :       #11 pc 00000000000b0f40  /data/app/~~N9JhjU44Je_v95SlzZ3IpA==/moe.tarsin.ehviewer-y5qC6Ulj89ThGeiT3ol78Q==/base.apk (W8.doInBackground+108)
07-31 23:33:32.078 19102 19102 F DEBUG   :       #12 pc 000000000058f85c  /system/framework/arm64/boot-framework.oat (android.os.AsyncTask$3.call+172) (BuildId: dc48722bc2d33192a78d87a5955cb011958e8eca)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
1.8.0.4还闪退吗

**Comment by asuka-mio** [comment]
我这已经复现不了了 1.8.0.4的hotfix就是修这个的 先关了 要是还有的话再开吧

**Comment by wordly123** [comment]
1.8.0.4是你刚更新的吧 这版本确实不会闪退了&nbsp; 但是11.8.0.3必定会闪退



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月1日(周一) 凌晨0:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Ehviewer-Overhauled/Ehviewer] 点击下载闪退 (Issue #154)




 
我这已经复现不了了 1.8.0.4的hotfix就是修这个的 先关了 要是还有的话再开吧

**Comment by txyyh** [comment]
你action版本填的是1.8.0.4的吧
请**务必**遵守 issue template 提的要求，谢谢

**Comment by wordly123** [comment]
我提的时候，刚好升级版本的号的那次提交吧 再之前的都是1.8.0.3 你主要是看版本号就行了啊 谁知道下载后的是哪次CI的代码啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月1日(周一) 上午9:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Ehviewer-Overhauled/Ehviewer] 点击下载闪退 (Issue #154)




 
你action版本填的是1.8.0.4的吧
 请务必遵守 issue template 提的要求，谢谢

**Comment by txyyh** [comment]
@wordly123 所以让你填写了 CI 版本的地址用于核查啊

目前开发状态是就一条线，要求上报者使用最新 CI 版本测试可以减少一些不必要的 issue（比如这个）

**Comment by wordly123** [comment]
其实这样无形当中提高了提bug的成本,久而久之我感觉会没人提的，当然这只是我个人的主观看法。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月1日(周一) 下午2:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Ehviewer-Overhauled/Ehviewer] 点击下载闪退 (Issue #154)




 
@wordly123 所以让你填写了 CI 版本的地址用于核查啊
 
目前开发状态是就一条线，要求上报者使用最新 CI 版本测试可以减少一些不必要的 issue
