### ISSUE TITLE
Migrate to androidx room or objectbox?

### ISSUE THREAD

**Issue by asuka-mio** [Ehviewer-Overhauled/Ehviewer#156]
greenDAO is no longer actively maintained, consider
https://developer.android.com/jetpack/androidx/releases/room
and https://github.com/objectbox/objectbox-java which is the successor of greenDAO

**Comment by tehcneko** [comment]
用 ROOM 做数据库的我有有个分支是（

**Comment by asuka-mio** [comment]
> 用 ROOM 做数据库的我有有个分支是（

好诶 给咱用用

**Comment by tehcneko** [comment]
> > 用 ROOM 做数据库的我有有个分支是（
> 
> 好诶 给咱用用

还是 Java 的，也有些小问题没时间没修

**Comment by tehcneko** [comment]
[room.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/9251031/room.zip)

**Comment by asuka-mio** [comment]
> 

谢了，我看看，先把greendao扬了再说，这玩意一年没更了

**Comment by tehcneko** [comment]
我这个改的还没做 Lazyload，历史记录之类的地方

**Comment by tehcneko** [comment]
一次性加载全部可能会比较卡（

**Comment by asuka-mio** [comment]
估计还得有点bug 所以我发的alpha版 之后有时间就完善下
