### ISSUE TITLE
使“详情”列表的缩略图大小可以调整

### ISSUE THREAD

**Issue by 6486449j** [Ehviewer-Overhauled/Ehviewer#193]
### 需求 / Requirement

使“详情”列表的缩略图大小可以调整

### 建议实现 / Suggested implements

在一些设备上，根据dpi计算出来的“详情”列表的缩略图大小可能不尽人意，希望能手动调整。

### EhViewer 版本号 / EhViewer version code

1.8.1.0

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/2845806470

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by txyyh** [comment]
请问下，您指的“缩略图”，指封面图还是指底下的漫画内容缩略图

**Comment by 6486449j** [comment]
![Screenshot_20220812-195341_EhViewer~2](https://user-images.githubusercontent.com/27111822/184349033-6df7708f-bc35-4d3a-912a-f69ce361638b.png)

漫画列表的旁边这些
