### ISSUE TITLE
希望能够优化鼠标滚轮的翻页距离

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [Ehviewer-Overhauled/Ehviewer#196]
### 需求 / Requirement

作者您好，因手持平板翻页太累人了，我有使用蓝牙鼠标连接平板（搭配懒人支架）的习惯
现在默认是滚动一次滚轮 翻一页，希望能改为滚动一次鼠标滚轮翻页20%

### 建议实现 / Suggested implements

Sorry，我对安卓开发一无所知

### EhViewer 版本号 / EhViewer version code

1.7.29.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/2843095635

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by txyyh** [comment]
我们目前不具备对应的环境。因而，所有相关功能的开发可能会有延迟

**Comment by ShoukakuChuuCC** [comment]
大佬，我的平板设备似乎只能安装1.7版本，能麻烦您更新一下1.7版吗？
ps:设备是小米平板5 pro，soc 骁龙870，安装1.8版会提示解析安装包失败

**Comment by txyyh** [comment]
明天我pick下
然后先用ci版本吧

**Comment by txyyh** [comment]
明天我pick下
然后先用ci版本吧

**Comment by txyyh** [comment]
@asuka-mio 不睡吗

**Comment by txyyh** [comment]
https://github.com/txyyh/Ehviewer/actions/runs/2893269507

仅供临时使用

**Comment by ShoukakuChuuCC** [comment]
十分感谢！
