### ISSUE TITLE
可以以txt文本格式，将快速搜索(用户书签栏) 导出。

### ISSUE THREAD

**Issue by HoriYuko** [Ehviewer-Overhauled/Ehviewer#198]
### 需求 / Requirement

在条件允许的情况下，为应用添加可以单独导出/导入用户自定义的书签栏的功能(txt格式) 。

### 建议实现 / Suggested implements

可以考虑参考AdGuard (正版付费) [Android /pc(插件) 中的导入/导出用户自定义配置的应用功能(其中包括txt文本格式)。

### EhViewer 版本号 / EhViewer version code

1.7.29.1

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/download/1.7.29.1

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by txyyh** [comment]
@HoriYuko

**Comment by txyyh** [comment]
@HoriYuko 通过设置-高级-导出数据，可以实现快速搜索列表的导出
这应该可以满足绝大多数场景的需要了

**Comment by txyyh** [comment]
@HoriYuko CI 版本链接错误，请安装测试 https://github.com/Ehviewer-Overhauled/Ehviewer/actions/workflows/ci.yml 中最新的 1.7.x.x 分支的ci版本

**Comment by asuka-mio** [comment]
如果导出只是为了导入的话， 导出导入数据库功能就已经把这个包含在内了

**Comment by HoriYuko** [comment]
其实我想要的是可以直接查看用户自己添加的书签栏(类似于截图中的效果)
![Screenshot_20220816_195751_com mixplorer silver](https://user-images.githubusercontent.com/98299926/184863601-480720e4-90f9-4f77-bc9b-0da9ea4ce323.jpg)
![Screenshot_20220816_195755_com mixplorer silver](https://user-images.githubusercontent.com/98299926/184863647-d4182ef0-ef25-46aa-bdb2-e4d7028db0c1.jpg)
cl版本：arm64-v8a-bf72d772b5ed83ea91ee02a7aabac3b68aaf4a3c
