### ISSUE TITLE
在系统处于亮色模式时，设置和本子详情界面的状态栏消失了

### ISSUE THREAD

**Issue by Walkar66** [Ehviewer-Overhauled/Ehviewer#199]
### 复现步骤 / Step to reproduce

1. 打开Ehviewer
2. 进入设置
3. 进入本子详情界面

### 预期行为 / Expected behaviour

在正常情况下，无论我的系统处于何种颜色模式，Ehviewer的状态栏应该是和背景的颜色相反，即背景颜色时暗色时状态栏图标的颜色应该是白色，亮色时状态栏图标颜色应该是黑色

### 实际行为 / Actual Behaviour

实际上Ehviewer在背景颜色处于亮色模式时，设置和本子详情界面的状态栏并没有自动反色，处于一种消失了的效果，然而其他界面是正常的，然后在暗色背景下，这些在亮色背景有问题的界面的状态栏颜色就都正常了，在我的两个设备和系统版本下均是如此

### EhViewer 版本号 / EhViewer version code

1.8.1.0

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/2847457861

### Android 系统版本 / Android version

MIUI 13.0.12，PixelExperience_Plus 12.1

### 设备型号 / Device model

Xiaomi 11 Pro，Google Pixel 3

### SoC 型号 / Soc model

Snapdragon 845，Snapdragon 888

### 应用日志 / App logs

这是Google Pixel 3
[log-2022-08-15-11-05-18-592.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/9334849/log-2022-08-15-11-05-18-592.zip)

这是Xiaomi 11 Pro
[log-2022-08-15-10-59-29-879.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/9334851/log-2022-08-15-10-59-29-879.zip)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
@Walkar66 CI 版本链接错误，请安装并填写 https://github.com/Ehviewer-Overhauled/Ehviewer/actions/workflows/ci.yml 中列出的最新1.8.x.x分支版本

**Comment by Walkar66** [comment]
> @Walkar66CI 版本链接错误，请安装并填写 https://github.com/Ehviewer-Overhauled/Ehviewer/actions/workflows/ci.yml 中列出的最新1.8.x.x分支版本

已经安装了最新的1.8.x.x的分支版本，问题仍旧存在
