### ISSUE TITLE
请修复一个从原代码分支中继承来的打开错误本子bug

### ISSUE THREAD

**Issue by liuxuming3303** [Ehviewer-Overhauled/Ehviewer#201]
### 复现步骤 / Step to reproduce

1、直接跳转到 大于2 页
2、往下拉动加载前一页
3、在新的一页封面全部加载完成前，旧一页的任一本子的第一次点击，会打开新一页对应位置的本子。新一页加载完成或任意本子页加载完成会让封面和本子详情页正确对应。

### 预期行为 / Expected behaviour

上拉下拉刷新都应该一样让封面和详情页正确对应，在eh的其他分支也有这bug所以是源代码问题。

### 实际行为 / Actual Behaviour

![屏幕截图 2022-08-16 110924](https://user-images.githubusercontent.com/56378343/184790726-7715c0cb-4c32-425f-9093-f3e29a2cfceb.jpg)
![无标题](https://user-images.githubusercontent.com/56378343/184790757-2782708b-b1f9-4274-8556-f2774abc3c7b.jpg)
![无标题](https://user-images.githubusercontent.com/56378343/184790768-e35dfb7d-ebd2-42ee-952e-bc7a75983fda.png)
![无标题3](https://user-images.githubusercontent.com/56378343/184790804-c06ba871-3ad9-44da-9f5d-9076dce82dbe.png)

### EhViewer 版本号 / EhViewer version code

1.8.1.1

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases

### Android 系统版本 / Android version

crDroidOS 8 Android 12

### 设备型号 / Device model

Redmi Note 7 Pro

### SoC 型号 / Soc model

Snapdragon 675

### 应用日志 / App logs

[log-2022-08-16-11-20-55-135.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/9347697/log-2022-08-16-11-20-55-135.zip)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
@liuxuming3303 CI 链接错误
请使用 https://github.com/Ehviewer-Overhauled/Ehviewer/actions/workflows/ci.yml 中最新的 1.8.x.x 分支的workflow产物进行测试

**Comment by liuxuming3303** [comment]
> 

已使用https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/2861326932的arm64-v8a版本，依然存在

**Comment by xb2016** [comment]
试了下，这个问题在触发 `加载上一页` 之后都会出现，和有没有加载完没关系
