### ISSUE TITLE
查看用户邮箱

### ISSUE THREAD

**Issue by HoriYuko** [Ehviewer-Overhauled/Ehviewer#202]
### 需求 / Requirement

在条件允许的情况下，能否添加查看可以在应用中查看用户邮箱的功能？

### 建议实现 / Suggested implements

在主界面的用户名称下显示用户邮箱。

### EhViewer 版本号 / EhViewer version code

1.7.29.2

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/download/1.7.29.3

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by txyyh** [comment]
@HoriYuko CI 链接错误
请使用 https://github.com/Ehviewer-Overhauled/Ehviewer/actions/workflows/ci.yml 中最新的 1.7.x.x 分支的workflow产物进行测试

**Comment by HoriYuko** [comment]
Cl版本：arm64-v8a-bf72d772b5ed83ea91ee02a7aabac3b68aaf4a3c

**Comment by HoriYuko** [comment]
https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.7.29.3
