### ISSUE TITLE
Ehviever 在按退出键(返回)后，不能退出应用。

### ISSUE THREAD

**Issue by HoriYuko** [Ehviewer-Overhauled/Ehviewer#204]
### 复现步骤 / Step to reproduce

1:点击并登陆EhViewer
2:在任意EhViewer 按返回键退出。
3:再次顶点击EhViewer, 发现应用界面仍在上一次打开的页面，并未回到初始界面

### 预期行为 / Expected behaviour

正常情况下在按退出键后，应用应该完全退出，再次登陆后，应用应该处于初始界面。

### 实际行为 / Actual Behaviour

实际应用扔处于上一次打开界面。

### EhViewer 版本号 / EhViewer version code

1.7.29.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/download/1.7.29.3

### Android 系统版本 / Android version

10, EMUI:10.1. 0

### 设备型号 / Device model

HUAWEI mate 30

### SoC 型号 / Soc model

HUAWEI Kirin 990 5G

### 应用日志 / App logs

--------- beginning of system
08-16 10:03:22.379 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:04:02.865 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:05:21.836 20895 20895 D ActivityThread: Won't deliver top position change in state=5
08-16 10:05:49.274 20895 20895 D ActivityThread: Won't deliver top position change in state=5
08-16 10:06:18.732 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:06:54.577 20895 20895 D ActivityThread: Won't deliver top position change in state=5
08-16 10:06:55.145 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:08:38.063 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:08:50.609 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:08:58.038 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:09:03.382 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:09:32.844 20895 20895 D TextClassifierService: No configured system TextClassifierService
08-16 10:09:32.847 20895 20895 D TextClassifierService: No configured system TextClassifierService
08-16 10:09:32.852 20895  9092 D TextClassifierService: No configured system TextClassifierService
08-16 10:11:00.891 20895 20895 D ActivityThread: Won't deliver top position change in state=5
08-16 10:11:07.602 20895 20895 D TextClassifierService: No configured system TextClassifierService
08-16 10:11:07.603 20895 20895 D TextClassifierService: No configured system TextClassifierService
08-16 10:11:07.604 20895  9092 D TextClassifierService: No configured system TextClassifierService
08-16 10:11:41.804 20895 20895 D ActivityThread: Won't deliver top position change in state=5
08-16 10:11:56.107 20895 20895 D ActivityThread: Won't deliver top position change in state=5
08-16 10:12:07.628 20895 20895 D ActivityThread: Won't deliver top position change in state=5
08-16 10:12:20.150 20895 20895 D ActivityThread: Won't deliver top position change in state=5
08-16 10:12:35.301 20895 20895 D ActivityThread: Won't deliver top position change in state=5
08-16 10:12:54.914 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:13:27.337 20895 20895 D ActivityThread: Won't deliver top position change in state=5
08-16 10:14:09.491 20895 20895 D ActivityThread: Won't deliver top position change in state=5
08-16 10:14:31.247 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:14:39.105 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:15:13.529 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:15:24.808 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:15:45.025 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:17:34.592 20895 20895 D ActivityThread: Won't deliver top position change in state=5
08-16 10:19:13.515 20895 20895 D TextClassifierService: No configured system TextClassifierService
08-16 10:19:13.517 20895 20895 D TextClassifierService: No configured system TextClassifierService
08-16 10:19:13.518 20895 31024 D TextClassifierService: No configured system TextClassifierService
08-16 10:19:25.498 20895 20895 D TextClassifierService: No configured system TextClassifierService
08-16 10:19:25.499 20895 20895 D TextClassifierService: No configured system TextClassifierService
08-16 10:19:25.500 20895 12111 D TextClassifierService: No configured system TextClassifierService
08-16 10:22:04.734 20895 20895 D ActivityThread: Won't deliver top position change in state=5
08-16 10:22:21.105 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:22:25.921 20895 20895 D TextClassifierService: No configured system TextClassifierService
08-16 10:22:25.922 20895 20895 D TextClassifierService: No configured system TextClassifierService
08-16 10:22:25.923 20895 10107 D TextClassifierService: No configured system TextClassifierService
08-16 10:22:48.869 20895 20895 D ActivityThread: Won't deliver top position change in state=5
08-16 10:23:34.604 20895 20895 D ActivityThread: Won't deliver top position change in state=5
08-16 10:23:51.701 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:23:56.495 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:24:52.138 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:25:08.070 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:25:15.228 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:25:25.118 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:26:49.405 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:27:07.335 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:27:11.898 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:28:15.359 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:28:39.681 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:28:46.097 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:28:53.373 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:29:30.756 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:29:51.490 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:30:05.778 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:30:45.178 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:31:19.450 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:31:55.260 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:33:27.049 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:33:51.303 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:34:00.422 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:34:14.686 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:36:17.477 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:36:38.397 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:36:46.930 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:37:21.673 20895 20895 D ActivityThread: Won't deliver top position change in state=5
08-16 10:37:23.316 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:37:49.417 20895 20895 W ContentPermission: getContentType, auth is null.
08-16 10:37:54.136 20895 20895 V ActivityThread: callActivityOnCreate
08-16 10:37:54.142 20895 20895 D ActivityThread: add activity client record, r= ActivityRecord{82a9fac token=android.os.BinderProxy@541eb02 {moe.tarsin.ehviewer/com.hippo.ehviewer.ui.SettingsActivity}} token= android.os.BinderProxy@541eb02
08-16 10:38:01.418 20895 20895 D ActivityThread: Won't deliver top position change in state=5
08-16 10:38:03.265 20895 20895 D ActivityThread: Won't deliver top position change in state=5
08-16 10:38:03.696 20895 20895 D ActivityThread: Remove activity client record, r= ActivityRecord{82a9fac token=android.os.BinderProxy@541eb02 {moe.tarsin.ehviewer/com.hippo.ehviewer.ui.SettingsActivity}} token= android.os.BinderProxy@541eb02
08-16 10:38:08.375 20895 20895 D ActivityThread: Remove activity client record, r= ActivityRecord{b1b735f token=android.os.BinderProxy@2cf8e1 {moe.tarsin.ehviewer/com.hippo.ehviewer.ui.MainActivity}} token= android.os.BinderProxy@2cf8e1
08-16 10:46:45.285 17591 17591 D ActivityThread: Attach thread to application
08-16 10:46:45.325 17591 17632 W ContentPermission: getContentType, auth is null.
08-16 10:46:45.342 17591 17591 V ActivityThread: callActivityOnCreate
08-16 10:46:45.359 17591 17591 W ContentPermission: getContentType, auth is null.
08-16 10:46:45.362 17591 17591 D ActivityThread: add activity client record, r= ActivityRecord{7ade67b token=android.os.BinderProxy@2cf8e1 {moe.tarsin.ehviewer/com.hippo.ehviewer.ui.MainActivity}} token= android.os.BinderProxy@2cf8e1
08-16 10:46:46.078 17591 17591 W HwApsManager: HwApsManagerService, registerCallback, start !
08-16 10:47:22.030 17591 17591 D TextClassifierService: No configured system TextClassifierService
08-16 10:47:22.033 17591 17591 D TextClassifierService: No configured system TextClassifierService
08-16 10:47:22.036 17591 20788 D TextClassifierService: No configured system TextClassifierService
08-16 10:47:22.147 17591 20788 D TextClassifierService: No configured system TextClassifierService
08-16 10:47:23.371 17591 17591 D TextClassifierService: No configured system TextClassifierService
08-16 10:47:23.372 17591 20788 D TextClassifierService: No configured system TextClassifierService
08-16 10:47:38.916 17591 17591 W ContentPermission: getContentType, auth is null.
08-16 10:47:50.094 17591 17591 W ContentPermission: getContentType, auth is null.
08-16 10:48:35.734 17591 17591 V ActivityThread: callActivityOnCreate
08-16 10:48:35.742 17591 17591 D ActivityThread: add activity client record, r= ActivityRecord{5fb41cf token=android.os.BinderProxy@2244d94 {moe.tarsin.ehviewer/com.hippo.ehviewer.ui.SettingsActivity}} token= android.os.BinderProxy@2244d94
08-16 10:49:04.894 17591 17591 D ActivityThread: Won't deliver top position change in state=5
08-16 10:49:15.269 17591 17591 D ActivityThread: Won't deliver top position change in state=5
08-16 10:49:17.066 17591 17591 D ActivityThread: Won't deliver top position change in state=5
08-16 10:49:17.483 17591 17591 D ActivityThread: Remove activity client record, r= ActivityRecord{5fb41cf token=android.os.BinderProxy@2244d94 {moe.tarsin.ehviewer/com.hippo.ehviewer.ui.SettingsActivity}} token= android.os.BinderProxy@2244d94
08-16 10:49:30.243 17591 17591 V ActivityThread: callActivityOnCreate
08-16 10:49:30.248 17591 17591 D ActivityThread: add activity client record, r= ActivityRecord{610caea token=android.os.BinderProxy@47fa430 {moe.tarsin.ehviewer/com.hippo.ehviewer.ui.SettingsActivity}} token= android.os.BinderProxy@47fa430
08-16 10:49:40.951 17591 17591 D ActivityThread: Won't deliver top position change in state=4
08-16 11:40:45.046 19967 19967 D ActivityThread: Attach thread to application
08-16 11:40:45.112 19967 20008 W ContentPermission: getContentType, auth is null.
08-16 11:40:45.132 19967 19967 V ActivityThread: callActivityOnCreate
08-16 11:40:45.153 19967 19967 W ContentPermission: getContentType, auth is null.
08-16 11:40:45.156 19967 19967 D ActivityThread: add activity client record, r= ActivityRecord{5a38e75 token=android.os.BinderProxy@2cf8e1 {moe.tarsin.ehviewer/com.hippo.ehviewer.ui.MainActivity}} token= android.os.BinderProxy@2cf8e1
08-16 11:40:45.635 19967 19967 W HwApsManager: HwApsManagerService, registerCallback, start !
08-16 11:40:46.348 19967 19967 V ActivityThread: callActivityOnCreate
08-16 11:40:46.357 19967 19967 D ActivityThread: add activity client record, r= ActivityRecord{18ec207 token=android.os.BinderProxy@2dccc6c {moe.tarsin.ehviewer/com.hippo.ehviewer.ui.SettingsActivity}} token= android.os.BinderProxy@2dccc6c
08-16 11:40:55.815 19967 19967 D ActivityThread: Won't deliver top position change in state=5
08-16 11:40:56.231 19967 19967 D ActivityThread: Remove activity client record, r= ActivityRecord{18ec207 token=android.os.BinderProxy@2dccc6c {moe.tarsin.ehviewer/com.hippo.ehviewer.ui.SettingsActivity}} token= android.os.BinderProxy@2dccc6c
08-16 11:41:03.105 19967 19967 D ActivityThread: Remove activity client record, r= ActivityRecord{5a38e75 token=android.os.BinderProxy@2cf8e1 {moe.tarsin.ehviewer/com.hippo.ehviewer.ui.MainActivity}} token= android.os.BinderProxy@2cf8e1
08-16 12:24:43.298 16318 16318 D ActivityThread: Attach thread to application
08-16 12:24:43.372 16318 16352 W ContentPermission: getContentType, auth is null.
08-16 12:24:43.391 16318 16318 V ActivityThread: callActivityOnCreate
08-16 12:24:43.413 16318 16318 W ContentPermission: getContentType, auth is null.
08-16 12:24:43.416 16318 16318 D ActivityThread: add activity client record, r= ActivityRecord{5a38e75 token=android.os.BinderProxy@2cf8e1 {moe.tarsin.ehviewer/com.hippo.ehviewer.ui.MainActivity}} token= android.os.BinderProxy@2cf8e1
08-16 12:24:48.564 16318 16318 D ActivityThread: Remove activity client record, r= ActivityRecord{5a38e75 token=android.os.BinderProxy@2cf8e1 {moe.tarsin.ehviewer/com.hippo.ehviewer.ui.MainActivity}} token= android.os.BinderProxy@2cf8e1
08-16 13:09:04.051 15183 15183 D ActivityThread: Attach thread to application
08-16 13:09:04.115 15183 15222 W ContentPermission: getContentType, auth is null.
08-16 13:09:04.134 15183 15183 V ActivityThread: callActivityOnCreate
08-16 13:09:04.156 15183 15183 W ContentPermission: getContentType, auth is null.
08-16 13:09:04.159 15183 15183 D ActivityThread: add activity client record, r= ActivityRecord{ffa3226 token=android.os.BinderProxy@2cf8e1 {moe.tarsin.ehviewer/com.hippo.ehviewer.ui.MainActivity}} token= android.os.BinderProxy@2cf8e1
08-16 13:09:04.730 15183 15183 W HwApsManager: HwApsManagerService, registerCallback, start !
08-16 13:09:06.115 15183 15183 V ActivityThread: callActivityOnCreate
08-16 13:09:06.121 15183 15183 D ActivityThread: add activity client record, r= ActivityRecord{bc3c5c0 token=android.os.BinderProxy@1fef7db {moe.tarsin.ehviewer/com.hippo.ehviewer.ui.SettingsActivity}} token= android.os.BinderProxy@1fef7db
08-16 13:09:17.594 15183 15183 D ActivityThread: Won't deliver top position change in state=5

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
CI 链接错误
请使用 https://github.com/Ehviewer-Overhauled/Ehviewer/actions/workflows/ci.yml 中最新的 1.7.x.x 分支的workflow产物进行测试

**Comment by asuka-mio** [comment]
我忘了在哪个android大版本之后 返回手势都是把应用挪到后台， 这应该是挺长时间的特性了， 而且这样就不用每次都冷启动了

**Comment by txyyh** [comment]
也就是说，返回键不完全退出应用而只是退到后台，本就是我们预期的行为
