### ISSUE TITLE
文本重叠

### ISSUE THREAD

**Issue by wordlesswind** [Ehviewer-Overhauled/Ehviewer#205]
### 复现步骤 / Step to reproduce

1. 打开 EhViewer

### 预期行为 / Expected behaviour

正常显示

### 实际行为 / Actual Behaviour

文本重叠

![image](https://user-images.githubusercontent.com/9050713/184808253-72815fbc-4377-474b-a56b-850269c5a08e.jpg)

### EhViewer 版本号 / EhViewer version code

1.8.1.1

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/2861326932

### Android 系统版本 / Android version

ColorOS 12.1

### 设备型号 / Device model

OnePlus 7 Pro

### SoC 型号 / Soc model

Qualcomm® Snapdragon™ 855

### 应用日志 / App logs

[log-2022-08-16-13-07-45-544.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/9348177/log-2022-08-16-13-07-45-544.zip)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
请问下，您选择的缩略图大小是大、中、小的哪一个

**Comment by wordlesswind** [comment]
> 请问下，您选择的缩略图大小是大、中、小的哪一个

![image](https://user-images.githubusercontent.com/9050713/184808938-263ca85d-36e5-442a-ac45-ffc5e2c226aa.jpg)

是中

**Comment by wordlesswind** [comment]
> 请问下，您选择的缩略图大小是大、中、小的哪一个

这个选项似乎失效了，修改后没有变化。

**Comment by asuka-mio** [comment]
![Screenshot_20220816-191209](https://user-images.githubusercontent.com/43900799/184865984-7f814359-27b5-4661-a5c1-f86d23d151f9.png)
用这个调整大小

**Comment by txyyh** [comment]
@asuka-mio 那个滑块吗

**Comment by asuka-mio** [comment]
> @asuka-mio 那个滑块吗

对

**Comment by asuka-mio** [comment]
> @asuka-mio 新feature和旧feature有冲突吗？ 因为之前就有缩略图大小这一设置 后来又有了新实现自定义化 需不需要把似乎失效的旧feature删了？

另外那个是控制画廊详情界面预览图的大小和列数的

**Comment by txyyh** [comment]
> 另外那个是控制画廊详情界面预览图的大小和列数的

那我改下设置中的描述吧
