### ISSUE TITLE
画廊略缩预览图显示未占满

### ISSUE THREAD

**Issue by Pony-CW** [Ehviewer-Overhauled/Ehviewer#207]
### 复现步骤 / Step to reproduce

不需要复现打开就是

### 预期行为 / Expected behaviour

应该占满

### 实际行为 / Actual Behaviour

![Screenshot_20220818_214506](https://user-images.githubusercontent.com/44076275/185420557-04eca9a7-1322-477b-9956-3f2e37f4d19d.JPG)

### EhViewer 版本号 / EhViewer version code

1.7.29.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/2861700718

### Android 系统版本 / Android version

Funtouch OS 9 (Android 8.1.0)

### 设备型号 / Device model

vivo Y81 (V1732T)

### SoC 型号 / Soc model

MediaTek Helio P22 (MT6762V/CB)

### 应用日志 / App logs

> ……
08-18 21:42:03.013 21490 21519 E         : nFreeSize: 1335119872
08-18 21:42:03.016 21490 21519 E         : nFreeSize: 1335119872
08-18 21:42:03.285 21490 21514 E         : nFreeSize: 1335103488
08-18 21:42:03.295 21490 21514 E         : nFreeSize: 1335095296
……

就这样一堆我感觉不用发了

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
https://github.com/Ehviewer-Overhauled/Ehviewer/commit/0190fc07bdc74289a4e16d53fb045e16d9ba81a3

**Comment by txyyh** [comment]
> [0190fc0](https://github.com/Ehviewer-Overhauled/Ehviewer/commit/0190fc07bdc74289a4e16d53fb045e16d9ba81a3)

好

**Comment by txyyh** [comment]
https://github.com/txyyh/Ehviewer/actions/runs/2889018500
请下载测试下这个CI，是否解决了您遇到的问题

**Comment by Pony-CW** [comment]
> https://github.com/txyyh/Ehviewer/actions/runs/2889018500
> 请下载测试下这个CI，是否解决了您遇到的问题

已解决
![Screenshot_20220820_153325.JPG](https://user-images.githubusercontent.com/44076275/185734417-cdae4da7-d13e-4954-9d23-6b1ca09f481c.JPG)
