### ISSUE TITLE
获取一页新本子时点击加载任意本子详情页，新本子加载会卡住

### ISSUE THREAD

**Issue by liuxuming3303** [Ehviewer-Overhauled/Ehviewer#210]
### 复现步骤 / Step to reproduce

1、打开任意非第一页主页本子页
2、下拉刷新新一页，此时上方会转圈显示加载
3、加载完成前，迅速点击任意本子，加载本子详情页
4、返回主页，此时转圈会卡死，新一页无法继续加载显示，也无法下拉
暂时解决办法：输入下一页的页码并跳转，可以杀死卡死的新一页加载，下拉加载恢复正常

### 预期行为 / Expected behaviour

在从本子详情页返回主页时，主页应该在后台已经完成了新页的加载，或继续转圈等待加载中并显示超时或完成新页的显示

### 实际行为 / Actual Behaviour

![屏幕截图 2022-08-19 081938](https://user-images.githubusercontent.com/56378343/185517128-e2473ec1-4e56-4d59-bc71-3fd4977760b9.jpg)
![屏幕截图 2022-08-19 082031](https://user-images.githubusercontent.com/56378343/185517131-2d6d42c4-42ad-4f01-97b1-dd9bb1675cae.jpg)
![屏幕截图 2022-08-19 082118](https://user-images.githubusercontent.com/56378343/185517135-5907f019-eaf0-4988-b16e-234ec4f98cdc.jpg)

### EhViewer 版本号 / EhViewer version code

1.8.1.1

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/2861326932

### Android 系统版本 / Android version

crDroidOS 8.5 Android 12

### 设备型号 / Device model

Xiaomi Redmi Note 7 Pro | violet

### SoC 型号 / Soc model

Snapdragon 675

### 应用日志 / App logs

[log-2022-08-19-08-29-31-675.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/9378362/log-2022-08-19-08-29-31-675.zip)

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
实测并没有停止加载，只是指示加载的动画不会继续进行，如果你等一会等下一页加载完成就可以继续下拉了

**Comment by asuka-mio** [comment]
实测并没有停止加载，只是指示加载的动画不会继续进行，如果你等一会等下一页加载完成就可以继续下拉了

**Comment by asuka-mio** [comment]
issue我会留到等动画修复了再关闭

**Comment by asuka-mio** [comment]
另 最近在忙Android13的bringup 这些事情可能需要过一段时间再处理（

**Comment by liuxuming3303** [comment]
我这边不只是指示加载的动画不会继续进行，或许我没说清楚，第3步 转圈还没消失 新一页的缩略图框架还没加载出来前点击本子，等了几分钟都是不会继续加载的，流量显示0KB速度，填数字跳转下一页杀死 卡死的进程后等一会就能显示下一页，此时下一页的缩略图不管从网速还是显示上都是才真正开始加载
