### ISSUE TITLE
Introduce libarchive context pool

### ISSUE THREAD

**Issue by asuka-mio** [Ehviewer-Overhauled/Ehviewer#213]
Now we only have one libarchive context, libarchive only support stream read, once we wanna to read something we have already read, we must reset the context and read from file/(vm mapping) head, what about introduce a pool which could save multiple libarchive context point to different file index, once we wanna read a single file, search context pool first, use the most recent context before the file index, If there is no context that meets the requirements, create one.
Considering libarchive context with mmap (archive_open_memory) doesn't take much memory, the pool can be quite small.

**Comment by txyyh** [comment]
睡啦睡啦喵～
