### ISSUE TITLE
[Bug]有关鼠标滚轮的操作

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [Ehviewer-Overhauled/Ehviewer#214]
### 复现步骤 / Step to reproduce

1.接入鼠标
2.点击开始阅读

### 预期行为 / Expected behaviour

能直接使用滚轮翻页

### 实际行为 / Actual Behaviour

需要点击一下或者拖动一下，滚轮翻页才正常

### EhViewer 版本号 / EhViewer version code

1.7.29.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/txyyh/Ehviewer/actions/runs/2893269507

### Android 系统版本 / Android version

MIUI 13.0.6

### 设备型号 / Device model

XiaoMi Pad 5 Pro

### SoC 型号 / Soc model

骁龙870

### 应用日志 / App logs

08-21 11:46:42.645  7406  7406 E tarsin.ehviewe: Not starting debugger since process cannot load the jdwp agent.
08-21 11:46:42.662  7406  7406 V MiuiFrameworkFactory: get AllImpl object = android.common.MiuiFrameworkFactoryImpl@1ef7c61
08-21 11:46:42.662  7406  7424 D AnrScout: AppScoutStateMachine created
08-21 11:46:42.683  7406  7406 I Perf    : Connecting to perf service.
08-21 11:46:42.687  7406  7406 D MiuiFreeDragHelper: get sInstance: android.freedrag.MiuiFreeDragImpl@8c343e0
08-21 11:46:42.687  7406  7406 D MiuiFreeDragImpl: initialize.
08-21 11:46:42.687  7406  7406 D MiuiFreeDragImpl: not in AllowList!
08-21 11:46:42.690  7406  7406 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
08-21 11:46:42.692  7406  7406 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
08-21 11:46:42.703  7406  7406 I ContentProviderMonitor: PerfMonitor installContentProviders : before publish content providers
08-21 11:46:42.736  7406  7406 D AppCompatDelegate: Checking for metadata for AppLocalesMetadataHolderService : Service not found
08-21 11:46:42.742  7406  7406 I AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
08-21 11:46:42.755  7406  7406 D DecorView[]: getWindowModeFromSystem  windowmode is 1
08-21 11:46:42.755  7406  7406 D DecorView:  old windowMode:0 new windowMode: 1 isNeedToChangeCaptionView false
08-21 11:46:42.755  7406  7406 D DecorView: createDecorCaptionView windowingMode:1 mWindowMode 1
08-21 11:46:42.772  7406  7441 D ViewContentFactory: initViewContentFetcherClass
08-21 11:46:42.772  7406  7441 D ViewContentFactory: getInterceptorPackageInfo
08-21 11:46:42.773  7406  7441 D ViewContentFactory: getInitialApplication took 1ms
08-21 11:46:42.773  7406  7441 D ViewContentFactory: packageInfo.packageName: com.miui.catcherpatch
08-21 11:46:42.779  7406  7441 D ViewContentFactory: initViewContentFetcherClass took 7ms
08-21 11:46:42.780  7406  7441 I ContentCatcher: ViewContentFetcher : ViewContentFetcher
08-21 11:46:42.780  7406  7441 D ViewContentFactory: createInterceptor took 8ms
08-21 11:46:42.939  7406  7463 D Se      : https://exhentai.org/
08-21 11:46:42.946  7406  7406 W Activity: Slow Operation: Activity moe.tarsin.ehviewer/com.hippo.ehviewer.ui.MainActivity onStart took 132ms
08-21 11:46:42.953  7406  7406 D DecorView[]: getWindowModeFromSystem  windowmode is 1
08-21 11:46:42.954  7406  7406 D DecorView:  old windowMode:1 new windowMode: 1 isNeedToChangeCaptionView false
08-21 11:46:42.954  7406  7406 D DecorView[]: updateDecorCaptionStatus displayWindowDecor is false
08-21 11:46:42.976  7406  7432 I AdrenoGLES-0: QUALCOMM build                   : 191610ae03, Ic907de5ed0
08-21 11:46:42.976  7406  7432 I AdrenoGLES-0: Build Date                       : 09/17/20
08-21 11:46:42.976  7406  7432 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.01
08-21 11:46:42.976  7406  7432 I AdrenoGLES-0: Local Branch                     : 
08-21 11:46:42.976  7406  7432 I AdrenoGLES-0: Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.9.12.10.00.00.582.274
08-21 11:46:42.976  7406  7432 I AdrenoGLES-0: Remote Branch                    : NONE
08-21 11:46:42.976  7406  7432 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
08-21 11:46:42.976  7406  7432 I AdrenoGLES-0: Build Config                     : S P 10.0.5 AArch64
08-21 11:46:42.976  7406  7432 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
08-21 11:46:42.979  7406  7432 I AdrenoGLES-0: PFP: 0x016dd091, ME: 0x00000000
08-21 11:46:43.033  7406  7406 D DecorView[]: onWindowFocusChanged hasWindowFocus true
08-21 11:46:43.033  7406  7406 I DecorView: showOrHideHighlightView: hasFocus=true; winMode=1; isMrgNull=true
08-21 11:46:44.683  7406  7421 W System  : A resource failed to call close. 
08-21 11:46:45.155  7406  7463 D Se      : https://exhentai.org/api.php
08-21 11:46:45.698  7406  7463 D Se      : https://exhentai.org/api.php
08-21 11:46:46.211  7406  7463 D Se      : https://exhentai.org/api.php
08-21 11:46:46.725  7406  7463 D Se      : https://exhentai.org/api.php
08-21 11:46:47.242  7406  7463 D Se      : https://exhentai.org/api.php
08-21 11:46:47.754  7406  7463 D Se      : https://exhentai.org/api.php
08-21 11:46:48.256  7406  7463 D Se      : https://exhentai.org/api.php
08-21 11:46:48.774  7406  7463 D Se      : https://exhentai.org/api.php
08-21 11:46:49.384  7406  7478 D TAG     : Conaco https://ehgt.org/50/75/5075ba616b5a8fda20f2a405708f6555f248a9cb-928363-2591-3624-jpg_l.jpg
08-21 11:46:49.385  7406  7479 D TAG     : Conaco https://ehgt.org/50/75/5075ba616b5a8fda20f2a405708f6555f248a9cb-928363-2591-3624-jpg_l.jpg
08-21 11:46:49.385  7406  7480 D TAG     : Conaco https://ehgt.org/1c/6e/1c6ee28eb7ee36a4cd9e01003b2892969e986038-2654272-1600-2260-jpg_l.jpg
08-21 11:46:50.694  7406  7428 I tarsin.ehviewe: ProcessProfilingInfo new_methods=153 is saved saved_to_disk=1 resolve_classes_delay=8000
08-21 11:46:51.231  7406  7478 D TAG     : Conaco https://ehgt.org/e3/f0/e3f0a5f6554622ace8c7be23c6d2dee3e35bf77d-3272475-2199-3106-jpg_l.jpg
08-21 11:46:51.536  7406  7479 D TAG     : Conaco https://ehgt.org/af/4f/af4f48603a547170cb48536da7bc01bc299c29d2-9794824-3307-4677-png_l.jpg
08-21 11:46:51.540  7406  7480 D TAG     : Conaco https://ehgt.org/71/19/71190cb4a82d91942c36a643cc24c50e71a963b5-3397242-4183-2976-jpg_l.jpg
08-21 11:46:51.631  7406  7478 D TAG     : Conaco https://ehgt.org/2e/63/2e637dbdccb7861d8016227724832b03b2d5fadb-3347260-4183-2976-jpg_l.jpg
08-21 11:46:51.949  7406  7480 D TAG     : Conaco https://ehgt.org/f4/14/f414926a8383db31b291dde21340fa97b389edc7-1428248-1133-1600-jpg_l.jpg
08-21 11:46:51.952  7406  7479 D TAG     : Conaco https://ehgt.org/d6/4b/d64b23d06b9ed89dc5b788c4081a2da18457ab37-954188-1072-1500-jpg_l.jpg
08-21 11:46:54.202  7406  7430 D Se      : https://exhentai.org/g/2305291/55d5e8daad/
08-21 11:46:54.801  7406  7478 D TAG     : Conaco https://ehgt.org/cd/83/cd83cdd5363a4802ade86536bf381f81db046601-312162-2591-3624-jpg_l.jpg
08-21 11:46:54.802  7406  7480 D TAG     : Conaco https://ehgt.org/fc/e5/fce5f1bd6be358efabaa5f714d0506c4635c6062-759995-2591-3624-jpg_l.jpg
08-21 11:46:54.802  7406  7479 D TAG     : Conaco https://ehgt.org/0b/66/0b660c75e8b0b9c62f5df83b4c6a84fa67fb5393-1434864-2591-3624-jpg_l.jpg
08-21 11:46:55.134  7406  7478 D TAG     : Conaco https://ehgt.org/d0/8c/d08c90ee36c62c1d234c384ab626168b574baa90-1287589-2591-3624-jpg_l.jpg
08-21 11:46:55.432  7406  7479 D TAG     : Conaco https://ehgt.org/f8/6c/f86c3a40768c74d213c9aaec303343e79afd49c5-1234968-2591-3624-jpg_l.jpg
08-21 11:46:55.730  7406  7406 I Timeline: Timeline: Activity_launch_request time:167473674
08-21 11:46:55.735  7406  7480 D TAG     : Conaco https://ehgt.org/1a/25/1a25bf5c26101017c4116abbab5c9eba57e55b89-1107411-2591-3624-jpg_l.jpg
08-21 11:46:55.741  7406  7478 D TAG     : Conaco https://ehgt.org/67/d7/67d712bb28acc477f2e07334129eacb14bad68d5-1283083-2591-3624-jpg_l.jpg
08-21 11:46:55.756  7406  7406 I AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
08-21 11:46:55.757  7406  7441 D ViewContentFactory: initViewContentFetcherClass
08-21 11:46:55.757  7406  7441 I ContentCatcher: ViewContentFetcher : ViewContentFetcher
08-21 11:46:55.757  7406  7441 D ViewContentFactory: createInterceptor took 0ms
08-21 11:46:55.758  7406  7406 D DecorView[]: getWindowModeFromSystem  windowmode is 1
08-21 11:46:55.758  7406  7406 D DecorView:  old windowMode:0 new windowMode: 1 isNeedToChangeCaptionView false
08-21 11:46:55.758  7406  7406 D DecorView: createDecorCaptionView windowingMode:1 mWindowMode 1
08-21 11:46:55.767  7406  7406 D DecorView:  old windowMode:0 new windowMode: 1 isNeedToChangeCaptionView false
08-21 11:46:55.767  7406  7406 D DecorView: createDecorCaptionView windowingMode:1 mWindowMode 1
08-21 11:46:55.797  7406  7406 D DecorView[]: getWindowModeFromSystem  windowmode is 1
08-21 11:46:55.797  7406  7406 D DecorView:  old windowMode:1 new windowMode: 1 isNeedToChangeCaptionView false
08-21 11:46:55.797  7406  7406 D DecorView[]: updateDecorCaptionStatus displayWindowDecor is false
08-21 11:46:55.822  7406  7421 W System  : A resource failed to call close. 
08-21 11:46:55.822  7406  7421 I chatty  : uid=10332(moe.tarsin.ehviewer) FinalizerDaemon identical 40 lines
08-21 11:46:55.822  7406  7421 W System  : A resource failed to call close. 
08-21 11:46:55.822  7406  7406 D SurfaceView: UPDATE null, mIsCastMode = false
08-21 11:46:55.823  7406  7421 W System  : A resource failed to call close. 
08-21 11:46:55.824  7406  7421 W System  : A resource failed to call close. 
08-21 11:46:55.827  7406  7406 D DecorView[]: onWindowFocusChanged hasWindowFocus false
08-21 11:46:55.827  7406  7406 I DecorView: showOrHideHighlightView: hasFocus=false; winMode=1; isMrgNull=true
08-21 11:46:55.830  7406  7406 D SurfaceView: UPDATE Surface(name=SurfaceView - moe.tarsin.ehviewer/com.hippo.ehviewer.ui.GalleryActivity)/@0xa195201, mIsProjectionMode = false
08-21 11:46:55.835  7406  7501 I GLRootView: onSurfaceChanged: 1600x2560, gl10: com.google.android.gles_jni.GLImpl@da0de94
08-21 11:46:55.835  7406  7501 I GLRootView: layout content pane 1600x2560 (compensation 0)
08-21 11:46:55.859  7406  7501 V GLRootView: --- 10 ---
08-21 11:46:55.865  7406  7479 D TAG     : Conaco https://ehgt.org/87/24/8724e93ca58066e920ffc2243bbe801de9e0d520-1137649-2591-3624-jpg_l.jpg
08-21 11:46:55.870  7406  7406 D DecorView[]: onWindowFocusChanged hasWindowFocus true
08-21 11:46:55.870  7406  7406 I DecorView: showOrHideHighlightView: hasFocus=true; winMode=1; isMrgNull=true
08-21 11:46:55.883  7406  7508 D Se      : https://exhentai.org/s/5075ba616b/2305291-1
08-21 11:46:55.886  7406  7501 V GLRootView: --- 9 ---
08-21 11:46:55.946  7406  7501 V GLRootView: --- 10 ---
08-21 11:46:56.070  7406  7480 D TAG     : Conaco https://ehgt.org/72/51/7251d12a834a9103f7f19dee6ec6cbdd8ceb8410-1502886-2591-3624-jpg_l.jpg
08-21 11:46:56.089  7406  7478 D TAG     : Conaco https://ehgt.org/2f/47/2f4725f4f3433c9ec21d88d003a69c5bb2c051df-1315009-2591-3624-jpg_l.jpg
08-21 11:46:56.199  7406  7479 D TAG     : Conaco https://ehgt.org/86/96/8696e51ebb9d07a784c4371f8361c442f534499c-2904251-2591-3624-jpg_l.jpg
08-21 11:46:56.265  7406  7512 D Se      : https://exhentai.org/api.php
08-21 11:46:56.266  7406  7510 D Se      : https://exhentai.org/api.php
08-21 11:46:56.267  7406  7513 D Se      : https://exhentai.org/api.php
08-21 11:46:56.267  7406  7509 D Se      : https://exhentai.org/api.php
08-21 11:46:56.268  7406  7507 D Se      : https://exhentai.org/api.php
08-21 11:46:56.268  7406  7511 D Se      : https://exhentai.org/api.php
08-21 11:46:56.270  7406  7501 V GLRootView: --- 9 ---
08-21 11:46:56.409  7406  7480 D TAG     : Conaco https://ehgt.org/0f/67/0f6720828a2c90b7ac12eecd8a7038aa739e6c5a-1258271-2591-3624-jpg_l.jpg
08-21 11:46:56.431  7406  7478 D TAG     : Conaco https://ehgt.org/f9/00/f9006abb2c06f5e368ef828b934f86fe0f63090d-1268794-2591-3624-jpg_l.jpg
08-21 11:46:56.578  7406  7479 D TAG     : Conaco https://ehgt.org/d6/4f/d64ffdaaa3fae9a0d430c0dee72e42e1eeff7dee-1438035-2591-3624-jpg_l.jpg
08-21 11:46:56.756  7406  7480 D TAG     : Conaco https://ehgt.org/e7/b2/e7b2464d5eaafec2a5ef26f19dd1f97be8006ab2-1319700-2591-3624-jpg_l.jpg
08-21 11:46:56.770  7406  7478 D TAG     : Conaco https://ehgt.org/a2/c3/a2c310445eca8bcaf36a4e9e76e8229f3503e8f7-1502855-2591-3624-jpg_l.jpg
08-21 11:46:56.915  7406  7479 D TAG     : Conaco https://ehgt.org/a8/ce/a8ce0273183e4cbddba751832f5013b40b733b2f-1557824-2591-3624-jpg_l.jpg
08-21 11:46:57.088  7406  7480 D TAG     : Conaco https://ehgt.org/1c/88/1c88556392a8d0018df886637eb9de8b528cc05f-1237820-2591-3624-jpg_l.jpg
08-21 11:46:57.107  7406  7478 D TAG     : Conaco https://ehgt.org/38/aa/38aabcb46776a9a874758056fd18b1b21eb2f9c2-1311010-2591-3624-jpg_l.jpg
08-21 11:46:57.284  7406  7479 D TAG     : Conaco https://ehgt.org/04/d0/04d0de279204042a93231fc830fa7b63f23aa171-1198676-2591-3624-jpg_l.jpg
08-21 11:46:57.325  7406  7508 D Se      : https://exhentai.org/api.php
08-21 11:46:57.431  7406  7501 V GLRootView: --- 13 ---
08-21 11:46:57.444  7406  7480 D TAG     : Conaco https://ehgt.org/c3/bb/c3bba276ab5c3f2f792e740aa56cf04c4ec011ef-1113785-2591-3624-jpg_l.jpg
08-21 11:46:57.459  7406  7478 D TAG     : Conaco https://ehgt.org/bd/f9/bdf9b5bb8731598a431d542327495ef058c79ac7-1372577-2591-3624-jpg_l.jpg
08-21 11:46:57.682  7406  7479 D TAG     : Conaco https://ehgt.org/14/ad/14ada09eee2ba6c938e0f04ff0ba0dfc98858c80-1346312-2591-3624-jpg_l.jpg
08-21 11:46:57.776  7406  7480 D TAG     : Conaco https://ehgt.org/f1/be/f1be80b9665fdd9e862abcbd9b87a61a4cc4bfa1-1435801-2591-3624-jpg_l.jpg
08-21 11:46:57.793  7406  7478 D TAG     : Conaco https://ehgt.org/cf/88/cf88b8f1e5d27bc5d15db49483053f2bc8fb357b-1545299-2591-3624-jpg_l.jpg
08-21 11:46:58.034  7406  7479 D TAG     : Conaco https://ehgt.org/79/dd/79ddd8cd21540083bd5eb7cf5cb31c349578d21c-1502604-2591-3624-jpg_l.jpg
08-21 11:46:58.141  7406  7480 D TAG     : Conaco https://ehgt.org/4d/90/4d90442d7b80919dd7766286b24969d69b93cdc6-1574818-2591-3624-jpg_l.jpg
08-21 11:46:58.160  7406  7478 D TAG     : Conaco https://ehgt.org/8d/2e/8d2e1b06ed534a578d475dca1142d0fc43deb115-1621817-2591-3624-jpg_l.jpg
08-21 11:46:58.306  7406  7421 W System  : A resource failed to call close. 
08-21 11:46:58.307  7406  7421 W System  : A resource failed to call close. 
08-21 11:46:58.371  7406  7479 D TAG     : Conaco https://ehgt.org/1f/c4/1fc4d0efd92364bda09d0238ad719d61a38a13a1-1727515-2591-3624-jpg_l.jpg
08-21 11:46:58.478  7406  7480 D TAG     : Conaco https://ehgt.org/2f/14/2f142b5ceaf52e0ac990f0c0bf776dcbbf29c5a8-1702719-2591-3624-jpg_l.jpg
08-21 11:46:58.497  7406  7478 D TAG     : Conaco https://ehgt.org/60/f7/60f75bbc5fe0bff5c1741147ea8907f5f18eb33b-1652158-2591-3624-jpg_l.jpg
08-21 11:46:58.698  7406  7513 D Se      : https://exhentai.org/api.php
08-21 11:46:58.707  7406  7479 D TAG     : Conaco https://ehgt.org/ae/53/ae53670fdbcb324b61ca2461b02bd946a9bdcd32-1536230-2591-3624-jpg_l.jpg
08-21 11:46:58.814  7406  7480 D TAG     : Conaco https://ehgt.org/32/e5/32e5aa05cc6b7e0a1226b7420c59e4cf9f891257-1631807-2591-3624-jpg_l.jpg
08-21 11:46:58.831  7406  7478 D TAG     : Conaco https://ehgt.org/6e/80/6e800d8eb09dc1b6e96e63afb17fb8bf804db6b3-1588666-2591-3624-jpg_l.jpg
08-21 11:46:59.042  7406  7479 D TAG     : Conaco https://ehgt.org/c2/7b/c27b8204693d7266db1b504cb6bbb61d81319a59-1107829-2591-3624-jpg_l.jpg
08-21 11:46:59.151  7406  7480 D TAG     : Conaco https://ehgt.org/45/7e/457eb4078a536ca5ef6b2f1543762f4a64d649db-810517-2591-3624-jpg_l.jpg
08-21 11:46:59.164  7406  7478 D TAG     : Conaco https://ehgt.org/37/76/377694130cee0f8d5255937adc4e82573ed903b8-3221581-2591-3624-jpg_l.jpg
08-21 11:46:59.197  7406  7421 W System  : A resource failed to call close. 
08-21 11:46:59.198  7406  7421 W System  : A resource failed to call close. 
08-21 11:46:59.401  7406  7479 D TAG     : Conaco https://ehgt.org/cd/83/cd83cdd5363a4802ade86536bf381f81db046601-312162-2591-3624-jpg_l.jpg
08-21 11:46:59.405  7406  7479 D TAG     : Conaco https://ehgt.org/72/96/729605879dbeaf49e395a8fa86220848a3cb37d3-316787-2591-3624-jpg_l.jpg
08-21 11:47:01.701  7406  7511 I ActivityThread: com.android.externalstorage.documents acquiringCount 2
08-21 11:47:01.708  7406  7508 D Se      : https://exhentai.org/api.php
08-21 11:47:01.710  7406  7511 D Se      : https://exhentai.org/api.php
08-21 11:47:02.843  7406  7507 W System.err: java.net.SocketTimeoutException: failed to connect to vmvnejg.zjletlgnvzpj.hath.network/91.193.7.10 (port 54964) from /10.10.10.4 (port 58166) after 5000ms
08-21 11:47:02.843  7406  7507 W System.err: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:190)
08-21 11:47:02.843  7406  7507 W System.err: 	at libcore.io.IoBridge.connect(IoBridge.java:134)
08-21 11:47:02.843  7406  7507 W System.err: 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
08-21 11:47:02.843  7406  7507 W System.err: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
08-21 11:47:02.843  7406  7507 W System.err: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
08-21 11:47:02.843  7406  7507 W System.err: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
08-21 11:47:02.844  7406  7507 W System.err: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
08-21 11:47:02.844  7406  7507 W System.err: 	at java.net.Socket.connect(Socket.java:621)
08-21 11:47:02.844  7406  7507 W System.err: 	at bw.e(Unknown Source:0)
08-21 11:47:02.844  7406  7507 W System.err: 	at D9.i(:23)
08-21 11:47:02.844  7406  7507 W System.err: 	at D9.h(:9)
08-21 11:47:02.844  7406  7507 W System.err: 	at cB.a(:6)
08-21 11:47:02.844  7406  7507 W System.err: 	at z9.a(:9)
08-21 11:47:02.844  7406  7507 W System.err: 	at Fx.b(:17)
08-21 11:47:02.844  7406  7507 W System.err: 	at M6.a(:151)
08-21 11:47:02.844  7406  7507 W System.err: 	at Fx.b(:17)
08-21 11:47:02.844  7406  7507 W System.err: 	at s6.a(:40)
08-21 11:47:02.844  7406  7507 W System.err: 	at Fx.b(:17)
08-21 11:47:02.844  7406  7507 W System.err: 	at mz.a(:38)
08-21 11:47:02.845  7406  7507 W System.err: 	at Fx.b(:17)
08-21 11:47:02.845  7406  7507 W System.err: 	at Bx.f(:25)
08-21 11:47:02.845  7406  7507 W System.err: 	at Bx.d(:12)
08-21 11:47:02.845  7406  7507 W System.err: 	at wC.a(:38)
08-21 11:47:02.845  7406  7507 W System.err: 	at wC.e(:71)
08-21 11:47:02.845  7406  7507 W System.err: 	at wC.run(:5)
08-21 11:47:02.845  7406  7507 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-21 11:47:02.845  7406  7507 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-21 11:47:02.845  7406  7507 W System.err: 	at java.lang.Thread.run(Thread.java:923)
08-21 11:47:02.845  7406  7507 W System.err: 	at Tw.run(:2)
08-21 11:47:02.845  7406  7507 D Se      : https://exhentai.org/s/fce5f1bd6b/2305291-3?nl=36432-461403
08-21 11:47:03.070  7406  7511 I ActivityThread: com.android.externalstorage.documents acquiringCount 2
08-21 11:47:03.323  7406  7421 W System  : A resource failed to call close. 
08-21 11:47:03.323  7406  7421 I chatty  : uid=10332(moe.tarsin.ehviewer) FinalizerDaemon identical 7 lines
08-21 11:47:03.323  7406  7421 W System  : A resource failed to call close. 
08-21 11:47:03.707  7406  7512 D Se      : https://exhentai.org/api.php
08-21 11:47:03.707  7406  7513 D Se      : https://exhentai.org/api.php
08-21 11:47:03.708  7406  7510 D Se      : https://exhentai.org/api.php
08-21 11:47:03.749  7406  7509 D Se      : https://exhentai.org/api.php
08-21 11:47:03.879  7406  7511 D Se      : https://exhentai.org/api.php
08-21 11:47:03.911  7406  7421 W System  : A resource failed to call close. 
08-21 11:47:03.912  7406  7421 W System  : A resource failed to call close. 
08-21 11:47:05.515  7406  7421 W System  : A resource failed to call close. 
08-21 11:47:05.515  7406  7421 W System  : A resource failed to call close. 
08-21 11:47:05.793  7406  7406 W Choreographer: Frame time is 0.08039 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
08-21 11:47:09.409  7406  7406 D MIUIInput: [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x8, repeatCount=0, eventTime=167487348, downTime=167487348, deviceId=-1, source=0x101, displayId=0 }
08-21 11:47:09.415  7406  7406 D MIUIInput: [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x8, repeatCount=0, eventTime=167487348, downTime=167487348, deviceId=-1, source=0x101, displayId=0 }
08-21 11:47:09.471  7406  7406 D DecorView[]: onWindowFocusChanged hasWindowFocus false
08-21 11:47:09.471  7406  7406 I DecorView: showOrHideHighlightView: hasFocus=false; winMode=1; isMrgNull=true
08-21 11:47:09.540  7406  7406 D DecorView[]: onWindowFocusChanged hasWindowFocus true
08-21 11:47:09.540  7406  7406 I DecorView: showOrHideHighlightView: hasFocus=true; winMode=1; isMrgNull=true
08-21 11:47:10.442  7406  7421 W System  : A resource failed to call close. 
08-21 11:47:10.443  7406  7421 I chatty  : uid=10332(moe.tarsin.ehviewer) FinalizerDaemon identical 1 line
08-21 11:47:10.443  7406  7421 W System  : A resource failed to call close. 
08-21 11:47:11.890  7406  7406 I Timeline: Timeline: Activity_launch_request time:167489834
08-21 11:47:11.919  7406  7406 I AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
08-21 11:47:11.919  7406  7441 D ViewContentFactory: initViewContentFetcherClass
08-21 11:47:11.920  7406  7441 I ContentCatcher: ViewContentFetcher : ViewContentFetcher
08-21 11:47:11.920  7406  7441 D ViewContentFactory: createInterceptor took 1ms
08-21 11:47:11.920  7406  7406 D DecorView[]: getWindowModeFromSystem  windowmode is 1
08-21 11:47:11.920  7406  7406 D DecorView:  old windowMode:0 new windowMode: 1 isNeedToChangeCaptionView false
08-21 11:47:11.921  7406  7406 D DecorView: createDecorCaptionView windowingMode:1 mWindowMode 1
08-21 11:47:11.928  7406  7406 D DecorView[]: getWindowModeFromSystem  windowmode is 1
08-21 11:47:11.928  7406  7406 D DecorView:  old windowMode:1 new windowMode: 1 isNeedToChangeCaptionView false
08-21 11:47:11.928  7406  7406 D DecorView[]: updateDecorCaptionStatus displayWindowDecor is false
08-21 11:47:11.955  7406  7406 D DecorView[]: onWindowFocusChanged hasWindowFocus false
08-21 11:47:11.955  7406  7406 I DecorView: showOrHideHighlightView: hasFocus=false; winMode=1; isMrgNull=true
08-21 11:47:11.973  7406  7406 D DecorView[]: onWindowFocusChanged hasWindowFocus true
08-21 11:47:11.973  7406  7406 I DecorView: showOrHideHighlightView: hasFocus=true; winMode=1; isMrgNull=true
08-21 11:47:13.133  7406  7406 W ListPreference: Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
08-21 11:47:13.135  7406  7406 W ListPreference: Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
08-21 11:47:16.922  7406  7406 I Timeline: Timeline: Activity_launch_request time:167494866
08-21 11:47:16.989  7406  7406 D DecorView[]: onWindowFocusChanged hasWindowFocus false
08-21 11:47:16.989  7406  7406 I DecorView: showOrHideHighlightView: hasFocus=false; winMode=1; isMrgNull=true
08-21 11:47:19.465  7406  7426 D AnrScout: AppScoutStateMachine created

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by ShoukakuChuuCC** [comment]
大佬们记得同步更新1.7，麻烦了

**Comment by txyyh** [comment]
https://github.com/txyyh/Ehviewer/actions/runs/2893269507
这个正常吗

**Comment by asuka-mio** [comment]
草 你MIUI13按理说是Android12呀 咋能安不上1.8呢（

**Comment by txyyh** [comment]
@asuka-mio MIUI 版本和 Android 版本没有绝对关联
MIUI 13 Android 11 的设备也是有的

**Comment by duzhaokun123** [comment]
> Android 系统版本 / Android version
> MIUI 13.0.6

@txyyh 那为什么要在 Android 版本里填 MIUI 版本呢

**Comment by txyyh** [comment]
@duzhaokun123 确定是否为 OEM 系统

**Comment by txyyh** [comment]
@duzhaokun123 另外那是我和另一维护者的对话，你不必过于在意

**Comment by ShoukakuChuuCC** [comment]
> https://github.com/txyyh/Ehviewer/actions/runs/2893269507 这个正常吗

不正常哦 这个issues填的CI版本就是这个actions的

**Comment by txyyh** [comment]
@ShoukakuChuuCC 咋填了我仓库的action（

好，收到

**Comment by asuka-mio** [comment]
在1.8这边我用otg鼠标连接手机已经复现不到了，在1.7还存在吗 @txyyh

**Comment by txyyh** [comment]
@asuka-mio 使用蓝牙鼠标测试，1.7.30.0不存在此问题
