### ISSUE TITLE
1.8.2.0 搜索就会崩溃

### ISSUE THREAD

**Issue by VoidxHoshi** [Ehviewer-Overhauled/Ehviewer#219]
### 复现步骤 / Step to reproduce

点击任意标签进行搜索或者直接使用搜索功能

### 预期行为 / Expected behaviour

不应该崩溃

### 实际行为 / Actual Behaviour

点击即崩溃

### EhViewer 版本号 / EhViewer version code

1.8.2.0

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/2901381725

### Android 系统版本 / Android version

MIUI 13 Android 12

### 设备型号 / Device model

redmi k30 pro

### SoC 型号 / Soc model

骁龙865

### 应用日志 / App logs

[log-2022-08-22-15-11-39-358.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/9392801/log-2022-08-22-15-11-39-358.zip)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
![Screenshot_20220822-171202](https://user-images.githubusercontent.com/43900799/185885020-31ce87e8-cc36-4df8-b30a-1b5eabfd08d4.png)
你的系统类库里缺方法了 并不是app问题

**Comment by txyyh** [comment]
[log-2022-08-22-17-15-03-061.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/9392974/log-2022-08-22-17-15-03-061.zip)
Redmi Note 9 Pro 骁龙 750G, Android 12L kaleidoscopeOS

**Comment by asuka-mio** [comment]
嘶 我看差了 这个是api33才有的方法 现在minsdk是31 抱歉

**Comment by asuka-mio** [comment]
草了 这还真不是我改的 Android studio自己优化代码优化的 离谱

**Comment by asuka-mio** [comment]
revert那条提交了 这回应该好了
