### ISSUE TITLE
画面加载卡顿，延迟明显

### ISSUE THREAD

**Issue by The-Hidden-Tree** [Ehviewer-Overhauled/Ehviewer#221]
### 复现步骤 / Step to reproduce

1.打开软件（EX）
2.随便点开一本漫画

### 预期行为 / Expected behaviour

应该正常加载本漫画的封面、tag、预览图、评论区......

### 实际行为 / Actual Behaviour

1.加载时间很长，大约10秒左右，而且第一张预览图大概率会崩溃/加载失败。
2.在阅读漫画时，图片的加载也比较慢（但此时手机任务栏的网速显示只有十几KB/s）；而且点击的那张画面加载特别慢，但前几张和后几张却加载完毕。（比如：我点的第7页，但第7页迟迟没有加载好，但4、5和8、9却加载好了/差不多了）

### EhViewer 版本号 / EhViewer version code

1.8.1.1

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/workflows/ci.yml

### Android 系统版本 / Android version

OriginOS ocean PD2217B_A_12.1.12.8.W10.V000L1

### 设备型号 / Device model

iqoo 10

### SoC 型号 / Soc model

晓龙8Gen＋1

### 应用日志 / App logs

[log-2022-08-22-19-52-45-174.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/9394136/log-2022-08-22-19-52-45-174.zip)

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
这是 CI
https://github.com/Ehviewer-Overhauled/Ehviewer/actions/workflows/ci.yml

**Comment by txyyh** [comment]
我们自己加载速度比较正常，麻烦更换到一个好的网络环境再试试

**Comment by The-Hidden-Tree** [comment]
> 这是 CI https://github.com/Ehviewer-Overhauled/Ehviewer/actions/workflows/ci.yml

好的，改完了

**Comment by asuka-mio** [comment]
> > 我们自己加载速度比较正常，换一个好的网络环境再试试
> 
> 我wifi和流量都试了，还是卡

换一个好的vpn试试？sni国内直连有时候速度可能不会很理想

**Comment by txyyh** [comment]
> > > 我们自己加载速度比较正常，换一个好的网络环境再试试
> > 
> > 
> > 我wifi和流量都试了，还是卡
> 
> 换一个好的vpn试试？sni国内直连有时候速度可能不会很理想

梯子

**Comment by txyyh** [comment]
我改下你表述

**Comment by The-Hidden-Tree** [comment]
> > > 我们自己加载速度比较正常，换一个好的网络环境试试
> > 
> > 
> > 我wifi和流量都试了，还是卡
> 
> 换一个国内好vpn？

嗯，挂上梯子后就好多了

**Comment by The-Hidden-Tree** [comment]
我升级到1.8.2.1 试试

**Comment by txyyh** [comment]
那就开梯子用啊吧，你那的网络环境我们没法解决

**Comment by asuka-mio** [comment]
> 那就开梯子用啊吧，你那的网络环境我们没法解决

你有时间把host更新下，挺长时间没更新了

**Comment by txyyh** [comment]
> > 那就开梯子用啊吧，你那的网络环境我们没法解决
> 
> 你有时间把host更新下，挺长时间没更新了

咱看看

**Comment by asuka-mio** [comment]
> > > 那就开梯子用啊吧，你那的网络环境我们没法解决
> > 
> > 
> > 你有时间把host更新下，挺长时间没更新了
> 
> 咱看看

https://github.com/Ehviewer-Overhauled/Ehviewer/blob/338848f1eb3c6f19d16302e6d0ad92a04bb12427/app/src/main/java/com/hippo/ehviewer/client/EhDns.java#L43

**Comment by The-Hidden-Tree** [comment]
> 那开梯子用吧，你那的网络环境我们无法解决

嗯，更新了之后情况好多了
