### ISSUE TITLE
在 WLAN 网络下使用 Cloudflare WARP 时错误提示“正在使用流量计费网络”

### ISSUE THREAD

**Issue by wordlesswind** [Ehviewer-Overhauled/Ehviewer#222]
### 复现步骤 / Step to reproduce

1. 启用 [Cloudflare WARP](https://play.google.com/store/apps/details?id=com.cloudflare.onedotonedotonedotone)
2. 打开 EhViewer

### 预期行为 / Expected behaviour

无提示

### 实际行为 / Actual Behaviour

提示“正在使用流量计费网络”

### EhViewer 版本号 / EhViewer version code

1.8.2.1

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/2911211114

### Android 系统版本 / Android version

ColorOS 12.1

### 设备型号 / Device model

OnePlus 7 Pro

### SoC 型号 / Soc model

Qualcomm® Snapdragon™ 855

### 应用日志 / App logs

[log-2022-08-24-01-00-19-413.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/9408013/log-2022-08-24-01-00-19-413.zip)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
请检查您的cloudflare warp设置，是否开启类似“使系统认为此VPN为流量计费网络”之类的词汇

**Comment by txyyh** [comment]
另，其他软件建立的的VPN没有此类现象吗

**Comment by tehcneko** [comment]
这是预期行为，WARP 就是计费网络

**Comment by txyyh** [comment]
这里的预期指，WARP 应用设置了一个按流量计费的 VPN 是预期行为。EhViewer 只是发现这是一个被设置为按流量计费的 VPN 连接并按此进行，并不是指 EhViewer 本身对 WARP 进行过识别和适配
