### ISSUE TITLE
画廊标题过长时预览卡片内标题和其它文字重叠

### ISSUE THREAD

**Issue by 500InternalError** [Ehviewer-Overhauled/Ehviewer#241]
### 复现步骤 / Step to reproduce

打开APP主界面

### 预期行为 / Expected behaviour

预期应当不重叠

### 实际行为 / Actual Behaviour

![Uploading Screenshot_20220828-223002_EhViewer.jpg…]()

### EhViewer 版本号 / EhViewer version code

1.8.2.1

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/2924490298

### Android 系统版本 / Android version

oneUI 4.1 Android 12

### 设备型号 / Device model

Samsung Galaxy s20

### SoC 型号 / Soc model

骁龙 865

### 应用日志 / App logs

[log-2022-08-28-22-39-23-848.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/9439877/log-2022-08-28-22-39-23-848.zip)

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by 500InternalError** [comment]
图片似乎上传失败了，重新上传下
![Screenshot_20220828-223002_EhViewer](https://user-images.githubusercontent.com/39024699/187080005-9de71638-313f-4464-b3a0-dec8b9fb9f6c.jpg)

**Comment by txyyh** [comment]
去设置加大详情模式缩略图大小

**Comment by 500InternalError** [comment]
有用，但是为什么不直接默认调大点呢（

**Comment by txyyh** [comment]
那较大屏幕设备就过大了

**Comment by 500InternalError** [comment]
如果没时间搞自适应的话我觉得会不会加个提示好一点
