### ISSUE TITLE
无法通过点击已下载画廊的封面来进入详情页面

### ISSUE THREAD

**Issue by wordlesswind** [Ehviewer-Overhauled/Ehviewer#251]
### 复现步骤 / Step to reproduce

1. 打开 EhViewer
2. 进入下载列表
3. 点击已下载画廊的封面

### 预期行为 / Expected behaviour

原本应当进入画廊的详情信息页面

### 实际行为 / Actual Behaviour

浏览画廊

### EhViewer 版本号 / EhViewer version code

1.8.2.1

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions

### Android 系统版本 / Android version

ColorOS 12.1

### 设备型号 / Device model

OnePlus 7 Pro

### SoC 型号 / Soc model

Qualcomm® Snapdragon™ 855

### 应用日志 / App logs

[log-2022-09-05-16-48-31-800.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/9488285/log-2022-09-05-16-48-31-800.zip)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
这是目前预期行为，并非bug

另外，如果直接打开被e站删除画廊的画廊详情界面，容易闪退

**Comment by wordlesswind** [comment]
> 这是目前预期行为，并非bug

那这个更改的原因是什么，是暂时的还是永久性的呢？

**Comment by asuka-mio** [comment]
因为已下载的画廊是为了离线访问的，在线画廊的一些数据，比如评论，更新什么的将不会保证能够正常获取，只会保证最基本的阅读内容的功能

**Comment by wordlesswind** [comment]
> 因为已下载的画廊是为了离线访问的，在线画廊的一些数据，比如评论，更新什么的将不会保证能够正常获取，只会保证最基本的阅读内容的功能

那么我希望至少能够提供复制画廊名称或是链接这些有利于分享的功能。

**Comment by txyyh** [comment]
#305 fixed
