### ISSUE TITLE
本地收藏搜索无效

### ISSUE THREAD

**Issue by wu-ya** [Ehviewer-Overhauled/Ehviewer#256]
### 复现步骤 / Step to reproduce

1.使用云端备份本地
2.打开本地收藏并搜索
3.无效

### 预期行为 / Expected behaviour

他应该正常生效

### 实际行为 / Actual Behaviour

实际上它无效

### EhViewer 版本号 / EhViewer version code

1.8.2.1

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3006153588

### Android 系统版本 / Android version

MIUI13安卓12

### 设备型号 / Device model

小米10

### SoC 型号 / Soc model

骁龙865

### 应用日志 / App logs

#
[log-2022-09-07-17-11-32-556.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/9504616/log-2022-09-07-17-11-32-556.zip)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
另，Author 在 #250 已经复现问题

**Comment by asuka-mio** [comment]
任何的搜索都是进行云端请求访问的，目前没有搜索本地的实现，也没有实现的打算
