### ISSUE TITLE
1.8.2.1点击任意tag闪退

### ISSUE THREAD

**Issue by eriri88888** [Ehviewer-Overhauled/Ehviewer#271]
### 复现步骤 / Step to reproduce

点击任意tag

### 预期行为 / Expected behaviour

点击任意tag

### 实际行为 / Actual Behaviour

闪退

### 备注 / Addition details

卸载之后用回

### EhViewer 版本号 / EhViewer version code

1.8.2.1

### EhViewer CI 版本 / EhViewer CI Version

1.8.2.1

### Android 系统版本 / Android version

12

### 设备型号 / Device model

moto X30PRO

### SoC 型号 / Soc model

8+gen1

### 应用日志 / App logs

卸载了。用回1.7.3没事

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
请提交日志
不提交日志，这点信息无法推断出任何问题

**Comment by txyyh** [comment]
CI 链接填写错误
请到[这里](https://github.com/Ehviewer-Overhauled/Ehviewer/actions/workflows/ci.yml)寻找对应分支最新ci

**Comment by asuka-mio** [comment]
闪退至少给个stacktrace呀。。。

**Comment by asuka-mio** [comment]
不回复我就先close了, feel free to reopen it
