### ISSUE TITLE
无法开启深色模式

### ISSUE THREAD

**Issue by su497776915** [Ehviewer-Overhauled/Ehviewer#282]
### 复现步骤 / Step to reproduce

深色主题选择总是开启之后会回退到主界面，依然还是浅色主题
选项自动回到跟随系统

### 预期行为 / Expected behaviour

应该变深色

### 实际行为 / Actual Behaviour

![QQ图片20220917132427](https://user-images.githubusercontent.com/17957030/190841963-2a0dc7d2-d5a8-4ab7-a97f-2f82fb1b52bf.jpg)
选总是开启会跳回跟随系统

### EhViewer 版本号 / EhViewer version code

1.8.2.2

### EhViewer CI 版本 / EhViewer CI Version

gh repo clone Ehviewer-Overhauled/Ehviewer

### Android 系统版本 / Android version

MIUI13 Android12

### 设备型号 / Device model

Xiaomi 12X

### SoC 型号 / Soc model

骁龙870

### 应用日志 / App logs

[log-2022-09-17-13-30-57-341.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/9591009/log-2022-09-17-13-30-57-341.zip)

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
> gh repo clone Ehviewer-Overhauled/Ehviewer
At least leave commit hash here
