### ISSUE TITLE
登录用户名显示存在问题

### ISSUE THREAD

**Issue by txyyh** [Ehviewer-Overhauled/Ehviewer#283]
### 复现步骤 / Step to reproduce

1. 断开设备网络
2. 使用有效 cookie 登录，此时app会显示“网络错误”
3. 恢复设备网络
4. 刷新/重启app，等待首页刷新出画廊
5. 进入 设置 - EH - 账户

### 预期行为 / Expected behaviour

它应该显示当前用户名

### 实际行为 / Actual Behaviour

实际上它显示“游客模式”

### EhViewer 版本号 / EhViewer version code

1.8.2.2

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3072499513

### Android 系统版本 / Android version

ArrowOS 12

### 设备型号 / Device model

Redmi Note 9 Pro

### SoC 型号 / Soc model

骁龙 750G

### 应用日志 / App logs

[log-2022-09-17-23-00-13-710.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/9592007/log-2022-09-17-23-00-13-710.zip)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
在设备没有网络时登录本身属于不支持行为

**Comment by txyyh** [comment]
@asuka-mio 这只是方便复现罢了
网络波动很常见
