### ISSUE TITLE
排行榜界面 只显示指定的类型

### ISSUE THREAD

**Issue by bai12123** [Ehviewer-Overhauled/Ehviewer#317]
### 需求 / Requirement

我平时只看漫画与同人志，在首页选择了这2个类型，但是排行榜默认显示全部类型。能否在排行榜界面显示指定的类型

### 建议实现 / Suggested implements

可以获取登录用户订阅的类型，然后在排行榜只显示订阅的类型。例如用户订阅了漫画与艺术家cg，排行榜只显示这2类。
或者在排行榜右滑侧边栏 添加所有类型，用户可以选择指定类型，然后显示指定类型（当然我觉得这个方案对用户来说更方便切换类型）

### EhViewer 版本号 / EhViewer version code

1.7.30.0

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/2916152912

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [x] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by txyyh** [comment]
我们提倡描述明确，简明扼要的标题，详见[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md#%E4%BD%BF%E7%94%A8%E6%9C%89%E6%84%8F%E4%B9%89%E4%B8%94%E6%8F%8F%E8%BF%B0%E6%98%8E%E7%A1%AE%E7%9A%84%E6%A0%87%E9%A2%98)

如有可能，希望您可以修改下标题，感谢您的理解与配合

**Comment by UjuiUjuMandan** [comment]
怎么关了，这个功能实现了吗？
