### ISSUE TITLE
画廊详情界面图片预览数量被限制为60

### ISSUE THREAD

**Issue by xb2016** [Ehviewer-Overhauled/Ehviewer#332]
### 复现步骤 / Step to reproduce

1. 网站设置预览数为 40 行
2. 使用 APP 访问任意大于 200 页的画廊

### 预期行为 / Expected behaviour

预览应有 200 图

### 实际行为 / Actual Behaviour

预览仅有 60 图

### EhViewer 版本号 / EhViewer version code

1.8.2.4

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3190505735

### Android 系统版本 / Android version

MIUI 13

### 设备型号 / Device model

Redmi K40 Pro

### SoC 型号 / Soc model

888

### 应用日志 / App logs

NA

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by tehcneko** [comment]
因为那个界面写的有点问题，预览多了会真的卡

**Comment by xb2016** [comment]
> 因为那个界面写的有点问题，预览多了会真的卡

最多也就 200 图，我的设备没有感觉到任何卡顿。
其次我认为就算真卡了，也应交由用户自行修改设置控制。

**Comment by asuka-mio** [comment]
> 因为那个界面写的有点问题，预览多了会真的卡

一说这个我想起来了 之前在一个mt6765 powervr的GPU 手机上 就这个预览页面非常卡顿 当时以为他们驱动问题

**Comment by tehcneko** [comment]
> > 因为那个界面写的有点问题，预览多了会真的卡
> 
> 最多也就 200 图，我的设备没有感觉到任何卡顿。 其次我认为就算真卡了，也应交由用户自行修改设置控制。

888 你说你🐴呢

**Comment by Longway22** [comment]
还是保留60页的限制吧，Pixel3上真的很卡。

**Comment by txyyh** [comment]
> 还是保留60页的限制吧，Pixel3上真的很卡。

已经恢复限制

**Comment by duzhaokun123** [comment]
做个开关很难吗

**Comment by xb2016** [comment]
> 做个开关很难吗

E站网页设置就能改预览数量啊 然而大多数人并没有这种意识 就这样继续让APP帮他们限制吧

**Comment by tehcneko** [comment]
> > 做个开关很难吗
> 
> E站网页设置就能改预览数量啊 然而大多数人并没有这种意识 就这样继续让APP帮他们限制吧

我不知道限制60问题在哪，想看很多你可以点开啊？

**Comment by xb2016** [comment]
> 我不知道限制60问题在哪，想看很多你可以点开啊？

按你这逻辑，我解锁E站预览图行数意义在哪？想看很多我可以多翻几页是吧？

**Comment by tehcneko** [comment]
> > 我不知道限制60问题在哪，想看很多你可以点开啊？
> 
> 按你这逻辑，我解锁E站预览图行数意义在哪？想看很多我可以多翻几页是吧？

解锁行数一样能少翻页，你到底用过没？

**Comment by txyyh** [comment]
别吵了
hide

**Comment by tehcneko** [comment]
> > 我不知道限制60问题在哪，想看很多你可以点开啊？
> 
> 按你这逻辑，我解锁E站预览图行数意义在哪？想看很多我可以多翻几页是吧？

另外你 fork 了我的版本并更改了协议，这是不允许的

**Comment by xb2016** [comment]
> 另外你 fork 了我的版本并更改了协议，这是不允许的

这一版本也是你的 fork，而我引用了这一版本的代码同时更改了协议，要改就一起改吧

**Comment by asuka-mio** [comment]
> > > 我不知道限制60问题在哪，想看很多你可以点开啊？
> > 
> > 
> > 按你这逻辑，我解锁E站预览图行数意义在哪？想看很多我可以多翻几页是吧？
> 
> 另外你 fork 了我的版本并更改了协议，这是不允许的

GPL v3兼容Apache 2.0协议

**Comment by asuka-mio** [comment]
> > > > 我不知道限制60问题在哪，想看很多你可以点开啊？
> > > 
> > > 
> > > 按你这逻辑，我解锁E站预览图行数意义在哪？想看很多我可以多翻几页是吧？
> > 
> > 
> > 另外你 fork 了我的版本并更改了协议，这是不允许的
> 
> GPL v3兼容Apache 2.0协议

而且GPL 是具有传染性的 所以xb那里改协议是正确的

**Comment by tehcneko** [comment]
> > > > > 我不知道限制60问题在哪，想看很多你可以点开啊？
> > > > 
> > > > 
> > > > 按你这逻辑，我解锁E站预览图行数意义在哪？想看很多我可以多翻几页是吧？
> > > 
> > > 
> > > 另外你 fork 了我的版本并更改了协议，这是不允许的
> > 
> > 
> > GPL v3兼容Apache 2.0协议
> 
> 而且GPL 是具有传染性的 所以xb那里改协议是正确的

更改协议对更改协议之前的代码不作效，而且没有提供 APL 协议原文和对变更的说明

**Comment by txyyh** [comment]
请不要在此讨论与本issue无关的话题，谢谢配合

**Comment by asuka-mio** [comment]
> > > > > > 我不知道限制60问题在哪，想看很多你可以点开啊？
> > > > > 
> > > > > 
> > > > > 按你这逻辑，我解锁E站预览图行数意义在哪？想看很多我可以多翻几页是吧？
> > > > 
> > > > 
> > > > 另外你 fork 了我的版本并更改了协议，这是不允许的
> > > 
> > > 
> > > GPL v3兼容Apache 2.0协议
> > 
> > 
> > 而且GPL 是具有传染性的 所以xb那里改协议是正确的
> 
> 更改协议对更改协议之前的代码不作效，而且没有提供 APL 协议原文和对变更的说明

我们很早以前就改协议了 他引用的是我更改之后的代码 至于你说的第二点我之后会和其他依赖库的协议一起补上 讨论到此为止

**Comment by txyyh** [comment]
@asuka-mio git commit msg 已提供全部对变更的说明

**Comment by asuka-mio** [comment]
现在已经全面采用硬件位图了，虽然还没换rv layout
问下 低配机器还会卡顿吗 我们是否还有必要继续保持这个限制
