### ISSUE TITLE
The dark mode reverses colors in part of non-clolorful preview images

### ISSUE THREAD

**Issue by QS0x01** [Ehviewer-Overhauled/Ehviewer#348]
### 复现步骤 / Step to reproduce

1. Select the galary and click into it.
2. Scroll to the preview.

### 预期行为 / Expected behaviour

It should only reverse the color of UI.

### 实际行为 / Actual Behaviour

![IMG_20221026_220127](https://user-images.githubusercontent.com/59040858/198047962-086fcdd9-1442-43f2-aabf-32f307771627.jpg)

### EhViewer 版本号 / EhViewer version code

1.7.30.0

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/2916152912

### Android 系统版本 / Android version

Android 11 MIUI 12.5.6.0 (RGGCNXM)

### 设备型号 / Device model

Redmi Note 8 Pro (begonia)

### SoC 型号 / Soc model

Helio G90T

### 应用日志 / App logs

[log-2022-10-27-12-44-59-987.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/9875844/log-2022-10-27-12-44-59-987.zip)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by QS0x01** [comment]
May be a little later. Some further comparison tests will be done during the daytime to confirm the culprit of this issue.

**Comment by QS0x01** [comment]
### Environment
Android: 11
System: MIUI 12.5.6 Stable

Ehviewer-Overhauled: 1.7.30.0
Gallary: https://exhentai.org/g/2331512/c1c8921e54/

### Test.1. Default Settings (System Dark Mode Switch: Enabled)
![01](https://user-images.githubusercontent.com/59040858/198163783-a71b0b26-9208-4831-ade2-1d47f9cde14f.png)

![02](https://user-images.githubusercontent.com/59040858/198163872-002e9ef7-f7d0-470d-96d7-cd2b94251fc1.png)

![03](https://user-images.githubusercontent.com/59040858/198163879-d9fd8d25-c3a8-4040-b136-5626150128cd.png)

### Test.2. Disabled System Dark Mode
App -> Settings -> EH -> Dark theme -> Always on
![04](https://user-images.githubusercontent.com/59040858/198164291-f99001ee-55d4-4936-b40c-52e8314938b3.png)

**Comment by txyyh** [comment]
Where is the CI version, device model and SoC model?

**Comment by QS0x01** [comment]
> Where is the CI version, device model, SoC model and logcat?
> Please note, what I list **must** be given at beginning.
> Just edit first msg, not append below.

√

**Comment by asuka-mio** [comment]
Seems that it works well on 1.8 branch 
![Screenshot_20221027-145928](https://user-images.githubusercontent.com/43900799/198213489-d7409687-26bc-4dfe-971c-bff26933affc.png)
I will go test 1.7

**Comment by asuka-mio** [comment]
![Screenshot_20221027-150946](https://user-images.githubusercontent.com/43900799/198215233-ea11bdcf-dad7-43d2-b3ce-d656882099cc.png)
I can't reproduce that problem with 1.7.30.0
Looks like something like MIUI Smart Dark Mode inverts the colors

**Comment by asuka-mio** [comment]
I suggest you report this problem to relevant MIUI department

**Comment by asuka-mio** [comment]
Furthermore, we have never implemented any function to invert the color of the image

**Comment by tehcneko** [comment]
给主题加上 forceDarkAllowed=false 就行了

**Comment by txyyh** [comment]
@tehcneko 不会主动适配OEM功能

**Comment by tehcneko** [comment]
> @tehcneko 不会主动适配OEM功能

傻逼

**Comment by tehcneko** [comment]
这又不是什么复杂的东西

**Comment by txyyh** [comment]
@tehcneko 这是主子定下的原则之一
长期内不会改

当然pr不影响

**Comment by tehcneko** [comment]
首先 forceDark 是原生 Android 的功能，MIUI 只是默认对应用开启了而已

**Comment by txyyh** [comment]
@tehcneko 还有

此处发言请遵循GitHub社区准则，并至少遵循基本的道德礼仪，谢谢

**Comment by tehcneko** [comment]
抱歉，对傻逼不需要什么礼仪
