### ISSUE TITLE
为应用(1.7.30.0)添加快速搜索栏删时需要再次确认的选项

### ISSUE THREAD

**Issue by HoriYuko** [Ehviewer-Overhauled/Ehviewer#353]
### 需求 / Requirement

为应用(1.7.x.x)添加删除快速搜索栏(书签) ，需要再次确认删除内容的选项(功能)。

      目前删除标签的方法(向左划动标签) 容易在编辑标签或者是日常使用中出现误删书签的现象。且无法临时撤销删除操作。

### 建议实现 / Suggested implements

删除所选标签(书签) 时,  用户需要再次确认删除内容 [应用弹出删除提示(确认 (删除) /取消) ]确认无误后，再由用户删除对应的标签(书签) 。

ps: 操作期间用户可以点击确认选项的四周来取消操作，或直接点击取消按键取消删除操作。

参考模板：![Screenshot_20221030_232416_com.xjs.ehviewer.jpg](https://user-images.githubusercontent.com/98299926/198886960-f65dfaac-09b8-40b0-97a9-3c7cc48c2724.jpg)

![Screenshot_20221031_000349_moe.tarsin.ehviewer.jpg](https://user-images.githubusercontent.com/98299926/198888815-ee01db2a-45da-4463-9714-8032e7f6c7da.jpg)

### 备注 / Addition details

若操作期间应用发生闪退导致删除操作意外结束，如何判断用户的操作是否生效呢？

### EhViewer 版本号 / EhViewer version code

1.7.30.0

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/2916152912

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [x] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by HoriYuko** [comment]
补充：用户可以点击删除提示的四周来取消操作(不包括确认按钮)

**Comment by HoriYuko** [comment]
好的，了解了。

请问之后的版本中能否添加 "需要再次确认删除内容的选项(功能)" 呢？

参考截图：(1) ![Screenshot_20221030_235728_moe.tarsin.ehviewer.jpg](https://user-images.githubusercontent.com/98299926/198986051-4906b38d-7b24-4691-b385-550ee9084fe8.jpg)


(2)![Screenshot_20221030_232416_com.xjs.ehviewer.jpg](https://user-images.githubusercontent.com/98299926/198986153-124b9c9c-6c47-45fa-9c25-7e702bd3920c.jpg)


补充：（2）中的界面不容易误触，但在整理分类书签时没有办法参考画集风格，整理起来会比较麻烦。

**Comment by asuka-mio** [comment]
> 好的，晓得了。
> 
> 请问之后的版本中能否添加 "需要再次确认删除内容的选项(功能)" 呢？
> 
> 参考截图：(1) ![Screenshot_20221030_235728_moe.tarsin.ehviewer.jpg](https://user-images.githubusercontent.com/98299926/198986051-4906b38d-7b24-4691-b385-550ee9084fe8.jpg)
> 
> (2)![Screenshot_20221030_232416_com.xjs.ehviewer.jpg](https://user-images.githubusercontent.com/98299926/198986153-124b9c9c-6c47-45fa-9c25-7e702bd3920c.jpg)
> 
> 补充：（2）中的界面不容易误触，但在整理分类书签时没有办法参考画集风格，整理起来会比较麻烦。

可以的

**Comment by asuka-mio** [comment]
1.7分支不再会被更新
Android9及以上的支持已被合并至1.8分支中
