### ISSUE TITLE
Convert galleryinfo to BottomSheet

### ISSUE THREAD

**Issue by asuka-mio** [Ehviewer-Overhauled/Ehviewer#354]
https://m3.material.io/components/bottom-sheets/overview
![Screenshot_20221031-171431](https://user-images.githubusercontent.com/43900799/198973283-06aa2cb0-80f5-420d-9e5c-440ccd161ca3.png)

**Comment by txyyh** [comment]
@asuka-mio

**Comment by txyyh** [comment]
![Screenshot_20221031-171609](https://user-images.githubusercontent.com/41893946/198973569-995339c4-3ffc-49f2-ab7c-a48df8b23de6.png)

**Comment by asuka-mio** [comment]
> ![Screenshot_20221031-171609](https://user-images.githubusercontent.com/41893946/198973569-995339c4-3ffc-49f2-ab7c-a48df8b23de6.png)
> 
> Wait Google's guideline.

No need to wait, see libchecker's usage
