### ISSUE TITLE
Search Indexing stuck to page 1

### ISSUE THREAD

**Issue by SilentAnime** [Ehviewer-Overhauled/Ehviewer#355]
### 复现步骤 / Step to reproduce

1. Open EhViewer
2. Scroll down to go reach next page

### 预期行为 / Expected behaviour

Ehviewer will load the next page

### 实际行为 / Actual Behaviour

No new page loaded
'Go to' button only shows 1 page is indexed

![Screenshot_20221102-205522_EhViewer](https://user-images.githubusercontent.com/117280580/199498696-a443cd29-5c01-4716-85d3-e35d3679cf57.png)

### 备注 / Addition details

https://twitter.com/ehentai/status/1587734749648490500?s=20

### EhViewer 版本号 / EhViewer version code

1.7.30.0

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3323000949

### Android 系统版本 / Android version

PixelReloaded 11.0.0_r46

### 设备型号 / Device model

ASUS Zenfone Max Pro M1

### SoC 型号 / Soc model

Snapdragon 6 Gen 1

### 应用日志 / App logs

[logcat-2022-11-02-21-09-40-057.txt](https://github.com/Ehviewer-Overhauled/Ehviewer/files/9920634/logcat-2022-11-02-21-09-40-057.txt)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
NOTE: check first checkbox means you will pull-request for it.
Feel free to unassigned

**Comment by atmazzerexe** [comment]
Yeah, my bad. I will try to unassign it

**Comment by txyyh** [comment]
@asuka-mio e-hentai make a change on there website, seems that it's the reason why it failed

**Comment by haywoodspartan** [comment]
https://forums.e-hentai.org/index.php?s=46b1e0abea7092f86fc937ffcc6dc865&showtopic=261743
The search engine has changed and is now using GIDs for search pages instead of actual page numbers

**Comment by biomolecule** [comment]
I've got the same bug, waiting for an update, thanks.

**Comment by asuka-mio** [comment]
Now basic things should work except scroll down to refresh pages and goto certain page

**Comment by txyyh** [comment]
Chinese translation:

目前除了刷新以及跳页的其他基本功能应当可以运转

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3383198482

**Comment by tonyzehs** [comment]
Encountered the same issue (from today as far as I can tell). Thanks for the developmental efforts!

**Comment by emmauss** [comment]
> Now basic things should work except scroll down to refresh pages and goto certain page
> 
> https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3383198482

Move to next page is a bit broken. It sometimes work, and sometimes doesn't until you refresh

**Comment by biomolecule** [comment]
> Chinese translation:
> 
> 目前除了刷新以及跳页的其他基本功能应当可以运转
> 
> https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3383198482

emmm，但是我现在的1.7.30，依然只能看第一页；请问是要下载新的么？我今天才重新装的

**Comment by txyyh** [comment]
@biomolecule https://github.com/txyyh/Ehviewer/actions/runs/3383282047

**Comment by xb2016** [comment]
当前 [最新 CI 版本](https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3384042506) 还有以下问题：
1. 订阅页面、TAG页面、上传者页面：无法翻页
2. 收藏页面：阅读第二页的本子后返回继续下拉，会重新从第一页加载，与主页已修复的问题相同

**Comment by Blazepoch** [comment]
最新1.7.版本存在以下问题： 
1. ”热门”可以无限翻页，内容重复且循环出现。
2. “收藏”无法翻页
3. 随机点进一个画廊，点击下方 tag 快捷搜索，订阅页面、TAG页面、上传者页面，显示的页面皆无法翻页，但是在搜索框主动搜索则无问题。

**Comment by SilentAnime** [comment]
@asuka-mio Thanks for the latest fix. I know "go to certain page" feature is broken, but if the "go to certain page" shows only 1 page or any small numbers, you can't load the next page when you reached that maximum page. The next page exists if you opened it from browser. Tested using @txyyh version of 1.7 if that matters, though I'm pretty sure the changed lines are totally the same.

![Screenshot_20221104-015704_EhViewer](https://user-images.githubusercontent.com/117280580/199812074-72e562a4-6266-4632-ba2c-594133f35b8b.png)

Here's the error log:
[logcat-2022-11-04-01-36-47-566.txt](https://github.com/Ehviewer-Overhauled/Ehviewer/files/9932304/logcat-2022-11-04-01-36-47-566.txt)

**Comment by txyyh** [comment]
@SilentAnime if version 1.7.31.0-alpha02 fix your problem?

**Comment by SilentAnime** [comment]
> @SilentAnime if version 1.7.31.0-alpha02 fix your problem?

Fixed by this release, haven't found any problem like https://github.com/Ehviewer-Overhauled/Ehviewer/issues/355#issuecomment-1302561267 anymore so far. Thanks for the info.
https://github.com/txyyh/Ehviewer/actions/runs/3386896194

**Comment by Nihilm** [comment]
Scroll seems to still be broken for favorites, though it seems to work on the home page/general searches.

**Comment by txyyh** [comment]
> Scroll seems to still be broken for favorites, though it seems to work on the home page/general searches.

If https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3391039954 solve your problem?

**Comment by pidove** [comment]
> > Scroll seems to still be broken for favorites, though it seems to work on the home page/general searches.
> 
> If https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3391039954 solve your problem?

I have installed this one, it doesn't work

**Comment by sekiro1008** [comment]
![Screenshot_2022-11-05-01-21-49-870_moe tarsin ehviewer](https://user-images.githubusercontent.com/117380691/200037719-cf6984ef-ab90-42f5-8f01-01afb66ec67f.jpg)
现在跳页界面是这样的

**Comment by txyyh** [comment]
> ![Screenshot_2022-11-05-01-21-49-870_moe tarsin ehviewer](https://user-images.githubusercontent.com/117380691/200037719-cf6984ef-ab90-42f5-8f01-01afb66ec67f.jpg) 现在跳页界面是这样的

显示错乱是正常的，实际上这个功能已经不奇效了

**Comment by tiger2012010** [comment]
你好，更新的1.7α版本在下载页面无法通过点击封面进入画廊详情了，在这之前的1.7版本是可以的，请问这是什么原因？

**Comment by txyyh** [comment]
@tiger2012010 
> 原则上单个 Issue 内只讨论单个问题

**Comment by xb2016** [comment]
目前 CI 版本还存在的问题：
1. 收藏页面的日期跳页无效，同时还要考虑本地收藏的跳页
2. 设置-高级-备份收藏列表 只能导入第一页的收藏

**Comment by Nihilm** [comment]
> > Scroll seems to still be broken for favorites, though it seems to work on the home page/general searches.
> 
> If https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3391039954 solve your problem?

[1.8.3.0-alpha04](https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.8.3.0-alpha04)

Updated to this and it is fixed now, thank you.

**Comment by asuka-mio** [comment]
Seems most things works well now, and e-hentai has followed this change, then we close it.
