### ISSUE TITLE
E站大改版，APP无法翻页

### ISSUE THREAD

**Issue by LzNOHentai** [Ehviewer-Overhauled/Ehviewer#356]
### 复现步骤 / Step to reproduce

APP只能看第一页，无法加载后续页面。

### 预期行为 / Expected behaviour

正常加载后续页面

### 实际行为 / Actual Behaviour

只能看第一页。

### 备注 / Addition details

E站大改版详情：https://forums.e-hentai.org/index.php?showtopic=261743
暂未发现其他BUG。

### EhViewer 版本号 / EhViewer version code

1.8.2.4

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.8.2.4

### Android 系统版本 / Android version

MIUI 13

### 设备型号 / Device model

Xiaomi 10 Ultra

### SoC 型号 / Soc model

骁龙865

### 应用日志 / App logs

暂无日志

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
与 issue #355 重复
Closed
