### ISSUE TITLE
采用从上往下模式看本子的时候，最终后一页的页数显示错误

### ISSUE THREAD

**Issue by lukemin** [Ehviewer-Overhauled/Ehviewer#362]
### 复现步骤 / Step to reproduce

打开一个本子滑到底

### 预期行为 / Expected behaviour

应该是 最后一页/最后一页，

### 实际行为 / Actual Behaviour

但实际上确实  最后一页-1或2/最后一页。

### EhViewer 版本号 / EhViewer version code

1.7.30.0

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3323000949

### Android 系统版本 / Android version

miui13 安卓11

### 设备型号 / Device model

小米max3

### SoC 型号 / Soc model

sd636

### 应用日志 / App logs

[log-2022-11-03-15-50-50-653.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/9926789/log-2022-11-03-15-50-50-653.zip)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by lukemin** [comment]
现在1.8版本的，Android 11 也可以安装，建议readme不要简单的删除，改成1.8版本现在支持Android 11版本。

**Comment by asuka-mio** [comment]
gid给下

**Comment by lukemin** [comment]
> gid给下

随便哪个本子都可以。

**Comment by FooIbar** [comment]
这不是bug而是预期行为
图片滑过屏幕顶部才算到了下一页
显示倒数第二页是因为在适应宽度的缩放模式下图片高度小于屏幕高度

**Comment by lukemin** [comment]
> 这不是bug而是预期行为 图片滑过屏幕顶部才算到了下一页 显示倒数第二页是因为在适应宽度的缩放模式下图片高度小于屏幕高度

那也应该加上一个一个判断，是否已经到了最后一页，要不本子原因显示没有看完。

**Comment by lukemin** [comment]
@asuka-mio 最新的pre版还是没有解决这个问题，怎么关闭issue了？

**Comment by asuka-mio** [comment]
> @asuka-mio 最新的pre版还是没有解决这个问题，怎么关闭issue了？

ci解决了
