### ISSUE TITLE
热门页翻页循环重复第一页内容

### ISSUE THREAD

**Issue by 3minutes3** [Ehviewer-Overhauled/Ehviewer#371]
### 复现步骤 / Step to reproduce

1、打开软件进入热门页
2、进行下滑的操作
3、会不停的重复循环第一页的内容

### 预期行为 / Expected behaviour

热门页应该进行刷新内容进入下一页，不会重复循环第一页的内容，或者热门页只有第一页

### 实际行为 / Actual Behaviour

不停的重复循环第一页的内容，刷新还是一样

### EhViewer 版本号 / EhViewer version code

1.7.31.0—alpha02

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3396145764

### Android 系统版本 / Android version

MIUI 12.5.2

### 设备型号 / Device model

小米8屏幕指纹版

### SoC 型号 / Soc model

高通骁龙845

### 应用日志 / App logs

>
[日志.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/9943402/default.zip)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by xb2016** [comment]
该页面只有一页，重复加载问题在最新版本已修复
