### ISSUE TITLE
缩略图改为宽度适配

### ISSUE THREAD

**Issue by mojunisme** [Ehviewer-Overhauled/Ehviewer#374]
### 需求 / Requirement

希望列表模式下的封面缩略图改成宽度适配，现在高度适配，导致部分横版封面被迫放大且显示不全。

### 建议实现 / Suggested implements

希望列表模式下的封面缩略图改成宽度适配

### EhViewer 版本号 / EhViewer version code

1.8.3.0-alpha03

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3399607302

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by txyyh** [comment]
由于您勾选了第一个选项，现 assgin 给您

feel free to unassigned it

**Comment by mojunisme** [comment]
不好意思，错误勾到了第一个选项，请帮我 unassign

**Comment by fuchanghao** [comment]
测试了1.7.31-alpha04，同样有这个问题。

**Comment by BeeBiu** [comment]
![suoluetu](https://user-images.githubusercontent.com/32611802/201404217-fbe5dee2-3b97-4319-987e-158c6fc53a2d.JPG)
借楼希望增加缩略图模式下，可调节大小的上限值提供更高的选择，图片太小了，完全看不到，或者调整成单列、2列、3列的选项，非常需要，谢谢

**Comment by txyyh** [comment]
> ![suoluetu](https://user-images.githubusercontent.com/32611802/201404217-fbe5dee2-3b97-4319-987e-158c6fc53a2d.JPG) 借楼希望增加缩略图模式下，可调节大小的上限值提供更高的选择，如280DP以上的选项，图片太小了，完全看不到，或者调整成单列、2列、3列的选项，非常需要，谢谢

> 不要在同一 issue 中讨论与 issue 主题无关内容
