### ISSUE TITLE
在主页点击漫画会卡顿一秒左右后进入

### ISSUE THREAD

**Issue by ndnxnxnx** [Ehviewer-Overhauled/Ehviewer#381]
### 复现步骤 / Step to reproduce

1.把以前的下载数据导入新版本后，点击主页的任意一本漫画。
2主页会在卡顿一秒钟左右后进入
3.退出该漫画后再次进入会立即进入

### 预期行为 / Expected behaviour

点击主页的任意一本漫画会立即进入

### 实际行为 / Actual Behaviour

点击主页任意一本漫画后卡顿后进入

### 备注 / Addition details

没有导入以前的数据时是正常的

### EhViewer 版本号 / EhViewer version code

1.8.3.0-alpha04

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.8.3.0-alpha04

### Android 系统版本 / Android version

miui13.0.7

### 设备型号 / Device model

redmik50ultra

### SoC 型号 / Soc model

骁龙8+

### 应用日志 / App logs

--------- beginning of system
11-06 21:00:56.208  9137  9137 I ForceDarkHelperStubImpl: initialize for moe.tarsin.ehviewer , ForceDarkOrigin
11-06 21:00:56.261  9137  9137 E MiuiMultiWindowUtils: initFreeFormResolutionArgs failed, device is diting
11-06 21:00:56.428  9137  9137 W Activity: PerfMonitor: Slow Operation: Activity moe.tarsin.ehviewer/com.hippo.ehviewer.ui.MainActivity onStart took 110ms
11-06 21:01:02.108  9137  9137 W BpBinder: Slow Binder: BpBinder transact took 618 ms, interface=android.content.IContentProvider, code=1 oneway=false
11-06 21:01:02.215  9137  9137 W Looper  : PerfMonitor doFrame : time=3ms vsyncFrame=0 latency=728ms procState=-1 historyMsgCount=15 (msgIndex=15 wall=725ms seq=673 running=100ms runnable=2ms io=1ms late=3ms h=android.os.Handler c=Wb)
11-06 21:01:08.430  9137  9161 W BpBinder: Slow Binder: BpBinder transact took 12107 ms, interface=android.content.IContentProvider, code=23 oneway=false
--------- beginning of main
11-06 21:03:16.672  9137  915

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
从这点信息判断不出啥
介意把数据私下出于debug的用途分享下吗
@txyyh 你去和他沟通下

**Comment by jerryfangr** [comment]
# 环境
- **1.7.31.0-alpha04**
- **骁龙855 Android 11 - miui12.5**
- **exhentai 配置**
    - **Image Size Settings: `Auto`**
    - **Thumbnail Settings (Rows): `20`**
    - **Search Result Count: `50results`**

# 描述
在我这出现了类似甚至更严重的卡顿问题，该问题在1.7.31.0-alpha02未遇到。
无论是单个图册的浏览，还是图册间的切换都会出现该卡顿问题。

# 复现
**Q1:** 打开任意超过100页的图册，在主页快速上下滑动，大约10s内app会变得肉眼可见的卡顿，停止操作一段时间会恢复流畅。

**Q2:**【打开任意图册，页面加载完就点击种子，种子加载出就退出当前图册】，然后再【点击下一图册，……点击种子……退出图册】，重复操作，大约在从第3个图册开始，app会越来越卡顿

# 日志
附件日志包含我找的一个相对好测试的案例`伯母に焦がれて`，添加到收藏栏后，在收藏夹进行上述复现步骤。
该图册系列有超过10本图册，每本图册超过100页内容，且每本图册都有种子。

**我已将日志文件的解压密码发送至一个公开的开发者邮箱[@txyyh](https://github.com/txyyh)的zjh330726@gmail.com**

[log-2022-11-07-15-16-29-442.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/9949061/log-2022-11-07-15-16-29-442.zip)

**Comment by asuka-mio** [comment]
我大概有头绪了 前段时间 @xb2016 放开了预览的限制 https://github.com/Ehviewer-Overhauled/Ehviewer/issues/332 然而由于我没有给e站课金 所以预览最多只能是是40张图片 一直不会导致此bug出现

**Comment by xb2016** [comment]
草 那把限制加回去？还是优化下这个页面

**Comment by asuka-mio** [comment]
@txyyh 你负责revert 下 我要摸鱼（

**Comment by asuka-mio** [comment]
但是这个问题应该只是另一个问题 和issue主的问题不是一个 那个我看是和数据库有关的性能问题

**Comment by xb2016** [comment]
> @txyyh 你负责revert 下 我要摸鱼（

别摸了别摸了 昨天说的闪退问题还没解呢

**Comment by txyyh** [comment]
@asuka-mio 好喵

**Comment by asuka-mio** [comment]
> > @txyyh 你负责revert 下 我要摸鱼（
> 
> 别摸了别摸了 昨天说的闪退问题还没解呢

我得复现才能修呀 你快告诉我复现方法

**Comment by jerryfangr** [comment]
> > 草 那把限制加回去？还是优化下这个页面
> 
> 因为我没课金帐号/设备性能太高 估计修不了 revert 吧

作者介意发下你的E站登录账号吗。
我还玩剩点Credits，应该够你换个50Hath，够解锁第一档`More Thumbnail`吧

**Comment by lauglam** [comment]
是否是外部存储的问题。我将下载目录更改为外部存储地址，如`/sdcard/EhViewer`就会出现这种情况，改回去之后问题消失

**Comment by lauglam** [comment]
我看了下源码，此处会遍历下载目录下面的文件夹。我的文件夹大概有1300个左右（55GB）

![image](https://user-images.githubusercontent.com/58240137/201953168-ca52a6b0-6d7d-4522-ab6c-fd89803115e4.png)

改了下载路径之后，这个路径也蛮奇怪的，是否是这种读取方法存在问题？

![微信图片_20221115231743](https://user-images.githubusercontent.com/58240137/201956348-01a7b688-bb99-4066-a046-0c13a3c75e12.jpg)

**Comment by lauglam** [comment]
这是我的日志文件。祝安好
[log-2022-11-15-23-09-04-633.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10013892/log-2022-11-15-23-09-04-633.zip)

**Comment by ndnxnxnx** [comment]
> > > 草 那把限制加回去？还是优化下这个页面
> > 
> > 
> > 因为我没课金帐号/设备性能太高 估计修不了 revert 吧
> 
> 作者介意发下你的E站账号名么吗，一般是登录的名称。 我还玩剩点Credits，转你应该够你换个50Hath，够解锁第一档吧`More Thumbnail`
我的吗

**Comment by lauglam** [comment]
> > 是否是外部存储的问题。我将下载目录更改为外部存储地址，如就会出现这种情况，改回去之后问题消失`/sdcard/EhViewer`
> 
> 我的是60多g，2000左右个文件夹，我是把下载文件夹从android里移到外边了，不导入数据的话一切正常，导入的话就出现那种状况了

我不是专业安卓开发，但怀疑是安卓10/11开始的这种沙箱读取造成的，我以前版本在数据`Android/data/xxx`下，文件夹一样很多，但没有发现这种情况。改为放到外面就会出现这种问题。

还是希望能解决一下，因为放在应用自己的文件夹在需要导出的情况下非常麻烦。用adb pull 因为文件路径过长，甚至无法导出，只能在Linux下操作。如果用Windows文件管理器导出，估计得好几个小时

**Comment by asuka-mio** [comment]
> > > 是否是外部存储的问题。我将下载目录更改为外部存储地址，如就会出现这种情况，改回去之后问题消失`/sdcard/EhViewer`
> > 
> > 
> > 我的是60多g，2000左右个文件夹，我是把下载文件夹从android里移到外边了，不导入数据的话一切正常，导入的话就出现那种状况了
> 
> 我不是专业安卓开发，但怀疑是安卓10/11开始的这种沙箱读取造成的，我以前版本在数据`Android/data/xxx`下，文件夹一样很多，但没有发现这种情况。改为放到外面就会出现这种问题。
> 
> 还是希望能解决一下，因为放在应用自己的文件夹在需要导出的情况下非常麻烦。用adb pull 因为文件路径过长，甚至无法导出，只能在Linux下操作。如果用Windows文件管理器导出，估计得好几个小时

我们之后打算重构现有的下载逻辑 将每个画廊保存至单独的cbz归档文件里 这样也会更方便管理 现在目前一个目录里一堆图片的设计太屎了

**Comment by asuka-mio** [comment]
> 刚查到一篇帖子，也许这是Android11以上存在的通病。具体[参阅](https://www.reddit.com/r/androiddev/comments/kpn68k/android_11_very_slow_file_access_performance/)
> 
> 只能说难顶！

虽然慢 但是在合理的实现下也是不应该出现卡顿的

**Comment by lauglam** [comment]
> > 刚查到一篇帖子，也许这是Android11以上存在的通病。具体[参阅](https://www.reddit.com/r/androiddev/comments/kpn68k/android_11_very_slow_file_access_performance/)
> > 只能说难顶！
> 
> 虽然慢 但是在合理的实现下也是不应该出现卡顿的

我将这段注释掉后，问题消失。

![image](https://user-images.githubusercontent.com/58240137/202076050-6bfa3b92-561a-46ec-b6cc-59dc00bca068.png)

我在想是否需要这一段？

逻辑是寻找是否有`dirname`，都没找到就创建一个放到`DOWNLOAD_DIRNAME`表中，但是否需要到下载目录里面找？或者可以在`DOWNLOAD`表里找？

如果不到下载目录里面找会怎么样？不太清楚
