### ISSUE TITLE
1.7.31.0-alpha04没有添加下载标签

### ISSUE THREAD

**Issue by iyjyjj** [Ehviewer-Overhauled/Ehviewer#384]
### 需求 / Requirement

需要下载标签分类

### 建议实现 / Suggested implements

需要在下载界面右滑打开下载标签页面添加下载标签

### 备注 / Addition details

无

### EhViewer 版本号 / EhViewer version code

1.7.31.0-alpha04

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.7.31.0-alpha04

### 自查步骤 / Verify steps

- [x] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by txyyh** [comment]
@iyjyjj 1. 由于您已经勾选第一个复选框，将为您assgin。Feel free to unassigned it
2. 请正确填充 ehviewer ci 版本，感谢配合

**Comment by iyjyjj** [comment]
我修改好了，您看看

**Comment by iyjyjj** [comment]
不好意思，经过我的四处点点设置，我知道了点击设置就可以添加标签和白e直接有一个+号操作逻辑不同

**Comment by asuka-mio** [comment]
> 不好意思，经过我的四处点点设置，我知道了点击设置就可以添加标签和白e直接有一个+号操作逻辑不同

草 刚注意到 我下回给它整成加号挪上去
