### ISSUE TITLE
是否取消或者增加搜索历史记录的上限

### ISSUE THREAD

**Issue by Aojiao** [Ehviewer-Overhauled/Ehviewer#392]
### 需求 / Requirement

尽可能的增大搜索栏历史记录的上限，现在由于达到现有记录量上限后会自动删除最早的记录，后期想翻阅早期的历史很困难

### 建议实现 / Suggested implements

增大或取消搜索历史记录上限

### EhViewer 版本号 / EhViewer version code

1.7.31.0-alpha04

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3403398947

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by txyyh** [comment]
@Aojiao action版本错误
请到action栏中寻找

**Comment by txyyh** [comment]
@Aojiao action版本错误
请到action栏中寻找

**Comment by Aojiao** [comment]
> 

已修改

**Comment by Aojiao** [comment]
> @Aojiao action版本错误 请到action栏中寻找

已修改

**Comment by Aojiao** [comment]
> @Aojiao动作版本错误 请到寻找动作出现

@txyyh 已修改
