### ISSUE TITLE
Redesign searchbar

### ISSUE THREAD

**Issue by asuka-mio** [Ehviewer-Overhauled/Ehviewer#397]
Although this cardview is md3 style, but such idiot design is not md3 at all

**Comment by asuka-mio** [comment]
https://github.com/material-components/material-components-android/blob/master/docs/components/Search.md#using-search-components

Seems we could follow this.

**Comment by txyyh** [comment]
Still have some problem
Searchbar margin is not the same as card

**Comment by txyyh** [comment]
And DO NOT leave card transparent
