### ISSUE TITLE
震动反馈可以多来点

### ISSUE THREAD

**Issue by wan0ge** [Ehviewer-Overhauled/Ehviewer#408]
### 需求 / Requirement

在可互动的按钮上适当增加震动反馈

### 建议实现 / Suggested implements

像是跳页的滑条就很适合做震动反馈，滑起来会非常舒适；收藏、下载、分享这样的按钮也可以加，点赞评论也可以，这类操作有个反馈会舒适很多。
![Screenshot_2022-11-13-01-14-57-941_moe tarsin ehviewer](https://user-images.githubusercontent.com/82034747/201487095-f5cd3f8d-7b1d-474f-9885-45b23785ecd4.jpg)

### 备注 / Addition details

可以加上开关

### EhViewer 版本号 / EhViewer version code

1.8.3.0-alpha04

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.8.3.0-alpha04

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by asuka-mio** [comment]
如果是线性马达的话 确实挺舒服的 不过那个组件直接用的mdc现成的 我一会看看怎么比较干净的改下

**Comment by asuka-mio** [comment]
笑死 刚想参考下gapps的谷歌时钟的触感反馈设计 结果他们整出bug了，那个闹钟card上的switch 点一下连着震两下

**Comment by wan0ge** [comment]
> 笑死 刚想参考下gapps的谷歌时钟的触感反馈设计 结果他们整出bug了，那个闹钟card上的switch 点一下连着震两下

草哈哈，这个[漫画图源聚合器](https://github.com/tachiyomiorg/tachiyomi) 的进度滑条就有震动，或许可以参考看看，虽然不知道用什么写的
