### ISSUE TITLE
`Ehviewer 1.8.3.0-alpha04` 在 `OPPO ColorOS 13.0 Android 13` 上被识别为病毒软件。

### ISSUE THREAD

**Issue by dyguests** [Ehviewer-Overhauled/Ehviewer#410]
### 复现步骤 / Step to reproduce

1. 安装最新版。
2. 微信支持等
3. 报病毒：
![{5XU)M6HB6 )F1_5M XTK81](https://user-images.githubusercontent.com/7933189/201516791-132d6505-1878-4b4d-9872-071ce367cb84.jpg)

### 预期行为 / Expected behaviour

不报病毒

### 实际行为 / Actual Behaviour

报病毒

### 备注 / Addition details

之前的版本无此问题。
忘记之前的版本号，不过应该是未适配新的分页逻辑的版本。

---

是否是因为引入了新的三方库导致的？
还是单纯因为是 Eh？

### EhViewer 版本号 / EhViewer version code

1.8.3.0-alpha04

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/download/1.8.3.0-alpha04/EhViewer-arm64-v8a-A12+.apk

### Android 系统版本 / Android version

ColorOS 13.0, Android 13

### 设备型号 / Device model

OPPO Reno 5 Pro

### SoC 型号 / Soc model

骁龙 865八核

### 应用日志 / App logs

无，外部问题，非App内部问题

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
https://github.com/Ehviewer-Overhauled/Ehviewer/issues/409#issuecomment-1312605772

 issue 重复

**Comment by dyguests** [comment]
sad. :(

**Comment by asuka-mio** [comment]
https://github.com/Ehviewer-Overhauled/Ehviewer/compare/1.8.3.0-alpha03...1.8.3.0-alpha04
这两个版本一共就这些更改
我不认为是app本身内部有（疑似）病毒特征代码导致的，何况我们的发布版都是经过混淆处理的，原生库也可以1排除掉，这两个版本间没有更改
所以只能是app的包名+版本号进他们病毒库黑名单了
同上 无法解决

**Comment by wordlesswind** [comment]
“特征码”与华为/荣耀的手机管家/平板管家相同，应该是腾讯的病毒库记录的样本信息。#409

![Screenshot_2022-11-24-13-40-35-56_035d55d4552197c94b0185899d8a326c](https://user-images.githubusercontent.com/9050713/203705662-cef746c1-d01e-448e-af90-d6ba5d88bb4b.jpg)

**Comment by asuka-mio** [comment]
> “特征码”与华为/荣耀的手机管家/平板管家相同，应该是腾讯的病毒库记录的样本信息。#409
> 
> ![Screenshot_2022-11-24-13-40-35-56_035d55d4552197c94b0185899d8a326c](https://user-images.githubusercontent.com/9050713/203705662-cef746c1-d01e-448e-af90-d6ba5d88bb4b.jpg)

是否有什么比较简单的修复方案
我对这方面不太了解 而且也没法测试

**Comment by wordlesswind** [comment]
> 是否有什么比较简单的修复方案
我对这方面不太了解 而且也没法测试

🤔我也不了解，第一次遇到这种问题。我看了下 Pornhub 的特征码是“Trojan.Expense.Android.PornManual.A”。
再根据 https://zhuanlan.zhihu.com/p/301027963 ，那这边的情况应该是被自动识别了，使用了本项目代码的 EhViewer-NekoInverter/EhViewer 也有相同情况。

但是无法确认是哪次变动导致的问题，就算现在我安装 [`1.8.0.0`](https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.8.0.0) 版本，华为平板管家仍然会出现提示。而腾讯手机管家也是如此
![IMG_20221124_235341](https://user-images.githubusercontent.com/9050713/203825419-77bc74f6-b2ec-497f-9e9a-c9d21d2c6602.jpg)

所以这更像是腾讯的病毒库在近期更新后，将某些字符串视为了敏感词，检测到即提示。

**Comment by dyguests** [comment]
目前比较严重的点是：手机识别这个病毒很严重，手机支付类应用（银行app）不让用，必须卸载了Eh才让用，否则支付类应用就进不去。

**Comment by asuka-mio** [comment]
> 目前比较严重的点是：手机识别这个病毒很严重，手机支付类应用（银行app）不让用，必须卸载了Eh才让用，否则支付类应用就进不去。

好家伙，现在国内这伙人行为这么恶劣了吗

**Comment by asuka-mio** [comment]
> 目前比较严重的点是：手机识别这个病毒很严重，手机支付类应用（银行app）不让用，必须卸载了Eh才让用，否则支付类应用就进不去。

那确实有必要解决一下，不过我没法提供什么帮助

**Comment by asuka-mio** [comment]
真就合起伙来搞绑架用户啊

**Comment by asuka-mio** [comment]
@txyyh 要reopen下吗 然后mark下help wanted

**Comment by asuka-mio** [comment]
> @asuka-mio 主要本项目明确写了不会对OEM系统官方做支持
> 
> 不过 help wanted 倒是可以等个pr啥的，主人自己还是不要在这上面浪费时间了

好

**Comment by txyyh** [comment]
@asuka-mio 重复 issue 不应该因为任何原因 reopen

**Comment by wordlesswind** [comment]
> 目前比较严重的点是：手机识别这个病毒很严重，手机支付类应用（银行app）不让用，必须卸载了Eh才让用，否则支付类应用就进不去。

什么系统？
