### ISSUE TITLE
详情页中，按钮组“收藏/分享/种子/.../相似画廊/搜索封面”的顺序是否可以优化下？

### ISSUE THREAD

**Issue by dyguests** [Ehviewer-Overhauled/Ehviewer#413]
### 需求 / Requirement

详情页中，按钮组“收藏/分享/种子/.../相似画廊/搜索封面”的顺序是否可以优化下？

在新版本中，详细页中的“收藏/.../相似画廊/...”的宽度变宽了，想使用的按钮不方便点击。

从我个人角度来说：使用频率最高的按钮依次是“相似画廊”、“搜索封面”等等。
能否按此顺序优化下按钮的顺序？

### 建议实现 / Suggested implements

按钮组“收藏/分享/种子/.../相似画廊/搜索封面”的顺序
改成：

相似画廊/搜索封面/收藏/分享/种子/压缩包

### 备注 / Addition details

无

### EhViewer 版本号 / EhViewer version code

1.8.3.0-alpha04

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/download/1.8.3.0-alpha04/EhViewer-arm64-v8a-A12+.apk

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by asuka-mio** [comment]
分享、种子、压缩包确实不算常用， 收藏应该是几乎所有人最常用的吧 我酌情调整
