### ISSUE TITLE
搜索-高级选项-最低评分复选框优化

### ISSUE THREAD

**Issue by dyguests** [Ehviewer-Overhauled/Ehviewer#414]
### 需求 / Requirement

搜索-高级选项 中
最低评分复选框 与旁边的 最低评分下拉框 是否可以合并成一个 Slider(ProgressBar，滑动条)

---

现有逻辑似乎是：
1. 不勾选，搜索 1~5评分
2. 勾选，下拉框选择 X，搜索 X~5评分

---

这样是否可以合并成一个 Slider（选择范围是1~5）
新的逻辑是：
1. Slider选择1，等同于之前的不勾选
2. Slider选择X(X>1)，等同于之前的勾选+下拉框选择X

### 建议实现 / Suggested implements

最低评分使用一个 Slider（选择范围是1~5）
新的逻辑是：
1. Slider选择1，等同于之前的不勾选
2. Slider选择X(X>1)，等同于之前的勾选+下拉框选择X

### 备注 / Addition details

无

### EhViewer 版本号 / EhViewer version code

1.8.3.0-alpha04

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/download/1.8.3.0-alpha04/EhViewer-arm64-v8a-A12+.apk

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by asuka-mio** [comment]
我感觉还是做成一个rangeslider直观， 虽然没有人会去限制最高评分（笑
