### ISSUE TITLE
改版后的跳页优化

### ISSUE THREAD

**Issue by wan0ge** [Ehviewer-Overhauled/Ehviewer#418]
### 需求 / Requirement

改版的跳页好难用，例如收藏界面在并不知道哪一天有自己收藏的东西的时候看到日期会非常茫然，有方法技术突破实现像之前那样跳页吗？如果没希望以后大佬们能研发出。
另外现跳页可以优化使用体验，像[绿E](https://github.com/xiaojieonly/Ehviewer_CN_SXJ) 那边就提供了几个更直观的选项
![IMG_20221116_222428](https://user-images.githubusercontent.com/82034747/202210853-9da52d23-b75a-4a85-a55b-5235486c057d.jpg)
彩E也可以这么加，最好在末尾再加一个跳转到“末尾”选项，算是在技术突破之前的尽量优化了

### 建议实现 / Suggested implements

如需求所示，在跳页界面添加一些更直观的选项，或者用更好的方案优化体验

### EhViewer 版本号 / EhViewer version code

1.8.3.0-beta01

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.8.3.0-beta01

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by txyyh** [comment]
@wan0ge 日期跳转直接使用谷歌提供的组件，另加实现的可能性不高
另提前一个月，提前一年的更改其实都可以实现（只改动月份年份即可）

**Comment by wan0ge** [comment]
> 1. 日期跳转直接使用谷歌提供的组件，改动实现的可能性不高
>    另提前几个月，提前几年的更改其实都可以实现（只改动月份年份即可）
> 2. 页码概念已经不再存在，上下一页和指定日期的内容全部由服务器即时生成，客户端要想实现页码概念本身已经算是不可能
>    跳转末尾同理，甚至理论上服务器都无从知晓何谓“末尾”，“页数”

这……这改动真有够大的，好吧理解了，但还是希望未来有方法可以实现，或者在此之前EhViewer再改动一次233

**Comment by asuka-mio** [comment]
关于直观这个概念， 我反而是觉得绝对时间更直观，相对时间更模糊，而且这些偏移量在目前的组件中也不需要复杂的操作就可以达成，反而我感觉这种一堆radiobutton的实现更丑。。。
