### ISSUE TITLE
已经下载好的本子封面缩略图，疑似在手机清理内存时被当作垃圾自动清理掉

### ISSUE THREAD

**Issue by jc667mc2** [Ehviewer-Overhauled/Ehviewer#419]
### 复现步骤 / Step to reproduce

下载好本子后关闭应用，使用手机自带的手机管家或者第三方手机管家进行内存清理，尽管EHviewer的文件不在被将要被清理的缓存垃圾之中显示，但重新打开app时发现这些本子的缩略图封面丢失，全部需要重新加载。

### 预期行为 / Expected behaviour

以Hippo版本的Ehviewer举例，已经下载好的本子封面缩略图，并不会受到手机管家后或是第三方内存清理的应用的影响。并不存在进行手机内存清理时，把已经下载好的本子封面缩略图给清理掉这一问题，进行手机清理后再重新打开Ehviewer，已经下载好的本子封面缩略图依旧保持原样，不需要重新加载。

### 实际行为 / Actual Behaviour

![Screenshot_20221117_120457_moe tarsin ehviewer_edit_46535138594460](https://user-images.githubusercontent.com/118359407/202355232-ae25422a-efb9-48a2-86c0-c9ba40ab8028.jpg)
我每次在使用手机自带的手机管家以及第三方应用进行清理后，已经下载的本子的封面缩略图就全部消失了，重新打开以后就成这种样子，全部需要重新加载。

### EhViewer 版本号 / EhViewer version code

1.7.31.0-alpha04

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/discussions/377

### Android 系统版本 / Android version

荣耀Magic 4.0  Android10

### 设备型号 / Device model

荣耀v20

### SoC 型号 / Soc model

麒麟980

### 应用日志 / App logs

[log-2022-11-17-12-19-19-839.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10027723/log-2022-11-17-12-19-19-839.zip)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
建议向手机管家的开发厂商反馈本问题

对此我们无从适配

**Comment by asuka-mio** [comment]
不是这个问题， 是我之前改成imagedecoder解码后端的时候，直接把缩略图加载的一个缓存扬了，因为imagedecoder只能接受seekable的文件描述符或者一段内存缓冲区，之后我重新实现一个第一张图片的fd重载进去

**Comment by txyyh** [comment]
@asuka-mio 你重开个issue

**Comment by asuka-mio** [comment]
先放一放 我之后要重构整个下载架构，换成archive-base的

**Comment by asuka-mio** [comment]
Deferred since issue #405

**Comment by FooIbar** [comment]
要不这个重开吧
