### ISSUE TITLE
安卓系统低于Q时GalleryActivity页无法保存

### ISSUE THREAD

**Issue by ChaoCaiGuo** [Ehviewer-Overhauled/Ehviewer#421]
### 复现步骤 / Step to reproduce

点击GalleryActivity长按出现的Dialog的保存

### 预期行为 / Expected behaviour

toast显示“图片至.....”

### 实际行为 / Actual Behaviour

toast显示“无法保存图片”

### 备注 / Addition details

此bug由其他人反馈到我这儿的bug。已经排查探明。
GalleryActivity里针对安卓Q版本以下需要申请一个写外部文件的权限（write_external_storage），但文件权限清单（AndroidManifest）中的write_external_storage权限被去掉了。只要把相关权限写回AndroidManifest，就能进行正常保存操作了。
官方文档上的[媒体]MediaStore API说明，在 Android 9（API 级别 28）或更低版本中，访问所有文件均需要相关权限

### EhViewer 版本号 / EhViewer version code

1.7.31.0-alpha04

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.7.31.0-alpha04

### Android 系统版本 / Android version

低于安卓Q版本

### 设备型号 / Device model

不重要

### SoC 型号 / Soc model

不重要

### 应用日志 / App logs

不重要

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
即使不重要，也请补全信息。感谢配合

**Comment by ChaoCaiGuo** [comment]
额这真没什么可补全信息，此bug由其他人反馈到我这儿的bug。我用模拟器调了个低版本的安卓系统（安卓8）运行调试的也复现了该bug，总不至于我要填写模拟器的名字吧.....
该bug由于com.hippo.ehviewer.ui下的GalleryActivity中的saveImage()方法下的Build.VERSION.SDK_INT < Build.VERSION_CODES.Q时会申请 Manifest.permission.WRITE_EXTERNAL_STORAGE权限，但在AndroidManifest中WRITE_EXTERNAL_STORAGE被去除导致无法动态申请到权限。只要在AndroidManifest补上    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        android:maxSdkVersion="29" />就行

> 即使不重要，也请补全信息。感谢配合

**Comment by ChaoCaiGuo** [comment]
在AndroidManifest补上`    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        android:maxSdkVersion="29" />`
