### ISSUE TITLE
使用Ehviewer-Overhauled直接浏览zip压缩包中本子，页面顺序错乱

### ISSUE THREAD

**Issue by VVaraiotoko** [Ehviewer-Overhauled/Ehviewer#427]
### 复现步骤 / Step to reproduce

1. 不解压zip，直接选择Ehviewer-Overhauled浏览其中本子文件
2. 页面顺序错乱，无法按照页码顺序甚至文件默认排列顺序翻页

### 预期行为 / Expected behaviour

它应该按页码顺序翻页

### 实际行为 / Actual Behaviour

![Screenshot_20221119-221547](https://user-images.githubusercontent.com/28192782/202855435-6c7046f5-a383-41d1-93f6-7d3fc279c8a6.png)
在ZArchiver中，zip文件内图片顺序正常
![Screenshot_20221119-221854](https://user-images.githubusercontent.com/28192782/202855541-a36be51c-9744-4170-b68b-6c8ef0eb9ab5.png)
在原版EhViewer中，第1页为封面，图片顺序正常
![Screenshot_20221119-222339](https://user-images.githubusercontent.com/28192782/202855670-563dbe8f-cff5-4fa8-94fa-e356a2c51f69.png)
在Ehviewer-Overhauled中，第1页为实际的第10页，图片顺序异常

### EhViewer 版本号 / EhViewer version code

1.8.3.0-beta02

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3489725580

### Android 系统版本 / Android version

Android 12, Sony Stock 58.2.A.7.93

### 设备型号 / Device model

Sony Xperia 1 II

### SoC 型号 / Soc model

骁龙865

### 应用日志 / App logs

[log-2022-11-19-22-34-22-671.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10047205/log-2022-11-19-22-34-22-671.zip)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by VVaraiotoko** [comment]
这应该是对原版的修改造成的bug，可否修复一下呢？

**Comment by asuka-mio** [comment]
https://github.com/Ehviewer-Overhauled/Ehviewer/discussions/240 这个或许可以帮助到你

**Comment by VVaraiotoko** [comment]
> > 这应该是对原版的修改造成的bug，可否修复一下呢？
> 
> 这是预期行为 我们从p7zip实现迁移到了libarchive实现 遵循流式读取 出现这种情况的原因是图片文件在压缩包中数据的先后顺序和页码并不是一个顺序 至于以后要不要实现按文件名排序功能我再考虑 因为现在本身应用的页码请求机制就不是面向流式优化的 我得先重构这块

实现的迁移肯定是为了提高应用运行效率，但还是希望能实现按文件名/页码顺序浏览吧，毕竟这样是符合用户直觉的，谢谢。

**Comment by asuka-mio** [comment]
> > > 这应该是对原版的修改造成的bug，可否修复一下呢？
> > 
> > 
> > 这是预期行为 我们从p7zip实现迁移到了libarchive实现 遵循流式读取 出现这种情况的原因是图片文件在压缩包中数据的先后顺序和页码并不是一个顺序 至于以后要不要实现按文件名排序功能我再考虑 因为现在本身应用的页码请求机制就不是面向流式优化的 我得先重构这块
> 
> 实现的迁移肯定是为了提高应用运行效率，但还是希望能实现按文件名/页码顺序浏览吧，毕竟这样是符合用户直觉的，谢谢。

其实主要是看p7zip不顺眼(
