### ISSUE TITLE
希望下载压缩包能包括不使用H@H Downloader的选项

### ISSUE THREAD

**Issue by VVaraiotoko** [Ehviewer-Overhauled/Ehviewer#429]
### 需求 / Requirement

希望能直接通过应用下载压缩包，无需H@H Downloader

### 建议实现 / Suggested implements

建议在下载压缩包中能添加直接下载的选项
![_20221119_234535](https://user-images.githubusercontent.com/28192782/202859615-3bc0866c-9042-412b-b8d6-61761ad210fd.JPG)
E-Hentai/ExHentai网页中下载压缩包本就有不同的选项，且H@H Downloader似乎并无Android端？
![Screenshot 2022-11-19 at 23-46-59 Archiver](https://user-images.githubusercontent.com/28192782/202859740-1f76b120-d6f2-4820-876b-e07507b572d2.png)
JHenTai中有类似功能
![_20221119_235041](https://user-images.githubusercontent.com/28192782/202859909-d6d7fd80-3381-4a20-903e-c40830ff8d2c.JPG)
![Screenshot_20221120-000224](https://user-images.githubusercontent.com/28192782/202860131-d682d3c9-ceee-4f50-bb21-ee7da2093413.png)

### EhViewer 版本号 / EhViewer version code

1.8.3.0-beta02

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3503995912

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by asuka-mio** [comment]
关于这个 我们之后会将下载系统重构为以归档文件为基础的
也就是 到时候你只要下载画廊就相当于获得了一个压缩包
届时将去除这个选项 （因为e站默认会提供7z格式的？） 7z并不适合进行流式读取，会损失很多预读取优化带来的性能提升

**Comment by asuka-mio** [comment]
Closed since #405

**Comment by FooIbar** [comment]
@asuka-mio e站提供的压缩包是deflate算法的zip
两者其实并不能完全替代
直接下载消耗的是image limit，通过e站提供的方式下载消耗的是GP
而且直接下原图要hath perk，但打包的原始档案没有这个要求

**Comment by VVaraiotoko** [comment]
> 关于这个 我们之后会将下载系统重构为以归档文件为基础的 也就是 到时候你只要下载画廊就相当于获得了一个压缩包 届时将去除这个选项 （因为e站默认会提供7z格式的？） 7z并不适合进行流式读取，会损失很多预读取优化带来的性能提升

这是官方网页提供的压缩包（格式应该是zip）下载方式。对于捐赠者来说，每周有压缩包免费下载配额，且不占用image limit，不用就浪费了。

**Comment by asuka-mio** [comment]
嗯 不太了解e站的机制 如果直接下载可行的话后续也会考虑实现

**Comment by VVaraiotoko** [comment]
> 嗯 不太了解e站的机制 如果直接下载可行的话后续也会考虑实现

因为E站网页Archive Download里有现成选项，大概不会超级困难吧…以下是已经实现此功能的JHenTai的链接，也许可以作为参考？本人无编程经验，如违反某某授权许可，当我没发😂
https://github.com/jiangtian616/JHenTai
另外也希望修复/优化zip查看功能，谢谢：
https://github.com/Ehviewer-Overhauled/Ehviewer/issues/427

**Comment by asuka-mio** [comment]
> > 嗯 不太了解e站的机制 如果直接下载可行的话后续也会考虑实现
> 
> 因为E站网页Archive Download里有现成选项，大概不会超级困难吧…以下是已经实现此功能的JHenTai的链接，也许可以作为参考？本人无编程经验，如违反某某授权许可，当我没发joy https://github.com/jiangtian616/JHenTai 另外也希望修复/优化zip查看功能，谢谢： #427

授权许可到没事， GPLv3可以随便拿APLv2的代码， 不过他们dart flutter写的， 我不玩dart

**Comment by Mapaler** [comment]
用VPS开H@H的，Archive Download 每周都有几个G的免费配额，下载压缩包直接解压会比较省 image limit。下载到 H@H ，还是得去 VPS 上的 H@H 再下载到本地，对于手机上看没有什么用。

**Comment by sdshdv** [comment]
E站网页上的Archive Download对于没捐赠的普通用户来说每次都要消耗GP点的，所以客户端这种消耗image limit的下载方式反而更好，反正image limit会随时间恢复。
当然如果一定要两种下载方式共存，建议对Archive Download加个会消耗多少GP的提醒
