### ISSUE TITLE
阅读页面，页面缩放增加“填充”模式。

### ISSUE THREAD

**Issue by dyguests** [Ehviewer-Overhauled/Ehviewer#432]
### 需求 / Requirement

我希望在阅读漫画时，页面缩放增加一个“填充”的模式。

目前阅读时，受限于手机尺寸，看漫画时一般是让图片占满屏幕，不显示黑边。
一般漫画分页比例相较于手机屏幕（竖屏），都是偏宽的，因此页面缩放通常选择**匹配长度**。

但对于条漫，或者横屏阅读时，需要**手动**将页面缩放更改成**匹配宽度**。

基于此现象，希望能增加**填充**模式。
此模式类似视频的去黑边，等比例缩放使短边抵满，长边超出。

### 建议实现 / Suggested implements

1. 基于屏幕宽高比，与图片宽高比，选择对应的页面缩放方式。
2. 对于翻页时，页面宽高比变化时，动态更新对应页面缩放方式。（优先度低）
3. 对于旋转屏幕时，屏幕宽高比变化时，动态更新对应页面缩放方式。
4. 对于屏幕尺寸变化时，屏幕宽高比变化时，动态更新对应页面缩放方式。（优先度低，针对小窗，浮窗，分屏，折叠屏等）

### EhViewer 版本号 / EhViewer version code

1.8.3.0-beta02

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/download/1.8.3.0-beta02/EhViewer-arm64-v8a-A12+.apk

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by asuka-mio** [comment]
以后这块的功能和tachiyomi同步更新 你说的我看应该是都实现了 要是还没有实现的话可以去他们那边提FR(
