### ISSUE TITLE
翻页手势优化

### ISSUE THREAD

**Issue by dyguests** [Ehviewer-Overhauled/Ehviewer#433]
### 需求 / Requirement

希望
1. 点击（左或右），下一页
2. 左滑，上一页
3. 右滑，下一面

阅读方向从右至左，右手手持手机时。原翻页逻辑是：

1. 点击左侧屏幕，下一页
3. 点击右侧屏幕，上一页
4. 左滑，上一页
5. 右滑，下一面

显然的，上述操作习惯下，“1. 点击左侧屏幕” 不方便实现。只能通过“4. 右滑，下一面”。

希望能改成：
1. 点击（左或右），下一页
2. 左滑，上一页
3. 右滑，下一面

### 建议实现 / Suggested implements

可以参考 起点阅读 的 阅读页面 设置 中 的 单手模式。

### EhViewer 版本号 / EhViewer version code

1.8.3.0-beta02

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/download/1.8.3.0-beta02/EhViewer-arm64-v8a-A12+.apk

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by asuka-mio** [comment]
把tachiyomi的手势全搬过来了 看够不够用 不够用再说他们架构好拓展
