### ISSUE TITLE
漫画列表页，FloatingAction优化。

### ISSUE THREAD

**Issue by dyguests** [Ehviewer-Overhauled/Ehviewer#435]
### 需求 / Requirement

漫画列表页中 FloatingAction的图标 “+” 能否改成 页码数？（个人感觉这个位置最好）
或者在其它地方明示？

### 建议实现 / Suggested implements

FloatingAction的图标 “+” 改成 页码数。

（假设当前第3页，共计10页）

显示成：

```
3
```

或者

```
3
  /
   10
```

### EhViewer 版本号 / EhViewer version code

1.8.3.0-beta02

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/download/1.8.3.0-beta02/EhViewer-arm64-v8a-A12+.apk

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by txyyh** [comment]
已无页码概念

**Comment by asuka-mio** [comment]
See #355

**Comment by BlackC0** [comment]
网页的e绅士仍然可以跳页数 只是没有页码出来了 所以e绅士的跳页数是怎么实现的？

**Comment by txyyh** [comment]
时间

**Comment by BlackC0** [comment]
我的意思是 他有时间和跳页数两种跳转

**Comment by BlackC0** [comment]
可能我理解错了 就此打住
