### ISSUE TITLE
快速搜索 希望能保存当前页面

### ISSUE THREAD

**Issue by dyguests** [Ehviewer-Overhauled/Ehviewer#436]
### 需求 / Requirement

将画廊列表保存为快捷搜索时，希望能保存当前页码。
在浏览基于快捷搜索生成的画廊列表时，画廊列表翻页时，希望能更新当前页码。

### 建议实现 / Suggested implements

将画廊列表保存为快捷搜索时，希望能保存当前页码。
在浏览基于快捷搜索生成的画廊列表时，画廊列表翻页时，希望能更新当前页码。

### EhViewer 版本号 / EhViewer version code

1.8.3.0-beta02

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/download/1.8.3.0-beta02/EhViewer-arm64-v8a-A12+.apk

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by txyyh** [comment]
已无页码概念

**Comment by txyyh** [comment]
如果您指的是仅仅保存当前页面，这个可以实现，麻烦改下用词

如果与页码本身有关，那抱歉无法实现

**Comment by dyguests** [comment]
嗯，现在似乎变成**日期**了？

大致愿望还是希望下次能继续基于之前的进度（日期）继续浏览。
