### ISSUE TITLE
画廊最后几张缩略图显示错误

### ISSUE THREAD

**Issue by LzNOHentai** [Ehviewer-Overhauled/Ehviewer#440]
### 复现步骤 / Step to reproduce

1.随意打开一个画廊;
2.最后几张缩略图显示错误。

### 预期行为 / Expected behaviour

应正确显示对应图片的缩略图。

### 实际行为 / Actual Behaviour

画廊最后几张缩略图显示错误，常表现为重复某一张。
![Screenshot_2022-11-21-18-14-29-947-edit_moe tarsin ehviewer](https://user-images.githubusercontent.com/22359967/203025799-c39c78c8-b5b2-4d32-97d2-1434b683858c.jpg)

### EhViewer 版本号 / EhViewer version code

1.8.30

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.8.3.0

### Android 系统版本 / Android version

MIUI 13, Android 12

### 设备型号 / Device model

Xiaomi 10 Ultra

### SoC 型号 / Soc model

骁龙865

### 应用日志 / App logs

[log-2022-11-21-18-23-31-970.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10055577/log-2022-11-21-18-23-31-970.zip)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
了解了

**Comment by asuka-mio** [comment]
@txyyh hotfix下吧
