### ISSUE TITLE
主页一直在转圈加载

### ISSUE THREAD

**Issue by RX93CN** [Ehviewer-Overhauled/Ehviewer#442]
### 复现步骤 / Step to reproduce

1.打开EhViewer
2.主页显示加载中

### 预期行为 / Expected behaviour

正常情况应该加载出当天的漫画，实际情况是一直处于加载中，收藏、热门、排行和历史均无法显示

### 实际行为 / Actual Behaviour

一直处于加载中
![Screenshot_2022-11-21-22-37-11-369_moe tarsin ehviewer](https://user-images.githubusercontent.com/110704357/203197302-eab41b63-2510-462e-b629-9faf5633b84c.jpg)

### 备注 / Addition details

另外的绿色EhViewer和老版白色EhViewer仍可加载，现版本需要加速器才能连上，且不稳定，裸连时网速为0

### EhViewer 版本号 / EhViewer version code

1.8.3.1

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/download/1.8.3.1/EhViewer-arm64-v8a-A12+.apk

### Android 系统版本 / Android version

MIUI12.5

### 设备型号 / Device model

Xiaomi 12

### SoC 型号 / Soc model

骁龙8+ Gen1

### 应用日志 / App logs

[log-2022-11-22-09-54-50-804.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10062388/log-2022-11-22-09-54-50-804.zip)

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
由于您勾选了第一个选项，现为您 assgin
Feel free to unassigned it

**Comment by txyyh** [comment]
另，由于不同地方网络环境千变万化，抱歉我们无法对直连功能做广泛支持

**Comment by tehcneko** [comment]
可以在自定义 Hosts 里添加
e-hentai.org 172.67.0.127

另外的两个 IP 104.20.135.21 和 104.20.134.21 似乎被墙了

**Comment by RX93CN** [comment]
请问最新的e站ip在那里可以获得，我试了很多都不行

**Comment by tehcneko** [comment]
> 请问最新的e站ip在那里可以获得，我试了很多都不行

它们 IP 基本上是固定的，不会变

**Comment by RX93CN** [comment]
那么现在还有几个ip可用?

**Comment by tehcneko** [comment]
> 那么现在还有几个ip可用?

我这里测试的只有 172.67.0.127

里站没问题

**Comment by RX93CN** [comment]
要重新申请账号了，原账号只能登录表站，里站的注册有什么注意事项吗？

**Comment by asuka-mio** [comment]
最新的ci应该修复了

**Comment by RX93CN** [comment]
@asuka-mio 下一版本是添加了新的ip来解决这个问题吗？

**Comment by Longway22** [comment]
@RX93CN 应该只是把不可用的IP删除了而已。
