### ISSUE TITLE
Collapsing Toolbar在内容未超出一屏时也可以滑动

### ISSUE THREAD

**Issue by FooIbar** [Ehviewer-Overhauled/Ehviewer#444]
### 复现步骤 / Step to reproduce

在历史/下载/设置页上滑

### 预期行为 / Expected behaviour

不能滑动

### 实际行为 / Actual Behaviour

可以滑动
![Screenshot_20221122-185745_EhViewer](https://user-images.githubusercontent.com/118464521/203297223-e06ebe1b-5e8a-452c-9151-910222592be8.png)
![Screenshot_20221122-185750_EhViewer](https://user-images.githubusercontent.com/118464521/203297286-65198eba-a411-4cf5-8dd4-d009ec683ee6.png)

### EhViewer 版本号 / EhViewer version code

1.8.3.2

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3521573868

### Android 系统版本 / Android version

Android 11

### 设备型号 / Device model

/

### SoC 型号 / Soc model

/

### 应用日志 / App logs

/

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
预期行为， 参见gapps里的短信app

**Comment by asuka-mio** [comment]
> 那右下角按钮显示不全应该不是预期行为吧

草 我以为你截图没截全 一会修
