### ISSUE TITLE
你好，安卓12翻译标签的功能好像失效了！

### ISSUE THREAD

**Issue by Guessop** [Ehviewer-Overhauled/Ehviewer#446]
### 需求 / Requirement

好像是因为安卓12有一个连接验证，如果在支持的连接里面没有该网址，是无法向其发送请求的。这只是猜测，我尝试了从客户端点击连接调用浏览器是无法访问任何不在支持的连接里面的网址的

### 建议实现 / Suggested implements

没有安装过客户端的手机，然后安装，翻译功能一直失效

### EhViewer 版本号 / EhViewer version code

1.8.3.0

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.8.3.0

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by txyyh** [comment]
@Guessop 与那个打开链接无关
那个与网络没有任何关系

单纯你网不好罢了

**Comment by Guessop** [comment]
你好 谢谢
嗯 是的
之前搞程序改了hosts   后来忘记还原了 
但是挺神奇的 每次我手动访问github都能访问 点程序就跳不过来  我是尝试了接近1个多小时才过来问的 
不好意思 打扰休息了
