### ISSUE TITLE
快速搜索记录GID信息/增加书签功能

### ISSUE THREAD

**Issue by FooIbar** [Ehviewer-Overhauled/Ehviewer#447]
### 需求 / Requirement

保存当前页面的搜索参数

### 建议实现 / Suggested implements

1. 在快速搜索中加入prev/next/jump/seek信息（可选是否保存）
2. 保持现有快速搜索不变，新增搜索书签功能

### 备注 / Addition details

以前页码会变存书签没用，现在能保证定位到相同的页面了
但是方案一要动数据库，会破坏和其他分支的兼容性
方案二和快速搜索功能重合度高，而且放哪里是个问题
我没想好怎么搞比较好，先开个issue
或者只记录退出前最后一次搜索的参数？

### EhViewer 版本号 / EhViewer version code

1.8.3.2

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3525084279

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by xb2016** [comment]
根据现有更改，我再提一些建议

1. 保存快速搜索时应提供选项，是否同时保存位置信息，因为很多时候并不需要保存
2. 当前搜索词已在快速搜索列表中时，点击保存按钮，可以提供以下选项：
    1. 删除当前搜索词 (xiaojieonly/Ehviewer_CN_SXJ/issues/452)
    2. 更新位置信息

**Comment by FooIbar** [comment]
> 根据现有更改，我再提一些建议
> 
> 1. 保存快速搜索时应提供选项，是否同时保存位置信息，因为很多时候并不需要保存
> 2. 当前搜索词已在快速搜索列表中时，点击保存按钮，可以提供以下选项：
>    
>    1. 删除当前搜索词 ([[功能建议] 书签栏 可否加个小功能 删除当前搜索书签 xiaojieonly/Ehviewer_CN_SXJ#452](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/452))
>    2. 更新位置信息

1. 这个我感觉可以做成一个记住上次的选择的checkbox
2. 如果有人想同一个搜索条件存多个不同进度的快速搜索呢

**Comment by xb2016** [comment]
> 2. 如果有人想同一个搜索条件存多个不同进度的快速搜索呢

~~那就再加一个选项~~

**Comment by FooIbar** [comment]
> > 2. 如果有人想同一个搜索条件存多个不同进度的快速搜索呢
> 
> ~那就再加一个选项~

如果一个搜索条件对应多个进度的话要更新更新哪个

**Comment by xb2016** [comment]
> 如果一个搜索条件对应多个进度的话要更新更新哪个

好问题，不如有多个进度的直接隐藏更新选项，自己管理
