### ISSUE TITLE
纯黑深色主题开关无效

### ISSUE THREAD

**Issue by Longway22** [Ehviewer-Overhauled/Ehviewer#449]
### 复现步骤 / Step to reproduce

1. 打开EhViewer
2. 在设置-EH关闭纯黑深色主题
3. 开启深色主题（用“总是开启”和“跟随系统”开启都行）

### 预期行为 / Expected behaviour

界面应当显示为灰色。

### 实际行为 / Actual Behaviour

界面仍然为纯黑色。

### EhViewer 版本号 / EhViewer version code

1.8.3.2

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3525084279

### Android 系统版本 / Android version

LineageOS 19 / Android 12

### 设备型号 / Device model

Google Pixel 3

### SoC 型号 / Soc model

高通骁龙845

### 应用日志 / App logs

[logcat-2022-11-24-01-31-29-179.txt](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10077892/logcat-2022-11-24-01-31-29-179.txt)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by duzhaokun123** [comment]
是否使用 Repainter 之类的工具启用了"纯黑背景"

这会导致所有使用 monet 取色的应用背景为纯黑的

**Comment by Longway22** [comment]
@duzhaokun123 没有哦。我确认是EhViewer的问题，我还用[隔壁xb2016的版本](https://github.com/EhViewer-NekoInverter/EhViewer)测试了，其可以切换 纯黑/灰色 深色主题。

**Comment by duzhaokun123** [comment]
那设置界面切换有没有立即生效

切换需要重构 activity 才会生效 主页可能没及时重构

**Comment by Longway22** [comment]
@duzhaokun123 xb2016 的是按了开关就会立即生效的。这个版本无论退出还是“强行停止”重新进入都没有变为灰色。

**Comment by Longway22** [comment]
经测试，灰色深色模式失效首次在 [1.7.26.7](https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.7.26.7)( https://github.com/Ehviewer-Overhauled/Ehviewer/commit/4278bf46314ba5a9e19d2089e4d27b8c68d15d10 )出现。
[1.7.26.6](https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.7.26.6) ( https://github.com/Ehviewer-Overhauled/Ehviewer/commit/bc38c8c135a3119adcfff1a911e55ac9fd6c28f6 )没有这个问题。

**Comment by txyyh** [comment]
我们无法复现
请更换设备尝试是否有效

**Comment by asuka-mio** [comment]
没什么头绪
不过你的上los19(Android 12),而不是19.1(Android 12.1),monet引擎是12.1才被开源到aosp的，所以之前有kdrag0n(Danny Lin)自己搓的引擎，不知道los拿没拿，我估计以他们习性应该不会拿
所以你的ROM应该目前处于没动态取色的特性
你指出的那两个版本我正好直接把主题换到了mdc提供的动态取色主题

**Comment by asuka-mio** [comment]
原则上还是 因为我们没法复现所以也不好修
您如果有基础的话自己调试下吧，毕竟设备也不在我们这

**Comment by Longway22** [comment]
抱歉少提供了一些信息。
经测试，灰色深色模式失效只会出现在系统为深色主题时，系统深色主题关闭时就能正常切换到灰色了。

@asuka-mio 

> 不过你的是los19(Android 12),而不是19.1(Android 12.1)

我的系统是 LineageOS 19.1 的。
![IMG_20221124_110105](https://user-images.githubusercontent.com/103419306/203684590-d68eac26-15a6-42f1-8d7e-e44dbe1dcae8.jpg)

**Comment by txyyh** [comment]
依然无法复现
我这边无论系统处于什么模式，纯黑深色都有效
