### ISSUE TITLE
点标签进去的搜索页面无法正常跳页

### ISSUE THREAD

**Issue by bakabaka2333** [Ehviewer-Overhauled/Ehviewer#450]
### 复现步骤 / Step to reproduce

1.例如单行本 点标签进去的是other:tankoubon  没法跳页到2020
2.但是手动搜索o:tankoubon 倒是能正常跳页
3.其他标签点进去的搜索页面跳页也基本都是失效的

### 预期行为 / Expected behaviour

正常情况下应该是能跳页

### 实际行为 / Actual Behaviour

目前情况下只是进入最新搜索的下一页

### EhViewer 版本号 / EhViewer version code

1.8.3.2

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3525084279

### Android 系统版本 / Android version

安卓9

### 设备型号 / Device model

酷比魔方 X Neo

### SoC 型号 / Soc model

660

### 应用日志 / App logs

[logcat-2022-11-24-10-26-06-587.txt](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10080188/logcat-2022-11-24-10-26-06-587.txt)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
无法复现，我这里可以跳页

**Comment by xb2016** [comment]
> 无法复现，我这里可以跳页
> 
> 你是表站还是里站

~~我都修了你跟我说可以跳~~
