### ISSUE TITLE
你好，请问是否能在应用主页内点击1次返回键就退出应用的设计调整为2次？

### ISSUE THREAD

**Issue by jc667mc2** [Ehviewer-Overhauled/Ehviewer#462]
### 需求 / Requirement

  你好，首先请允许我向你们的付出表达感谢！
  我在使用Ehviewer-Overhauled过程中发现:在收藏，快速搜索，设置等界面时，如果想要点击安卓屏幕内三键式导航中的“返回上一级界面”进行切换到主页时，容易因为误触，多点了一次返回键，导致app直接退出关闭。又或是在主页浏览时，误触返回键，导致直接退出应用。
  请问是否能在未来的版本中针对这一问题进行改进？

### 建议实现 / Suggested implements

建议参考Hippo原版Ehv设计，加一个“双动扳机保险”式的设计，在主页点到3键导航的“返回上一级界面”时，不会直接立即退出app，而是会弹出一个不需要手动点击确认的提示，显示“再按一次退出”，来避免在浏览过程中因为误触导致的退出应用的问题，谢谢！
![Screenshot_20221127_003403_com hippo ehviewer_edit_37444302761473](https://user-images.githubusercontent.com/118359407/204100041-19fab51f-9cb2-490d-90d9-c70acda3affb.jpg)

### EhViewer 版本号 / EhViewer version code

1.8.3.2

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.8.3.2

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by asuka-mio** [comment]
我们是完全遵守谷歌规范的app，不会考虑做这些“国内流行”的习惯设计
