### ISSUE TITLE
优化搜索/订阅/收藏页的跳转UI

### ISSUE THREAD

**Issue by FooIbar** [Ehviewer-Overhauled/Ehviewer#466]
### 需求 / Requirement

优化页面跳转UI
快速跳转至结果的最后

### 建议实现 / Suggested implements

- 快速搜索按钮没有什么必要，明明都有左滑打开了
- 刷新按钮现在的行为实际上相当于网页上的first而不是刷新当前页面 ，建议图标改称类似![216362-200](https://user-images.githubusercontent.com/118464521/204144270-b8ea4b12-f5bc-4cc0-b0ee-d9d47f6589c5.png)这种的避免误解
- 增加一个按钮实现网页上的last

### EhViewer 版本号 / EhViewer version code

1.8.3.2

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3552797628

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by xb2016** [comment]
说下我的看法
1. 确实功能重复，但感觉是故意的，为了凑三个 fab
2. 没有必要，换成回到顶部这种图标反而更容易误解
3. 这个主要是针对不知道最后一页日期的情况，比如说收藏页面，日期选太早会直接白屏
    我的想法是把 2007-03 整个月的日期都替换为直接跳转 `?prev=1`

**Comment by indefined** [comment]
https://forums.e-hentai.org/index.php?showtopic=261844
个人感觉可以做成类似这个脚本的UI，加一个滑条直接拉到大概GID跳页，当然再加一个文本框接受直接输入GID跳页最好。
以及如果实现GID跳页的话在画廊详情页可以增加一个类似“查看前后”的转跳按钮，这样收藏画廊就可以粗略用作书签了

**Comment by tehcneko** [comment]
1是因为当时有人反馈三星的曲面屏手机上没法滑出右抽屉

**Comment by asuka-mio** [comment]
> 1是因为当时有人反馈三星的曲面屏手机上没法滑出右抽屉

草 还有这bug呢

**Comment by duzhaokun123** [comment]
> 1是因为当时有人反馈三星的曲面屏手机上没法滑出右抽屉

当然屏幕也很难滑就是了

**Comment by FooIbar** [comment]
能滑出左边的滑不出右边的？
也不用从屏幕边缘开始滑啊

**Comment by tehcneko** [comment]
> 能滑出左边的滑不出右边的？ 也不用从屏幕边缘开始滑啊

我也没三星手机不知道，但是不只是一个人反馈这个问题
