### ISSUE TITLE
进入一本新的漫画会在页面卡顿

### ISSUE THREAD

**Issue by TY12354** [Ehviewer-Overhauled/Ehviewer#468]
### 复现步骤 / Step to reproduce

1.打开软件，打开任意一本漫画会立即进入漫画详情页面，
2.导入下载列表，下载位置更改到存放漫画的文件夹后，点击任意一本没看过的漫画，会有一个卡顿 
3.退出漫画页面再次点击这本漫画后会立即进入，卡顿消失

### 预期行为 / Expected behaviour

不管是不是没点击过的漫画都不会有卡顿

### 实际行为 / Actual Behaviour

第一次点击的漫画都会有卡顿

### EhViewer 版本号 / EhViewer version code

1.8.3.2

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases

### Android 系统版本 / Android version

miui13.0.10.0

### 设备型号 / Device model

红米k50u

### SoC 型号 / Soc model

骁龙8+

### 应用日志 / App logs

[log-2022-11-28-23-03-19-099.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10104896/log-2022-11-28-23-03-19-099.zip)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by duzhaokun123** [comment]
如果你有大量下载内容并且通过 saf 访问的下载那这是已知问题
#381

**Comment by TY12354** [comment]
> 



> 如果你有大量下载内容并且通过 saf 访问的下载那这是已知问题 #381

都是老版本的下载的漫画
