### ISSUE TITLE
删除和重命名右侧快速搜索栏里保存的标签

### ISSUE THREAD

**Issue by 123LaoShiRen** [Ehviewer-Overhauled/Ehviewer#472]
### 需求 / Requirement

我需要一个删除或重命名右侧快速搜索栏里保存的标签的功能

### 建议实现 / Suggested implements

长按右侧快速搜索栏内某一标签，会出现重命名和删除这两个选项，或者在快速搜索栏右上角再加一个管理标签的选项

### EhViewer 版本号 / EhViewer version code

1.8.3.2

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by txyyh** [comment]
@123LaoShiRen 滑动删除

**Comment by 123LaoShiRen** [comment]
谢谢，我是傻逼
