### ISSUE TITLE
当快速连续翻页时，使屏幕不闪烁，并完整地显示所有图像

### ISSUE THREAD

**Issue by tglsf** [Ehviewer-Overhauled/Ehviewer#473]
### 需求 / Requirement

当观看大量的图像和CG集时，会使用长按音量键快速连续翻页，以定位某个位置或跳过某个部分。当翻页速度过快时，一些图像会被跳过而不显示在屏幕上。
希望可以当快速连续翻页（已下载的画廊）时，使屏幕不闪烁，并完整地显示所有图像。

### 建议实现 / Suggested implements

1. 等到图像完全加载完毕后再翻页，否则将连续显示前一个图像。
2. （已下载的画廊）增加一个可调选项，限制快速连续翻页的速度。如：使图像显示至少（100ms、300ms、500ms）。

### EhViewer 版本号 / EhViewer version code

1.8.3.2

### EhViewer CI 版本 / EhViewer CI Version

（已修改）
https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3569882991

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [x] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by txyyh** [comment]
@tglsf ci版本错误

**Comment by xb2016** [comment]
不赞成此更改
这只会导致毫无意义的配额浪费
应当使用画廊预览功能进行定位
