### ISSUE TITLE
在安卓12中的闪退问题

### ISSUE THREAD

**Issue by Kagura-Nanaa** [Ehviewer-Overhauled/Ehviewer#476]
### 复现步骤 / Step to reproduce

阅读方向为从上至下
进入图库阅读一到两分钟左右会闪退

### 预期行为 / Expected behaviour

正常浏览

### 实际行为 / Actual Behaviour

闪退到桌面或闪退到图库详情页

### EhViewer 版本号 / EhViewer version code

1.8.3.2

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.8.3.2

### Android 系统版本 / Android version

miui13,安卓12

### 设备型号 / Device model

小米9

### SoC 型号 / Soc model

855

### 应用日志 / App logs

[log-2022-12-01-07-55-39-066.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10128383/log-2022-12-01-07-55-39-066.zip)
闪退发生在7点55分

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
草 米酒什么时候有A12用了

**Comment by Kagura-Nanaa** [comment]
> 草 米酒什么时候有A12用了

很多机型都有官改能上更高版本哇
