### ISSUE TITLE
画廊预览缩略图炸了

### ISSUE THREAD

**Issue by LzNOHentai** [Ehviewer-Overhauled/Ehviewer#483]
### 复现步骤 / Step to reproduce

打开任意画廊

### 预期行为 / Expected behaviour

应正常显示画廊预览缩略图

### 实际行为 / Actual Behaviour

![Screenshot_2022-12-02-14-08-28-227-edit_moe tarsin ehviewer](https://user-images.githubusercontent.com/22359967/205226933-1f613d04-b2a3-470d-b1cf-8501d87b6681.jpg)
![Screenshot_2022-12-02-14-08-44-321-edit_moe tarsin ehviewer~01](https://user-images.githubusercontent.com/22359967/205226948-d48f38df-4ea7-4735-bebc-58f3b677a20f.jpg)

### EhViewer 版本号 / EhViewer version code

1.8.3.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/asuka-mio/Ehviewer/actions/runs/2650399893

### Android 系统版本 / Android version

MIUI 13, Android 12

### 设备型号 / Device model

Xiaomi 10 Ultra

### SoC 型号 / Soc model

骁龙865

### 应用日志 / App logs

[log-2022-12-02-14-14-03-065.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10138558/log-2022-12-02-14-14-03-065.zip)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
![Screenshot_20221202-142019~2](https://user-images.githubusercontent.com/43900799/205228490-751093c4-8514-4da7-92c6-222933937f79.png)
调下这个看看
