### ISSUE TITLE
gif播放时撕裂

### ISSUE THREAD

**Issue by SaigyoujiYusora** [Ehviewer-Overhauled/Ehviewer#485]
### 复现步骤 / Step to reproduce

1.打开一个包含gif 动图的画廊，例如g/2391021/31fc2b5fae/
2.任意点开一张gif

### 预期行为 / Expected behaviour

不应该观察到图像撕裂

### 实际行为 / Actual Behaviour

不仅播放卡顿，甚至连滑动切换图片的动画都会一起卡

### 备注 / Addition details

已测试手机图片查看器，播放时不会出现撕裂

### EhViewer 版本号 / EhViewer version code

1.8.3.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3600531027

### Android 系统版本 / Android version

ONE UI 4.1 Android12

### 设备型号 / Device model

Samsung Note 20 Ultra

### SoC 型号 / Soc model

骁龙865+

### 应用日志 / App logs

[log-2022-12-03-01-56-51-268.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10143316/log-2022-12-03-01-56-51-268.zip)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
我们与代码fork来源已经有着相当大的差异（尤其图像解析）
列举白版的现象可以说毫无意义

**Comment by SaigyoujiYusora** [comment]
> 我们与代码fork来源已经有着相当大的差异（尤其图像解析） 列举白版的现象可以说毫无意义

主要想表达的是手机应该是有能力流畅的播放gif 的（
