### ISSUE TITLE
想登入账号，一直卡bug

### ISSUE THREAD

**Issue by weyeee** [Ehviewer-Overhauled/Ehviewer#486]
### 复现步骤 / Step to reproduce

打开eh-设置-EH-账户-退出登录-关闭eh应用-打开eh-显示登录界面一瞬间回到eh主页
由此无限循环bug

### 预期行为 / Expected behaviour

打开eh-设置-EH-账户-退出登录-关闭eh应用-打开eh-显示登录界面-登入账号-完

### 实际行为 / Actual Behaviour

如复现步骤

### EhViewer 版本号 / EhViewer version code

1.8.3.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.8.3.3

### Android 系统版本 / Android version

安卓12  PixelPlusUI 4.8

### 设备型号 / Device model

Redmi K40

### SoC 型号 / Soc model

骁龙870

### 应用日志 / App logs

--------- beginning of main
12-04 00:38:58.312 10153 10153 I AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
12-04 00:38:58.770 10153 10175 D OpenGLRenderer: endAllActiveAnimators on 0xb40000772c581c00 (NavigationMenuItemView) with handle 0xb4000078679da7e0
12-04 00:39:03.211 10153 10153 W ListPreference: Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
12-04 00:39:03.213 10153 10153 W ListPreference: Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
12-04 00:39:05.036 10153 10175 D OpenGLRenderer: endAllActiveAnimators on 0xb40000771ee23f00 (RippleDrawable) with handle 0xb40000772c44c120
12-04 00:39:07.895 10153 10153 D CompatibilityChangeReporter: Compat change id reported: 78294732; UID 10441; state: ENABLED

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
关闭你的广告跳过软件

**Comment by txyyh** [comment]
从ci 版本错误

**Comment by weyeee** [comment]
OK，关闭了跳过开屏软件即可

**Comment by txyyh** [comment]
你确定是1.8.3.3吗
是哪个词语被识别为广告

**Comment by weyeee** [comment]
> 你确定是1.8.3.3吗 是哪个词语被识别为广告

确定，刚下的

**Comment by duzhaokun123** [comment]
很有可能是 跳过登录 的 跳过

**Comment by txyyh** [comment]
@duzhaokun123 那个词改成了游客模式

**Comment by duzhaokun123** [comment]
🤔 那太离谱了 不会游客模式就是关键字吧

**Comment by duzhaokun123** [comment]
具体是什么跳过工具

**Comment by duzhaokun123** [comment]
@txyyh 

经测试 对于李跳跳(派大星2.01) 会识别 id 带有 skip 的 view 点击
