### ISSUE TITLE
退出登陆后重启app无法登陆

### ISSUE THREAD

**Issue by zhwe83** [Ehviewer-Overhauled/Ehviewer#488]
### 复现步骤 / Step to reproduce

1.在设置eh里退出登录帐号
2.关闭应用
3.再次打开应用后发现登陆页面会一闪而过直接进入eh主界面

### 预期行为 / Expected behaviour

应该和刚安装应用一样进行登陆流程

### 实际行为 / Actual Behaviour

实际上直接跳过了登录界面进入主界面

### EhViewer 版本号 / EhViewer version code

1.8.3.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases

### Android 系统版本 / Android version

miui13.0.4

### 设备型号 / Device model

Xiaomi 12s urtal

### SoC 型号 / Soc model

骁龙 8+gen 1

### 应用日志 / App logs

无

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
重复 #486
