### ISSUE TITLE
WebDav 支持

### ISSUE THREAD

**Issue by Eroge-Newton** [Ehviewer-Overhauled/Ehviewer#491]
### 需求 / Requirement

建议添加 WebDav 支持
随着E站版权炮越来越多，很多本子只有下载下来看才放心，但时间一长，存储压力也越来越大，所以 **建议添加 WebDav 支持**

### 建议实现 / Suggested implements

虽然 Fork 了一份，但这两个月实在没空，没有时间贡献代码，所以来提 issue 了（AS真心不好用）
具体实现上，没有什么建议的
不过可以参考一下 FEhViewer
https://github.com/honjow/FEhViewer
（作者是用 Dart 写的）

### EhViewer 版本号 / EhViewer version code

1.8.3.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/run

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by txyyh** [comment]
本应用不对本地阅读做深度适配
建议寻找其他替代方案

**Comment by asuka-mio** [comment]
不会考虑集成 但是你应该可以将下载目录指向一个webdavfs
