### ISSUE TITLE
历史记录页面中的收藏判断无效

### ISSUE THREAD

**Issue by xb2016** [Ehviewer-Overhauled/Ehviewer#509]
### 复现步骤 / Step to reproduce

1. 从收藏页面阅读一个画廊
2. 转到历史记录页面，长按该画廊

### 预期行为 / Expected behaviour

菜单应该显示 取消收藏

### 实际行为 / Actual Behaviour

显示为 收藏

### 备注 / Addition details

HistoryInfo 数据库中并没有保存收藏状态，从 HistoryInfo 转换而来的 gi.favoriteSlot 无意义
长按菜单后可以先查询本地收藏，再在线获取 GalleryInfo 获取收藏状态

### EhViewer 版本号 / EhViewer version code

1.8.4.0-alpha02

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3656758515

### Android 系统版本 / Android version

MIUI 13

### 设备型号 / Device model

K40P

### SoC 型号 / Soc model

888

### 应用日志 / App logs

NA

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
请标注具体版本号
不接受lastest这种含糊其辞的写法

**Comment by FooIbar** [comment]
在线获取的问题是，没有比较廉价的方式获取收藏信息，E站API返回的信息不包括收藏
要么执行一次GID搜索，要么请求整个画廊页面，而且每次都要重新获取

最简单的解决方案无疑是加个字段
而从最大限度保留兼容性的角度考虑，HistoryInfo那张表里的MODE字段根本没用到，可以用来存favoriteSlot #517

**Comment by asuka-mio** [comment]
> 在线获取的问题是，没有比较廉价的方式获取收藏信息，E站API返回的信息不包括收藏 要么执行一次GID搜索，要么请求整个画廊页面，而且每次都要重新获取
> 
> 最简单的解决方案无疑是加个字段 而从最大限度保留兼容性的角度考虑，HistoryInfo那张表里的MODE字段根本没用到，可以用来存favoriteSlot #517

可以的👍
