### ISSUE TITLE
图片下载失败后点击“重试”会让应用崩溃

### ISSUE THREAD

**Issue by Longway22** [Ehviewer-Overhauled/Ehviewer#525]
### 复现步骤 / Step to reproduce

1. 随便找个画廊，进入看图。
2. 在图片还在加载时断开网络连接，这时有的图片应该会出现“无法加载该图片”
3. 点“重试”

### 预期行为 / Expected behaviour

重新下载图片。

### 实际行为 / Actual Behaviour

应用崩溃，界面回到画廊介绍页面。

### EhViewer 版本号 / EhViewer version code

1.8.5.0-preview

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3686399324

### Android 系统版本 / Android version

LineageOS 19.1 / Android 12

### 设备型号 / Device model

Google Pixel 3

### SoC 型号 / Soc model

高通骁龙845

### 应用日志 / App logs

以下是日志文件导出后其中一个以 crash 开头的文件内容。

```
TIME=2022-12-13-22-47-37-467

======== PackageInfo ========
PackageName=moe.tarsin.ehviewer
VersionName=1.8.5.0-preview
VersionCode=180027
Signature=A0:26:97:6F:97:A4:78:BB:1E:83:EE:43:C4:31:E8:AF:C6:88:36:A1

======== Runtime ========
TopActivity=eu.kanade.tachiyomi.ui.reader.ReaderActivity
TopScene=null

======== DeviceInfo ========
BOARD=blueline
BOOTLOADER=b1c1-0.4-7617406
SUPPORTED_ABIS=[arm64-v8a, armeabi-v7a, armeabi]
DEVICE=blueline
DISPLAY=lineage_blueline-userdebug 12 SQ3A.220705.004 eng.root.20221202.144008 dev-keys
FINGERPRINT=google/blueline/blueline:12/SP1A.210812.016.C2/8618562:user/release-keys
HARDWARE=blueline
HOST=c9999c8a8215
ID=SQ3A.220705.004
MANUFACTURER=Google
MODEL=Pixel 3
PRODUCT=blueline
RADIO=g845-00194-210812-B-7635520
TAGS=dev-keys
TYPE=userdebug
USER=root
CODENAME=REL
INCREMENTAL=eng.root.20221202.144008
RELEASE=12
SDK=32
MEMORY=13.6 MiB
MEMORY_NATIVE=37.5 MiB
MEMORY_MAX=512.0 MiB
MEMORY_TOTAL=3.5 GiB

======== CrashInfo ========
C4: An operation is not implemented.
	at eE.onClick(Unknown Source:11)
	at android.view.View.performClick(View.java:7455)
	at com.google.android.material.button.MaterialButton.performClick(Unknown Source:9)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28810)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by Longway22** [comment]
@asuka-mio 现在是不会崩溃了，但是点击“重试”后EhViewer看起来什么都没有做，也不会重新加载图片。

**Comment by asuka-mio** [comment]
> @asuka-mio 现在是不会崩溃了，但是点击“重试”后EhViewer看起来什么都没有做，也不会重新加载图片。

会尝试重新加载啊

**Comment by Longway22** [comment]
不不不，没有任何反应。

**Comment by asuka-mio** [comment]
> 不不不，没有任何反应。

我这现在是点完以后重新转圈，然后图片一会就出来了

**Comment by Longway22** [comment]
emm...也不知道怎么复现的，总之安装CI的最新版之后没有再看到这个问题。
