### ISSUE TITLE
Tag autocompletion in search bar

### ISSUE THREAD

**Issue by soredake** [Ehviewer-Overhauled/Ehviewer#528]
### 需求 / Requirement

It will be nice if search bar can have tag auto-completion.

### 建议实现 / Suggested implements

Adding tag auto-completion in search bar.

### 备注 / Addition details

https://e-hentai.org/mytags this page for example tag auto-completion, and there is script (not working now) that provided tag auto-completion to e-hentai site search box https://forums.e-hentai.org/index.php?showtopic=242709

### EhViewer 版本号 / EhViewer version code

1.8.5.0-preview

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3693448003

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by txyyh** [comment]
"CI Version" is wrong ,please fill in the correct information.

**Comment by FooIbar** [comment]
It seems not too hard to support it in English, I'll look into it
