### ISSUE TITLE
能否在移除下载标签页的时候添加一个确认的弹窗以防误删？

### ISSUE THREAD

**Issue by 1670081661** [Ehviewer-Overhauled/Ehviewer#529]
### 需求 / Requirement

我需要在移除下载标签的时候添加一个确认是否删除标签的询问弹窗。目前版本删除下载标签的方式太过容易（导致也容易手滑）。因此如果不打算变更删除标签的方式的话，能否添加一个确认的弹窗以防误删？

### 建议实现 / Suggested implements

建议在左滑移除标签页后先弹出确认移除的弹窗。选择是则删除标签，选择否则保留标签。
当然，这是基于移除标签过于容易导致也容易手滑的前提。如果作者能找到更好的防止误删标签的解决方法那更不错（如直接更改移除标签的方式）

### EhViewer 版本号 / EhViewer version code

1.8.5.0 preview

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.8.5.0-preview

### 自查步骤 / Verify steps

- [] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by 1670081661** [comment]
在？没人给个回复吗？

**Comment by asuka-mio** [comment]
改成长按弹个对话框删除吧

**Comment by asuka-mio** [comment]
不过目前这个右侧抽屉UI的UI 很烂 以后都需要被重新设计成material3风格的

**Comment by txyyh** [comment]
> 在？没人给个回复吗？

考虑到各种因素，我们并不会对全部issue给予回复，谢谢配合

**Comment by txyyh** [comment]
由于您勾选了第一个选项，现为您assgin
feel free to unassign it by yourself

**Comment by txyyh** [comment]
ci 版本错误，请填入正确 ci 版本

**Comment by 1670081661** [comment]
哦抱歉我好像是没看懂那个PR是啥意思就不小心选了第一项，我打算取消他。
