### ISSUE TITLE
从多图片画廊中间或靠后部分开始阅读加载极慢

### ISSUE THREAD

**Issue by LzNOHentai** [Ehviewer-Overhauled/Ehviewer#536]
### 复现步骤 / Step to reproduce

点开一个数百张图片的画廊，点击预览缩略图直接从中后段开始阅读，加载极慢。
已排除网络问题，从网速监测上看流量是正常的。加载速度似乎与图片数和在画廊中的位置成正比，越靠前图片越少加载越快。

不太确定这是BUG还是需要优化的问题，体感上慢过头了，在旧阅读器上印象里是很快的。
https://streamable.com/l9geho

### 预期行为 / Expected behaviour

应该迅速加载。

### 实际行为 / Actual Behaviour

图片多的话几乎无限加载。

### EhViewer 版本号 / EhViewer version code

1.8.5.0-preview

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3700877990

### Android 系统版本 / Android version

MIUI 13, Android 12

### 设备型号 / Device model

Xiaomi 10 Ultra

### SoC 型号 / Soc model

骁龙865

### 应用日志 / App logs

[log-2022-12-15-19-18-14-204.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10236446/log-2022-12-15-19-18-14-204.zip)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
无法复现 如果你之前是缓慢的拖动slider到后面的页面倒是会有这种问题 不过已经修复 直接点缩略图进去我倒是没有复现
提供一个详细的最小可复现环境吧 比如对新安装的app进行那些设置读取哪个画廊这种 录个屏

**Comment by asuka-mio** [comment]
你补全信息之后再开就行

**Comment by LzNOHentai** [comment]
> 无法复现 如果你之前是缓慢的拖动slider到后面的页面倒是会有这种问题 不过已经修复 直接点缩略图进去我倒是没有复现 提供一个详细的最小可复现环境吧 比如对新安装的app进行那些设置读取哪个画廊这种 录个屏

演示机型是小米13 Pro，MIUI 14，Android 13。不过在10u上也试了一下同样如此。
已更新最新CI#638版本。
虽然测试的是直接点进度条，不过点缩略图也是一样的问题。不清楚为什么仅仅只是改变阅读方向就会这样。
https://streamable.com/s2i96h
