### ISSUE TITLE
左下角和设置菜单中的阅读模式不同步

### ISSUE THREAD

**Issue by FooIbar** [Ehviewer-Overhauled/Ehviewer#539]
### 复现步骤 / Step to reproduce

在左下角或设置菜单中更改阅读模式

### 预期行为 / Expected behaviour

二者立即同步

### 实际行为 / Actual Behaviour

设置菜单中更改阅读模式会立即同步
左下角更改退出后才会同步

https://user-images.githubusercontent.com/118464521/208005228-8e727f34-b765-4c7b-8375-48c657f09433.mp4

### 备注 / Addition details

*tachiyomi-r5348有同样问题

### EhViewer 版本号 / EhViewer version code

1.8.5.0-preview

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3707445053/jobs/6283861157

### Android 系统版本 / Android version

PixelExperience 11

### 设备型号 / Device model

Moto Z2 Play

### SoC 型号 / Soc model

Snapdragon 626

### 应用日志 / App logs

/

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
上游问题还挺多的

**Comment by VVaraiotoko** [comment]
话说既然阅读界面的设置菜单就是全局设置了，为什么选项上面还有个“本作品”的标题呢？其实我觉得要搬Tachiyomi就照搬好了，保留外面的全局设置，阅读界面里有单个作品的个性化设置。

**Comment by asuka-mio** [comment]
> 话说既然阅读界面的设置菜单就是全局设置了，为什么选项上面还有个“本作品”的标题呢？其实我觉得要搬Tachiyomi就照搬好了，保留外面的全局设置，阅读界面里有单个作品的个性化设置。

忘删了
我觉得这种不分章节的本子是没必要一个作品一个设置的

**Comment by txyyh** [comment]
> 话说既然阅读界面的设置菜单就是全局设置了，为什么选项上面还有个“本作品”的标题呢？其实我觉得要搬Tachiyomi就照搬好了，保留外面的全局设置，阅读界面里有单个作品的个性化设置。

我觉得好看
