### ISSUE TITLE
希望能新增下载排序功能

### ISSUE THREAD

**Issue by Bzmhl** [Ehviewer-Overhauled/Ehviewer#54]
尊敬的作者您好，目前在ehviewer上，我下载的作品可能在后续被删除了，虽然我可以在本地浏览，但是我并不能改变它在下载列表中的位置，不能和续集放在一起，希望您能出一个手动排序功能，谢谢！

**Comment by txyyh** [comment]
请注意
不按照 issue template 创建的 issue，我们将不会受理
下不为例

**Comment by txyyh** [comment]
@asuka-mio 本功能是否已经实现
