### ISSUE TITLE
已下载的画廊被和谐后无法阅读

### ISSUE THREAD

**Issue by CCCCCCCCCC333** [Ehviewer-Overhauled/Ehviewer#547]
### 复现步骤 / Step to reproduce

1.下载画廊，确认正常可以从菜单栏里的已下载列表里打开阅读
2.该画廊因版权问题被和谐，打不开画廊详细页
3.此时从下载列表里点击该画廊封面以外的部分尝试阅读。

### 预期行为 / Expected behaviour

进入阅读界面，并且可以正常阅读

### 实际行为 / Actual Behaviour

本应弹出的阅读界面变为一片漆黑，下方不显示页数，点击屏幕也无法呼出菜单，滑动屏幕也不会翻页。只能后退至下载菜单
![Screenshot_20221218_151355](https://user-images.githubusercontent.com/64525123/208286122-4e8238d5-ac63-4bf2-90aa-f125dabc4675.jpg)

https://user-images.githubusercontent.com/64525123/208286386-e69d7e56-7b85-4d99-85a7-9a0c45e2d76c.mp4

### EhViewer 版本号 / EhViewer version code

1.8.5.0-preview

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3707445053/jobs/6283861157

### Android 系统版本 / Android version

originos3 安卓13

### 设备型号 / Device model

vivo×90pro+

### SoC 型号 / Soc model

骁龙8gen2

### 应用日志 / App logs

[log-2022-12-18-15-17-06-455.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10253342/log-2022-12-18-15-17-06-455.zip)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
你这下载状态不是失败吗

**Comment by CCCCCCCCCC333** [comment]
> 你这下载状态不是失败吗

无法阅读的问题从画廊被和谐之后就出现了，当时下载状态还是已完成，下载状态显示失败是因为我不信邪，在画廊被和谐之后又去点了一下下载按钮，就从已完成变成未完成了，下载的文件还在手机里可以看到。
![Screenshot_20221219_130550](https://user-images.githubusercontent.com/64525123/208351902-e31ea169-cae8-45bb-b02e-408e5118838f.jpg)

**Comment by txyyh** [comment]
发份导出的下载列表和已被删除画廊的本地下载文件

**Comment by CCCCCCCCCC333** [comment]
> 发份导出的下载列表和已被删除画廊的本地下载文件
> 
> 我们这一时没法复现

[压缩文件.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10323704/default.zip)
