### ISSUE TITLE
改进某些显示比例/dpi下的排版

### ISSUE THREAD

**Issue by LzNOHentai** [Ehviewer-Overhauled/Ehviewer#557]
### 复现步骤 / Step to reproduce

机型为小米13 Pro，6.73英寸屏幕，3200*1440分辨率。
稳定版MIUI 14.0.8，Android 13。
字体为默认，大小同样默认标准。
开发者选项——最小宽度为默认的393dp。
未改动ehviewer设置，均为默认。

下载页面评分被遮盖，其他页面长标题与作者有重叠。
不确定是否为系统问题，MIUI 14刚发布目前还不算稳定，暂未在其他常见APP发现类似问题。
![Screenshot_2022-12-20-09-33-54-191_moe tarsin ehviewer](https://user-images.githubusercontent.com/22359967/208561806-a3e41f2a-6df4-4e73-bde1-66f4f315229e.jpg)
![Screenshot_2022-12-20-09-34-50-679_moe tarsin ehviewer-edit](https://user-images.githubusercontent.com/22359967/208561824-3d1b332b-f7f4-4944-bad2-f173b61f28bf.jpg)

### 预期行为 / Expected behaviour

应该正常排版。

### 实际行为 / Actual Behaviour

元素有覆盖重叠现象。

### EhViewer 版本号 / EhViewer version code

1.8.5.0

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.8.5.0

### Android 系统版本 / Android version

MIUI 14, Android 13

### 设备型号 / Device model

小米13 Pro

### SoC 型号 / Soc model

骁龙8 Gen2

### 应用日志 / App logs

[log-2022-12-20-09-49-49-567.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10264066/log-2022-12-20-09-49-49-567.zip)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
![Screenshot_20221220-095918~2](https://user-images.githubusercontent.com/43900799/208563455-fcd9bb5b-9eba-43bd-a491-133cd5775706.png)
