### ISSUE TITLE
画廊读取速度

### ISSUE THREAD

**Issue by RogerYan096** [Ehviewer-Overhauled/Ehviewer#560]
### 复现步骤 / Step to reproduce

1.阅读在线画廊与离线画廊时均会发生

### 预期行为 / Expected behaviour

应该
1.优先按顺序加载
2.优先加载即将阅读部分

### 实际行为 / Actual Behaviour

1.在在线观看与下载观看时加载速度很慢
2.在线加载、离线加载不是按照顺序来，而是乱序、倒序，不会优先加载马上阅读的部分，会加载中间的图片以及最后几张图片，影响阅读体验

### 备注 / Addition details

从左到右阅读正常从右到左阅读加载有问题

### EhViewer 版本号 / EhViewer version code

1.8.50

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3732571006

### Android 系统版本 / Android version

miui14

### 设备型号 / Device model

xiaomi12spro

### SoC 型号 / Soc model

8+gen1

### 应用日志 / App logs

none

### 自查步骤 / Verify steps

- [] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
离线画廊咋可能用加载 不都半秒钟不到就好了

**Comment by RogerYan096** [comment]
> 

我不到啊  我这确实读取转圈圈 而且先是读取页码倒序的页面

**Comment by RogerYan096** [comment]
> 离线画廊咋可能用加载 不都半秒钟不到就好了

我检查了一下 我开的是从右到左模式 这个模式应该是有bug

**Comment by RogerYan096** [comment]
应该是从右到左模式有问题 只是让把1-末位的图片顺序反了过来 加载还是按照从左至右的方式加载 希望可以修复

**Comment by RogerYan096** [comment]
> > 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue
> 
> 请删除备注内多余的内容

已删除
