### ISSUE TITLE
Build failed due to Jitpack servers' unavailability

### ISSUE THREAD

**Issue by FooIbar** [Ehviewer-Overhauled/Ehviewer#572]
### 复现步骤 / Step to reproduce

https://github.com/Baseflow/PhotoView/issues/827
https://github.com/jitpack/jitpack.io/issues/5337

### 预期行为 / Expected behaviour

/

### 实际行为 / Actual Behaviour

/

### 备注 / Addition details

Consider moving away from Jitpack

### EhViewer 版本号 / EhViewer version code

/

### EhViewer CI 版本 / EhViewer CI Version

/

### Android 系统版本 / Android version

/

### 设备型号 / Device model

/

### SoC 型号 / Soc model

/

### 应用日志 / App logs

/

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
直接把photoview inline 了吧反正他们也不更新了

**Comment by FooIbar** [comment]
现在好像暂时还能用，因为有 cf 的缓存，不过是 `cf-cache-status: STALE`
原仓库很久不活跃了，估计也不会发布到 MavenCentral
Jitpack 那边一天多了还一点反应都没有

**Comment by asuka-mio** [comment]
https://github.com/jitpack/jitpack.io/issues/5337#issuecomment-1363840754
