### ISSUE TITLE
阅读模式下翻转页面会导致闪退死循环

### ISSUE THREAD

**Issue by MrSakamoto777** [Ehviewer-Overhauled/Ehviewer#579]
### 复现步骤 / Step to reproduce

1. 打开应用设置，选择“EH”。
2. 将“详情模式下缩略图大小”修改至50。
3. 打开任意一个下载的内容，进入阅读模式。
4. 选择页面下方的从左至右第三个图标（页面设置）。
5. 调整为“反向竖屏”，或者先调整为横屏再调整为反向竖屏。
6. 页面闪退，系统弹窗“null发生错误”（null已关闭，因为该应用程序出现了错误。请在其开发者提供此错误的修复后再尝试更新它。）
7. 因设置已保存，此后每次进入阅读模式都会闪退，无法恢复正常。

### 预期行为 / Expected behaviour

应正常翻转屏幕。
另外，逻辑上应允许用户在阅读模式页面外设置页面翻转的相关设置，以避免死循环的情况发生。

### 实际行为 / Actual Behaviour

应用闪退并报错，弹出“需要开发者修复”的系统提示。

https://user-images.githubusercontent.com/121399004/209514930-7611b9b8-f1ec-4cac-b482-b1a0cf6cb8d2.mp4

### 备注 / Addition details

此bug使阅读所有内容无法正常进行，且用户无法正常使用，比较紧急可以考虑尽快修复，谢谢。

### EhViewer 版本号 / EhViewer version code

1.8.5.1

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.8.5.1

### Android 系统版本 / Android version

one UI 5.0 / Android 13

### 设备型号 / Device model

Samsung Note 20 Ultra

### SoC 型号 / Soc model

骁龙865 Plus

### 应用日志 / App logs

Can't parse gallery list
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>ExHentai.org</title>
<link rel="stylesheet" type="text/css" href="https://exhentai.org/z/0354/x.css" />
</head>
<body>
<script type="text/javascript">
function popUp(URL,w,h) {
	window.open(URL,"_pu"+(Math.random()+"").replace(/0\./,""),"toolbar=0,scrollbars=0,location=0,statusbar=0,menubar=0,resizable=0,width="+w+",height="+h+",left="+((screen.width-w)/2)+",top="+((screen.height-h)/2));
	return false;
}
</script>
<div id="nb" class="nosel"><div><a class="nbw" href="https://exhentai.org/">Front<span class="nbw1"> Page</span></a></div><div><a href="https://exhentai.org/watched">Watched</a></div><div><a href="https://exhentai.org/popular">Popular</a></div><div><a href="https://exhentai.org/torrents.php">Torrents</a></div><div><a href="https://exhentai.org/favorites.php">Fav<span class="nbw1">orite</span>s</a></div><div><a href="https://exhentai.org/uconfig.php">Settings</a></div><div><a href="https://exhentai.org/upld/manage"><span class="nbw2">My </span>Uploads</a></div><div><a href="https://exhentai.org/mytags">My Tags</a></div></div>
<div class="ido">
<div id="toppane">
<h1 class="ih">ExHentai.org - <a href="http://exhentai55ld2wyap5juskbm67czulomrouspdacjamjeloj7ugjbsad.onion">Now With Layers</a> &nbsp;<a href="https://en.wikipedia.org/wiki/Tor_(anonymity_network)">[?]</a></h1><div id="searchbox" class="idi"><form action="https://exhentai.org/" method="get" style="margin:0px; padding:0px"><input type="hidden" id="f_cats" name="f_cats" value="0" disabled="disabled" /><table class="itc"><tr><td><div id="cat_2" class="cs ct2" onclick="toggle_category(2)">Doujinshi</div></td><td><div id="cat_4" class="cs ct3" onclick="toggle_category(4)">Manga</div></td><td><div id="cat_8" class="cs ct4" onclick="toggle_category(8)">Artist CG</div></td><td><div id="cat_16" class="cs ct5" onclick="toggle_category(16)">Game CG</div></td><td><div id="cat_512" class="cs cta" onclick="toggle_category(512)">Western</div></td></tr><tr><td><div id="cat_256" class="cs ct9" onclick="toggle_category(256)">Non-H</div></td><td><div id="cat_32" class="cs ct6" onclick="toggle_category(32)">Image Set</div></td><td><div id="cat_64" class="cs ct7" onclick="toggle_category(64)">Cosplay</div></td><td><div id="cat_128" class="cs ct8" onclick="toggle_category(128)">Asian Porn</div></td><td><div id="cat_1" class="cs ct1" onclick="toggle_category(1)">Misc</div></td></tr></table><div><input type="text" id="f_search" name="f_search" placeholder="Search Keywords" value="&quot;Osaka no Kyuujitsu&quot;" size="90" maxlength="200" /><input type="submit" value="Search" onclick="search_presubmit()" /><input type="button" value="Clear" onclick="top.location.href='https://exhentai.org/'; return false" /></div><div>[<a href="#" onclick="toggle_advsearch_pane(this); return false">Show Advanced Options</a>] &nbsp; &nbsp;[<a href="#" onclick="toggle_filesearch_pane(this); return false">Show File Search</a>]</div><div id="advdiv" style="display:none"></div></form></div><div id="fsdiv" class="idi" style="margin-top:10px; display:none"></div>
<script type="text/javascript" src="https://exhentai.org/z/0354/ehg_index.c.js"></script>

<script type="text/javascript">
var ulhost = "https://exhentai.org/upld/";
</script>

</div><div style="position:relative; z-index:2"><div class="searchtext"><p>Found 9 results. </p></div>
<div class="searchnav">
	<div></div>
	<div><a href="https://exhentai.org/?f_search=%22Osaka+no+Kyuujitsu%22">&lt;&lt; First</a></div><div><a href="https://exhentai.org/?f_search=%22Osaka+no+Kyuujitsu%22&amp;prev=2305668">&lt; Prev</a></div><div><span>Next &gt;</span></div><div><span>Last &gt;&gt;</span></div>
	<div><select onchange="document.location='https://exhentai.org/?f_search=%22Osaka+no+Kyuujitsu%22&amp;inline_set=dm_'+this.value+'&amp;next=2305669'"><option value="m">Minimal</option><option value="p">Minimal+</option><option value="l" selected="selected">Compact</option><option value="e">Extended</option><option value="t">Thumbnail</option></select></div>
</div><table class="itg gltc"><tr><th></th><th>Published</th><th>Title</th><th class="glhide">Uploader</th></tr><tr><td style="text-align:center; font-style:italic; padding:10px 0" colspan="4">No more unfiltered results found.</td></tr></table><div class="searchnav"><div></div><div><a href="https://exhentai.org/?f_search=%22Osaka+no+Kyuujitsu%22">&lt;&lt; First</a></div><div><a href="https://exhentai.org/?f_search=%22Osaka+no+Kyuujitsu%22&amp;prev=2305668">&lt; Prev</a></div><div><span>Next &gt;</span></div><div><span>Last &gt;&gt;</span></div><div></div></div></div></div>
<div class="dp" style="margin:0 auto 5px">
	<a href="https://exhentai.org/">Front Page</a>
	
	  &nbsp; <a href="http://exhentai55ld2wyap5juskbm67czulomrouspdacjamjeloj7ugjbsad.onion">Onion</a>
</div>
</body>
</html>

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
什么上下翻转 没看到相关设置 你录个屏吧 说的太模糊了

**Comment by txyyh** [comment]
ci版本错误
请填写正确ci版本

**Comment by MrSakamoto777** [comment]
> 什么上下翻转 没看到相关设置 你录个屏吧 说的太模糊了

不好意思记错了 是阅读模式点齿轮 然后屏幕方向改成横屏之后 软件就闪退了 并且每次点进某个本阅读的时候都会闪退 所以没办法录屏复现

**Comment by MrSakamoto777** [comment]
> 什么上下翻转 没看到相关设置 你录个屏吧 说的太模糊了

具体复现步骤描述和bug视频已更新，请查收，谢谢。

**Comment by FooIbar** [comment]
这没解决啊，问题是 rotation_type 那个 string-array 少了一项

**Comment by asuka-mio** [comment]
> 这没解决啊，问题是 rotation_type 那个 string-array 少了一项

嗯？目测是不会闪退了 那个array我看看
