### ISSUE TITLE
上下翻页(连续)和条漫模式，向上翻页会回弹！

### ISSUE THREAD

**Issue by YukiiYuna** [Ehviewer-Overhauled/Ehviewer#581]
### 复现步骤 / Step to reproduce

1.打开上下翻页（连续）模式
2.直接点开30+页向上回看

### 预期行为 / Expected behaviour

它应该流畅回看之前的页数

### 实际行为 / Actual Behaviour

实际上会回弹

https://user-images.githubusercontent.com/94183301/209521286-cc1a7957-21eb-4bfa-9dfa-91eccccabb00.mp4

### EhViewer 版本号 / EhViewer version code

1.8.5.1

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/download/1.8.5.1/EhViewer-universal.apk

### Android 系统版本 / Android version

miui14

### 设备型号 / Device model

小米12su

### SoC 型号 / Soc model

8+gen 1

### 应用日志 / App logs

[log-2022-12-26-15-44-37-372.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10302275/log-2022-12-26-15-44-37-372.zip)

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
应该已经被 3484261b5023e0e5e3fc1fbe93fcd05c846a9672 修复了
