### ISSUE TITLE
应用冷启动时，主页无法正常载入，持续显示转圈动画

### ISSUE THREAD

**Issue by VVaraiotoko** [Ehviewer-Overhauled/Ehviewer#587]
### 复现步骤 / Step to reproduce

1、确保应用彻底关闭
2、启动应用

### 预期行为 / Expected behaviour

它应该正常载入主页内容

### 实际行为 / Actual Behaviour

 实际上它持续显示转圈动画，必须手动搜索一下才能显示主页内容

https://user-images.githubusercontent.com/28192782/209707997-91a30107-8333-4530-a25a-a5463100c130.mp4

### EhViewer 版本号 / EhViewer version code

1.8.5.1

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3785966345

### Android 系统版本 / Android version

Android 12, Stock ROM 58.2.A.7.93

### 设备型号 / Device model

Sony Xperia 1 II 

### SoC 型号 / Soc model

骁龙865

### 应用日志 / App logs

[log-2022-12-28-02-32-02-943.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10310134/log-2022-12-28-02-32-02-943.zip)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
复现不了

**Comment by VVaraiotoko** [comment]
> 复现不了

我也觉得很奇怪，升级前没有这问题

**Comment by asuka-mio** [comment]
> > 复现不了
> 
> 我也觉得很奇怪，升级前没有这问题

新安装的有这问题吗

**Comment by VVaraiotoko** [comment]
> > > 复现不了
> > 
> > 
> > 我也觉得很奇怪，升级前没有这问题
> 
> 全新安装的有这问题吗

又试了一下卸载重装后立刻打开，有，再清除一遍应用数据，以游客模式访问E-Hentai，没有了，但是导入数据用账户登录ExHentai就又有了…

https://user-images.githubusercontent.com/28192782/209758564-41e9303e-2c0a-4a15-8514-a52e32d520fe.mp4

**Comment by asuka-mio** [comment]
就挺离谱的 不过我最近没改主页这块 都是大改阅读器了

**Comment by VVaraiotoko** [comment]
> 就挺离谱的 不过我最近没改主页这块 都是大改阅读器了

我又试了一下，“隐私”中关闭“需要解锁”不会出现这种情况，反之则会出现，你看能不能复现
