### ISSUE TITLE
条漫模式下裁剪边缘导致页面滑动

### ISSUE THREAD

**Issue by FooIbar** [Ehviewer-Overhauled/Ehviewer#589]
### 复现步骤 / Step to reproduce

1. 从非起始页打开任意画廊
2. 切换裁剪边缘设置

### 预期行为 / Expected behaviour

保持在当前位置

### 实际行为 / Actual Behaviour

https://user-images.githubusercontent.com/118464521/209791033-3663d2c3-bc05-4337-b85c-cc710c5761b6.mp4

### EhViewer 版本号 / EhViewer version code

1.8.5.1

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3792743190

### Android 系统版本 / Android version

PixelExperience 11

### 设备型号 / Device model

Moto Z2 Play

### SoC 型号 / Soc model

Snapdragon 626

### 应用日志 / App logs

/

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
tachiyomi 那个 decoder 才支持裁剪边缘啊，~~不如把这个选项先删了吧~~

**Comment by asuka-mio** [comment]
> tachiyomi 那个 decoder 才支持裁剪边缘啊，~不如把这个选项先删了吧~

他们那个解码器糊的也差点意思，而且还不支持硬件位图，虽然自己上传到HardwareBuffer也就几句的事
而且我不是很想外置解码器，那解码器赶上咱们一个apk大了
这样的话我自己写cropborder写一个效率优先的实现还是得用ndk接口解码，那个Android S才有的，不过没动图支持R就有了，动图也不用裁剪
删了吧还是 先不支持了
等过几年minsdk标配31了再说

**Comment by asuka-mio** [comment]
我还是先写个arm64汇编或者neon intrinsics和他们c实现对比下效率
看看能不能想办法用gpu处理之类的

**Comment by asuka-mio** [comment]
如果能直接用gpu处理就不用先解码到本地堆读取计算再上传到hwbuffer上了

**Comment by FooIbar** [comment]
解码器的问题另说，只要在WebtoonViewer里调用了refreshAdapter都会出现这个issue里的问题
当初为啥要把notifyItemRangeChanged改成notifyDataSetChanged？

**Comment by asuka-mio** [comment]
> 解码器的问题另说，只要在WebtoonViewer里调用了refreshAdapter都会出现这个issue里的问题 当初为啥要把notifyItemRangeChanged改成notifyDataSetChanged？

忘了 反正当时是有毛病的
你可以改回去试试看看到底会出啥毛病 我记得是adapter 抛出了个数组溢出的异常

**Comment by FooIbar** [comment]
> > 解码器的问题另说，只要在WebtoonViewer里调用了refreshAdapter都会出现这个issue里的问题 当初为啥要把notifyItemRangeChanged改成notifyDataSetChanged？
> 
> 忘了 反正当时是有毛病的 你可以改回去试试看看到底会出啥毛病 我记得是adapter 抛出了个数组溢出的异常

测不出啥问题，不过感觉改回去也是治标不治本，只是把真正的问题掩盖了
