### ISSUE TITLE
希望为种子下载添加下载提示并避免重复下载

### ISSUE THREAD

**Issue by VVaraiotoko** [Ehviewer-Overhauled/Ehviewer#592]
### 需求 / Requirement

如题，现在的种子下载没有上述功能，点按后没有界面反馈，有时会让人以为没点到、没开始下载，重复点按也没有对话框提醒，导致重复下载同一个种子文件数遍。

### 建议实现 / Suggested implements

建议点按下载种子时至少弹出toast/snackbar提醒“正在下载种子”，种子下载中再次点按下载种子则再次提醒，并/或禁止同时下载同一种子。

### EhViewer 版本号 / EhViewer version code

1.8.5.1

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3794596637

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by FooIbar** [comment]
这个有系统提示啊，不过默认是静音的

https://user-images.githubusercontent.com/118464521/210057989-9d8c8bc2-bcfc-4ee7-a008-2921eee07326.mp4

**Comment by VVaraiotoko** [comment]
> 这个有系统提示啊，不过默认是静音的
> 
>  dm.mp4

这个是下载完成后的提醒吧？虽然种子不大，在网络延迟的情况下还是有误以为连接失败，而重复下载的可能，那能否考虑至少加个限制/确认重复下载的功能呢？
![Screenshot_20221231-222606](https://user-images.githubusercontent.com/28192782/210140036-c87479f3-d4af-4801-9726-06773675b154.png)

**Comment by FooIbar** [comment]
> > 这个有系统提示啊，不过默认是静音的
> > dm.mp4
> 
> 这个是下载完成后的提醒吧？虽然种子不大，在网络延迟的情况下还是有误以为连接失败，而重复下载的可能，那能否考虑至少加个限制/确认重复下载的功能呢？ ![Screenshot_20221231-222606](https://user-images.githubusercontent.com/28192782/210140036-c87479f3-d4af-4801-9726-06773675b154.png)

开始下载之后就有提示，你仔细看00:02那里
