### ISSUE TITLE
收藏按钮，状态变化前后不明显

### ISSUE THREAD

**Issue by XiacheOfficial** [Ehviewer-Overhauled/Ehviewer#605]
### 需求 / Requirement

我希望那个按钮更明显

### 建议实现 / Suggested implements

未收藏：
![2484A4B4ED1C2081954FCDE9E4BE508A](https://user-images.githubusercontent.com/89523476/210171936-e53c1c9b-35ea-4ad6-99fa-a79add8d0b7c.jpg)
现在：已经收藏：
![6B166FDA7D3B692A148B2E01CD2B338B](https://user-images.githubusercontent.com/89523476/210171932-f281f305-4943-4f39-8e44-057c187a84da.jpg)
希望：已经收藏：
![image](https://user-images.githubusercontent.com/89523476/210172269-b45ed11d-dc13-4590-9e12-a41faa4ad380.png)

### EhViewer 版本号 / EhViewer version code

1.8.5.2

### EhViewer CI 版本 / EhViewer CI Version

嗯？我不太清楚这是什么，对不起

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by txyyh** [comment]
笨猫

**Comment by XiacheOfficial** [comment]
> 

？？？
