### ISSUE TITLE
自定义图标功能

### ISSUE THREAD

**Issue by XiacheOfficial** [Ehviewer-Overhauled/Ehviewer#609]
### 需求 / Requirement

可以考虑下三个维护者绘制的三个不同图标的切换功能吗？个人比较喜欢neko维护的那一版的图标（
我在discussion里发布了一些新图标的建议，可以考虑一下吗（

### 建议实现 / Suggested implements

在设置项-关于中可以添加切换图标选项

### EhViewer 版本号 / EhViewer version code

1.8.5.2

### EhViewer CI 版本 / EhViewer CI Version

最新的

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by asuka-mio** [comment]
不考虑

**Comment by asuka-mio** [comment]
我们的设计语言是完全遵循谷歌Material Design 3的
图标的设计也是模仿谷歌gapps四色设计

**Comment by XiacheOfficial** [comment]
> 我们的设计语言是完全遵循谷歌Material Design 3的 图标的设计也是模仿谷歌gapps四色设计

呃，就我看来，应用程序图标设计可能和md3标准不冲突。
不论怎样，感谢你的回复。
