### ISSUE TITLE
阅读中图片向后预载逻辑似乎出现了一些问题

### ISSUE THREAD

**Issue by MegoCat** [Ehviewer-Overhauled/Ehviewer#612]
### 复现步骤 / Step to reproduce

观察中发现打开gallery会向后预载7张图片，但只有在阅读到第7张图片时才会触发下一次预载（此时会一次性向后预载到第13张），快速阅读时影响体验

### 预期行为 / Expected behaviour

每一次翻页都应触发预载，保持缓存容量充足

### 实际行为 / Actual Behaviour

如上

### EhViewer 版本号 / EhViewer version code

1.8.5.2

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3814412310

### Android 系统版本 / Android version

PixelOS Android 12.1

### 设备型号 / Device model

Redmi note 8

### SoC 型号 / Soc model

骁龙665

### 应用日志 / App logs

--------- beginning of main
01-02 16:08:40.417  8972  8972 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
01-02 16:08:49.383  8972  8972 I AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
01-02 16:08:49.893  8972 16186 D OpenGLRenderer: endAllActiveAnimators on 0xb4000072c145f700 (NavigationMenuItemView) with handle 0xb40000733acb48c0
01-02 16:08:56.899  8972  8972 I Yc      : Can't parse url: https://github.com/Ehviewer-Overhauled/Ehviewer

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
预载是在SpiderQueen里处理的
54bd6f6 56ba52d 这里命中了缓冲就没有request

**Comment by asuka-mio** [comment]
草 我才意识到 感谢指出问题
@FooIbar 你有时间就修一下吧 我晚上没法写
