### ISSUE TITLE
点按“历史”应用立即闪退

### ISSUE THREAD

**Issue by VVaraiotoko** [Ehviewer-Overhauled/Ehviewer#628]
### 复现步骤 / Step to reproduce

在左侧侧滑菜单中点按“历史”

### 预期行为 / Expected behaviour

它应该打开“历史”页面

### 实际行为 / Actual Behaviour

实际上它立即闪退

https://user-images.githubusercontent.com/28192782/210702843-385ca0ae-717b-4f98-90cc-2b0f01bc95af.mp4

### EhViewer 版本号 / EhViewer version code

1.8.5.2

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3842366891

### Android 系统版本 / Android version

Android 12, Stock ROM 58.2.A.7.93

### 设备型号 / Device model

Sony Xperia 1 II 

### SoC 型号 / Soc model

骁龙865

### 应用日志 / App logs

[log-2023-01-05-12-40-29-097.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10349374/log-2023-01-05-12-40-29-097.zip)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
哎呦 确实 我这块忘测试了
