### ISSUE TITLE
“画廊信息”活动页覆盖了消息提示

### ISSUE THREAD

**Issue by wordlesswind** [Ehviewer-Overhauled/Ehviewer#633]
### 复现步骤 / Step to reproduce

1. 打开某一画廊的“画廊信息”页面
2. 随意点击一条目以复制该条目内容

### 预期行为 / Expected behaviour

“复制成功”的消息提示应在“画廊信息”上方

### 实际行为 / Actual Behaviour

“复制成功”的消息提示在“画廊信息”下方

![IMG_20230105_200537](https://user-images.githubusercontent.com/9050713/210834232-971e4908-dd5f-4064-9790-b24c8ee8f52f.jpg)

![IMG_20230105_200525](https://user-images.githubusercontent.com/9050713/210834261-c8f0ce1f-d1b3-4966-bf17-ff59c234db61.jpg)

### EhViewer 版本号 / EhViewer version code

1.8.5.2

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3814411327

### Android 系统版本 / Android version

ColorOS for OnePlus 12.1

### 设备型号 / Device model

OnePlus 7 Pro

### SoC 型号 / Soc model

Snapdragon 855

### 应用日志 / App logs

N/A

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
这个我也没招啊 snackbar没法显示在这上面
要不这用toast吧直接
