### ISSUE TITLE
GIF播放速度错误

### ISSUE THREAD

**Issue by yuganxia** [Ehviewer-Overhauled/Ehviewer#641]
### 复现步骤 / Step to reproduce

0.已重新安装软件
1.打开ex画廊https://exhentai.org/g/385295/17aacbb448/
Asian Animated Gifs ~Cosplay Edition~
2.打开任意GIF
3.GIF播放速度极快
4.将图片下载在本地打开播放速度正常

### 预期行为 / Expected behaviour

Gif播放速度不正常

### 实际行为 / Actual Behaviour

GIF播放速度极快，无法使用屏幕GIF录制捕捉(录屏下来是严重抽帧的

### EhViewer 版本号 / EhViewer version code

1.8.5.3-a03

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/download/1.8.5.3-alpha03/EhViewer-universal.apk

### Android 系统版本 / Android version

Hydrogen OS 11.0.13/Android 11

### 设备型号 / Device model

一加 8p

### SoC 型号 / Soc model

snapdragon 865

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
https://github.com/coil-kt/coil/issues/540
@asuka-mio 之前好像说打算把解码交给coli来着？

**Comment by asuka-mio** [comment]
> [coil-kt/coil#540](https://github.com/coil-kt/coil/issues/540) @asuka-mio 之前好像说打算把解码交给coil来着？

画廊里目前还是直接用的ImageDecoder

**Comment by tehcneko** [comment]
这个是 ImageDecoder 的 Bug

> > [coil-kt/coil#540](https://github.com/coil-kt/coil/issues/540) @asuka-mio 之前好像说打算把解码交给coil来着？
> 
> 画廊里目前还是直接用的ImageDecoder

**Comment by asuka-mio** [comment]
先前的修复导致了大量性能损失和在低配设备上的问题
经过考虑决定revert掉，同时reopen此issue

**Comment by asuka-mio** [comment]
用measureTimeMillis 测试了下，这个实现对于不用修复的图片，包括gif,时间消耗连一毫秒都不到， 对于需要进行整个修复的图片大约在10毫秒 看图片大小而定
而且进行修复的时间消耗大部分也都是populate了下page cache,就直接节省后面解码的缺页成本了
