### ISSUE TITLE
通过外部链接冷启动 EhViewer，无法返回主界面

### ISSUE THREAD

**Issue by wordlesswind** [Ehviewer-Overhauled/Ehviewer#643]
### 复现步骤 / Step to reproduce

0. 全新安装 EhViewer
1. 通过外部链接（[https://e-hentai.org/g/2375442/e827cf8721/](https://e-hentai.org/g/2375442/e827cf8721/)）冷启动 EhViewer

录屏：[screen-20230107-214730.mp4.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10366424/screen-20230107-214730.mp4.zip)

### 预期行为 / Expected behaviour

点击返回按钮可返回至 EhViewer 主界面

### 实际行为 / Actual Behaviour

点击返回按钮将返回至上级应用
从启动器进入 EhViewer 也是如此

### 备注 / Addition details

返回上级应用的行为合理，但是既然现在大多数人都使用着手势导航，而从底部向右滑即可返回上级应用，那么 EhViewer 中的返回行为就显得有些多余。

而且虽然在正常画廊下，用户可以通过搜索“相似画廊”等方式返回主界面，但是如果打开的是因各种原因而被移除的画廊，那么用户只能强制停止 EhViewer，重新启动才能进入主界面。

### EhViewer 版本号 / EhViewer version code

1.8.5.3-alpha03

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3859725814

### Android 系统版本 / Android version

LineageOS 20

### 设备型号 / Device model

OnePlus 7 Pro

### SoC 型号 / Soc model

Snapdragon 855

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by duzhaokun123** [comment]
你完全可以通过左侧菜单去主页

https://user-images.githubusercontent.com/39830683/211155333-980b922f-a135-46ac-81d6-2560ecb01099.mp4

**Comment by asuka-mio** [comment]
左侧导航抽屉干啥用的
