### ISSUE TITLE
无翻页模式设置接口

### ISSUE THREAD

**Issue by f0banzai** [Ehviewer-Overhauled/Ehviewer#645]
### 复现步骤 / Step to reproduce

Pre.似乎阅读器用了Tachiyomi的阅读界面。
但是没有设置项。
因此在左右滑动和条漫之间的设置
都会应用于全局。
1.设置翻页模式

### 预期行为 / Expected behaviour

翻页模式应该只对应于当前画廊。

### 实际行为 / Actual Behaviour

实际上此设置作用于全局。

### EhViewer 版本号 / EhViewer version code

1.8.5.3-alpha3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/download/1.8.5.3-alpha03/EhViewer-universal.apk

### Android 系统版本 / Android version

ZUI 13.5 Android12

### 设备型号 / Device model

联想Y90

### SoC 型号 / Soc model

骁龙8G1

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
https://github.com/Ehviewer-Overhauled/Ehviewer/issues/539#issuecomment-1359432886
预期行为

**Comment by ErEbusE** [comment]
看来你得提一个功能需求了
