### ISSUE TITLE
增加下载原图功能

### ISSUE THREAD

**Issue by 1235789gzy1** [Ehviewer-Overhauled/Ehviewer#651]
### 需求 / Requirement

希望添加一个下载原图功能，各大ehviewer设置中的 “下载原图” 均为 “加载原图”，虽然可以打开此选项达到下载原图的目的，但是我希望是先预览略缩图，然后在选择下载选项的时候单独下载这一张原图，而不是将配额浪费在其他不想下载的图片上。
eh网页上是有单独的下载原图按钮的，貌似并不是Hath Perks独有的功能。
![image](https://user-images.githubusercontent.com/52618207/211543745-c2d402e7-665e-49ea-b8db-7af6e83f012a.png)

### 建议实现 / Suggested implements

将原本的“下载原图”文本更改为加载原图
新增“下载原图”选项，开启此选项时，浏览画廊依旧使用略缩图，只有长按选择 下载/另存为 时才下载原图

### EhViewer 版本号 / EhViewer version code

1.8.5.3-alpha03

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3859725814

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [x] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by txyyh** [comment]
ci版本错误，请填写正确ci版本
