### ISSUE TITLE
mumu模拟器无法安装

### ISSUE THREAD

**Issue by no-name-2020** [Ehviewer-Overhauled/Ehviewer#662]
### 复现步骤 / Step to reproduce

1，使用mumu模拟器（mac）安装
2，显示开始安装
3，显示安装失败 [install_failed_invalid_apk]
<img width="345" alt="屏幕快照 2023-01-12 下午12 18 56" src="https://user-images.githubusercontent.com/76810019/211975609-d25671fb-9d31-4e3d-b4e0-00348f7ff555.png">
<img width="346" alt="屏幕快照 2023-01-12 下午12 21 10" src="https://user-images.githubusercontent.com/76810019/211975621-5d7b061f-07f7-47fa-b4ef-a9fa2fcc988e.png">

### 预期行为 / Expected behaviour

它应该显示完成安装

### 实际行为 / Actual Behaviour

实际上它显示安装失败 [install_failed_invalid_apk]
<img width="345" alt="屏幕快照 2023-01-12 下午12 18 56" src="https://user-images.githubusercontent.com/76810019/211975656-b6a8fa15-5aad-479e-a5fc-c090898ec975.png">

### EhViewer 版本号 / EhViewer version code

1.8.5.3

### EhViewer CI 版本 / EhViewer CI Version

……

### Android 系统版本 / Android version

6.0.1

### 设备型号 / Device model

mumu模拟器

### SoC 型号 / Soc model

mumu模拟器 使用电脑为2.6 GHz Intel Core i7

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
目前只支持Android9及以上
