### ISSUE TITLE
在看图的时候能不能关闭那个最下面的页数选择进度条

### ISSUE THREAD

**Issue by yinzhefuyun** [Ehviewer-Overhauled/Ehviewer#668]
### 需求 / Requirement

在看图的时候能不能关闭那个最下面的页数选择进度条
我看图用的是条漫模式，手指经常是放在屏幕上滑动的，误操作概率是200%

### 建议实现 / Suggested implements

建议添加一个开关能隐藏那个页数选择进度条，或者把进度条移动到屏幕上面

### EhViewer 版本号 / EhViewer version code

1.8.5.3

### EhViewer CI 版本 / EhViewer CI Version

arm64-v8a-3b32ad5fed0d17f73d7bacf3e5c93b6bf252caf6

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by FooIbar** [comment]
进度条不是会自动隐藏吗

**Comment by yinzhefuyun** [comment]
> 进度条不是会自动隐藏吗

会不小心点击屏幕两次然后就跳出来了，而且现在屏幕老长了，本来操作区域就在下面，而且那个条不是最下面于是每次看本都会点到

**Comment by FooIbar** [comment]
> > 进度条不是会自动隐藏吗
> 
> 会不小心点击屏幕两次然后就跳出来了，而且现在屏幕老长了，本来操作区域就在下面，而且那个条不是最下面于是每次看本都会点到

点屏幕中间才会唤出菜单啊，我不理解怎么才能误操作

**Comment by yinzhefuyun** [comment]
> 



> > > 进度条不是会自动隐藏吗
> > 
> > 
> > 会不小心点击屏幕两次然后就跳出来了，而且现在屏幕老长了，本来操作区域就在下面，而且那个条不是最下面于是每次看本都会点到
> 
> 点屏幕中间才会唤出菜单啊，我不理解怎么才能误操作

点按区域 选 关闭，因为我就喜欢条漫+手指滑动

**Comment by Xqh233** [comment]
果然是各有需求，我单手握持的时候就靠这个滑动条切换进度

**Comment by yinzhefuyun** [comment]
> 果然是各有需求，我单手握持的时候就靠这个滑动条切换进度

每个人操作习惯不一样
