### ISSUE TITLE
当开启画廊详情页加载200页后，加载完200页点击“查看更多预览”默认显示更多预览的第1张缩略图不是第201张缩略图

### ISSUE THREAD

**Issue by yinzhefuyun** [Ehviewer-Overhauled/Ehviewer#675]
### 复现步骤 / Step to reproduce

当开启画廊详情页加载200页后，加载完200页点击“查看更多预览”默认显示更多预览的第1张不是第201张（经过您的优化加载200张缩略图手机已经不会掉帧了）

### 预期行为 / Expected behaviour

加载完200页点击“查看更多预览”默认显示是第201张
或者考虑点击只点最后那几个小字进入页面的时候 才会自动跳页

### 实际行为 / Actual Behaviour

加载完200页点击“查看更多预览”默认显示预览的第1张

### 备注 / Addition details

这个bug其实源远流长
早期是因为Hippo对详情页缩略图加载没有优化所以当开始加载200张缩略图的时候会掉帧
然后NekoInverter fork的时候天天Issue里面被人说掉帧，然后NekoInverter直接设置成21张缩略图，然后我用三星note3为基准测试，大于60张会卡，而且基本上那2021年没有比三星note3还老的手机，所以就设置成详情页默认显示60张缩略图，然后就发现一个bug，就是如果自己能看到200张缩略图，默认只显示60张，点击“查看更多预览”会跳到201张，所以修改的默认显示第1张缩略图
然后现在经过你的优化，同时加载200张缩略图详情页也不会卡顿掉帧，就是点开“查看更多预览”默认还是第1页
我只记得大概是https://gitlab.com/NekoInverter/EhViewer/-/commit/fcd4f3732d61c19c6302ac260a117f1146b46b2e
这个Commit左右开始改的，至于是哪个Commit后面改的我就不清楚了

### EhViewer 版本号 / EhViewer version code

1.8.5.3

### EhViewer CI 版本 / EhViewer CI Version

eada1bc023fc3528f3cf8dfcfe5551d1f907ef1b

### Android 系统版本 / Android version

miui14/安卓13

### 设备型号 / Device model

红米K50U

### SoC 型号 / Soc model

8+

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
我没优化这块啊 我连课金账号都没有（）

**Comment by yinzhefuyun** [comment]
> 我没优化这块啊 我连课金账号都没有（）

https://t.me/ehviewer你在这里面吗？或者通过@yin123123123这个加我，到时候我确认你是谁后，我帮你解锁那几个功能

**Comment by tehcneko** [comment]
一直都是跳到第一页的，从来没跳到下一页过

**Comment by yinzhefuyun** [comment]
> 一直都是跳到第一页的，从来没跳到下一页过

难道我失意了？
