### ISSUE TITLE
排行榜功能

### ISSUE THREAD

**Issue by wordly123** [Ehviewer-Overhauled/Ehviewer#68]
### 需求 / Requirement

这个功能非常难实现，实现不了也不强求，（我知道e站的画廊只有详情才有收藏数，外面列表是看不见的）如今e站排行榜只能说存在不能说能用，我希望能有一个比较好用的排行榜，下面我列下这个排行榜应该有的功能
1. 能根据用户的选择 显示今天/今周/今月或者今年（可能有点夸张） 收藏数量最多的画廊显示在列表里 自上往下 由高到低 
2. 可以选择指定的语言 根据语言当做条件过滤排行榜 （或者其他标签也行，当然我希望语言是首位）
3. 可以选择前10或者前20  这个条目数可以让用户选择展示前几的排行榜

### 建议实现 / Suggested implements

可以考虑用服务器存这些信息，当然也可以在程序中实现，e站对查询有限制的 ，查询过多可能会出问题，而且e站中文区一天的上次量是多少我也不清， 总之排行榜最开始建议还是画廊的上次时间从今天00:00:00分到今天23:59:59秒为止，语言为中文的list查出来，然后对每个画廊进行循环调用拿出收藏数然后再排序，当然这是我想的可能，中文区上次数太大循环崩了也可能，最好带个画廊类型，当然以上都是我想到的，只当做建议。

### 其他细节 / Addition details

暂无

### EhViewer 版本号 / EhViewer version code

1.7.27.6

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/asuka-mio/Ehviewer/actions/runs/2562775408

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/asuka-mio/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/asuka-mio/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/asuka-mio/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/asuka-mio/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by txyyh** [comment]
我们会考虑您的建议。但由于实现此功能工程量确实较大，我们之后将再作考虑。

**Comment by wordly123** [comment]
> 我们会考虑您的建议。但由于实现此功能工程量确实较大，我们之后将再作考虑。

愿意做就行，时间要多久或者排在多后面都没啥问题，毕竟这个确实要写的话需要思考挺久的

**Comment by txyyh** [comment]
经过查验，您所说的大部分功能已经实现

1. 排行页面已经实现
2. 您可以在设置 - EH - E-hentai 设置实现本功能
3. 不往下翻页不就可以了嘛））

因此我们将不再考虑另行实现
