### ISSUE TITLE
Go to page opens date selection

### ISSUE THREAD

**Issue by MrShef** [Ehviewer-Overhauled/Ehviewer#693]
### 复现步骤 / Step to reproduce

0.press "+" button
![IMG_20230118_094053](https://user-images.githubusercontent.com/122965071/213112283-a2e58799-f4d5-4a2d-a1da-cd883b5fb342.jpg)

1.press go to page button
![IMG_20230118_094118](https://user-images.githubusercontent.com/122965071/213112317-acd13d18-69ef-40f5-a552-9afc7a1b62a7.jpg)

### 预期行为 / Expected behaviour

It should apper this 
![Screenshot_2023-01-18-09-35-45-800_moe tarsin ehviewer](https://user-images.githubusercontent.com/122965071/213112349-a93ac82c-ae23-468e-acd4-368ad856213e.jpg)

### 实际行为 / Actual Behaviour

But apears this
![Screenshot_2023-01-18-09-30-48-787_moe tarsin ehviewer](https://user-images.githubusercontent.com/122965071/213112411-cabe6583-bc54-4b17-8ded-ad1916b1c8b8.jpg)

### EhViewer 版本号 / EhViewer version code

1.8.5.3-alpha05

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/download/1.8.5.3-alpha05/EhViewer-arm64-v8a.apk

### Android 系统版本 / Android version

MIUI 13.0.1 ANDROID 12

### 设备型号 / Device model

Poco x3 nfc

### SoC 型号 / Soc model

Qualcomm Snapdragon 732G

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
https://github.com/Ehviewer-Overhauled/Ehviewer/issues/355
