### ISSUE TITLE
横屏下画廊预览缩略图bitmap出现溢出/错位

### ISSUE THREAD

**Issue by hathlife** [Ehviewer-Overhauled/Ehviewer#696]
### 复现步骤 / Step to reproduce

1.在电视上启动应用
2.打开画廊详情页面
3.滚动到预览板块或点开画廊预览界面

### 预期行为 / Expected behaviour

缩略图bitmap正常处于框架内

### 实际行为 / Actual Behaviour

随着页数序号增大，框架中实际显示Bitmap异常，表现为显示为两页合并的接缝/某页的长条部分
![Screenshot_20230118-203246](https://user-images.githubusercontent.com/19867269/213174576-99d179a6-5a76-49d4-9bb6-f1d845b4c2d9.png)
![Screenshot_20230118-205913](https://user-images.githubusercontent.com/19867269/213178571-786abfbf-8735-4cc0-a262-efd8ec3cd68a.png)
![Screenshot_20230118-205927](https://user-images.githubusercontent.com/19867269/213178684-d409fd3d-78e4-4d75-83a7-1757be4fc611.png)

### EhViewer 版本号 / EhViewer version code

1.8.5.3-alpha04

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3948125956

### Android 系统版本 / Android version

Google TV 11

### 设备型号 / Device model

TCL 50C725

### SoC 型号 / Soc model

Realtek RTD2851

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
画廊链接给一个

**Comment by asuka-mio** [comment]
我这复现不了 以前也这样吗

**Comment by hathlife** [comment]
> 我这复现不了 以前也这样吗

以前没有，换到1.8.x.x分支开始才这样的

**Comment by asuka-mio** [comment]
那奇怪了 按理说电视和手机平板横屏这块应该没啥差别啊

**Comment by hathlife** [comment]
![image](https://user-images.githubusercontent.com/19867269/213189684-fdd84d6c-8ccf-44a4-bd0e-2a650422c6f2.png)
![image](https://user-images.githubusercontent.com/19867269/213190041-06f8effc-072e-4265-ad40-98055ea8f8e7.png)

模拟器可以复现

**Comment by FooIbar** [comment]
我这里缩略图大小改成normal就能复现，不需要横屏

**Comment by FooIbar** [comment]
缩略图大小设为large时是单独的图片，而设为normal时是从一张长图里剪裁的
![](https://ehgt.org/m/002439/2439420-00.jpg)
应该是剪裁的时候出了问题
