### ISSUE TITLE
避免在 Normal 模式下对同一张图片的多次网络请求

### ISSUE THREAD

**Issue by FooIbar** [Ehviewer-Overhauled/Ehviewer#698]
### 需求 / Requirement

Normal 模式下缩略图是从长图裁剪而来的
![](https://ehgt.org/m/002439/2439420-00.jpg)
而现有方式会对该图片进行重复请求

### 建议实现 / Suggested implements

https://github.com/coil-kt/coil/issues/1461

### EhViewer 版本号 / EhViewer version code

1.8.5.3-alpha06

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3949284136

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by asuka-mio** [comment]
不会 coil cache 住了

**Comment by asuka-mio** [comment]
你会发现这些获取的drawable全是同一个对象

**Comment by FooIbar** [comment]
第一个请求拿到之后才有 cache
实际的请求数量小于缩略图数量但大于1

**Comment by asuka-mio** [comment]
获取同一个对象是之前迁移到imagedecoder java api的事情 迁移到coil我还真没测试

**Comment by asuka-mio** [comment]
确实得解决一下

**Comment by asuka-mio** [comment]
应该是同一个对象 毕竟memory cache key是一样的

**Comment by FooIbar** [comment]
这个需求和coil那个issue的需求几乎是一模一样，不过他那边还没实现

**Comment by asuka-mio** [comment]
我觉得可以改一下coil的httpurifetcher
然后维护一个hashmap 把请求的部分synchronize下 然后后面直接用suspendcancelablecoroutine去回调

**Comment by asuka-mio** [comment]
我明天看看

**Comment by asuka-mio** [comment]
https://github.com/Ehviewer-Overhauled/coil/commit/d6792c659119def8642aebffce3dec2290d01c31
这个实现何如

**Comment by asuka-mio** [comment]
我还没构建测试 不过意思就是大概这个意思 明天再测试
