### ISSUE TITLE
在下载中支持搜索

### ISSUE THREAD

**Issue by FooIbar** [Ehviewer-Overhauled/Ehviewer#705]
### 需求 / Requirement

在下载中搜索

### 建议实现 / Suggested implements

顶部改成searchbar，过滤、全部开始、全部停止移到fab里
原来的fab里保留全选，开始、停止、删除、移动移到选中后的toolbar里，类似这种？
![705](https://user-images.githubusercontent.com/118464521/213741552-cb18bd18-ab66-4ebf-adda-831c7ea7f0cf.png)

### EhViewer 版本号 / EhViewer version code

1.8.5.3-rc01

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3968857051

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by tehcneko** [comment]
那个叫 ActionMode，Android 自己的实现 Bug 很多

**Comment by asuka-mio** [comment]
下个版本打算先把历史界面拿compose 重写下 然后整个searchbar上去支持搜索

**Comment by FooIbar** [comment]
![fab](https://user-images.githubusercontent.com/118464521/214858590-580de37a-fc05-4496-9644-c5c563e969f1.png)
横屏的时候这个fab要突破天际了

**Comment by asuka-mio** [comment]
> ![fab](https://user-images.githubusercontent.com/118464521/214858590-580de37a-fc05-4496-9644-c5c563e969f1.png) 横屏的时候这个fab要突破天际了

改成横屏往左弹得了（）

**Comment by tehcneko** [comment]
> > ![fab](https://user-images.githubusercontent.com/118464521/214858590-580de37a-fc05-4496-9644-c5c563e969f1.png) 横屏的时候这个fab要突破天际了
> 
> 改成横屏往左弹得了（）

左不 Material （

**Comment by deyangyvtian** [comment]
顶了，确实需要下载页搜索

**Comment by FooIbar** [comment]
https://github.com/FooIbar/EhViewer/commit/facfb8ace33a956c83e2ffb3b2e62e0b49638b80
