### ISSUE TITLE
部分本体网站资源无法被检索到

### ISSUE THREAD

**Issue by sdddddf80** [Ehviewer-Overhauled/Ehviewer#706]
### 复现步骤 / Step to reproduce

在软件（已登录，里站）内搜索vavacung，查看是否有2022年1月22日的更新

### 预期行为 / Expected behaviour

应该如本体网站（未登录）一样出现[Vacacung] Second World Vol. 11 的资源
![Screenshot_20230121_000733_com android chrome_edit_901787211997290](https://user-images.githubusercontent.com/53573250/213749174-db2b19fa-d5d8-42eb-8abb-7725a14655af.jpg)

### 实际行为 / Actual Behaviour

实际上并未检索到该资源
![Screenshot_20230121_000836_moe tarsin ehviewer](https://user-images.githubusercontent.com/53573250/213749544-88d4b02a-c8bf-4908-a0d9-08213c1af411.jpg)

### 备注 / Addition details

软件已登录且选择了里站

### EhViewer 版本号 / EhViewer version code

1.8.5.3-rc01

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer

### Android 系统版本 / Android version

HarmonyOS 2.0.0

### 设备型号 / Device model

HUAWEI P30

### SoC 型号 / Soc model

huawei kirin 980

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by duzhaokun123** [comment]
你这一个普通搜一个用标签是来找茬的吗

**Comment by sdddddf80** [comment]
> 你这一个普通搜一个用标签是来找茬的吗

用关键词也是一样的结果
![Screenshot_20230121_004616_moe tarsin ehviewer](https://user-images.githubusercontent.com/53573250/213755495-3a977e30-c65b-41c7-b0f1-dd3374c4ea1b.jpg)

**Comment by duzhaokun123** [comment]
> 用关键词也是一样的结果

那网页里站呢

**Comment by FooIbar** [comment]
还能这么对比的？
你要么都登录了搜要么都没登录搜，谁知道你设了什么filter

**Comment by skymkmk** [comment]
未复现你的问题，你要不统一一下变量

**Comment by sdddddf80** [comment]
> 能否检查一下 App 内的 设置-EH-屏蔽列表？

发现了，貌似是从别的ehviewer迁移过来的数据里有个屏蔽cg标签的忘记去掉了😂
