### ISSUE TITLE
画廊标题被图片遮挡

### ISSUE THREAD

**Issue by Krosec** [Ehviewer-Overhauled/Ehviewer#712]
### 复现步骤 / Step to reproduce

画廊界面中下拉查看详细标题，出现封面遮挡标题的情况

https://user-images.githubusercontent.com/107551827/213871828-a93443a6-737e-45f5-8104-c2f052cee1ca.mp4

### 预期行为 / Expected behaviour

下拉后，它应该不会出现封面遮挡详细标题的情况

### 实际行为 / Actual Behaviour

实际上，下拉后，出现封面遮挡详细标题的情况

### 备注 / Addition details

下拉前，上方的标题没有省略号，而下拉时发生换行，该bug才会出现。
画廊：https://exhentai.org/g/2440090/0253e523c4/

### EhViewer 版本号 / EhViewer version code

1.8.5.3-rc01

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3972725940

### Android 系统版本 / Android version

OxygenOS 12.1, Android 12

### 设备型号 / Device model

OnePlus 7t

### SoC 型号 / Soc model

Snapdragon 855+

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
https://github.com/material-components/material-components-android/issues/3142

上游问题 等他们修
