### ISSUE TITLE
站内画廊链接跳转失效

### ISSUE THREAD

**Issue by Yuuz12** [Ehviewer-Overhauled/Ehviewer#714]
### 复现步骤 / Step to reproduce

1.进入画廊评论区
2.点击他人发送的站内画廊地址

### 预期行为 / Expected behaviour

点击画廊链接后应该在eh内打开

### 实际行为 / Actual Behaviour

点击画廊链接后跳转浏览器打开

### 备注 / Addition details

经测试，功能失效于 1.8.5.3-alpha04
附效果录屏：

https://user-images.githubusercontent.com/66946066/213884714-5a88c0d0-f539-4574-aa08-7e59e25cb15d.mp4

### EhViewer 版本号 / EhViewer version code

1.8.5.3-rc01

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3975304641

### Android 系统版本 / Android version

OriginOS Ocean, Android 12

### 设备型号 / Device model

IQOO Neo3

### SoC 型号 / Soc model

骁龙 865

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
![Screenshot_20230122-084912](https://user-images.githubusercontent.com/43900799/213895621-0dbd420b-8609-472d-95b7-6985881f0492.png)
请配置 默认打开

**Comment by asuka-mio** [comment]
为保持行为一致性 我们始终向系统发送链接 然后让系统决定它该被哪个应用处理 所以如果你想让ehviewer打开链接 在系统里允许ehviewer打开支持的链接

**Comment by tehcneko** [comment]
我知道的国产系统里没砍这个的只有 MIUI

**Comment by Yuuz12** [comment]
![Screenshot_20230207_070357](https://user-images.githubusercontent.com/66946066/217107611-6d4e6824-551f-4c42-87a6-c2d0c09a751c.jpg)

补充下，我正确设置了默认打开，但问题还是存在。估计就是功能被砍了罢

**Comment by asuka-mio** [comment]
> ![Screenshot_20230207_070357](https://user-images.githubusercontent.com/66946066/217107611-6d4e6824-551f-4c42-87a6-c2d0c09a751c.jpg)
> 
> 补充下，我正确设置了默认打开，但问题还是存在。估计就是功能被砍了罢

支持的链接里全部勾选了吗

**Comment by Yuuz12** [comment]
> > ![Screenshot_20230207_070357](https://user-images.githubusercontent.com/66946066/217107611-6d4e6824-551f-4c42-87a6-c2d0c09a751c.jpg)
> > 补充下，我正确设置了默认打开，但问题还是存在。估计就是功能被砍了罢
> 
> 支持的链接里全部勾选了吗

![Screenshot_20230207_162605](https://user-images.githubusercontent.com/66946066/217191871-4b1db6f6-3f23-4786-aa4f-1b531a9bd59d.jpg)
没有勾选项
