### ISSUE TITLE
请求新增“缓存清理”功能

### ISSUE THREAD

**Issue by Gokou-Ruri** [Ehviewer-Overhauled/Ehviewer#732]
### 需求 / Requirement

因为“下载原图”和“下载分辨率”需要手动切换，有时候在本子里看到一张非常不错的壁纸，但苦于平时默认下载尺寸都是1280（因为配额不够用），低分辨率图片已经缓存到本地了，不能清理缓存的话就没法重新下载原图了。

### 建议实现 / Suggested implements

![Screenshot_20230127-083323-627](https://user-images.githubusercontent.com/26711804/214980904-146ac6fe-a474-4ca3-a71b-f550bdb8a135.png)

### EhViewer 版本号 / EhViewer version code

1.8.5.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3982528720

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by Gokou-Ruri** [comment]
> ![Screenshot_20230127-090634](https://user-images.githubusercontent.com/43900799/214984685-08dc5b8d-9f59-4d7a-8ecd-9be7bb9bd1f4.png)

原来eh内存里的图片数据会实时缓存到闪存里？

**Comment by asuka-mio** [comment]
> > ![Screenshot_20230127-090634](https://user-images.githubusercontent.com/43900799/214984685-08dc5b8d-9f59-4d7a-8ecd-9be7bb9bd1f4.png)
> 
> 原来eh内存里的图片数据会实时缓存到闪存里？

嗯 只有已经下载的画廊和数据库啥的算数据 缓存随便清没事

**Comment by Gokou-Ruri** [comment]
> > > ![Screenshot_20230127-090634](https://user-images.githubusercontent.com/43900799/214984685-08dc5b8d-9f59-4d7a-8ecd-9be7bb9bd1f4.png)
> > 
> > 
> > 原来eh内存里的图片数据会实时缓存到闪存里？
> 
> 嗯 只有已经下载的画廊和数据库啥的算数据 缓存随便清没事

好的！谢谢解惑！
