### ISSUE TITLE
压缩包-H@H下载不起作用

### ISSUE THREAD

**Issue by t0saki** [Ehviewer-Overhauled/Ehviewer#735]
### 复现步骤 / Step to reproduce

0. 重装
1. 点击任意画廊
2. 点击压缩包，选择任意分辨率的H@H下载
3. 下方显示 无法下载压缩包

https://user-images.githubusercontent.com/15712521/215157157-4738b974-a170-4914-af1f-28112f1c03b1.mp4

### 预期行为 / Expected behaviour

下方应该显示 正在下载压缩包
![Screenshot_20230128_014432_EhViewer](https://user-images.githubusercontent.com/15712521/215157466-c99b05d7-d75a-4d7e-a695-7949752ea1a6.jpg)

### 实际行为 / Actual Behaviour

实际上下方显示 无法下载压缩包（录屏在复现步骤）

### 备注 / Addition details

仅在1.8.5.3版本上复现，1.8.5.1版本、ex网页、1.9.4.4的[Ehviewer_CN_SXJ](https://github.com/xiaojieonly/Ehviewer_CN_SXJ)均可正常下载

### EhViewer 版本号 / EhViewer version code

1.8.5.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4023474914

### Android 系统版本 / Android version

同时于OneUI 5 Android 13和WSA Android 13上复现

### 设备型号 / Device model

Samsung Galaxy Tab S8, Windows Subsystem

### SoC 型号 / Soc model

Snapdragon 8G1, x86 CPU

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
这是kotlin化的时候把DownloadArchiveListener那个String转成非空的了
要么改那里要么让EhEngine那边不要返回空
不过我今天有事可能修不了，看别人有没有空吧

**Comment by asuka-mio** [comment]
> 这是kotlin化的时候把DownloadArchiveListener那个String转成非空的了 要么改那里要么让EhEngine那边不要返回空 不过我今天有事可能修不了，看别人有没有空吧

我这测试不了 我没H@H 等别人吧（

**Comment by FooIbar** [comment]
> > 这是kotlin化的时候把DownloadArchiveListener那个String转成非空的了 要么改那里要么让EhEngine那边不要返回空 不过我今天有事可能修不了，看别人有没有空吧
> 
> 我这测试不了 我没H@H 等别人吧（

https://github.com/Ehviewer-Overhauled/Ehviewer/blob/581b32e8a2cd7fa7af438aae8a5b529feca25382/app/src/main/java/com/hippo/ehviewer/ui/scene/GalleryDetailScene.kt#L1289 这里要求成功时返回值非空
https://github.com/Ehviewer-Overhauled/Ehviewer/blob/581b32e8a2cd7fa7af438aae8a5b529feca25382/app/src/main/java/com/hippo/ehviewer/client/EhEngine.kt#L759 但这里当下载类型是H@H的时候会在成功时返回空

**Comment by sakuyamaij** [comment]
使用这个功能的目的不是下载到本地，而是下载到自己的h@h客户端上。
网页端使用这个功能后会提示
```
An original resolution download has been queued for client #12345
Downloads should start processing within a couple of minutes.
```

楼主的预期是显示`正在下载压缩包`，其实有些不太对
1. 会让一些用户误会，以为在往手机本地下载
2. 实际h@h客户端那边下载成功后，是创建一个本子标题的文件夹，里面都是散装的图片jpg/png文件，再加一个galleryinfo.txt。也不算是压缩包了

所以预期返回结果最好可以是
```
原始分辨率的下载请求已添加到下载队列，使用客户端 #12345
下载应该会在几分钟内开始。
```
或者其简化信息

**Comment by t0saki** [comment]
> 使用这个功能的目的不是下载到本地，而是下载到自己的h@h客户端上。 网页端使用这个功能后会提示
> 
> ```
> An original resolution download has been queued for client #12345
> Downloads should start processing within a couple of minutes.
> ```
> 
> 楼主的预期是显示`正在下载压缩包`，其实有些不太对
> 
> 1. 会让一些用户误会，以为在往手机本地下载
> 2. 实际h@h客户端那边下载成功后，是创建一个本子标题的文件夹，里面都是散装的图片jpg/png文件，再加一个galleryinfo.txt。也不算是压缩包了
> 
> 所以预期返回结果最好可以是
> 
> ```
> 原始分辨率的下载请求已添加到下载队列，使用客户端 #12345
> 下载应该会在几分钟内开始。
> ```
> 
> 或者其简化信息

是的，之前h@h客户端队列太长了没进行测试，现在测试后发现即使显示`无法下载压缩包`，h@h也在正常进行下载，请求是正常发送的。
