### ISSUE TITLE
Remember search options

### ISSUE THREAD

**Issue by soredake** [Ehviewer-Overhauled/Ehviewer#736]
### 需求 / Requirement

It will be nice if ehviewer can remember my search options so i don't need to set them again after each app launch.

### 建议实现 / Suggested implements

Remember search options.

### EhViewer 版本号 / EhViewer version code

1.8.5.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4031127416

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by FooIbar** [comment]
Wdym remember? Like what?
You can save your searches as quick searches.

**Comment by soredake** [comment]
>Wdym remember? Like what?

I for example set minimum pages to 15, an after restarting app and going to to advanced options it will still be 15.

> You can save your searches as quick searches.

How?

**Comment by FooIbar** [comment]
> > Wdym remember? Like what?
> 
> I for example set minimum pages to 15, an after restarting app and going to to advanced options it will still be 15.
> 
> > You can save your searches as quick searches.
> 
> How?

Simply swipe from right to left, but I guess that's not exactly what you want.

**Comment by soredake** [comment]
> Simply swipe from right to left

Can you show me exactly where it located?

**Comment by FooIbar** [comment]
> > Simply swipe from right to left
> 
> Can you show me exactly where it located?


https://user-images.githubusercontent.com/118464521/215304458-1aad4a95-628c-43e1-8115-107deb24bf6e.mp4

**Comment by soredake** [comment]
@FooIbar thanks, that cover my needs.
