### ISSUE TITLE
历史页面闪屏

### ISSUE THREAD

**Issue by FooIbar** [Ehviewer-Overhauled/Ehviewer#740]
### 复现步骤 / Step to reproduce

打开历史页面

### 预期行为 / Expected behaviour

直接显示历史记录，如不存在则显示占位符

### 实际行为 / Actual Behaviour

先显示占位符，稍后显示历史记录

### 备注 / Addition details

另外占位符那个文本一点边距都没有，中文字少没区别，换其他语言就很明显

### EhViewer 版本号 / EhViewer version code

1.8.5.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4041414877

### Android 系统版本 / Android version

PixelExperience 11

### 设备型号 / Device model

Moto Z2 Play

### SoC 型号 / Soc model

Snapdragon 626

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
dex2oat一遍试试？
compose 挺吃 art编译的 不优化直接解释确实卡

**Comment by asuka-mio** [comment]
打算先revert回去 compose 确实缺点东西 我应该先把详情界面compose 了

**Comment by asuka-mio** [comment]
Will reland it after https://issuetracker.google.com/issues/150812265 resolved
