### ISSUE TITLE
画廊评论编辑器增强

### ISSUE THREAD

**Issue by wordlesswind** [Ehviewer-Overhauled/Ehviewer#741]
### 需求 / Requirement

[画廊评论](https://ehwiki.org/wiki/Gallery_Commenting)支持使用“粗体、下划线、删除线和斜体”以及“论坛的和画廊的链接”的 BBCode 代码。
希望 EhViewer 的画廊评论编辑器能够支持简易输入且可视化上述代码。

### 建议实现 / Suggested implements

希望能够实现类似于 Telegram 的或者其他更好的行为：

EhViewer
![EhViewer-Comment](https://user-images.githubusercontent.com/9050713/215544262-559561da-80b3-4d1f-a074-e63c735a506f.png)

Telegram
![Telegram-Comment](https://user-images.githubusercontent.com/9050713/215544282-58738b94-829c-48c2-b418-88971d12985f.png)

### EhViewer 版本号 / EhViewer version code

1.8.5.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/3982528720

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by tehcneko** [comment]
这 bbcode 有示例吗

**Comment by wordlesswind** [comment]
> 这 bbcode 有示例吗

应该是通用的 [BBCode](https://en.wikipedia.org/wiki/BBCode)

```
[b]粗体[/b]
[i]斜体[/i]
[u]下划线[/u]
[s]删除线[/s]
[url=https://example.com/]Example Domain[/url]
```

考虑到部分人能在评论里张贴上传至 E-Hentai.org 的“表情包”图像，也许 `[img]https://example.com/image.png[/img]` 也是可用的，但可能仅限青铜及以上等级的捐献者（可创建私人画廊）可用，未做测试。

**Comment by FooIbar** [comment]
[img]只能用用e站上的缩略图，所以基本上是需要一个私人画廊的

**Comment by tehcneko** [comment]
> [img]只能用用e站上的缩略图，所以基本上是需要一个私人画廊的

上传但是不发布就行
