### ISSUE TITLE
Migrate image downloading to libcurl

### ISSUE THREAD

**Issue by asuka-mio** [Ehviewer-Overhauled/Ehviewer#744]
Okhttp responsebody is always a BufferedSource, okio assume we will operate it on JVM.
But fact is that we never process raw images data on JVM, what we do is just save them to real file, and deliver it to skia decoder engine later.
What about try to avoid copying data from socket to JVM bytearrays, and write these bytearrays to file (this is currently what okhttp does, but very stupid if we don't need operate response body on JVM),
Instead we directly save the socket data to file with Linux method?

**Comment by asuka-mio** [comment]
@FooIbar @tehcneko 
Any idea about this zero-copy implementation?

**Comment by asuka-mio** [comment]
This zero-copy can never be achieved since Android's TLS provider, conscrypt, its SSLSocket is not backed by an real file descriptor, it's just an inputstream delegate by conscrypt engine, decryption always need JVM to participate unless we enable clear text transmission.

**Comment by tehcneko** [comment]
内 置 c u r l

**Comment by asuka-mio** [comment]
> 内 置 c u r l

到可以考虑给curl写个jni wrapper 不过感觉代价还是太大了 我再看

**Comment by tehcneko** [comment]
> > 内 置 c u r l
> 
> 到可以考虑给curl写个jni wrapper 不过感觉代价还是太大了 我再看

不如直接把 Spider 挪到 native(x
https://github.com/vvb2060/curl-android

**Comment by asuka-mio** [comment]
> > > 内 置 c u r l
> > 
> > 
> > 到可以考虑给curl写个jni wrapper 不过感觉代价还是太大了 我再看
> 
> 不如直接把 Spider 挪到 native(x https://github.com/vvb2060/curl-android

确实 不过我还是不希望apk体积膨胀太多 先放roadmap里吧（）

**Comment by asuka-mio** [comment]
https://github.com/google/conscrypt/blob/ca6485b689219323e91d3bbe0410715b5b2d687f/common/src/main/java/org/conscrypt/AbstractConscryptSocket.java#L293

如果conscrypt实现了SSLSocket的SocketChannel的话 效率应该也和curl差不多
conscrypt从原始socket读也是直接读进directbuffer, 然后jni调用native decrypt
如果实现了socketchannel的话， 我们直接通过FileChannel transferFrom 这个socketchannel 那就相当于直接从原始socket读取出来的directbuffet 直接解码到 文件映射的MappedByteBuffer了 过程里也没有JVM堆分配

**Comment by asuka-mio** [comment]
额外成本应该也就是几个jni调用

**Comment by asuka-mio** [comment]
https://github.com/google/conscrypt/issues/1111

**Comment by FooIbar** [comment]
这个有到性能瓶颈的程度吗？
考虑到阅读速度，正常浏览的时候进行下载的频率其实是比较低的，只有在用下载功能短时间内大量下载的时候有可能有性能问题
而ehv这种爬虫式的下载方式本来也不适合短时间内大量下载，容易触发ip ban

**Comment by asuka-mio** [comment]
> 这个有到性能瓶颈的程度吗？ 考虑到阅读速度，正常浏览的时候进行下载的频率其实是比较低的，只有在用下载功能短时间内大量下载的时候有可能有性能问题 而ehv这种爬虫式的下载方式本来也不适合短时间内大量下载，容易触发ip ban

那到没有 不过我还是能优化尽量优化 所以我更倾向于让conscrypt适配而不是迁移到curl, 后者带来的改动太大了

**Comment by asuka-mio** [comment]
ktor的实现应该已经是可以的了，虽然不是直接从rawsocket向filechannel解码，不过用的是directbuffer池当缓冲
