### ISSUE TITLE
画廊类型 Private 无法在夜间模式正常显示

### ISSUE THREAD

**Issue by Krosec** [Ehviewer-Overhauled/Ehviewer#756]
### 复现步骤 / Step to reproduce

将 app 深色主题和纯黑深色主题勾选，打开任意一个私人画廊。

### 预期行为 / Expected behaviour

画廊界面中，应该能正常显示类型 Private 

### 实际行为 / Actual Behaviour

实际上它与背景色混淆了，无法分辨出类别为 Private 
![Screenshot](https://user-images.githubusercontent.com/107551827/216687613-437d95a7-f28c-47c3-a9b8-7dde11a89474.jpg)

### 备注 / Addition details

可以与 app 的类别 Misc 一样，不使用 ehentai 的类别颜色，换其他颜色避免其与背景色混淆

### EhViewer 版本号 / EhViewer version code

1.8.5.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4080688467

### Android 系统版本 / Android version

OxygenOS 12.1, Android 12

### 设备型号 / Device model

OnePlus 7t

### SoC 型号 / Soc model

Snapdragon 855+

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
我想 如果不指定文本颜色 使用m3默认的文本颜色 你们会介意吗（

**Comment by Krosec** [comment]
@asuka-mio 每次打开app，从收藏或者历史界面而不是通过链接进入私人画廊，Private 仍然会与背景色相混淆。

**Comment by FooIbar** [comment]
不如直接把那两个chip的背景色改成和上面的card一样好了
效果大概这样
![756](https://user-images.githubusercontent.com/118464521/216772585-83cf0b6d-a405-4203-9364-1d760f62cab8.png)
