### ISSUE TITLE
日文标题显示异常，重复进入才正常显示日文

### ISSUE THREAD

**Issue by KiWinger** [Ehviewer-Overhauled/Ehviewer#767]
### 复现步骤 / Step to reproduce

0.安装应用，cookie登录
1.刷新页面，直接点击进入详情页
2.问题出现，退出详情页
3.再次进入详情页，显示为日文标题
4.再次重复进入有极小概率显示英文标题

### 预期行为 / Expected behaviour

应该第一次进入就显示日文标题，且后续不会返回英文标题

### 实际行为 / Actual Behaviour

第一次进入详情页必为英文标题
![IMG_20230206_161801](https://user-images.githubusercontent.com/49084827/216926701-f6eef9fe-420a-4f2c-89e3-b5edf48eb060.jpg)

### 备注 / Addition details

未开代理，可直连，NekoInverter版本显示正常
![Screenshot_20230206_160911](https://user-images.githubusercontent.com/49084827/216923912-92309a9b-c22e-4668-a840-7c800113ddd6.jpg)

### EhViewer 版本号 / EhViewer version code

1.8.5.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4096924232

### Android 系统版本 / Android version

OriginOS1.0/安卓11

### 设备型号 / Device model

IQOO Neo5

### SoC 型号 / Soc model

骁龙870

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
画廊列表显示的是英文标题还是日文标题？

**Comment by KiWinger** [comment]
okay，确实没开
