### ISSUE TITLE
没有触发自动补齐标签

### ISSUE THREAD

**Issue by KiWinger** [Ehviewer-Overhauled/Ehviewer#768]
### 复现步骤 / Step to reproduce

0.安装应用，cookie登录
1.刷新页面，直接点击进入搜索页
2.键入关键词
3.问题出现

### 预期行为 / Expected behaviour

应该出现备选标签下拉框

### 实际行为 / Actual Behaviour

没有触发自动补齐
![IMG_20230206_160943](https://user-images.githubusercontent.com/49084827/216929767-a6132dde-8f81-461a-ba67-5a8648bb319d.jpg)

### 备注 / Addition details

未开代理，可直连，NekoInverter版本显示正常
历史搜索记录正常显示，但是自动补齐未显示

### EhViewer 版本号 / EhViewer version code

1.8.5.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4096924232

### Android 系统版本 / Android version

OriginOS1.0/安卓11

### 设备型号 / Device model

IQOO Neo5

### SoC 型号 / Soc model

骁龙870

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
这跟#766 是一样的，是标签数据库没准备好
可以去data目录下的files/tag-translations看看有没有文件

**Comment by KiWinger** [comment]
> 这跟#766 是一样的，是标签数据库没准备好 可以去data目录下的files/tag-translations看看有没有文件 如果不知道怎么看就把日志传上来

"files/tag-translations"没有这个文件夹，仅有crash\download\parse_error三个文件夹
日志如下：
[log-2023-02-06-22-11-38-240.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10663903/log-2023-02-06-22-11-38-240.zip)

**Comment by FooIbar** [comment]
> > 这跟#766 是一样的，是标签数据库没准备好 可以去data目录下的files/tag-translations看看有没有文件 如果不知道怎么看就把日志传上来
> 
> "files/tag-translations"没有这个文件夹，仅有crash\download\parse_error三个文件夹 测试 #60 的raw hosts是可以直连的 日志如下： [log-2023-02-06-22-11-38-240.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10663903/log-2023-02-06-22-11-38-240.zip)

我说的是/data/data不是Android/data

**Comment by KiWinger** [comment]
> > > 这跟#766 是一样的，是标签数据库没准备好 可以去data目录下的files/tag-translations看看有没有文件 如果不知道怎么看就把日志传上来
> > 
> > 
> > "files/tag-translations"没有这个文件夹，仅有crash\download\parse_error三个文件夹 测试 #60 的raw hosts是可以直连的 日志如下： [log-2023-02-06-22-11-38-240.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10663903/log-2023-02-06-22-11-38-240.zip)
> 
> 我说的是/data/data不是Android/data

如果你说的是系统文件夹根目录system下的data，那么没有权限
如果是/storage/emulated/0/下的data，那么此data文件夹内也没有对应的“files/tag-translations”文件夹

**Comment by FooIbar** [comment]
标签数据是存在根目录的data下的，没权限就算了吧

你这日志里看不到有关的异常，要么是
1.标签数据下载、解析成功了
要么是
2.日志被清掉了，强行停止ehv重开再导出试试

**Comment by KiWinger** [comment]
> 标签数据是存在根目录的data下的，没权限就算了吧
> 
> 你这日志里看不到有关的异常，要么是 1.标签数据下载、解析成功了 要么是 2.日志被清掉了，强行停止ehv重开再导出试试

[logcat-2023-02-06-23-12-12-881.txt](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10664462/logcat-2023-02-06-23-12-12-881.txt)

**Comment by HSINNX** [comment]
> > 标签数据是存在根目录的data下的，没权限就算了吧
> > 你这日志里看不到有关的异常，要么是 1.标签数据下载、解析成功了 要么是 2.日志被清掉了，强行停止ehv重开再导出试试
> 
> [logcat-2023-02-06-23-12-12-881.txt](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10664462/logcat-2023-02-06-23-12-12-881.txt)

测试了需要先开代理下载标签

**Comment by KiWinger** [comment]
> 所以是为啥

https://github.com/Ehviewer-Overhauled/Ehviewer/issues/768#issuecomment-1419403989
需开代理下载数据包，开代理挂机一次后恢复了。

另就是如果能有个检测翻译包是否下载的地方就好了，
或者额外添加一个手动/自动点击下载/更新，附个下载进度/上次更新时间什么的。

**Comment by FooIbar** [comment]
> > 所以是为啥
> 
> [#768 (comment)](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/768#issuecomment-1419403989) 需开代理下载数据包，开代理挂机一次后恢复了。
> 
> 另就是如果能有个检测翻译包是否下载的地方就好了， 或者额外添加一个手动/自动点击下载/更新，附个下载进度/上次更新时间什么的。

你不是说能连上内置hosts里raw的ip吗
按理说连不上应该会报错啊

更新的话每次重启应用就会更新

**Comment by KiWinger** [comment]
> > > 所以是为啥
> > 
> > 
> > [#768 (comment)](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/768#issuecomment-1419403989) 需开代理下载数据包，开代理挂机一次后恢复了。
> > 另就是如果能有个检测翻译包是否下载的地方就好了， 或者额外添加一个手动/自动点击下载/更新，附个下载进度/上次更新时间什么的。
> 
> 你不是说能连上内置hosts里raw的ip吗 按理说连不上应该会报错啊
> 
> 更新的话每次重启应用就会更新

确实 #60 的raw ip浏览器可以直接打开
但是下载状态就不得而知了，也许下载的慢，也许···

如果有个连接性检测弹窗/按钮，就很简单知道了
或是添加一个手动更新按钮：
————————————————————
**手动更新补充翻译　　　　　更新完成/失败**
上次更新时间2023.2.9/12:10
————————————————————
