### ISSUE TITLE
“启动时请求新闻页面”功能失效

### ISSUE THREAD

**Issue by VVaraiotoko** [Ehviewer-Overhauled/Ehviewer#770]
### 复现步骤 / Step to reproduce

1、打开“启动时请求新闻页面”
2、UTC+8后首次打开应用
3、等待新闻页奖励通知出现

### 预期行为 / Expected behaviour

它应该出现奖励通知

### 实际行为 / Actual Behaviour

实际上没有触发奖励通知
![Screenshot_20230207-093125](https://user-images.githubusercontent.com/28192782/217126678-1662a88e-1717-4d76-823b-fa79b8e8fc66.png)
![Screenshot_20230207-093148](https://user-images.githubusercontent.com/28192782/217126705-095fa822-d7fc-44c0-ba6e-314806cf2ba5.png)
![Screenshot_20230207-093215](https://user-images.githubusercontent.com/28192782/217126711-9b7820ff-a2ad-4b2d-a0f4-8ce9f8624254.png)

### 备注 / Addition details

HV中遭遇怪物的通知也不会出现
[log-2023-02-07-09-32-55-933.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10670815/log-2023-02-07-09-32-55-933.zip)

### EhViewer 版本号 / EhViewer version code

1.8.5.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4105096504

### Android 系统版本 / Android version

Android 12, Stock ROM 58.2.A.7.93

### 设备型号 / Device model

Sony Xperia 1 II 

### SoC 型号 / Soc model

骁龙865

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
我刚看到你这个issue打开app就看到新闻页面弹出来了。。。

**Comment by VVaraiotoko** [comment]
> 我刚看到你这个issue打开app就看到新闻页面弹出来了。。。

然而你看我截图的时间，它就是不弹出来😂

**Comment by yinzhefuyun** [comment]
建议每次启动app的时候本地先校验一次UTC+0时区0点至今的24小时内是否签到过

**Comment by VVaraiotoko** [comment]
> https://github.com/FooIbar/Ehviewer/actions/runs/4124544230/jobs/7123926605 你那两个日志里都没有异常啊，试试这个

我下载了你的最新CI（https://github.com/FooIbar/Ehviewer/actions/runs/4126206240），打开就能弹出奖励通知😂
![Screenshot_20230209-105328](https://user-images.githubusercontent.com/28192782/217706103-7b40ade4-96eb-46fb-94df-4bfa25c62ba2.png)
[log-2023-02-09-10-56-36-466.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10693091/log-2023-02-09-10-56-36-466.zip)

**Comment by xb2016** [comment]
都不用看了 盲猜根本没退出APP 只滑到了后台

**Comment by yinzhefuyun** [comment]
> 都不用看了 盲猜根本没退出APP 只滑到了后台

那看来真的只能上定时器UTC+0时触发（菠萝：什么DDOS攻击）

**Comment by VVaraiotoko** [comment]
> 都不用看了 盲猜根本没退出APP 只滑到了后台

首先我习惯性清空不使用的近期应用，其次我是跟着CI版更新的，更新应用总会强制退出了吧？
![Screenshot_20230209-115524](https://user-images.githubusercontent.com/28192782/217714041-a2c54a7e-cea0-4870-a151-8e8a62f26410.png)

**Comment by yinzhefuyun** [comment]
1.8.7.0-a1你们签到能成功吗？我一个手机设置8点整，一个手机设置8点01分，都没签到成功，或者获取到随机暴乱

**Comment by FooIbar** [comment]
https://issuetracker.google.com/issues/113676489
国产手机好像是重灾区，得引导用户关闭电池优化吧

**Comment by FooIbar** [comment]
https://issuetracker.google.com/issues/110745313
而且有的系统会在从最近使用中删除的时候强行停止应用

**Comment by asuka-mio** [comment]
> https://issuetracker.google.com/issues/110745313 而且有的系统会在从最近使用中删除的时候强行停止应用

这我帮不上忙 到时候单开个discussion 讨论得了
app内引导直接指向discussion

**Comment by FooIbar** [comment]
> > https://issuetracker.google.com/issues/110745313 而且有的系统会在从最近使用中删除的时候强行停止应用
> 
> 这我帮不上忙 到时候单开个discussion 讨论得了 app内引导直接指向discussion

![Screenshot_20230223-174920_Tachiyomi~2 1](https://user-images.githubusercontent.com/118464521/220873598-4bc3a2d6-524c-4109-bbd7-cda38e04a748.png)
直接抄Tachiyomi吧
