### ISSUE TITLE
未完成下载的图片被标记为已完成

### ISSUE THREAD

**Issue by FooIbar** [Ehviewer-Overhauled/Ehviewer#783]
### 复现步骤 / Step to reproduce

无法稳定复现

### 预期行为 / Expected behaviour

/

### 实际行为 / Actual Behaviour

```
android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error.
	at android.graphics.ImageDecoder.nCreate(Native Method)
	at android.graphics.ImageDecoder.access$200(ImageDecoder.java:173)
	at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:250)
	at android.graphics.ImageDecoder.decodeDrawableImpl(ImageDecoder.java:1758)
	at android.graphics.ImageDecoder.decodeDrawable(ImageDecoder.java:1751)
	at com.hippo.image.Image.<init>(Image.kt:35)
	at com.hippo.image.Image.<init>(Unknown Source:0)
	at com.hippo.image.Image$Companion.decode(Image.kt:99)
	at com.hippo.image.Image.decode(Unknown Source:2)
	at com.hippo.ehviewer.spider.SpiderQueen$SpiderDecoder.run(SpiderQueen.java:868)
	at java.lang.Thread.run(Thread.java:923)
	at com.hippo.yorozuya.thread.PriorityThread.run(PriorityThread.java:38)
```

### EhViewer 版本号 / EhViewer version code

1.8.5.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4126369764

### Android 系统版本 / Android version

PixelExperience 11

### 设备型号 / Device model

Moto Z2 Play

### SoC 型号 / Soc model

Snapdragon 626

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
这个一般是图片尺寸太大了 所以得downsampling

**Comment by yinzhefuyun** [comment]
> 这个一般是图片尺寸太大了 所以得downsampling

其实开hath后可以开启
原始图像
当可用的时候，使用原始图像代替压缩过的版本？

**Comment by FooIbar** [comment]
> > 这个一般是图片尺寸太大了 所以得downsampling
> 
> 其实开hath后可以开启 原始图像 当可用的时候，使用原始图像代替压缩过的版本？

下载原图不是有个选项吗，不需要hath perk
而且这里本来就已经过大了你还整原图

**Comment by REXUEDE9** [comment]
> 这个一般是图片尺寸太大了 所以得缩减采样

即使下载调整到780X，阅读缓存调整到1280也没什么用，同样的图片sxj版和xb2016版没有解码失败的情况，这完全是这个app的问题

**Comment by FooIbar** [comment]
> 这个一般是图片尺寸太大了 所以得downsampling

这个实际上应该是下载失败了，今天又遇到一例，发现文件是0B

**Comment by REXUEDE9** [comment]
什么是downsampling，我尝试在下载里降低图片分辨率到780x，同时扩大或缩小下载线程和预载图片，扩大阅读缓存到1280MB，且反复删除下载，刷新画廊，重新下载，仍然会出现这个问题，直到我尝试挂vpn这个问题才有概率缓解，我个人怀疑可能与网络有关，但没什么测试方法来证明。
备注：sxj和xb2016版本下载失败或者图片撕裂可以通过刷新重新下载有问题的图片，彩e解码失败后会无限卡刷新


&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ehviewer-Overhauled/Ehviewer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月18日(星期六) 晚上11:39
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ehviewer-Overhauled/Ehviewer] 随机图片解码失败 (Issue #783)





  
这个一般是图片尺寸太大了 所以得downsampling
  
这个实际上应该是下载失败了，今天又遇到一例，发现文件是0B
