### ISSUE TITLE
同一画廊无法在下载的同时阅读

### ISSUE THREAD

**Issue by FooIbar** [Ehviewer-Overhauled/Ehviewer#791]
### 复现步骤 / Step to reproduce

1. 下载某一画廊
2. 点击阅读

### 预期行为 / Expected behaviour

可以阅读已下载的部分

### 实际行为 / Actual Behaviour

无限加载

### 备注 / Addition details

另外阅读会重置下载页显示的下载进度

### EhViewer 版本号 / EhViewer version code

1.8.5.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4143520017

### Android 系统版本 / Android version

PixelExperience 11

### 设备型号 / Device model

Moto Z2 Play

### SoC 型号 / Soc model

Snapdragon 626

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
哎呦 才发现
这个得等我把解码器作用域也协程化 两个拼一起然后直接join fetcher对应的job

**Comment by asuka-mio** [comment]
Should be fixed now?

**Comment by FooIbar** [comment]
> Should be fixed now?

好像还有问题啊，会先解码再下载
```
libjpeg error 105 <  Ss=0, Se=63, Ah=0, Al=0> from Incomplete image data
android.graphics.ImageDecoder$DecodeException: Input was incomplete.
Start download image 18
Download image succeed 18
```
这里下载完成了，但没有进行解码，导致下面又重新下了一遍
```
Start download image 18
Download image succeed 18
```

**Comment by asuka-mio** [comment]
> > Should be fixed now?
> 
> 好像还有问题啊，会先解码再下载
> 
> ```
> libjpeg error 105 <  Ss=0, Se=63, Ah=0, Al=0> from Incomplete image data
> android.graphics.ImageDecoder$DecodeException: Input was incomplete.
> Start download image 18
> Download image succeed 18
> ```
> 
> 这里下载完成了，但没有进行解码，导致下面又重新下了一遍
> 
> ```
> Start download image 18
> Download image succeed 18
> ```

这回应该好了
