### ISSUE TITLE
在首頁、訂閱或熱門（頁面下），點擊進入快速搜尋後，無法直接返回該頁面

### ISSUE THREAD

**Issue by ximellon** [Ehviewer-Overhauled/Ehviewer#794]
### 复现步骤 / Step to reproduce

1. 從左側導覽進入任一基礎主畫面（再次返回即離開）：首頁、訂閱或熱門。
2. 點擊進入任一快速搜尋。
3. 點擊原先進入之畫面（例如：訂閱→任一快速搜尋→訂閱）

### 预期行为 / Expected behaviour

舊版（極舊之 1.7 ）行為如下：
從問題所述三頁面點擊快速搜尋跳轉後，高亮即清除，意即離開該頁面。此時欲返回原頁面或前往其他兩個頁面時，只需直接點擊便能正確跳轉。

### 实际行为 / Actual Behaviour

新版欲返回原頁面（例如：一開始進入訂閱，點擊快速搜尋後，想再次回到訂閱）時，應會發現該頁面仍被選取而高亮著，此時點擊並不觸發頁面轉移，變成需要透過點擊非高亮之項目（以前例訂閱為例，可點擊首頁或熱門任一頁面），正常觸發跳轉後，才能再次點擊回原頁面。

### EhViewer 版本号 / EhViewer version code

1.8.3.5

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4152456263

### Android 系统版本 / Android version

One UI 3.1/Android 11

### 设备型号 / Device model

Galaxy Tab A 8.0 with S Pen (SM-P200)

### SoC 型号 / Soc model

Exynos 7904

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by ximellon** [comment]
剛才試過 1.8.5.2 ，確定是好的。

**Comment by yinzhefuyun** [comment]
> 剛才試過 1.8.5.2 ，確定是好的。

那你不关闭 issue ？

**Comment by FooIbar** [comment]
这不止是快速搜索的问题，普通搜索也一样
