### ISSUE TITLE
搜索行为无法统一

### ISSUE THREAD

**Issue by xiaozixun** [Ehviewer-Overhauled/Ehviewer#807]
### 复现步骤 / Step to reproduce

1.在搜索栏输入关键字进行搜索；
2.点击“+”进行进一步的类别区分搜索；
3.区分搜索不会成功，上述两步只会出现相应搜索方式的搜索结果。
4.即使把1与2步骤交换前后结果亦如3一般。

### 预期行为 / Expected behaviour

上面的2步骤应该是1步骤的补充，不应该是又一种的搜索行为。

### 实际行为 / Actual Behaviour

实际上1与2步骤就是两种不同的搜索方法

### 备注 / Addition details

这个问题一直有，但因为我没有积极更新，所以不清楚是从什么版本开始的。
同样我是从中途才开始使用本客户端，所以不知道这是个bug还是特意如此的，只是之前使用过其他版本的客户端不会有这种情况，所以还是选择报bug。
例子：1.搜索栏搜索“Chinese”；2.点击“+”只选择“misc”标签；3.结果应该是同时具有Chinese和misc条件的画廊，但现在只会出现最后一次设置搜索条件的结果，而不是同时满足两次的搜索设置。

### EhViewer 版本号 / EhViewer version code
1.8.6.0

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/download/1.8.6.0-alpha04/EhViewer-arm64-v8a.apk

### Android 系统版本 / Android version

Harmony OS 3.0.0

### 设备型号 / Device model

HUAWEI Mate 40 Pro

### SoC 型号 / Soc model

Kirin 9000

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
什么意思？你的意思是2应该在结果中搜索？

**Comment by skymkmk** [comment]
> 区分搜索不会成功，上述两步只会出现相应搜索方式的搜索结果

这里姑且认为区分搜索是高级搜索，那使用高级搜索出来的结果和普通搜索不一样，这不是预期行为吗？什么叫做区分搜索不会成功

或许可以提供复现步骤，以便理解你的意思。这几个不同的分支版本在这一点上的表现应当是一样的。

**Comment by txyyh** [comment]
自行更新版本并填补版本号
之后再open

**Comment by xiaozixun** [comment]
> 自行更新版本并填补版本号 之后再open

已经改了

**Comment by Pony-CW** [comment]
我自己试了试，其实就是说如果不点+再点搜索的话，+里面的选项不会生效

**Comment by skymkmk** [comment]
> 我自己试了试，其实就是说如果不点+再点搜索的话，+里面的选项不会生效@FooIbar

设计如此，本来 + 号里边就是高级搜索，和 e 站的高级搜索逻辑对应。如果你想持久化屏蔽某些分类，你应该在网站设置屏蔽某些分类。哪个分支版本的逻辑都是这样的，没有区别。

**Comment by xiaozixun** [comment]
> > 我自己试了试，其实就是说如果不点+再点搜索的话，+里面的选项不会生效@FooIbar
> 
> 设计如此，本来 + 号里边就是高级搜索，和 e 站的高级搜索逻辑对应。如果你想持久化屏蔽某些分类，你应该在网站设置屏蔽某些分类。哪个分支版本的逻辑都是这样的，没有区别。

那只是个例子，用来说明的。
还是个例子：1.搜索“Chinese Linda”；2.点击+设置“仅显示被删除画廊”3.一片空白。4.如果把1的条件改成Chinese再进行2的话一直往前找的话会看到Linda的画廊。
又一个例子：1.搜索artist:"abe inori$"2.点击+设置“仅显示被删除画廊”3.（此时应该是abe inori的被删画廊，这位作者也有被删作品的）实际上却是全部被删画廊。

**Comment by skymkmk** [comment]
> > > 我自己试了试，其实就是说如果不点+再点搜索的话，+里面的选项不会生效@FooIbar
> > 
> > 
> > 设计如此，本来 + 号里边就是高级搜索，和 e 站的高级搜索逻辑对应。如果你想持久化屏蔽某些分类，你应该在网站设置屏蔽某些分类。哪个分支版本的逻辑都是这样的，没有区别。
> 
> 那只是个例子，用来说明的。 还是个例子：1.搜索“Chinese Linda”；2.点击+设置“仅显示被删除画廊”3.一片空白。4.如果把1的条件改成Chinese再进行2的话一直往前找的话会看到Linda的画廊。

1. 搜索 Chinese Linda 是搜索标题，既然标题里没有这些关键词，那当然就搜不到了。
2. 关于你编辑前的第二个例子，artist 和 uploader 是有区别的，不知道你是否在这方面的理解上有问题

总之，如果你觉得搜索结果不对，你可以先考虑去网站用同样条件去搜索，如果网站的搜索和 EhV 一致，那说明不是 EhV 的问题。你举的例子经测试，网站表现和 EhV 完全一致，无法证明这是 EhV 的问题。

**Comment by xiaozixun** [comment]
> > > > 我自己试了试，其实就是说如果不点+再点搜索的话，+里面的选项不会生效@FooIbar
> > > 
> > > 
> > > 设计如此，本来 + 号里边就是高级搜索，和 e 站的高级搜索逻辑对应。如果你想持久化屏蔽某些分类，你应该在网站设置屏蔽某些分类。哪个分支版本的逻辑都是这样的，没有区别。
> > 
> > 
> > 那只是个例子，用来说明的。 还是个例子：1.搜索“Chinese Linda”；2.点击+设置“仅显示被删除画廊”3.一片空白。4.如果把1的条件改成Chinese再进行2的话一直往前找的话会看到Linda的画廊。
> 
>     1. 搜索 Chinese Linda，若所有剔除的画廊里元信息都没有这些关键词，那当然就搜不到了。
> 
>     2. 关于你编辑前的第二个例子，artist 和 uploader 是有区别的，不知道你是否在这方面的理解上有问题
> 
> 
> 总之，如果你觉得搜索结果不对，你可以先考虑去网站用同样条件去搜索，如果网站的搜索和 EhV 一致，那说明不是 EhV 的问题。你举的例子经测试，网站表现和 EhV 完全一致，无法证明这是 EhV 的问题。

g/2452763/284ab16686/ ，这本有信息，但也搜不到。
我的梯子访问网页版就被ban了，所以无法论证。
第二个例子是因为我不能百分百触发，所以删了。

**Comment by FooIbar** [comment]
@txyyh ~~其实没必要重开~~
linda是[DNP](https://forums.e-hentai.org/index.php?showtopic=19797)，搜不到和ehv无关

**Comment by txyyh** [comment]
@asuka-mio 确实如此的话你close下
