### ISSUE TITLE
写画廊评论时，选择全部不生效

### ISSUE THREAD

**Issue by Krosec** [Ehviewer-Overhauled/Ehviewer#808]
### 复现步骤 / Step to reproduce

1. 在任一画廊写上一串文字
2. 选择部分文字
3. 在更多选项中按下 选择全部

### 预期行为 / Expected behaviour

它应该能选择全部文字

### 实际行为 / Actual Behaviour

实际上它把文字取消选择了

### EhViewer 版本号 / EhViewer version code

1.8.6.0-alpha04

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4171954456

### Android 系统版本 / Android version

OxygenOS 12.1, Android 12

### 设备型号 / Device model

OnePlus 7t

### SoC 型号 / Soc model

Snapdragon 855+

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
其实是默认的操作全无效了，因为这里没有处理
https://github.com/Ehviewer-Overhauled/Ehviewer/blob/63cd60b2379a8ca778363f03816c21a05440dbfb/app/src/main/java/com/hippo/ehviewer/ui/scene/GalleryCommentsScene.kt#L256
