### ISSUE TITLE
将“需要解锁”的条件变更为每次重新加载应用之后

### ISSUE THREAD

**Issue by wordlesswind** [Ehviewer-Overhauled/Ehviewer#81]
### 需求 / Requirement

目前“需要解锁”的条件是在启动阶段进行解锁判定，而基于多方面考虑（例如用户没有清理后台应用程序的习惯），建议将条件变更为每次重新加载应用之后。

### 建议实现 / Suggested implements

将“需要解锁”的条件变更为每次重新加载应用之后

### EhViewer 版本号 / EhViewer version code

1.7.28.0

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/asuka-mio/Ehviewer/actions/runs/2630854617

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/asuka-mio/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/asuka-mio/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/asuka-mio/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/asuka-mio/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by wordlesswind** [comment]
#86

**Comment by wordlesswind** [comment]
https://github.com/asuka-mio/Ehviewer/actions/runs/2650399893
在阅读界面和设置界面下，重载应用不需要解锁即可浏览。

**Comment by asuka-mio** [comment]
> https://github.com/asuka-mio/Ehviewer/actions/runs/2650399893 在阅读界面和设置界面下，重载应用不需要解锁即可浏览。

这个需要解锁的判定是应用进入缓存 所以你可能需要多等那么几秒 不是说直接划出去再点进来就会要你解锁的
不多也就三四秒样子

**Comment by asuka-mio** [comment]
> https://github.com/asuka-mio/Ehviewer/actions/runs/2650399893 在阅读界面和设置界面下，重载应用不需要解锁即可浏览。

哦我知道了 你从最近任务点进去的吧（这个我还没考虑过

**Comment by wordlesswind** [comment]
在未离开 EhViewer 的情况下，在 EhViewer 打开外部链接，前往 Custom Tab 窗口后，返回 EhViewer 本身也会触发“需要解锁”。

**Comment by txyyh** [comment]
> 在未离开 EhViewer 的情况下，在 EhViewer 打开外部链接，前往 Custom Tab 窗口后，返回 EhViewer 本身也会触发“需要解锁”。

Custom Tab 本身就是由外部应用提供，返回后自然会触发“需要解锁”
