### ISSUE TITLE
加载完毕的图片无法显示

### ISSUE THREAD

**Issue by Krosec** [Ehviewer-Overhauled/Ehviewer#814]
### 复现步骤 / Step to reproduce

1. 清理app 缓存
2. 打开[画廊](https://exhentai.org/g/2466327/208a5049dd/)
3. 点击阅读，并拉动进度条至p45-p48
4. 正常浏览每一页图片
5. P49无法显示

### 预期行为 / Expected behaviour

P49 应该显示

### 实际行为 / Actual Behaviour

P49 停留在加载界面，无法正常显示，需要左右划动，返回P49 才能正常显示

### 备注 / Addition details

这个复现需要将阅读方式改为从右往左，从左往右无法复现。除了上述的画廊，平时用从右往左的阅读其他画廊，也会偶尔出现该情况

### EhViewer 版本号 / EhViewer version code

1.8.6.0-alpha04

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4179468306

### Android 系统版本 / Android version

OxygenOS 12.1, Android 12

### 设备型号 / Device model

OnePlus 7t

### SoC 型号 / Soc model

Snapdragon 855+

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
大概知道咋回事了 我重构时候又没考虑rtl
明天修
