### ISSUE TITLE
在打开画廊详情页面时预热PageLoader?

### ISSUE THREAD

**Issue by asuka-mio** [Ehviewer-Overhauled/Ehviewer#818]
很久之前的行为是 进入一个新的详情页面时先把spider* 预热一遍读取阅读进度 这个过程伴随着的是一堆新线程的创建
然后我们把读取阅读进度的操作分离了出来 避免了每打开一个画廊详情就创建一堆线程这种昂贵操作
之后我们把spider* 用协程重写了
不过现在的一个缺憾是因为不会在详情页面预热了，就导致打开阅读器的时候获取元数据的时间延长了一点
等到把最后一个线程创建操作清理掉之后 预热操作的代价应该就显得"微不足道"了

**Comment by FooIbar** [comment]
说到这个我想起来，现在在获取元数据这步失败了的话是不会提示重试的，直接返回了

**Comment by FooIbar** [comment]
GalleryDetailScene 是不是不应该持有 SpiderQueen 的引用，预热应该是一个一次性的行为
目前在详情页删除正在下载的下载项时由于仍持有 SpiderQueen 的引用会导致下载不会停止

**Comment by asuka-mio** [comment]
> GalleryDetailScene 是不是不应该持有 SpiderQueen 的引用，预热应该是一个一次性的行为 目前在详情页删除正在下载的下载项时由于仍持有 SpiderQueen 的引用会导致下载不会停止

嗯 确实
预热仅仅把元数据从网络抓到磁盘缓存就够了 读取磁盘缓存相比网络请求还是可以接受的
