### ISSUE TITLE
排行页面下的右侧时间调整列表因左右滑动而崩溃

### ISSUE THREAD

**Issue by VoidxHoshi** [Ehviewer-Overhauled/Ehviewer#820]
### 复现步骤 / Step to reproduce

1. 点击进入排行视图
2. 点击原快速搜索按钮
3. 滑动列表项，如“昨天”
4. 崩溃

### 预期行为 / Expected behaviour

不应该崩溃

### 实际行为 / Actual Behaviour

发生崩溃

### 备注 / Addition details

猜测因和快速搜索共用逻辑而崩溃
排行调整时间的操作也比较麻烦，希望更显眼一些。

### EhViewer 版本号 / EhViewer version code

1.8.6.0-alpha04

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4179468306

### Android 系统版本 / Android version

MIUI 14, Android 13

### 设备型号 / Device model

Redmi K50 Ultra

### SoC 型号 / Soc model

骁龙 8+ gen 1

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
这个不打算支持滑动 笑死我了
