### ISSUE TITLE
Chrome for Android 打开HentaiVerse 会跳转到app

### ISSUE THREAD

**Issue by Krosec** [Ehviewer-Overhauled/Ehviewer#830]
### 复现步骤 / Step to reproduce

Chrome 打开ehentai 点击hv

### 预期行为 / Expected behaviour

打开hv时，不跳转到app

### 实际行为 / Actual Behaviour

打开hv时，跳转到app，弹出无法解析https://e-hentai.org/bounce_login.php?bt=6&hvreturn=1&encounter=

### 备注 / Addition details

除此之外，将Chrome 设置成默认浏览器，app 弹出怪物遭遇战的信息时，点击后，会先跳转到Chrome 打开hv 然后跳转到app，弹出无法解析https://e-hentai.org/bounce_login.php?bt=6&hvreturn=1&encounter=

### EhViewer 版本号 / EhViewer version code

1.8.6.0

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4203264042

### Android 系统版本 / Android version

OxygenOS 12.1, Android 12

### 设备型号 / Device model

OnePlus 7t

### SoC 型号 / Soc model

Snapdragon 855+

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by duzhaokun123** [comment]
默认打开应用的锅

但应用在处理不能解析的 e站 链接应该尝试在 webview 中打开 毕竟本来就是网页

**Comment by tehcneko** [comment]
无法解决

**Comment by tehcneko** [comment]
预期行为

**Comment by xb2016** [comment]
这个是 Chrome 的问题
点击链接打开的是 hentaiverse.org 的链接，但是如果浏览器的 HV 是未登录状态，会 302 跳转到 https://e-hentai.org/bounce_login.php 尝试登录，正常情况下 302 不应该唤起 APP，但是迷惑的 Chrome 做到了，其他浏览器并没有这种行为

**Comment by tehcneko** [comment]
> 

唤起 App 才是正确的，其他的浏览器实现有问题。尤其是 Via，问题很多

**Comment by xb2016** [comment]
> 唤起 App 才是正确的，其他的浏览器实现有问题。尤其是 Via，问题很多

这样的吗？不过 Via 要唤起应用的时候会有个弹窗让用户选择，这点还是挺好的

**Comment by tehcneko** [comment]
有个 workaround 是 manifest 里 path 改成 e-hentai.org/g/*，但是这样其他的一些链接（搜索结果、排行榜等列表）就没法拉起 App 了

**Comment by asuka-mio** [comment]
已经提供复制选项了 自己粘贴到浏览器打开吧
这里是必定唤起app的
