### ISSUE TITLE
条漫/从上到下阅读模式，双指缩小再连点放大无法拉到底

### ISSUE THREAD

**Issue by Pony-CW** [Ehviewer-Overhauled/Ehviewer#832]
### 复现步骤 / Step to reproduce

1.打开一个画廊并阅读
2.设置条漫/从上到下（连续）
3.任意位置双指缩小（无论何种程度）
4.拉到最低再连点放大至正常（反着来也行），bug出现

https://user-images.githubusercontent.com/44076275/219681421-14664d4e-1852-48f0-a28f-15401b470161.mp4

### 预期行为 / Expected behaviour

应该能往下拉完

### 实际行为 / Actual Behaviour

卡在半路，必须再放大/缩小一下才能拉完

### 备注 / Addition details

tachiyomi预览版r5513也有这bug，顺便连点放大至正常后连触控操作面都会被放大错位

### EhViewer 版本号 / EhViewer version code

1.8.6.0

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4203264042

### Android 系统版本 / Android version

ColorOS 12 PGZ110_11_A.09 / Android 12

### 设备型号 / Device model

一加 Ace 竞速版 / PGZ110

### SoC 型号 / Soc model

天玑 8100-MAX

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
#535

**Comment by Pony-CW** [comment]
> #535

好吧重复了😂没搜下的我的锅
