### ISSUE TITLE
随机图片解码失败

### ISSUE THREAD

**Issue by REXUEDE9** [Ehviewer-Overhauled/Ehviewer#836]
### 复现步骤 / Step to reproduce

无法复现，只要下载90%概率会出现此问题

### 预期行为 / Expected behaviour

正常下载完成，阅读不会出现解码失败。

### 实际行为 / Actual Behaviour

下载经常0b，阅读显示解码失败且刷新无效
![Screenshot_20230218_133551_moe tarsin ehviewer](https://user-images.githubusercontent.com/75521341/219843150-abddcc77-5bbe-4ee4-b4e2-a699f3074b65.jpg)
![Screenshot_20230218_133159_moe tarsin ehviewer](https://user-images.githubusercontent.com/75521341/219843157-ec3b94ec-ec5a-45a9-958d-b669cce7b54a.jpg)
![Screenshot_20230218_132928_moe tarsin ehviewer](https://user-images.githubusercontent.com/75521341/219843159-65b0b69f-c97f-4d70-bc9c-f61290a925b2.jpg)

### 备注 / Addition details

同样的图片sxj和xb2016的版本没有相关问题，希望赶快修复，过于影响使用
![Screenshot_20230218_133240_com xjs ehviewer](https://user-images.githubusercontent.com/75521341/219843204-335ccbc4-060e-4e2e-a9d3-d143c76da5fb.jpg)
![Screenshot_20230218_133317_com xjs ehviewer](https://user-images.githubusercontent.com/75521341/219843217-9dd39b15-2ca1-4b13-9585-432281f01060.jpg)

### EhViewer 版本号 / EhViewer version code

1.8.6.1

### EhViewer CI 版本 / EhViewer CI Version

无

### Android 系统版本 / Android version

harmonyOS 2.0.0.236

### 设备型号 / Device model

华为荣耀30s

### SoC 型号 / Soc model

huawei kirin 820

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
日志

**Comment by REXUEDE9** [comment]
> 日志

[log-2023-02-18-15-29-34-767.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10773609/log-2023-02-18-15-29-34-767.zip)

**Comment by REXUEDE9** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月18日(周六) 下午3:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Ehviewer-Overhauled/Ehviewer] 随机图片解码失败 (Issue #836)




 
日志

**Comment by REXUEDE9** [comment]
> 日志

日志已发送

**Comment by wordlesswind** [comment]
这个问题我也遇到了，会卡最后一张，比如 99/100。

有时候实际上，所有图像是下载完成的，但是仍然显示 99/100，停止并恢复下载即可完成下载。

有时候确确实实是有一张图像未能完成下载，但不知道是不是应用重置了下载模块的原因，99/100 并不意味着是最后一张图像下载失败，
而且随机，我显示的不是解码失败，而是网络错误。
这个时候即便是重启下载也无法完成下载。

在一番测试后，发现在较多图像文件时，或者有多个画廊等待下载时，会较大概率触发这个问题。

**Comment by REXUEDE9** [comment]
> 这个问题我也遇到了，但我的表现形式是会卡一张，比如 99/100。
> 
> 有时候实际上，所有图像是下载完成的，但是仍然显示 99/100，停止并恢复下载即可完成下载。
> 
> 有时候确确实实是有一张图像未能完成下载，但不知道是不是应用重置了下载模块的原因，99/100 并不意味着是最后一张图像下载失败， 而且随机，我显示的不是解码失败，而是网络错误。 这个时候即便是重启下载也无法完成下载。
> 
> 在一番测试后，发现在较多图像文件时，或者有多个画廊等待下载时，会较大概率触发这个问题。

没错，经常99/100然后检查发现是随机图片读不出来，而且无法刷新下载，有些版权资源上架一会就没了，下完卡99%真的很无奈

**Comment by REXUEDE9** [comment]
> 日志

我按照邮件的说法测试，即使我将下载页面分辨率降低到780x并且扩大了图片的预载和下载，同时将阅读缓存提升到最高级别。但是问题依然存在，直到我尝试挂vpn这个问题才有所改善，我怀疑该问题可能与网络有关，请修复这个问题吧，这太影响app的使用了。

**Comment by FooIbar** [comment]
> 这个问题我也遇到了，但我的表现形式是会卡一张，比如 99/100。
> 
> 有时候实际上，所有图像是下载完成的，但是仍然显示 99/100，停止并恢复下载即可完成下载。
> 
> 有时候确确实实是有一张图像未能完成下载，但不知道是不是应用重置了下载模块的原因，99/100 并不意味着是最后一张图像下载失败， 而且随机，我显示的不是解码失败，而是网络错误。 这个时候即便是重启下载也无法完成下载。
> 
> 在一番测试后，发现在较多图像文件时，或者有多个画廊等待下载时，会较大概率触发这个问题。

之前网络错误重试的时候不会换源https://github.com/Ehviewer-Overhauled/Ehviewer/issues/789

**Comment by REXUEDE9** [comment]
> 

下载的单行本基本都会有这个问题，且只有挂梯子就有概率下载完成，能否解决这个bug

**Comment by REXUEDE9** [comment]
> 日志

下载的单行本基本都会有这个问题，且只有挂梯子就有概率下载完成，能否解决这个bug

**Comment by wordlesswind** [comment]
安装最新 CI 版本后问题变成了会提示“配额耗尽”的问题。

![Uploading Screenshot_2023-02-20-15-44-51-24_b783bf344239542886fee7b48fa4b892.jpg…]()

**Comment by FooIbar** [comment]
> 安装最新 CI 版本后问题变成了会提示“配额耗尽”的问题。
> 
> ![Screenshot_2023-02-20-15-44-51-24_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/9050713/220043954-cb72052b-17e8-4877-8e4f-16476e28456b.jpg)

配额耗尽你应该去检查配额啊
日志里也应该能看到509

**Comment by wordlesswind** [comment]
问题是，没耗尽啊，我只是那一个画廊不能下载了，点下载就提示耗尽，换个画廊就可以下载。

**Comment by FooIbar** [comment]
> 问题是，没耗尽啊，我只是那一个画廊不能下载了，点下载过一会就提示耗尽，换个画廊就可以下载。
> 
> 等于卡 0b/s 的问题确实没有了，但仍然没有解决下载的问题。

日志里有没有509

**Comment by REXUEDE9** [comment]
> 问题是，没耗尽啊，我只是那一个画廊不能下载了，点下载过一会就提示耗尽，换个画廊就可以下载。
> 
> 等于卡 0b/s 的问题确实没有了，但仍然没有解决下载的问题。

你看一下设置>EH里有个图片配额，那玩意是不是用光了，可以重置的

**Comment by wordlesswind** [comment]
![Screenshot_2023-02-20-17-47-09-76_f2f1746601bf3b868d00d5efaf12e601](https://user-images.githubusercontent.com/9050713/220071626-96a5793b-4467-4fea-ac14-9c4d357fb29d.jpg)

[log-2023-02-20-17-45-11-854.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10783078/log-2023-02-20-17-45-11-854.zip)

![Screenshot_2023-02-20-17-51-55-71_f2f1746601bf3b868d00d5efaf12e601](https://user-images.githubusercontent.com/9050713/220071950-68881038-da57-445c-8914-517133305039.jpg)

![Screenshot_2023-02-20-17-52-27-80_f2f1746601bf3b868d00d5efaf12e601](https://user-images.githubusercontent.com/9050713/220071969-7695c163-1297-405d-9153-d51d8ee2a6a3.jpg)

都说了我换个画廊就能下载，跟配额没有关系，我就是有张图下不来

**Comment by REXUEDE9** [comment]
> ![Screenshot_2023-02-20-17-47-09-76_f2f1746601bf3b868d00d5efaf12e601](https://user-images.githubusercontent.com/9050713/220071626-96a5793b-4467-4fea-ac14-9c4d357fb29d.jpg)
> 
> [日志-2023-02-20-17-45-11-854.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10783078/log-2023-02-20-17-45-11-854.zip)
> 
> ![Screenshot_2023-02-20-17-51-55-71_f2f1746601bf3b868d00d5efaf12e601](https://user-images.githubusercontent.com/9050713/220071950-68881038-da57-445c-8914-517133305039.jpg)
> 
> ![Screenshot_2023-02-20-17-52-27-80_f2f1746601bf3b868d00d5efaf12e601](https://user-images.githubusercontent.com/9050713/220071969-7695c163-1297-405d-9153-d51d8ee2a6a3.jpg)
> 
> 都说了我换个画廊就能下载，跟配额没有关系，我就是有张图下不来

这问题真没碰见过，建议再下个sxj或者xb2016版本做备用吧

**Comment by FooIbar** [comment]
> [log-2023-02-20-17-45-11-854.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10783078/log-2023-02-20-17-45-11-854.zip)
> 

大概知道了，他509检查的是后缀，刚好这张图的文件名是509

**Comment by wordlesswind** [comment]
0 B/S 问题在 1.8.6.2 还是存在。

**Comment by FooIbar** [comment]
> 0 B/S 问题在 1.8.6.2 还是存在。

当然还在，因为1.8.6.2不包含那个pr

**Comment by FooIbar** [comment]
@asuka-mio 这个应该已经修了，让他有问题再开吧
