### ISSUE TITLE
由于默认绕过 VPN，导致无法通过网页登录帐户

### ISSUE THREAD

**Issue by wordlesswind** [Ehviewer-Overhauled/Ehviewer#841]
### 复现步骤 / Step to reproduce

0. 重置 EhViewer
1. 选择“通过网页登录”

### 预期行为 / Expected behaviour

页面应当正常加载

### 实际行为 / Actual Behaviour

net::ERR_CONNECTION_TIMED_OUT

### 备注 / Addition details

同理，绕过 VPN 后也无法打开 E-Hentai 网页设置。

### EhViewer 版本号 / EhViewer version code

1.8.7.0-alpha01

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4209673302

### Android 系统版本 / Android version

LineageOS 20

### 设备型号 / Device model

Xiaomi MI 8

### SoC 型号 / Soc model

Snapdragon 845

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
登录的是要修一下，因为域前置是默认开的，登录的时候改不了设置
打不开网页设置是预期行为，因为webview不支持域前置，所以要通过VPN访问
