### ISSUE TITLE
移除下载项后重新下载画廊，实际上未能调用重新下载的图像

### ISSUE THREAD

**Issue by wordlesswind** [Ehviewer-Overhauled/Ehviewer#844]
### 复现步骤 / Step to reproduce

0. 重置 EhViewer
1. 下载画廊
2. 移除下载项
3. 重新下载画廊

### 预期行为 / Expected behaviour

它应该完成下载

### 实际行为 / Actual Behaviour

实际上打开画廊后还需要下载

### 备注 / Addition details

[log-2023-02-19-02-30-20-100.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10774930/log-2023-02-19-02-30-20-100.zip)

如果再移除一次，再重新下载，会直接完成下载，并且图像完整。之后重复多少次移除后重新下载，都是直接完成下载，可能是阅读缓存的缘故。

### EhViewer 版本号 / EhViewer version code

1.8.7.0-alpha01

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4209673302

### Android 系统版本 / Android version

LineageOS 20

### 设备型号 / Device model

Xiaomi MI 8

### SoC 型号 / Soc model

Snapdragon 845

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
移除下载项的时候选删除文件了吗

**Comment by wordlesswind** [comment]
> 移除下载项的时候选删除文件了吗

没动，默认开启。

**Comment by FooIbar** [comment]
> > 移除下载项的时候选删除文件了吗
> 
> 没动，默认开启。

如果你是先阅读再下载的话会从阅读缓存里复制，删除下载文件不会删阅读缓存
如果是直接下载的话不会写阅读缓存，删了要重下

**Comment by FooIbar** [comment]
> 不，我遇到的问题是：
> 
> 我直接开始下载，没有事先阅读。 然后我点进去，确认了是已完成下载的，删掉，重新下载。 之后等下载页面中显示已完成后，我再点进去，是没有任何一张是已下载的，它会直接以阅读的方式下载图像。 如果这个时候我退出来（不等它阅读缓存完毕），删掉，再重新下载，会直接完成，并且每一张都在。
> 
> 所以如果我要完成重新下载这个步骤，我现在要重新下载两次，我不知道为什么，很显然第一次重新下载的图像不知道藏哪去了，可能是变成了阅读缓存，而我需要第二次重新下载，才能读取到这阅读缓存。

我没能复现，最新的CI还有这个问题吗

**Comment by wordlesswind** [comment]
[4217140258](https://github.com/FooIbar/Ehviewer/actions/runs/4217140258) 一样复现

https://user-images.githubusercontent.com/9050713/219963250-c4828218-463d-4925-b9d8-715049893120.mp4

我是在画廊详情页点“已下载”按钮删除画廊，再点击“下载”重新下载的。

**Comment by wordlesswind** [comment]
你这个版本出现了新的情况，第一次重新下载，文件“消失”，点进去需要下载，第二次重新下载，直接完成，文件都在，第三次重新下载，顺着第一次重新下载的预读（前六张）继续下载，但是实际上跟第一次重新下载一样，文件“消失”，第四次重新下载，直接完成，文件都在，第五次重新下载，顺着第三次重新下载的预读数量继续下载。

变成了反复的情况，而不是跟之前那样后续的下载都是直接完成。

**Comment by FooIbar** [comment]
我发现在详情页删除下载不会停止下载，笑死

**Comment by FooIbar** [comment]
最新 CI 还有这个问题吗

**Comment by wordlesswind** [comment]
已修复
