### ISSUE TITLE
eh里站不能用cookies登陆

### ISSUE THREAD

**Issue by farawayshore** [Ehviewer-Overhauled/Ehviewer#845]
### 复现步骤 / Step to reproduce

0.重新安装应用
1.进入登陆界面，选择cookies登陆
2.从剪贴板导入
“igneous:d587a8374
ipb_member_id:4948176
ipb_pass_hash:c843c660d8f3facb94a5fbc7cde144c2”(截止上传时间此cookies确定可用)
3.部分时段成功(本人第一次重下及两位朋友测试)，部分时段失败(本人为了测试第二次重下，显示time out cookies可能不正确)
4.(成功情况下)正常使用exhentai
5.在某段时间刷新突然显示sad panda，试图从设置中导出cookies并重新登陆
6.重新进入cookies登陆，从剪切板导入发现igneous的值显示mystery
7.登陆显示Not logged in
8修改igneous一栏为cookies对应值
9.仍显示Not logged in

### 预期行为 / Expected behaviour

它应该在点击从剪贴板导入后显示加载栏，并在较短时间内登陆成功，跳转到选择画廊界面，选择exhentai后可正常使用

### 实际行为 / Actual Behaviour

实际上它显示Not logged in
![Screenshot_2023-02-19-13-53-08-654_moe tarsin ehviewer](https://user-images.githubusercontent.com/53212436/219932185-7ae486b0-0a71-4f96-be41-6fbcfd2dae69.jpg)
或time out
![Screenshot_2023-02-19-13-56-45-131_moe tarsin ehviewer](https://user-images.githubusercontent.com/53212436/219932420-f6d4e35c-7b40-43c1-bc5f-81817544196d.jpg)

### 备注 / Addition details

实际上本问题在隔壁xiaojieonly版本中已被解决，看起来是因为旧绿E在登陆页面时默认访问的是e-hentai，而其后e站登陆方式有更新，表站不支持里站的cookies形式了，因而igneous一栏直接显示mystery。解决方案好像是直接加一个应用在全局的exhentai host就可以。
[这里是隔壁的issue界面](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/150) 

### EhViewer 版本号 / EhViewer version code

1.8.6.1

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.8.6.1

### Android 系统版本 / Android version

MIUI 13.0.7

### 设备型号 / Device model

Redmi K40

### SoC 型号 / Soc model

snapdragon 870

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by farawayshore** [comment]
呃，第二次的timeout可能是个人问题，刚刚发现没开host，开了之后又变成network error了。但是Not logged in是确实多次实验都存在的

**Comment by farawayshore** [comment]
确认了，就是个人问题，第一次没开host，第二次没开SNI，开完之后就变Not logged in了

**Comment by asuka-mio** [comment]
不是。。你确定你cookies就直接扔这了？谁都能看见的

**Comment by FooIbar** [comment]
Not logged in就是登不上，你用网页试试

**Comment by farawayshore** [comment]
以上这两条我觉得我可以统一回复，这就不是我的cookies，我曾经试过整里站号，但是失败了，所以这是网上他人公开的cookies，只拿到cookies据我所知应该做不了什么，这个cookies也没有买那个用账号计算流量限额，所以大概不会有什么影响，放出还能说明cookies无误。也是同理，我就用不了网页版，因为我没有原账号

> 不是。。你确定你cookies就直接扔这了？谁都能看见的

> Not logged in就是登不上，你用网页试试

**Comment by FooIbar** [comment]
> 以上这两条我觉得我可以统一回复，这就不是我的cookies，我曾经试过整里站号，但是失败了，所以这是网上他人公开的cookies，只拿到cookies据我所知应该做不了什么，这个cookies也没有买那个用账号计算流量限额，所以大概不会有什么影响，放出还能说明cookies无误。也是同理，我就用不了网页版，因为我没有原账号
> 
> > 不是。。你确定你cookies就直接扔这了？谁都能看见的
> 
> > Not logged in就是登不上，你用网页试试

用网页也能用cookie登录，不过你这估计就是cookie不行，换个号吧

**Comment by farawayshore** [comment]
> > 以上这两条我觉得我可以统一回复，这就不是我的cookies，我曾经试过整里站号，但是失败了，所以这是网上他人公开的cookies，只拿到cookies据我所知应该做不了什么，这个cookies也没有买那个用账号计算流量限额，所以大概不会有什么影响，放出还能说明cookies无误。也是同理，我就用不了网页版，因为我没有原账号
> > > 不是。。你确定你cookies就直接扔这了？谁都能看见的
> > 
> > 
> > > Not logged in就是登不上，你用网页试试
> 
> 用网页也能用cookie登录，不过你这估计就是cookie不行，换个号吧

呃，真不是，因为xiaojieonly版那边是可以登上去的，但是他那边封面图会爆，所以不大好使。
![Screenshot_2023-02-20-21-34-08-736_com xjs ehviewer](https://user-images.githubusercontent.com/53212436/220122715-d02057dc-a6ae-4078-83a8-1431ecce5b38.jpg)

至于网页登陆，我的确不知道怎么在ehviewer里用网页再通过cookies登陆，您要愿意的话能不能教一下，毕竟看起来这个issue是不打算修了

**Comment by FooIbar** [comment]
> > > 以上这两条我觉得我可以统一回复，这就不是我的cookies，我曾经试过整里站号，但是失败了，所以这是网上他人公开的cookies，只拿到cookies据我所知应该做不了什么，这个cookies也没有买那个用账号计算流量限额，所以大概不会有什么影响，放出还能说明cookies无误。也是同理，我就用不了网页版，因为我没有原账号
> > > > 不是。。你确定你cookies就直接扔这了？谁都能看见的
> > > 
> > > 
> > > > Not logged in就是登不上，你用网页试试
> > 
> > 
> > 用网页也能用cookie登录，不过你这估计就是cookie不行，换个号吧
> 
> 呃，真不是，因为xiaojieonly版那边是可以登上去的，但是他那边封面图会爆，所以不大好使。
> 
> 至于网页登陆，我的确不知道怎么在ehviewer里用网页再通过cookies登陆，您要愿意的话能不能教一下，毕竟看起来这个issue是不打算修了

SXJ版你mystery的igneous能上里站？

**Comment by farawayshore** [comment]
> > > > 以上这两条我觉得我可以统一回复，这就不是我的cookies，我曾经试过整里站号，但是失败了，所以这是网上他人公开的cookies，只拿到cookies据我所知应该做不了什么，这个cookies也没有买那个用账号计算流量限额，所以大概不会有什么影响，放出还能说明cookies无误。也是同理，我就用不了网页版，因为我没有原账号
> > > > > 不是。。你确定你cookies就直接扔这了？谁都能看见的
> > > > 
> > > > 
> > > > > Not logged in就是登不上，你用网页试试
> > > 
> > > 
> > > 用网页也能用cookie登录，不过你这估计就是cookie不行，换个号吧
> > 
> > 
> > 呃，真不是，因为xiaojieonly版那边是可以登上去的，但是他那边封面图会爆，所以不大好使。
> > 至于网页登陆，我的确不知道怎么在ehviewer里用网页再通过cookies登陆，您要愿意的话能不能教一下，毕竟看起来这个issue是不打算修了
> 
> SXJ版你mystery的igneous能上里站？

可以的
![Screenshot_2023-02-20-22-22-34-779_com xjs ehviewer](https://user-images.githubusercontent.com/53212436/220132941-771303ae-86bf-4f78-9b6b-63c3f4e4d43b.jpg)

**Comment by niuguangyu** [comment]
手机上对比了一下SXJ版本的代码，发现使用cookie登录后不做校验，而CookieSignInScreen.kt 打开了profile校验cookie是否有效。
问题可能与公共账号无法打开profile页面有关。

https://github.com/Ehviewer-Overhauled/Ehviewer/blob/f5e9bf2459436f4ead5c86438c41aebc3fac1e89/app/src/main/java/com/hippo/ehviewer/ui/login/CookieSignInScreen.kt#L121
