### ISSUE TITLE
图片无法分享

### ISSUE THREAD

**Issue by REXUEDE9** [Ehviewer-Overhauled/Ehviewer#855]
### 复现步骤 / Step to reproduce

无需复现，随意选择一张图片长按点分享选择一个社交软件即可复现

### 预期行为 / Expected behaviour

点击分享并选择应用软件后会弹出对应的应用

### 实际行为 / Actual Behaviour

实际上没有任何反应，分享功能并不工作

### 备注 / Addition details

同样的操作 sxj和xb2016版本没有问题。

### EhViewer 版本号 / EhViewer version code

1.8.6.1

### EhViewer CI 版本 / EhViewer CI Version

无

### Android 系统版本 / Android version

harmonyOS 2.0.0.236

### 设备型号 / Device model

华为荣耀30s

### SoC 型号 / Soc model

huawei kirin 820

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
无法复现 用最新的ci测试 发下日志录个屏
