### ISSUE TITLE
浏览图片弹出Incomplete 错误，按下retry 无法重加载图片

### ISSUE THREAD

**Issue by Krosec** [Ehviewer-Overhauled/Ehviewer#859]
### 复现步骤 / Step to reproduce

1. 打开图片
2. 加载过程中按下refresh
3. 弹出Incomplete 错误
4. 按下retry

### 预期行为 / Expected behaviour

按下retry 后，图片应该能加载成功

### 实际行为 / Actual Behaviour

仍旧显示Incomplete，无法重加载

### 备注 / Addition details

以上的复现只能在1.8.6.2 中稳定复现，1.8.7.0-alpha01 无法通过以上方法复现Incomplete 错误。1.8.6.2 在正常浏览图片时也会偶尔出现Incomplete 错误，无法通过按下retry 重加载图片

### EhViewer 版本号 / EhViewer version code

1.8.6.2

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4222745622

### Android 系统版本 / Android version

OxygenOS 12.1, Android 12

### 设备型号 / Device model

OnePlus 7t

### SoC 型号 / Soc model

Snapdragon 855+

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
看看日志
~~最新CI没问题那就是没问题~~

**Comment by Krosec** [comment]
> 看看日志 ~最新CI没问题那就是没问题~

[log-2023-02-20-21-35-35-641.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10784917/log-2023-02-20-21-35-35-641.zip)

**Comment by FooIbar** [comment]
复现不了，如果最新CI没问题就当是已经修了吧
