### ISSUE TITLE
闪退问题

### ISSUE THREAD

**Issue by Sayaori** [Ehviewer-Overhauled/Ehviewer#863]
### 复现步骤 / Step to reproduce

打开某一本子，无论是从阅读按钮还是点画廊预览都会导致闪退问题

### 预期行为 / Expected behaviour

应该打开本子

### 实际行为 / Actual Behaviour

闪退

### 备注 / Addition details

附上崩溃日志
链接：https://pan.baidu.com/s/1Bt0TK758AD63kf_NkjsCLw?pwd=oh4s
提取码：oh4s

### EhViewer 版本号 / EhViewer version code

1.8.6.2

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.8.6.2

### Android 系统版本 / Android version

安卓13/ColorOS13

### 设备型号 / Device model

一加9pro

### SoC 型号 / Soc model

骁龙888

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
看了一下，都是因为这里的check失败了
https://github.com/Ehviewer-Overhauled/Ehviewer/blob/25500da4865564d1046c83ccd7ef52a5ac7c6ebb/app/src/main/java/eu/kanade/tachiyomi/ui/reader/loader/PageLoader.kt#L14-L17

**Comment by FooIbar** [comment]
题外话，从1.8.5.3-alpha03开始全是这个，真亏你能忍这么久啊

**Comment by FooIbar** [comment]
https://github.com/Ehviewer-Overhauled/Ehviewer/blob/ce823e9b201f98811151bd0e028c2c8656999763/app/src/main/java/com/hippo/ehviewer/gallery/EhPageLoader.java#L117-L123
可能是因为这里`mSpiderQueen`为空的时候会返回`STATE_ERROR`(-2)
不过这部分已经重构了，你试试[最新的CI](https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4228224582)还有没有问题吧

**Comment by Sayaori** [comment]
最新的版本应该就是2023.02.20发布的1.8.6.2吧，我目前用的就是这个版本
应该也不常用，部分本子还是可以看的，或者闪退过一次后第二次能够看就懒得管了。

**Comment by asuka-mio** [comment]
这种最基础的功能咋可能这么频繁闪退， 而且正经的release都是经过一些时间稳定后的
还有 发日志禁止度盘之类的国内网盘， 建议用pastebin或者pasteubuntu之类的， 哪怕你直接粘贴上来我也不会有意见。。。

**Comment by txyyh** [comment]
> 这种最基础的功能咋可能这么频繁闪退， 而且正经的release都是经过一些时间稳定后的 还有 发日志禁止度盘之类的国内网盘， 建议用pastebin或者pasteubuntu之类的， 哪怕你直接粘贴上来我也不会有意见。。。

pastebin/pasteubuntu要翻墙
