### ISSUE TITLE
下载标签排序功能错误

### ISSUE THREAD

**Issue by lamsass** [Ehviewer-Overhauled/Ehviewer#864]
### 复现步骤 / Step to reproduce

0.重新安装应用
1.进入下载标签界面
2.移动选定的下载标签位置，调整其在列表中顺序
3.退出应用重新进入下载标签界面

### 预期行为 / Expected behaviour

下载标签调整顺序位置后，该标签应当属于调整后位置

### 实际行为 / Actual Behaviour

实际处于另一位置，该位置不固定

### 备注 / Addition details

多次重新启动app后发现，部分下载标签位置不固定，即使未进行调整，其位置也会自行发生变化

### EhViewer 版本号 / EhViewer version code

1.8.6.2

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases

### Android 系统版本 / Android version

MIUI14.0.18

### 设备型号 / Device model

Redmi K60 Pro

### SoC 型号 / Soc model

骁龙8gen2

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
发个视频 信息太少

**Comment by lamsass** [comment]
https://user-images.githubusercontent.com/46513618/220555365-136b7228-56e4-4355-bd9c-326b9e6915bd.mp4

**Comment by lamsass** [comment]
你好，如视频所示，我希望将标签按一定顺序排放，但退出重进后又，该标签又回到了原位

**Comment by tehcneko** [comment]
这问题还没修好...

**Comment by 2kunagisa** [comment]
这问题我几个月前按作者整理库存的时候就发现了，没想到还没修好hhhh
