### ISSUE TITLE
希望添加【标签翻译】的手动更新功能

### ISSUE THREAD

**Issue by ZerOri** [Ehviewer-Overhauled/Ehviewer#872]
### 需求 / Requirement

**[EH]>[显示标签翻译]**功能貌似是每隔24小时自动更新一次？本人因为维护ehtag的需要，希望能添加一个手动更新按钮，方便同步ehtag实现实时预览标签更新。

### 建议实现 / Suggested implements

添加一个【同步标签翻译】按钮以实现实时同步ehtag

### EhViewer 版本号 / EhViewer version code

1.8.6.2

### EhViewer CI 版本 / EhViewer CI Version

1.8.6.2

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [x] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by asuka-mio** [comment]
更新是通过 https://github.com/Ehviewer-Overhauled/EhTagTranslation 仓库ci触发的

**Comment by ZerOri** [comment]
> 更新是通过 https://github.com/Ehviewer-Overhauled/EhTagTranslation 仓库ci触发的

哦，好吧，仓库的更新周期是每天几点啊？

**Comment by asuka-mio** [comment]
如果要在本地实现同步流程 还得引入个markdown解析器 

> > 更新是通过 https://github.com/Ehviewer-Overhauled/EhTagTranslation 仓库ci触发的
> 
> 哦，好吧，仓库的更新周期是每天几点啊？

应该是每天七点四十九

**Comment by FooIbar** [comment]
UTC七点四十九，北京时间是下午四点左右

为什么要用ehv预览，ehtag的编辑器上不是能直接看吗

**Comment by ZerOri** [comment]
> UTC七点四十九，北京时间是下午四点左右
> 
> 为什么要用ehv预览，ehtag的编辑器上不是能直接看吗

因为网页端的eh注射器脚本能做到实时同步所以就想到这个功能，不过app实现起来貌似比较麻烦，那就作罢吧。
