### ISSUE TITLE
优化 Cookie 以缓解 IP 屏蔽

### ISSUE THREAD

**Issue by xb2016** [Ehviewer-Overhauled/Ehviewer#873]
### 需求 / Requirement

在使用被屏蔽的 IP 访问 E 站后 (表现为白屏，没有任何信息)，部分情况下会留下一条名为 `__utmp` 的 cookie，后续带此 cookie 发起请求的 IP 会被直接拉黑。

**下面是针对此行为的测试：**
1. 使用未被屏蔽的 IP (Azure) 访问 E 站，正常访问
2. 换用被屏蔽的 IP (EXFLUX) 访问，白屏，多了一条名为 `__utmp` 的 cookie
3. 删除 `__utmp`，换回未被屏蔽的 IP (Azure) 访问，正常访问
4. 继续换用被屏蔽的 IP (EXFLUX) 访问，再次生成 `__utmp` cookie
5. 保留 `__utmp`，换回未被屏蔽的 IP (Azure) 访问，白屏
6. 删除 `__utmp`，仍然白屏，该 IP (Azure) 也被拉黑

![screen-2023-02-23](https://user-images.githubusercontent.com/31783875/220832065-7958faf5-09b9-453e-bb00-68c6eb892181.gif)

此外，对于捐赠用户，会多出一条名为 `star` 的 cookie，带此 cookie 请求可以绕过白屏

![screen-2023-02-23-2](https://user-images.githubusercontent.com/31783875/220834809-70872320-78bd-4bd5-90db-95d69364717a.gif)

### 建议实现 / Suggested implements

1. 在出现 Sad Panda 或 Empty Page 错误时检查是否保存了名为 `__utmp` 的 cookie，有则删除
2. 在导出 cookie 和使用 cookie 登录时包括名为 `star` 的 cookie

### EhViewer 版本号 / EhViewer version code

1.8.6.2

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4248094374

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by asuka-mio** [comment]
https://github.com/Ehviewer-Overhauled/Ehviewer/blob/6022144dce41cfbe73f96176632141a03f7c3820/app/src/main/java/com/hippo/ehviewer/client/EhCookieStore.kt#L184 在这直接拦截下utmp应该就行

star的话 我这边不方便测试 等人pr吧
