### ISSUE TITLE
Moving downloads from default folder to another will show up in both locations.

### ISSUE THREAD

**Issue by ArbitraryFox** [Ehviewer-Overhauled/Ehviewer#875]
### 复现步骤 / Step to reproduce

1. Download any doujin into default download list.
2. Move the doujin into another download list.

### 预期行为 / Expected behaviour

The moved doijin should disappear from default list and appear in moved list.

### 实际行为 / Actual Behaviour

The doujin appears in the moved list AND default download list.

### 备注 / Addition details

Deleting from the default list also removes from the moved list.

### EhViewer 版本号 / EhViewer version code

1.8.6.0

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/download/1.8.6.1/EhViewer-arm64-v8a.apk

### Android 系统版本 / Android version

11

### 设备型号 / Device model

Mi 9T

### SoC 型号 / Soc model

Snapdragon 730

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
Can't reproduce, can you provide a screenrecord or screenshots?
Note we have `All` and `Default` download label.
All downloads will be displayed under `All` label.

**Comment by ArbitraryFox** [comment]
Thank you for replying. I checked and it was indeed looking at the All folder. I wish it was not the default because I prefer separate folder viewing.

**Comment by FooIbar** [comment]
It will remember your last visited label.
