### ISSUE TITLE
Blockers not working

### ISSUE THREAD

**Issue by ArbitraryFox** [Ehviewer-Overhauled/Ehviewer#876]
### 复现步骤 / Step to reproduce

1. Block a tag like male:yaoi
2. Go to settings > EH > blocker to confirm it appears

### 预期行为 / Expected behaviour

Searching should remove all yaoi tags.

### 实际行为 / Actual Behaviour

Searches with yaoi tags still appear.

### 备注 / Addition details

Tried blocking uploaders, also didnt work.
Tried m:yaoi and male:yaoi, also didn't work.

### EhViewer 版本号 / EhViewer version code

1.8.6.1

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases/download/1.8.6.1/EhViewer-arm64-v8a.apk

### Android 系统版本 / Android version

11

### 设备型号 / Device model

Mi 9T

### SoC 型号 / Soc model

Snapdragon 730

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
Are you using  `Thumbnail` display mode?
![image](https://user-images.githubusercontent.com/118464521/220921320-7a5a2ee1-6a34-4bde-91d2-396da67d4788.png)
It doesn't contain tag and uploader information so we can't filter them.
It's better to use [My Settings](https://e-hentai.org/uconfig.php) and [My Tags](https://ehwiki.org/wiki/My_Tags) to block uploaders and tags.

**Comment by ArbitraryFox** [comment]
Yes, I use thumbnail display.

**Comment by FooIbar** [comment]
You have to use other display modes like compact or extended.
You can create a new settings profile if you don't want to mess up your default settings.
![image](https://user-images.githubusercontent.com/118464521/220934463-28587e08-3180-4a70-90af-2d5d658eb837.png)

**Comment by ArbitraryFox** [comment]
Thank you, it works now.

**Comment by FooIbar** [comment]
BTW, any particular reason not to use the site's filters?
Site's filters are superior.
Let's say you want to block yaoi tag, if you use site's filters it will give you 50 galleries without yaoi tag.
But if you use app's filters, it will get 50 galleries (may contain 10 yaoi galleries) from the site, then filter the yaoi galleries out.
So you'll see less galleries per page comparing to site's filters.

**Comment by ArbitraryFox** [comment]
I got too many blocked tags, don't feel like manually copying them over, that's all. And some doujins are worth unblocking, which is easier from the app rather than the website.
