### ISSUE TITLE
退出详情页后再次进入，缩略图停止加载

### ISSUE THREAD

**Issue by FooIbar** [Ehviewer-Overhauled/Ehviewer#886]
### 复现步骤 / Step to reproduce

1. 进入画廊详情页
2. 退出
3. 再次进入

### 预期行为 / Expected behaviour

继续加载缩略图

### 实际行为 / Actual Behaviour

https://user-images.githubusercontent.com/118464521/221278183-ba82a553-290b-4080-9478-48ea3630bf23.mp4

### 备注 / Addition details

缩略图是大图模式，小图载太快没法测

### EhViewer 版本号 / EhViewer version code

1.8.7.0-alpha

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4265257747

### Android 系统版本 / Android version

PixelExperience 11

### 设备型号 / Device model

Moto Z2 Play

### SoC 型号 / Soc model

Snapdragon 626

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by deyangyvtian** [comment]
下载项目也是，在下载列表中有部分项目封面不显示
