### ISSUE TITLE
无法打开已经下载过的画廊

### ISSUE THREAD

**Issue by WonderfulSoap** [Ehviewer-Overhauled/Ehviewer#887]
### 复现步骤 / Step to reproduce

以下是不同的复现方法，以不同的方法和形式但复现了同样的问题

方法一：
1. 下载安装CI版本 1.8.7.0-alpha，设置下载目录为 `ehviewer` （下载目录其实没影响单纯为了方便说明）
2. 随便下载一个画廊A，进入画廊点击 `阅读` 按钮会打开下载完毕的本地画廊
3. 卸载app重装（或者清除app数据）。启动app将下载目录重新设置回 `ehviewer` 目录
4. 再次进入画廊A，点击 `阅读` 阅读画廊，但是并未调用本地已经存在的画廊而是直接转圈圈

方法二（这种重现方法假设用户从其他版本的eh客户端迁移过来）：
1. 安装NekoInverter版本的eh客户端，设置下载目录为 `ehviewer`，然后随便下载一个画廊A
2. 导出NekoInverter版本客户端的数据
3. 安装本repository版本的eh客户端，导入NekoInverter版本的数据，然后将下载目录设置为 `ehviewer` 。
4. 因为导入了NekoInverter版本的数据，**所以下载界面已经出现了NekoInverter中下载的画廊A的下载记录**
5. 点击画廊A开始阅读，但是并未调用本地已经存在的画廊数据而是直接直接转圈圈

方法三（此方法展示了与之前两种方法矛盾的地方）
1. 下载安装最先CI版本 1.8.7.0-alpha
2. 随便下载一个画廊A，点击画廊A的 `阅读` 按钮会打开下载完毕的本地画廊
3. 删除画廊A的下载记录（**不勾选删除图片文件**），同时清空浏览记录（）
4. 这时从UI角度app已经完全没有画廊A的任何数据，但是点击画廊A的 `阅读` 按钮后却直接调用了本地完成下载的画廊（这点和方法一、二的直接转圈圈相冲突）

### 预期行为 / Expected behaviour

当本地已经存在有下载完成的画廊数据时，app应打开本地已经下载完成的画廊

### 实际行为 / Actual Behaviour

即便画廊已经完成下载，也不会打开本地已经完成下载的画廊。

> 对于上面方法一，二的情形，如果重新点击画廊的 `下载` 按钮，画廊会在一瞬间完成下载，然后就能正常调用本地下载好的数据了

### 备注 / Addition details

上面的三种复现方法似乎都揭示了目前app内部有个隐藏的 `xxx画廊已完成下载` 的flag或记录。只有当flag为 `true` 的时候app才会尝试从本地获取画廊。这点是不太合理的，因为

1. 很多用户都是从其他版本的eh客户端迁移过来的，在迁移过来之前很多用户都已经用其他版本的客户端下载好了很多画廊。而目前的app因为上面说的原因无法直接读取本地下载好的画廊
2. 虽然进入画廊重新下载就能读取本地画廊，但是下载的画廊很多的时候一个个重下是不现实的。而且很多画廊之后都被版权炮删除再也无法重新下载，对于这些画廊明明本地有数据也有下载记录但却无法读取是不合理的
3. 建议将app逻辑改为本地有下载数据直接从本地读取而不是参考app内部的记录。或者实在不行可以参照 `设置 - 下载 - 清理下载冗余` 这个功能，添加个 `扫描本地画廊` 的按钮

### EhViewer 版本号 / EhViewer version code

1.8.7.0-alpha

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4262435702

### Android 系统版本 / Android version

MIUI 13.0.14

### 设备型号 / Device model

Redmi Note 11T Pro+ 

### SoC 型号 / Soc model

MediaTek Dimensity 8100

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
你得恢复下载项啊
![Screenshot_20230225-152313~2](https://user-images.githubusercontent.com/43900799/221344596-74aaefd1-a280-4c7d-8284-0fbc9b4f5049.png)

**Comment by WonderfulSoap** [comment]
@asuka-mio Oh no，原来这个按钮功能是这个。完全理解错这个的功能了。不好意思打扰了
