### ISSUE TITLE
版本更新导致已下载漫画封面丢失

### ISSUE THREAD

**Issue by Sayaori** [Ehviewer-Overhauled/Ehviewer#888]
### 复现步骤 / Step to reproduce

https://user-images.githubusercontent.com/73752368/221359842-195f22ef-d092-45d5-ad36-caf3a216d1ee.mp4

### 预期行为 / Expected behaviour

已下载漫画封面依旧存在

### 实际行为 / Actual Behaviour

丢失，因网络问题，想要重新加载需要翻墙

### EhViewer 版本号 / EhViewer version code

1.8.7.0-alpha

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4262435701

### Android 系统版本 / Android version

安卓13，colorOS13

### 设备型号 / Device model

oneplus 9 pro

### SoC 型号 / Soc model

骁龙888

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by 1429886467** [comment]
不仅如此，进入详情页的画廊的分辨率还很低，以前预览就能看清，现在糊的啥都看不清，而且在eh设置里切换缩略图分辨率也没用

**Comment by FooIbar** [comment]
> 不仅如此，进入详情页的画廊的分辨率还很低，以前预览就能看清，现在糊的啥都看不清，而且在eh设置里切换缩略图分辨率也没用

eh设置里的是封面缩略图分辨率，预览要去网页调

**Comment by 1429886467** [comment]
> > 不仅如此，进入详情页的画廊的分辨率还很低，以前预览就能看清，现在糊的啥都看不清，而且在eh设置里切换缩略图分辨率也没用
> 
> eh设置里的是封面缩略图分辨率，预览要去网页调

试过了，没有用，而且用其他APP打开预览是正常的，就1.8.7.0是糊的

**Comment by 1429886467** [comment]
> > 不仅如此，进入详情页的画廊的分辨率还很低，以前预览就能看清，现在糊的啥都看不清，而且在eh设置里切换缩略图分辨率也没用
> 
> eh设置里的是封面缩略图分辨率，预览要去网页调

感谢，解决了，现在就是下载完原图，重新进入会解析错误以及获取ptoken失败，从而导致下载好的丢失

**Comment by FooIbar** [comment]
#419
