### ISSUE TITLE
下载好的漫画，进入后数据错误或获取ptoken错误

### ISSUE THREAD

**Issue by 1429886467** [Ehviewer-Overhauled/Ehviewer#889]
### 复现步骤 / Step to reproduce

https://user-images.githubusercontent.com/107488796/221361330-84c01091-2fda-4a31-8775-d10df718929d.mp4

### 预期行为 / Expected behaviour

应该正常浏览下载好的漫画

### 实际行为 / Actual Behaviour

实际上下载好的漫画会丢失图片

### EhViewer 版本号 / EhViewer version code

1.8.7.0-alpha

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/releases

### Android 系统版本 / Android version

miui14

### 设备型号 / Device model

xiaomi12 s

### SoC 型号 / Soc model

骁龙8+

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by 1429886467** [comment]
只有下载原图的本会出现进入重新加载的问题，不按原图下载的本没有问题

**Comment by REXUEDE9** [comment]
绝了，如果我没记错这是版权本，看不了基本等于无了

**Comment by 1429886467** [comment]
> 绝了，如果我没记错这是版权本，看不了基本等于无了

是的，看之前我去根目录看了，图片一个不少，点进去就开始转圈显示解析错误，再去根目录一看发现少一张

**Comment by FooIbar** [comment]
如果报的是解码失败大概率是文件损坏了
重试会删除原文件重下

**Comment by 1429886467** [comment]
> 如果报的是解码失败大概率是文件损坏了 重试会删除原文件重下

在点进去之前我进过下载根目录，里面的文件是正常的，但是从APP进入就会开始转圈

**Comment by REXUEDE9** [comment]
> > 如果报的是解码失败大概率是文件损坏了 重试会删除原文件重下
> 
> 在点进去之前我进过下载根目录，里面的文件是正常的，但是从APP进入就会开始转圈

尝试在下载路径里查看该图片是否正常，如果路径里正常说明是软件问题，如果路径里无法阅读或者根本没有说明没有下载完

**Comment by 1429886467** [comment]
> > > 如果报的是解码失败大概率是文件损坏了 重试会删除原文件重下
> > 
> > 
> > 在点进去之前我进过下载根目录，里面的文件是正常的，但是从APP进入就会开始转圈
> 
> 尝试在下载路径里查看该图片是否正常，如果路径里正常说明是软件问题，如果路径里无法阅读或者根本没有说明没有下载完

从下载路径里面是能正常看的，刚下载完的时候从APP里面也是正常能看的，退出重新进入就开始转圈解析错误了

**Comment by 1429886467** [comment]
> > > > > 如果报的是解码失败大概率是文件损坏了 重试会删除原文件重下
> > > > 
> > > > 
> > > > 在点进去之前我进过下载根目录，里面的文件是正常的，但是从APP进入就会开始转圈
> > > 
> > > 
> > > 尝试在下载路径里查看该图片是否正常，如果路径里正常说明是软件问题，如果路径里无法阅读或者根本没有说明没有下载完
> > 
> > 
> > 从下载路径里面是能正常看的，刚下载完的时候从APP里面也是正常能看的，退出重新进入就开始转圈解析错误了
> 
> 录制视频让发出来@官方吧。

一楼就有视频，本来在下载路径能正常看的图，从APP进入之后不能看，然后重新去下载路径就直接被删了

**Comment by 1429886467** [comment]
https://user-images.githubusercontent.com/107488796/222099748-f3a3c682-d57e-4a1e-8371-75acdc1b0e5d.mp4

其实更新了之后还是会导致下载好的图重新加载，然后因为被版权炮了下不了了。。。（未完成是因为加载失败后重新点了下载，不是之前就没下载完）

**Comment by asuka-mio** [comment]
Resolved with 5787753279c923035ea4f273503f656c02e15198
元数据在停止爬取协程作用域时可能没有被及时写入
