### ISSUE TITLE
版本更新后还是会导致下载好的本丢失图片

### ISSUE THREAD

**Issue by 1429886467** [Ehviewer-Overhauled/Ehviewer#904]
### 复现步骤 / Step to reproduce

https://user-images.githubusercontent.com/107488796/222102485-4b557853-3a13-4f7e-9bf7-0ce735a9baac.mp4

（未完成是下载完加载失败重新点了下载，不是没有下载完）

### 预期行为 / Expected behaviour

下载好的本应该在断网状态能看

### 实际行为 / Actual Behaviour

刚下载好的本可以用APP看，从根目录也能看，重新用APP看就开始重新加载

### EhViewer 版本号 / EhViewer version code

1.8.7.0

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer

### Android 系统版本 / Android version

miui14

### 设备型号 / Device model

xiaomi12s

### SoC 型号 / Soc model

骁龙8+

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by 1429886467** [comment]
https://user-images.githubusercontent.com/107488796/222104301-01ec63d7-b5be-4e0c-bc2d-ae669b45bbcd.mp4

**Comment by HistoryMonitor** [comment]
上述正解，还要加多一步，设置-下载-恢复下载项，等它自己转好

**Comment by 1429886467** [comment]
> 上述正解，还要加多一步，设置-下载-恢复下载项，等它自己转好

关键是，从APP进去开始重新转圈之后，在根目录的图片就已经自动消失了，相当于从来没下过这个图片，回收站都找不到，恢复下载项也没用

**Comment by 1429886467** [comment]
> 上述正解，还要加多一步，设置-下载-恢复下载项，等它自己转好

普通本还好，重新下载就重新下载，更关键的是版权本，好不容易下完了，兴冲冲去看了，结果画廊没了，图也下不回来了

**Comment by asuka-mio** [comment]
Resolved with 5787753279c923035ea4f273503f656c02e15198
元数据在停止爬取协程作用域时可能没有被及时写入
