### ISSUE TITLE
在【搜索列表】和【画廊预览】只加载当前能显示在屏幕上面的缩略图，不会预加载剩下的图片

### ISSUE THREAD

**Issue by yinzhefuyun** [Ehviewer-Overhauled/Ehviewer#905]
### 复现步骤 / Step to reproduce

在【搜索列表】和【画廊预览】只加载当前能显示在屏幕上面的缩略图，不会预加载剩下的图片
例如【搜索列表】只加载屏幕能显示的4张缩略图不会加载完一页的量
【画廊预览】也只加载屏幕能显示的6张，导致余下的缩略图需要手指下滑才会进行加载

### 预期行为 / Expected behaviour

【搜索列表】和【画廊预览】位置的缩略图能和【画廊详情】页一样，一口气加载完当前一页的缩略图

### 实际行为 / Actual Behaviour

【搜索列表】只加载屏幕能显示的4张缩略图不会加载完一页的量
【画廊预览】也只加载屏幕能显示的6张，导致余下的缩略图需要手指下滑才会进行加载

### 备注 / Addition details

由于不会进行预加载缩略图导致看图速度明显下降
其实本来就不会浪费多少资源免费用户本来就只能加载20张，而20张缩略图体积极小，消耗的图片配额也是极少
而解锁用户自己的配额根本用不完（主要是缩略图的体积小本身配额消耗也小）

### EhViewer 版本号 / EhViewer version code

1.8.7.0

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4302451866

### Android 系统版本 / Android version

miui14/安卓13

### 设备型号 / Device model

红米K50U

### SoC 型号 / Soc model

8+

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by duzhaokun123** [comment]
> 其实本来就不会浪费多少资源免费用户本来就只能加载20张，而20张缩略图体积极小，消耗的图片配额也是极少

其实素略图不耗配额

**Comment by yinzhefuyun** [comment]
> 所有地方地方都是看到才加载的

本子点进去的详情页那里的缩略图那里是你停着就能加载完200张的，这也是我为什么早期去解锁200张缩略图的动力，而且本来也不会卡呀不是吗

**Comment by tehcneko** [comment]
> > 所有地方地方都是看到才加载的
> 
> 本子点进去的详情页那里的缩略图那里是你停着就能加载完200张的，这也是我为什么早期去解锁200张缩略图的动力，而且本来也不会卡呀不是吗

这个是 Bug

**Comment by yinzhefuyun** [comment]
> > > 所有地方地方都是看到才加载的
> > 
> > 
> > 本子点进去的详情页那里的缩略图那里是你停着就能加载完200张的，这也是我为什么早期去解锁200张缩略图的动力，而且本来也不会卡呀不是吗
> 
> 这个是 Bug

不过这个【BUG】实际上让快速浏览本子内容成为可能性，对于这种良性的【BUG】应该叫做特性，
PS：所以我应该改成【建议】不是【BUG】咯

**Comment by xb2016** [comment]
> 这个是 Bug

不算 bug 吧，这地方都没用 RecycleView，本来就是全部加载的吧

**Comment by FooIbar** [comment]
> > 这个是 Bug
> 
> 不算 bug 吧，这地方都没用 RecycleView，本来就是全部加载的吧

Fixed（

**Comment by tehcneko** [comment]
> > > 这个是 Bug
> > 
> > 
> > 不算 bug 吧，这地方都没用 RecycleView，本来就是全部加载的吧
> 
> Fixed（

没做嵌套滑动

**Comment by FooIbar** [comment]
> > > > 这个是 Bug
> > > 
> > > 
> > > 不算 bug 吧，这地方都没用 RecycleView，本来就是全部加载的吧
> > 
> > 
> > Fixed（
> 
> 没做嵌套滑动

RecycleView 本来就支持嵌套滑动啊

**Comment by tehcneko** [comment]
> > > > > 这个是 Bug
> > > > 
> > > > 
> > > > 不算 bug 吧，这地方都没用 RecycleView，本来就是全部加载的吧
> > > 
> > > 
> > > Fixed（
> > 
> > 
> > 没做嵌套滑动
> 
> RecycleView 本来就支持嵌套滑动啊

你这体验稀烂。。

**Comment by FooIbar** [comment]
> > > > > > 这个是 Bug
> > > > > 
> > > > > 
> > > > > 不算 bug 吧，这地方都没用 RecycleView，本来就是全部加载的吧
> > > > 
> > > > 
> > > > Fixed（
> > > 
> > > 
> > > 没做嵌套滑动
> > 
> > 
> > RecycleView 本来就支持嵌套滑动啊
> 
> 你这体验稀烂。。

确实，我在想改成水平的会不会好一点

**Comment by yinzhefuyun** [comment]
> > > 这个是 Bug
> > 
> > 
> > 不算 bug 吧，这地方都没用 RecycleView，本来就是全部加载的吧
> 
> Fixed（

别修呀，你这修完后我就要等加载了，直接体验降级，本来就是预览用来快速过图，结果却要等一张一张加载导致等待时间大幅增加，建议取消除大图展示外的所有 RecycleView 让图片加载变快

**Comment by yinzhefuyun** [comment]
> > > > > > > 这个是 Bug
> > > > > > 
> > > > > > 
> > > > > > 不算 bug 吧，这地方都没用 RecycleView，本来就是全部加载的吧
> > > > > 
> > > > > 
> > > > > Fixed（
> > > > 
> > > > 
> > > > 没做嵌套滑动
> > > 
> > > 
> > > RecycleView 本来就支持嵌套滑动啊
> > 
> > 
> > 你这体验稀烂。。
> 
> 确实，我在想改成水平的会不会好一点

那是灾难呀，屏幕先显示4-6个，你先先下从上到下看完4-6个，然后右划再从上看到下面，什么糟糕体验，等同于在详情页面强制横屏观看
