### ISSUE TITLE
更新最新CI版后，有里站权限的已捐赠账户浏览里站显示sad panda，退出重新直接登录因无法进行人机验证而失败，通过网页登录应用直接崩溃

### ISSUE THREAD

**Issue by VVaraiotoko** [Ehviewer-Overhauled/Ehviewer#909]
### 复现步骤 / Step to reproduce

1、进入应用内置E站登录界面
2、直接登录账户，应用无法显示人机验证，提示失败，建议通过网页登录
3、点按“通过网页登录”，应用在数秒后崩溃，回到上一界面，或显示“屡次停止运行”

### 预期行为 / Expected behaviour

1、应用更新不影响已登录账户状态
2、应用内置E站登录界面最好能显示人机验证
3、“通过网页登录”不崩溃

### 实际行为 / Actual Behaviour

实际上此更新导致我第一次在彩E遇到sad panda，应用内置E站登录界面如果能显示人机验证直接可登录最好，“通过网页登录”作为最后保险居然崩溃了
![Screenshot_20230302-205626~2](https://user-images.githubusercontent.com/28192782/222435607-5cf0ac81-fe24-4157-b35c-ad9c72ffa15b.png)
![Screenshot_20230302-205642](https://user-images.githubusercontent.com/28192782/222435616-b5bd1fa8-2b80-4cbc-8195-d409bea094e7.png)
[log-2023-03-02-20-18-07-943.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10871575/log-2023-03-02-20-18-07-943.zip)

### 备注 / Addition details

印象中，应用内置E站登录界面本来支持谷歌自动填充，是修改了还是我记错了？
P.S. 经测试，https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4311461493 的版本可正常通过网页登录

### EhViewer 版本号 / EhViewer version code

1.8.7.0

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4311838438

### Android 系统版本 / Android version

Android 12, Stock ROM 58.2.A.7.93

### 设备型号 / Device model

Sony Xperia 1 II 

### SoC 型号 / Soc model

骁龙865

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
拿room重构了存cookies的数据库
没存cookies吗（）cookies不是最方便的（
那个崩了估计是主线程query数据库了 我没考虑到

**Comment by asuka-mio** [comment]
人机验证打算做 最近没啥时间
