### ISSUE TITLE
Can't read downloaded manga when no internet connection

### ISSUE THREAD

**Issue by Tuna221** [Ehviewer-Overhauled/Ehviewer#914]
### 复现步骤 / Step to reproduce

0. Download manga
1. Turn off wifi/mobile data
2. Open downloaded manga

### 预期行为 / Expected behaviour

Read downloaded manga

### 实际行为 / Actual Behaviour

black screen, no page indicator, can't tap to open setting like while reading
some works, some don't
![0d022df11948c3169a591](https://user-images.githubusercontent.com/103440593/222560209-f848c1b7-837b-4ae8-ab7e-9a026bca4685.jpg)
![e563ca90fe2924777d382](https://user-images.githubusercontent.com/103440593/222560282-ed7c21c1-a591-4b3c-81c0-935eb798b782.jpg)

### EhViewer 版本号 / EhViewer version code

1.8.7.0

### EhViewer CI 版本 / EhViewer CI Version

1.8.7.0

### Android 系统版本 / Android version

Modified ZUI 12.5.126 ST

### 设备型号 / Device model

Lenovo Pad Pro 2021

### SoC 型号 / Soc model

Snapdragon 870

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
Resolved with 5787753279c923035ea4f273503f656c02e15198
