### ISSUE TITLE
快速搜索项目/下载项目排序问题

### ISSUE THREAD

**Issue by xb2016** [Ehviewer-Overhauled/Ehviewer#915]
### 复现步骤 / Step to reproduce

1. 确保项目多于一屏距
2. 将第一个项目往下拖拽排序

https://user-images.githubusercontent.com/31783875/222647727-9213b21b-070b-43ae-933c-fe46df321a54.mp4

### 预期行为 / Expected behaviour

它应该正常完成排序

### 实际行为 / Actual Behaviour

移动被中断 或者移动速度过快

### 备注 / Addition details

该问题与协程内更新 UI 有关

### EhViewer 版本号 / EhViewer version code

1.8.7.0

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4319289504

### Android 系统版本 / Android version

MIUI 13

### 设备型号 / Device model

Redmi K40P

### SoC 型号 / Soc model

888

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by lwzaaz** [comment]
能不能在下载页面添加一个一键分类（根据画师名字），或者是搜索功能啊。现在只能手动写下载标签分类有点麻烦。
