### ISSUE TITLE
无法断网观看，已上传录屏

### ISSUE THREAD

**Issue by deyangyvtian** [Ehviewer-Overhauled/Ehviewer#918]
### 复现步骤 / Step to reproduce

下载完成的内容在没有网络的情况下无法正常打开
部分画廊可以正常断网观看部分不行
在根目录里面都可以正常打开
重新下载依然有问题

https://user-images.githubusercontent.com/60131840/222878255-9559944e-2629-481a-a9d2-260f6fac3808.mp4

### 预期行为 / Expected behaviour

下载好的应该可以断网观看

### 实际行为 / Actual Behaviour

实际上必须联网才可以观看

### 备注 / Addition details

我看了其他的issue感觉不太一样 我没有开原图下载，而且bug过程中也没有提示重试

### EhViewer 版本号 / EhViewer version code

1.8.7.0

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/suites/11320769812/artifacts/581338065

### Android 系统版本 / Android version

Android11

### 设备型号 / Device model

xiaomi11

### SoC 型号 / Soc model

骁龙888

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by xb2016** [comment]
和 #889 #904 应该是同一个问题
看表现应该是阅读时没有优先取本地下载文件，直接去读了缓存

**Comment by asuka-mio** [comment]
Resolved with 5787753279c923035ea4f273503f656c02e15198
元数据在停止爬取协程作用域时可能没有被及时写入

**Comment by deyangyvtian** [comment]
您好，修复之后是只能一个一个下载项目点击加载元数据吗，能否一键加载全部下载的数据
