### ISSUE TITLE
优化缓存空间占用

### ISSUE THREAD

**Issue by FooIbar** [Ehviewer-Overhauled/Ehviewer#920]
### 需求 / Requirement

25cddb2 d4dc65a 和 a7bce9c 导致缓存路径发生改变，而未删除原缓存文件
此外，当前缩略图加载交给了 coil ，然而未对缓存大小进行限制

### 建议实现 / Suggested implements

删除旧版本缓存
提供缩略图缓存大小设置，或者和阅读缓存共用

### EhViewer 版本号 / EhViewer version code

1.8.7.0-alpha

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4330013445

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by asuka-mio** [comment]
> ### 需求 / Requirement
> 
> [25cddb2](https://github.com/Ehviewer-Overhauled/Ehviewer/commit/25cddb2d6118eaee1605422fc4871fe611071b07) 和 [d4dc65a](https://github.com/Ehviewer-Overhauled/Ehviewer/commit/d4dc65a4bac3c5ac9128a56bc3cdd9c340c2bc7c) 导致缓存路径发生改变，而未删除原缓存文件 此外，当前缩略图加载交给了 coil ，然而未对缓存大小进行限制
> ### 建议实现 / Suggested implements
> 
> 删除旧版本缓存 提供缩略图缓存大小设置，或者和阅读缓存共用
> ### 备注 / Addition details
> 
> _No response_
> ### EhViewer 版本号 / EhViewer version code
> 
> 1.8.7.0-alpha
> ### EhViewer CI 版本 / EhViewer CI Version
> 
> https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4330013445
> ### 自查步骤 / Verify steps
> 
>     * [ ]  如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
> 
>     * [x]  您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
> 
>     * [x]  您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
> 
>     * [x]  您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
> 
>     * [x]  您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

旧版缓存手动清除下缓存就好了
coil默认有限制的 disksize的百分之0.2貌似

**Comment by asuka-mio** [comment]
共用一个缓存目录倒是可以 毕竟是LRU的

**Comment by FooIbar** [comment]
> 旧版缓存手动清除下缓存就好了 coil默认有限制的 disksize的百分之0.2貌似

手动清是可以，但是你不说用户不会知道有一堆旧版缓存占着空间

**Comment by FooIbar** [comment]
https://github.com/coil-kt/coil/blob/d919d320790f074bbd91c69db546e971367ca3a4/coil-base/src/main/java/coil/disk/DiskCache.kt#L120-L122
coil 默认的是 2% 或者 250MB 取小的

**Comment by FooIbar** [comment]
共用（然后增加默认的缓存大小）可能比较好
缩略图 250MB 存了快两万张，而 320MB 的阅读缓存只有不到两千张，如果开原图的话就更捉襟见肘了

另外缩略图的 cache key 不应该用完整的 URL ，现在这样会导致换画廊站点之后重新请求
