### ISSUE TITLE
使用SAF路径下载报错

### ISSUE THREAD

**Issue by LuoKX** [Ehviewer-Overhauled/Ehviewer#921]
### 复现步骤 / Step to reproduce

1. [Android Samba Client](https://f-droid.org/en/packages/com.google.android.sambadocumentsprovider/)挂载Samba
2. 下载路径设置为
![Screenshot_2023-03-04-20-15-12-629-edit_moe tarsi](https://user-images.githubusercontent.com/37505203/222900515-fff59cd1-b87f-41ab-af3e-38df11733e09.jpg)
3. 选择任意一个画廊下载

### 预期行为 / Expected behaviour

samba服务器创建对应画廊文件夹，并开始下载

### 实际行为 / Actual Behaviour

samba服务器创建了对应文件夹，但是下载的图片文件为0kb

## 截图
![image](https://user-images.githubusercontent.com/37505203/222900732-34c26d4e-80bf-4336-9520-1c8d96e6f6c8.png)

## 日志
03-04 20:19:43.582 11612 16796 D EhSSLSocketFactory: Host: eeugqms.wgabjvvvaqqc.hath.network Address: null Protocol:TLSv1.2 CipherSuite:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
03-04 20:19:43.752 11612 16827 W System.err: java.io.IOException: Illegal seek
03-04 20:19:43.752 11612 16827 W System.err: 	at sun.nio.ch.FileDispatcherImpl.pwrite0(Native Method)
03-04 20:19:43.752 11612 16827 W System.err: 	at sun.nio.ch.FileDispatcherImpl.pwrite(FileDispatcherImpl.java:81)
03-04 20:19:43.752 11612 16827 W System.err: 	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:89)
03-04 20:19:43.752 11612 16827 W System.err: 	at sun.nio.ch.IOUtil.write(IOUtil.java:51)
03-04 20:19:43.752 11612 16827 W System.err: 	at sun.nio.ch.FileChannelImpl.writeInternal(FileChannelImpl.java:829)
03-04 20:19:43.753 11612 16827 W System.err: 	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:815)
03-04 20:19:43.753 11612 16827 W System.err: 	at sun.nio.ch.FileChannelImpl.transferFromArbitraryChannel(FileChannelImpl.java:728)
03-04 20:19:43.753 11612 16827 W System.err: 	at sun.nio.ch.FileChannelImpl.transferFrom(FileChannelImpl.java:762)
03-04 20:19:43.753 11612 16827 W System.err: 	at vg0.e(Unknown Source:63)
03-04 20:19:43.753 11612 16827 W System.err: 	at vg0.d(Unknown Source:303)
03-04 20:19:43.753 11612 16827 W System.err: 	at ug0.g(Unknown Source:16)
03-04 20:19:43.753 11612 16827 W System.err: 	at n9.w(Unknown Source:8)
03-04 20:19:43.753 11612 16827 W System.err: 	at Jo.run(Unknown Source:108)
03-04 20:19:43.753 11612 16827 W System.err: 	at dM.run(Unknown Source:11)
03-04 20:19:43.753 11612 16827 W System.err: 	at Gk0.run(Unknown Source:2)
03-04 20:19:43.753 11612 16827 W System.err: 	at ll.run(Unknown Source:76)
03-04 20:19:43.753 11612 16827 E SpiderQueenWorker: Can't download all of image data

### 备注 / Addition details

在samba服务器中下载路径有对应画廊的文件时，可以正常浏览图片，只是无法正常下载

### EhViewer 版本号 / EhViewer version code

1.8.7.0

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4280115883

### Android 系统版本 / Android version

MIUI 13.0.7

### 设备型号 / Device model

XiaoMi 10

### SoC 型号 / Soc model

骁龙865

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
emm nio的transferFrom实现需要文件描述符seekable

**Comment by asuka-mio** [comment]
到可以workaround下弄个临时文件往里写 然后直接sendfile过去 不过一来效率低二来不优雅

**Comment by asuka-mio** [comment]
@FooIbar 有什么好主意吗（

**Comment by asuka-mio** [comment]
其实不用我们这解决 samba是支持seekable fd的
https://github.com/google/samba-documents-provider/pull/54
fdroid只提供的32位版本

**Comment by asuka-mio** [comment]
@LuoKX  如果你有能力 建议自己编译一个64位版本的https://github.com/google/samba-documents-provider
或者编译一个应用了https://github.com/google/samba-documents-provider/pull/54 的32位版本
我们这不提供解决方案

**Comment by asuka-mio** [comment]
> @LuoKX 如果你有能力 建议自己编译一个64位版本的https://github.com/google/samba-documents-provider 或者编译一个应用了[google/samba-documents-provider#54](https://github.com/google/samba-documents-provider/pull/54) 的32位版本 我们这不提供现成的解决方案

**Comment by asuka-mio** [comment]
并且建议您向fdroid官方指出这个bug 让他们修复下

**Comment by tehcneko** [comment]
应该等 MaterialFiles 实 ACTION_OPEN_DOCUMENT_TREE（
https://github.com/zhanghai/MaterialFiles/issues/153

**Comment by LuoKX** [comment]
> @LuoKX 如果你有能力 建议自己编译一个64位版本的https://github.com/google/samba-documents-provider 或者编译一个应用了[google/samba-documents-provider#54](https://github.com/google/samba-documents-provider/pull/54) 的32位版本 我们这不提供现成的解决方案

不太确定是否是版本的问题，找到了64位的samba-documents-provider，仍然存在System.err: java.io.IOException: Illegal seek
也编译了一个应用了https://github.com/google/samba-documents-provider/pull/54 的32位版本，同样存在这个问题。

为了验证是否为Samba导致的，使用了一个webdav document provider [rcx](https://github.com/x0b/rcx)，同样有一样的问题

**Comment by asuka-mio** [comment]
> > @LuoKX 如果你有能力 建议自己编译一个64位版本的https://github.com/google/samba-documents-provider 或者编译一个应用了[google/samba-documents-provider#54](https://github.com/google/samba-documents-provider/pull/54) 的32位版本 我们这不提供现成的解决方案
> 
> 不太确定是否是版本的问题，找到了64位的samba-documents-provider，仍然存在System.err: java.io.IOException: Illegal seek 也编译了一个应用了[google/samba-documents-provider#54](https://github.com/google/samba-documents-provider/pull/54) 的32位版本，同样存在这个问题。
> 
> 为了验证是否为Samba导致的，使用了一个webdav document provider [rcx](https://github.com/x0b/rcx)，同样有一样的问题

还有日志吗 我看看

**Comment by asuka-mio** [comment]
不是很理解 但这个文件描述符行为肯定有问题 我看看

**Comment by LuoKX** [comment]
03-05 10:53:58.556 25027 25234 D SpiderQueenWorker: Start download image 1
03-05 10:53:59.565 25027 25105 D EhSSLSocketFactory: Host: gzkftsh.shotwkzpjwwo.hath.network Address: null Protocol:TLSv1.2 CipherSuite:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
03-05 10:54:00.019 25027 25234 W System.err: java.io.IOException: Illegal seek
03-05 10:54:00.019 25027 25234 W System.err: 	at sun.nio.ch.FileDispatcherImpl.pwrite0(Native Method)
03-05 10:54:00.020 25027 25234 W System.err: 	at sun.nio.ch.FileDispatcherImpl.pwrite(FileDispatcherImpl.java:81)
03-05 10:54:00.020 25027 25234 W System.err: 	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:89)
03-05 10:54:00.020 25027 25234 W System.err: 	at sun.nio.ch.IOUtil.write(IOUtil.java:51)
03-05 10:54:00.020 25027 25234 W System.err: 	at sun.nio.ch.FileChannelImpl.writeInternal(FileChannelImpl.java:829)
03-05 10:54:00.020 25027 25234 W System.err: 	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:815)
03-05 10:54:00.020 25027 25234 W System.err: 	at sun.nio.ch.FileChannelImpl.transferFromArbitraryChannel(FileChannelImpl.java:728)
03-05 10:54:00.020 25027 25234 W System.err: 	at sun.nio.ch.FileChannelImpl.transferFrom(FileChannelImpl.java:762)
03-05 10:54:00.020 25027 25234 W System.err: 	at vg0.e(Unknown Source:63)
03-05 10:54:00.020 25027 25234 W System.err: 	at vg0.d(Unknown Source:303)
03-05 10:54:00.020 25027 25234 W System.err: 	at ug0.g(Unknown Source:16)
03-05 10:54:00.020 25027 25234 W System.err: 	at n9.w(Unknown Source:8)
03-05 10:54:00.020 25027 25234 W System.err: 	at Jo.run(Unknown Source:108)
03-05 10:54:00.020 25027 25234 W System.err: 	at dM.run(Unknown Source:11)
03-05 10:54:00.020 25027 25234 W System.err: 	at Gk0.run(Unknown Source:2)
03-05 10:54:00.020 25027 25234 W System.err: 	at ll.run(Unknown Source:76)
03-05 10:54:00.020 25027 25234 E SpiderQueenWorker: Can't download all of image data
03-05 10:54:00.021 25027 25234 D Us      : https://exhentai.org/s/74cdd8bcf2/2484574-2?nl=36514-466106
03-05 10:54:01.323 25027 25234 D SpiderQueenWorker: https://gotbjbqvnxfkunugorzh.hath.network/om/122085970/74cdd8bcf26a824095b7c69984b61c752cb265fb-7989739-872-492-gif/x/0/2yfdrkc4owvbnvz03c/GIF_2023_3_5_3_36_32.gif

![Screenshot_2023-03-05-10-55-33-841-edit_com absin](https://user-images.githubusercontent.com/37505203/222939174-fab7a8ef-29d9-4ebc-8a8c-6fc496f717a1.jpg)

而且还有一个现象，下载失败后，有时候有`.ehviewer`，有时候没有

**Comment by asuka-mio** [comment]
稍微看了眼 rclone那个saf实现的有问题 拿管道当缓冲然后开个线程往上flush数据
我不多评价

**Comment by asuka-mio** [comment]
那现在只能说这个文件描述符不支持seek 需要做transferFrom的fallback

**Comment by asuka-mio** [comment]
。。。你更最新CI吧 现在已经不是transferFrom实现了

**Comment by asuka-mio** [comment]
说了多少次用最新CI测试

**Comment by asuka-mio** [comment]
我刚打开电脑准备修 我一看我咋找不着在哪用的transferFrom来着 早改没了换ktor了

**Comment by LuoKX** [comment]
那我关闭这个issue用最新的CI后重开一个issue？

**Comment by asuka-mio** [comment]
> 那我关闭这个issue用最新的CI后重开一个issue？

修了 还开啥 最新的ci不要求fd是seekable的了
