### ISSUE TITLE
退出程序后阅读进度丢失

### ISSUE THREAD

**Issue by KIrayamoto** [Ehviewer-Overhauled/Ehviewer#931]
### 复现步骤 / Step to reproduce

1.进入画廊
2.阅读至某一页
3.退出软件
4.重新打开软件进入画廊

https://user-images.githubusercontent.com/38139345/223310968-dad6b095-9638-480a-86b0-c30eda1dba96.mp4

### 预期行为 / Expected behaviour

打开画廊时，回到上次的阅读进度

### 实际行为 / Actual Behaviour

进度丢失，进入画廊第一页

### 备注 / Addition details

不只是新产生的阅读进度，以往的阅读进度也全部丢失

### EhViewer 版本号 / EhViewer version code

1.8.7

### EhViewer CI 版本 / EhViewer CI Version

d3d07f9

### Android 系统版本 / Android version

Android13

### 设备型号 / Device model

IQOO Neo5

### SoC 型号 / Soc model

骁龙870

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
另 软件在离开画廊后三秒才会向磁盘写入阅读进度
此外 强行杀死进程（aosp下划掉后台并不会杀死进程 但我们不知道oem系统的行为）我们不会也永远无法保证数据的完整性
