### ISSUE TITLE
画廊部分页面无法加载

### ISSUE THREAD

**Issue by Krosec** [Ehviewer-Overhauled/Ehviewer#935]
### 复现步骤 / Step to reproduce

https://exhentai.org/g/2485579/0a0dcbd329/
该画廊的p75无法加载，其他页面无问题

### 预期行为 / Expected behaviour

正常加载

### 实际行为 / Actual Behaviour

无法加载

### 应用日志 / App logs

[log-2023-03-08-11-37-34-109.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10916962/log-2023-03-08-11-37-34-109.zip)

### 备注 / Addition details

使用浏览器浏览该画廊的p75能加载成功

### EhViewer 版本号 / EhViewer version code

1.8.8.0-dev

### EhViewer CI 版本 / EhViewer CI Version

cdf53c8

### Android 系统版本 / Android version

OxygenOS 12.1, Android 12

### 设备型号 / Device model

OnePlus 7t

### SoC 型号 / Soc model

Snapdragon 855+

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
我这里正常加载

**Comment by Krosec** [comment]
> 我这里正常加载

这个复现是在11:25-11:45的时候稳定复现的，现在我在不更新app的情况下点击画廊P75也能正常加载。当时复现的时候不断清理缓存，app和手机浏览器交替浏览该画廊，只有在使用app出现其他P正常加载，P75无法加载的情况，浏览器正常。当时的手机网络环境应该不是影响P75无法加载的主要因素

**Comment by FooIbar** [comment]
```
03-08 11:36:48.969  3431  3431 D U90     : moveToPage 75
03-08 11:36:48.971  3431  3431 I Quality : Skipped: false 2 cost 30.161098 refreshRate 0 processName moe.tarsin.ehviewer
03-08 11:36:48.976  3431  4910 D Rv      : https://exhentai.org/api.php
03-08 11:36:48.991  3431  4585 D SpiderQueenWorker: Download image cancelled 74
03-08 11:36:48.999  3431  5464 D Rv      : https://exhentai.org/api.php
03-08 11:36:49.369  3431  3472 E BLASTBufferQueue: BLASTBufferItemConsumer::onDisconnect()
03-08 11:36:49.369  3431  3472 D OpenGLRenderer: endAllActiveAnimators on 0xb400007c5e635e00 (FixedThumb) with handle 0xb400007c4ebd87c0
03-08 11:36:51.685  3431  4599 D SpiderQueenWorker: https://okpwpmi.nqqwqfcsnwtq.hath.network:23333/h/feb323763b5a70c2a155cc19fd685256a04f9f22-312134-1280-1808-jpg/keystamp=1678247100-48eefdc59c;fileindex=121779624;xres=1280/iris_completebook_073.jpg
03-08 11:36:51.686  3431  4599 D SpiderQueenWorker: Start download image 74
```
日志中只出现了这么一次

**Comment by Krosec** [comment]
> ```
> 03-08 11:36:48.969  3431  3431 D U90     : moveToPage 75
> 03-08 11:36:48.971  3431  3431 I Quality : Skipped: false 2 cost 30.161098 refreshRate 0 processName moe.tarsin.ehviewer
> 03-08 11:36:48.976  3431  4910 D Rv      : https://exhentai.org/api.php
> 03-08 11:36:48.991  3431  4585 D SpiderQueenWorker: Download image cancelled 74
> 03-08 11:36:48.999  3431  5464 D Rv      : https://exhentai.org/api.php
> 03-08 11:36:49.369  3431  3472 E BLASTBufferQueue: BLASTBufferItemConsumer::onDisconnect()
> 03-08 11:36:49.369  3431  3472 D OpenGLRenderer: endAllActiveAnimators on 0xb400007c5e635e00 (FixedThumb) with handle 0xb400007c4ebd87c0
> 03-08 11:36:51.685  3431  4599 D SpiderQueenWorker: https://okpwpmi.nqqwqfcsnwtq.hath.network:23333/h/feb323763b5a70c2a155cc19fd685256a04f9f22-312134-1280-1808-jpg/keystamp=1678247100-48eefdc59c;fileindex=121779624;xres=1280/iris_completebook_073.jpg
> 03-08 11:36:51.686  3431  4599 D SpiderQueenWorker: Start download image 74
> ```
> 
> 日志中只出现了这么一次

每次复现成功后都会清理缓存并把后台杀了，重新打开app，这样会对日志记录有影响吗
