### ISSUE TITLE
画廊详情页下拉页面后长标题仍然显示不全

### ISSUE THREAD

**Issue by devioa** [Ehviewer-Overhauled/Ehviewer#954]
### 复现步骤 / Step to reproduce

1. 进入一个长标题的画廊详情页
2. 默认是折叠标题
3. 通过下拉页面展开标题
4. 展开后长标题仍然显示不全
5. 且标题顶部有很大面积的空白区域

### 预期行为 / Expected behaviour

长标题展开后应当显示完整标题，整个页面布局是紧凑的、不会有无意义的空白区域

### 实际行为 / Actual Behaviour

![Screenshot_2023-03-13-11-36-55-137_moe tarsin ehv](https://user-images.githubusercontent.com/38558065/224602988-10c8905c-2b4a-404a-9b42-fba16ddbf75a.jpg)

### EhViewer 版本号 / EhViewer version code

1.8.7.1

### EhViewer CI 版本 / EhViewer CI Version

45eed26

### Android 系统版本 / Android version

MIUI 14 Android 13

### 设备型号 / Device model

Redmi K50 Ultra

### SoC 型号 / Soc model

骁龙 8+ Gen1

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
大面积是md3 design，设计如此

**Comment by devioa** [comment]
很难苟同这样的设计，这块空白区域按理来说是不该出现的，它占用这块区域毫无意义

**Comment by txyyh** [comment]
> 很难苟同这样的设计，这块空白区域按理来说是不该出现的，它占用这块区域毫无意义

md3设计如此
建议找谷歌方面反馈

**Comment by devioa** [comment]
> > 很难苟同这样的设计，这块空白区域按理来说是不该出现的，它占用这块区域毫无意义
> 
> md3设计如此 建议找谷歌方面反馈

好的了解了

**Comment by FooIbar** [comment]
> > 很难苟同这样的设计，这块空白区域按理来说是不该出现的，它占用这块区域毫无意义
> 
> md3设计如此 建议找谷歌方面反馈

谷歌也没要求用large啊

**Comment by txyyh** [comment]
> > > 很难苟同这样的设计，这块空白区域按理来说是不该出现的，它占用这块区域毫无意义
> > 
> > 
> > md3设计如此 建议找谷歌方面反馈
> 
> 谷歌也没要求用large啊

Guidelines

**Comment by FooIbar** [comment]
> > > > 很难苟同这样的设计，这块空白区域按理来说是不该出现的，它占用这块区域毫无意义
> > > 
> > > 
> > > md3设计如此 建议找谷歌方面反馈
> > 
> > 
> > 谷歌也没要求用large啊
> 
> Guidelines

Guidelines里还说标题不应该被截断呢（
