### ISSUE TITLE
长按下载项无法弹出操作菜单，只能拖动排序

### ISSUE THREAD

**Issue by tiger2012010** [Ehviewer-Overhauled/Ehviewer#970]
### 复现步骤 / Step to reproduce

如视频所示，长按下载项，右下方不会弹出菜单，只可以上下拖动下载项排序

https://user-images.githubusercontent.com/95688933/226779922-79a4ce96-467b-443e-8c23-1cc5951f0a92.mp4

### 预期行为 / Expected behaviour

本来的操作流程是:长按一个下载项，右下方弹出操作菜单，可以删除，也可以拖动下载项

### 实际行为 / Actual Behaviour

但是现在长按下载项，右下方不会弹出菜单，只可以上下拖动下载项排序，非常低概率能成功弹出操作菜单

### 备注 / Addition details

更新到新版本之后发现这个问题，老版本没有

### EhViewer 版本号 / EhViewer version code

1.8.7.2

### EhViewer CI 版本 / EhViewer CI Version

9cadf11

### Android 系统版本 / Android version

emui 11.0 Android10

### 设备型号 / Device model

华为mate 20 pro

### SoC 型号 / Soc model

麒麟980

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by sgy1005** [comment]
我的双指长按可以弹出

**Comment by asuka-mio** [comment]
这块确实有一些问题 拖动和长按的threshold几乎差不多
我想想咋改好点

**Comment by tiger2012010** [comment]
> 我的双指长按可以弹出

我双指长按没反应，既没法拖动，也没法删除

**Comment by tiger2012010** [comment]
> 这块确实有一些问题 拖动和长按的threshold几乎差不多 我想想咋改好点

现在有办法能删除吗，我几乎没法删除了

**Comment by xb2016** [comment]
> 现在有办法能删除吗，我几乎没法删除了

长按点不出来的话，进画廊详情页可以删

**Comment by asoulist** [comment]
> 这块确实有一些问题 拖动和长按的threshold几乎差不多
> 我想想咋改好点

中央部分点按侧滑进入排序状态，正常长按呼出操作菜单，这样呢？

**Comment by FooIbar** [comment]
#1265
