### ISSUE TITLE
更新版本后标签无法翻译

### ISSUE THREAD

**Issue by luckkill** [Ehviewer-Overhauled/Ehviewer#985]
### 需求 / Requirement

更新版本后标签无法翻译

### 建议实现 / Suggested implements

更新版本后标签无法翻译

### EhViewer 版本号 / EhViewer version code

1.8.7.2

### EhViewer CI 版本 / EhViewer CI Version

9cadf11

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by txyyh** [comment]
CI 版本错误

**Comment by luckkill** [comment]
![Screenshot_2023-03-25-15-38-58-585_moe tarsin ehviewer](https://user-images.githubusercontent.com/128595281/227704208-810adec7-92e7-4079-853a-c92ae3f69bed.jpg)
![Screenshot_2023-03-25-15-39-10-263_moe tarsin ehviewer](https://user-images.githubusercontent.com/128595281/227704212-a7acb02f-0fe3-4ef8-9462-106af743f5c5.jpg)

**Comment by asuka-mio** [comment]
网络问题
