### ISSUE TITLE
漫画阅读页面黑屏

### ISSUE THREAD

**Issue by dyguests** [Ehviewer-Overhauled/Ehviewer#988]
### 复现步骤 / Step to reproduce

0. 啊这...

### 预期行为 / Expected behaviour

1. 下载页面
2. 点击一部漫画
3. 显示漫画内容，并显示上一次阅读进度对应的页面。

### 实际行为 / Actual Behaviour

1. 下载页面
2. 点击一部漫画（已下载完成的）
3. 黑屏（图片未加载，可以显示状态栏等）。
3.1. 有时过几秒会显示图片，有时一直不显示，需要返回上一级页面，再重进才显示图片。
3.2. 阅读进度未同步，显示在第一页。

### EhViewer 版本号 / EhViewer version code

1.8.7.0

### EhViewer CI 版本 / EhViewer CI Version

d3d07f9

### Android 系统版本 / Android version

ColorOS 13.0, Android 13

### 设备型号 / Device model

OPPO Reno 9

### SoC 型号 / Soc model

天玑8100-Max

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
1.8.7.2已修复 更新啊

**Comment by asuka-mio** [comment]
https://github.com/Ehviewer-Overhauled/Ehviewer/releases/tag/1.8.7.1

**Comment by dyguests** [comment]
才看到，我去更新.
