### ISSUE TITLE
Webtoon view

### ISSUE THREAD

**Issue by Cinj216** [Ehviewer-Overhauled/Ehviewer#990]
### 复现步骤 / Step to reproduce

Changing the view to webtoon mode leaves you unable to change the view to anything else as pressing the bottom of the screen just advances the image and you can no longer access the menu.

### 预期行为 / Expected behaviour

The menu should still be accessible

### 实际行为 / Actual Behaviour

It is not

### EhViewer 版本号 / EhViewer version code

1.8.7.2

### EhViewer CI 版本 / EhViewer CI Version

9cadf11

### Android 系统版本 / Android version

Android 13

### 设备型号 / Device model

Galaxy S22 Ultra

### SoC 型号 / Soc model

Snapdragon 8 Gen 1

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by Cinj216** [comment]
After messing around further I discovered you can bring the menu up if you pinch the image and zoom all the way out and then press the bottom of the screen. I still feel this behavior needs to be tweaked in some way as it's not obvious how to regain access to the menu once switching to webtoon and I'll leave the issue open.

**Comment by FooIbar** [comment]
The "menu zone" is the center of the screen, not the bottom.
And I'm pretty sure there will be a prompt for tap zones after switching view modes.

**Comment by Cinj216** [comment]
You are absolutely right. I've used the original and abandoned EHViewer for so long before switching to this fork that I'm way too stuck on the behaviors of that version it's hard to break the habit. Sorry and thanks.
