### ISSUE TITLE
在搜索列表中，使用不同颜色的心形符号或在其上添加数字，以表示不同的收藏夹

### ISSUE THREAD

**Issue by tglsf** [Ehviewer-Overhauled/Ehviewer#994]
### 需求 / Requirement

在搜索列表中，使用不同颜色的心形符号或在其上添加数字，以表示不同的收藏夹

有时，我们用不同的收藏夹来对作品进行分类，并用于在其他设备上标记阅读进度。在目前的版本中，添加到收藏夹的作品是用心形符号表示的，无法区分哪些作品在哪个收藏夹。

### 建议实现 / Suggested implements

1. 在搜索列表中，使用不同颜色的心形符号
2. 在搜索列表中的心形符号上添加数字

### EhViewer 版本号 / EhViewer version code

1.8.7.2

### EhViewer CI 版本 / EhViewer CI Version

9cadf11

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by txyyh** [comment]
@asuka-mio 目前有靠谱点的M3颜色生成方案吗
