### ISSUE TITLE
退出画廊后划掉后台阅读进度丢失

### ISSUE THREAD

**Issue by mojiedepulini** [Ehviewer-Overhauled/Ehviewer#996]
### 复现步骤 / Step to reproduce

1.从1.8.7.0-alpha覆盖升级至1.8.7.2
2.进入已下载画廊，跳至某一页
3.返回键退出至下载列表，然后后台划掉结束进程
4.重新进入画廊阅读，发现进度变为了最开始打开时的进度

### 预期行为 / Expected behaviour

退出阅读界面时就已保留阅读进度，下次点开延续上次的进度

### 实际行为 / Actual Behaviour

退出后重新点开进度为最开始时的进度，例：之前在第2页阅读至12页后退出，再次点开时又变为了第二页
但在退出至列表时停留3秒再结束后台时，下次进度又是延续上次进度，如上例，点开后回到12页

### 备注 / Addition details

https://github.com/Ehviewer-Overhauled/Ehviewer/issues/931
在该条里看到了相似问题，但看到1.8.7.1已修复，但现在自己使用的1.8.7.2仍存在该问题。
重装了这3个版本arm64-v8a   universal  armeabi-v7a均是相同情况(虽说不懂什么区别..)
或者是自己理解错误，“软件在离开画廊后三秒才会向磁盘写入阅读进度”，并不是存在的问题而是本身就是这样设计的吗？
之前用的版本一直没注意到这个问题，感觉比较影响体验感
对github不太熟悉，如果有冒犯或违规的情况请见谅。感谢

### EhViewer 版本号 / EhViewer version code

1.8.7.2

### EhViewer CI 版本 / EhViewer CI Version

9cadf11

### Android 系统版本 / Android version

Android11

### 设备型号 / Device model

真我realme gt neo闪速版

### SoC 型号 / Soc model

天玑1200

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
就这样设计的
